### ISSUE TITLE
Support LXC and LXD nesting

### ISSUE THREAD

**Issue by rcj4747** [lxc/lxd#1002]
Running trusty with lxd from ppa:ubuntu-lxc/lxd-git-master nested inside a trusty container results in a lxd service continually restarting in the container because it can't access the newly created certificate.

Steps to reproduce
```
lxc remote add images images.linuxcontainers.org
lxc image copy images:ubuntu/trusty/amd64 local: --alias=trusty
lxc launch trusty trusty
lxc stop trusty
lxc config set trusty raw.lxc 'lxc.aa_profile=lxc-container-default-with-nesting'
lxc start trusty
lxc exec trusty -- apt-get -y install software-properties-common
lxc exec trusty -- add-apt-repository -y ppa:ubuntu-lxc/lxd-git-master
lxc exec trusty -- apt-get update
lxc exec trusty -- apt-get -y dist-upgrade
lxc exec trusty -- apt-get -y install lxd
lxc exec trusty -- lxc image list
```
    Generating a client certificate. This may take a minute...
    If this is your first run, you will need to import images using the 'lxd-images' script.
    For example: 'lxd-images import lxc ubuntu trusty amd64 --alias ubuntu/trusty'.
    LXD socket not found; is LXD running?

```
lxc exec trusty -- stop lxd
lxc exec trusty -- lxd --debug -v
```
    INFO[08-10|20:44:45] LXD is starting. 
    INFO[08-10|20:44:45] Default uid/gid map: 
    INFO[08-10|20:44:45]  - u 0 100000 65536 
    INFO[08-10|20:44:45]  - g 0 100000 65536 
    INFO[08-10|20:44:45] looking for existing certificates:       cert=/var/lib/lxd/server.crt    key=/var/lib/lxd/server.key
    error: permission denied

```
lxc exec trusty -- ls -l /var/lib/lxd/server*
```
    -rw-r--r-- 1 root root 1984 Aug 10 20:44 /var/lib/lxd/server.crt
    -rw------- 1 root root 3243 Aug 10 20:44 /var/lib/lxd/server.key

```
lxc --version
```
    0.15

```
lxc exec trusty -- lxc --version
```
    0.15

**Comment by stgraber** [comment]
Is there any apparmor failure in your kernel log?

**Comment by rcj4747** [comment]
'''Aug 17 13:48:06 guster kernel: [244633.122037] audit: type=1400 audit(1439837286.431:48): apparmor="DENIED" operation="mount" info="failed type match" error=-13 profile="lxc-container-default-with-nesting" name="/var/lib/lxd/shmounts/" pid=19518 comm="lxd" srcname="/var/lib/lxd/shmounts/" flags="rw, bind"'''

**Comment by hallyn** [comment]
Running with a uidmap of range 200000 (to leave room for the default nested 100000..165536 range), with both the default plus a new nested profile:

ubuntu@lxd1:/etc/apparmor.d/lxc$ lxc profile show nested
name: nested
config:
  raw.lxc: |
    lxc.aa_profile=lxd-nesting
    lxc.mount.auto=cgroup
devices: {}

and with this lxd-nested profile:

# Do not load this file.  Rather, load /etc/apparmor.d/lxc-containers, which
# will source all profiles under /etc/apparmor.d/lxc
profile lxd-nesting flags=(attach_disconnected,mediate_deleted) {
  #include <abstractions/lxc/container-base>
  mount /var/lib/lxd/shmounts/ -> /var/lib/lxd/shmounts/,
  mount none -> /var/lib/lxd/shmounts/,
  mount options=bind,
  mount options=(rw,make-rshared),
  mount options=bind /var/lib/lxd/shmounts/** -> /var/lib/lxd/**,
}

allows lxd to start and partially create containers.  The creation now fails because the image untar wants to create devices.
