### ISSUE TITLE
Allow copying containers which have static IP's

### ISSUE THREAD

**Issue by harolds** [lxc/lxd#10114]
When copying a container that has one or more static IP addresses it should not fail with this error:

`Error: Failed creating instance record: Failed initialising instance: Failed to load device to add “eth0”: IP address “10.0.10.4” already defined on another NIC`

I know that I can remove the old IP settings first with this command:

`lxc copy <old> <new> -d eth0,ipv4.address=`

But why not let LXC remove the static IP when there is an conflict? And show a message that it did copy the container but remove the double IP address.

Also see:
https://discuss.linuxcontainers.org/t/unable-to-copy-container-due-to-already-defined-ip-address/13654/13

**Comment by tomponline** [comment]
See also https://github.com/lxc/lxd/issues/10113

I think we need to arrive at a common solution for these scenarios where an old (effectively read-only) config cannot be safely applied to a new instance (such as due to an IP or MAC address conflict) or some other type of device conflict.

Scenarios are:

- `lxc restore` restoring a snapshot that has old invalid config. Currently invalid config is ignored at restore time and enforced at start time, but this could cause problems because it would mean the device is not added correctly or could interfere with another device on an existing instance.
- `lxc import` - see https://github.com/lxc/lxd/issues/10113 (one can modify the config file inside the tarball but its non-trivial).
- `lxc copy` - this particular issue. There is already an established solution to this which is to override the problematic device config using the `-d` flag. This is safe as it prevents the device ever existing with conflicting config and also avoids modifying/removing an explicitly set config key (as opposed to a volatile key) without the user's persmission.

**Comment by tomponline** [comment]
> And show a message that it did copy the container but remove the double IP address.

If we did proceed with transparently altering the instance's config we would probably also need to exist the command with a non-zero exit code (as opposed to just displaying a message) as otherwise people calling the `lxc copy` command via a script would not be able to detect the scenario occurring, and would assume the copy had succeeded normally (which it hadn't).

**Comment by harolds** [comment]
I agree

**Comment by stgraber** [comment]
I'd prefer we move those checks to startup time when possible. It may mean we need to move some of the dnsmasq logic to occur on first start instead then.

**Comment by Viktor-Yakovchuk** [comment]
Let me try to solve it.

**Comment by tomponline** [comment]
I've assigned it to you, thanks!
