### ISSUE TITLE
What is the difference between this project and similar docker hyper project?

### ISSUE THREAD

**Issue by a93ushakov** [lxc/lxd#1019]
[hyper official site](http://hyper.sh)  
[hyper github page](https://github.com/hyperhq/hyper)

**Comment by stgraber** [comment]
LXD is container based, we don't require any kind of virtualization technology, don't have any of that overhead and offer an API which is tailored specifically for containers, instead of attempting to make yet another libvirt which tries to abstract VMs and containers, having to compromise on features and ease of use by trying to abstract everything.
