### ISSUE TITLE
Can't build current 0.16

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#1025]
```
$ go get github.com/lxc/lxd
# github.com/lxc/lxd/shared
go/src/github.com/lxc/lxd/shared/util_linux.go: In function ‘create_pipe’:
go/src/github.com/lxc/lxd/shared/util_linux.go:100:6: warning: implicit declaration of function ‘pipe2’ [-Wimplicit-function-declaration]
  if (pipe2(pipefd, O_CLOEXEC) < 0) {
      ^
```

**Comment by stgraber** [comment]
This is a non-fatal warning and not something particularly new, this pipe2 call has been there for quite a few releases now.

**Comment by tych0** [comment]
We should still `#define _GNU_SOURCE` in that file to get rid of it though. I don't know what exactly causes it, but it seems intermittent (which is extremely weird). Anyway, I can send a patch later today.

**Comment by techtonik** [comment]
Maybe it should be reported upstream to https://github.com/golang/go ?

**Comment by techtonik** [comment]
And also, is it possible to show some message that all is ok at the end?

**Comment by stgraber** [comment]
thanks @tych0 

We could have the Makefile print something yeah, we however don't have any control on what go build prints.

As far as reporting upstream, it's not an upstream go bug, it's likely due to the way includes are processed by your compiler, depending on the order, it'll have the variable set or not at the point it gets to the clone2 syscall. Anyway, as @tych0 said, this is a weird bug but easy enough to fix by doing the right thing and setting GNU_SOURCE.

**Comment by stgraber** [comment]
@tych0 I did it quickly as I was looking at this :)
