### ISSUE TITLE
Unintuitive semantics of lxc copy

### ISSUE THREAD

**Issue by antifob** [lxc/lxd#10291]
# Required information

 * Distribution: Debian
 * Distribution version: sid
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0-3-amd64
   * LXC version: 5.0.0
   * LXD version: 5.0.0
   * Storage backend in use: dir

# Issue description

`lxc copy` has unintuitive semantics. For example, when copying an image from the local server to a remote using `lxc copy local:c1 remote:c1`, the operation fails with `Error: The source server isn't listening on the network`. However, it is possible to copy from a remote server to local using `lxc copy remote:c1 local:c1` and between two (2) remotes without issue `lxc copy r1:c1 r2:c1`. The `--mode` argument allows a local container to be copied to a remote server, but it isn't clear how it works. According to the help message:
```
      --mode                 Transfer mode. One of pull (default), push or relay (default "pull")
```
From a `cp` point of view, the image identified by the first operand should be copied to the destination identified by the second operand. `pull` (the default) has more of a "download"-like semantics, while `push` would be more intuitive, but what is `relay`? I couldn't find documentation the topic.

# Steps to reproduce

```
lxc copy local:c1 remote:c1 # fails
lxc copy remote:c1 local:c1 # succeeds
lxc copy rem1:c1 rem2:c1 # succeeds
lxc copy --mode=push local:c1 remote:c1 # succeeds
```

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
The way LXD migration works is that the CLI tells the target server to connect to the source server.
In your case, your local LXD isn't listening on the network (likely doesn't have core.https_address set) which then prevents the target server from connecting to it.

Your other examples work because both `remote` and `r1` in your examples, do have `core.https_address` set, allowing for the target server to connect to them.

`--mode` can indeed be used to have the CLI reverse the flow or act as a relay. In push mode, it gets temporary credentials from the target server which it feeds to the source server along with the target address. In relay mode, it has both source and target server issue temporary credentials and then connects to both acting as a relay.

All 3 options allow for handling most cases of firewalling and NAT that can occur in the wild. LXD always defaults to `pull` mode as that's the only mode which has always been supported in LXD, push and relay both require reasonably recent LXD versions on both source and target server.

**Comment by antifob** [comment]
Noted. Thanks @stgraber and @tomponline
