### ISSUE TITLE
LXD 5.3 REST API responses do not match Swagger Spec

### ISSUE THREAD

**Issue by alvassin** [lxc/lxd#10628]
[Swagger says](https://linuxcontainers.org/lxd/api/master/#/certificates/certificates_get), if i would request handler (for example `GET /1.0/certificates`) as unauthorized user, i should get following response:

```(json)
{
  "type": "error",
  "error": "not authorized",
  "code": 403
}
```

In fact i got following response (where is `code` field? it is missing). How i can develop clients and rely on this documentation?
```(json)
{
  "type": "error", 
  "error": "not authorized",
  "status": "",  # not present in swagger
  "status_code": 0,  # not present in swagger
  "operation": "",  # not present in swagger
  "error_code": 403,  # not present in swagger 
  "metadata": null  # not present in swagger
}
```

Second example:
```
root@lxd:~# curl --unix-socket /var/snap/lxd/common/lxd/unix.socket lxd/1.0/certificates/2 | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   126  100   126    0     0   123k      0 --:--:-- --:--:-- --:--:--  123k
{
  "type": "error",
  "status": "",
  "status_code": 0,
  "operation": "",
  "error_code": 404,
  "error": "Certificate not found",
  "metadata": null
}
```

[Model does not match](https://github.com/lxc/lxd/blob/54250ef87954803b64ac4baf1beef2ca78330f50/shared/api/response.go#L26) swagger too.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-121-generic
   * LXC version: 5.3
   * LXD version: 5.3

**Comment by stgraber** [comment]
LXD's swagger model is primarily used for documentation purposes and isn't expected to be 100% matching what you're getting on wire.

In this particular case. All those extra fields are using their unset value, they only show up because of how Go structs get turned into JSON. None of those fields have an actual useful value and so weren't included in those manual swagger definitions as they shouldn't be considered by someone implementing an API client.

It'd probably be better if LXD could somehow have those fields be entirely hidden in the response and I remember trying using omitempty for this. The problem is that omitempty would cause a 0 status_code for a response that does use that field to similarly disappear, leading to quite a bit more confusion and breakage than the status quo.

**Comment by alvassin** [comment]
Ok for the extra fields, they do not seem to be critical. But where is `code` field? You've promised it.

**Comment by stgraber** [comment]
I'm looking at what's going on with the code thing.
