### ISSUE TITLE
Review Ceph storage docs

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#10659]
1. In https://github.com/lxc/lxd/pull/10643#pullrequestreview-1031121323 we discussed the original intention around the https://linuxcontainers.org/lxd/docs/master/reference/storage_ceph/#limitations section labelled "Ceph Sharing the OSD storage pool between installations"

Originally it referenced `lxd import` which no longer exists, and @ru-fu changed it to `lxd recover`. 
But as we were not sure what the original intention of that section was for, it would be good for us to review whether the actual statement is still accurate.

2. We are also wondering whether the recommendation to use XFS for setting up a Ceph cluster is A) in scope for our docs and B) still accurate given that filestore isn't recommend anymore. See https://github.com/lxc/lxd/pull/10643#pullrequestreview-1031124175

- [x] Doc fixes (https://github.com/lxc/lxd/pull/10664)
- [x] Mark ceph.osd.force_reuse as deprecated in code comments (https://github.com/lxc/lxd/pull/10666)

**Comment by stgraber** [comment]
The XFS part can be removed entirely. I'm not sure why we ever made this comment as it's really outside of LXD's control. LXD should just expect a properly setup Ceph cluster.

XFS used to be important in the FileStore days prior to the switch to BlueStore, but even then, it feels odd to have that in LXD docs.

On the `lxd import` part. `lxd import` required the volumes be setup on disk and mounted prior to import being possible. In the case of ceph, this apparently required it be first added to LXD. This shouldn't be relevant anymore and `lxd recover` should be able to access a ceph cluster correctly when all settings are passed to it. As a result, this particular config key should be deprecated. We can't remove it from the code because of upgrades and potential older tooling still setting it, but we should remove it from documentation and mark it as deprecated in code comments.

**Comment by tomponline** [comment]
@stgraber looking into this more closely now I've come to deprecate it in the code, I'm not sure we should deprecate it.

LVM has the same option (https://linuxcontainers.org/lxd/docs/master/reference/storage_lvm/#storage-pool-configuration), and its useful when you want to use an existing volume group that has non-LXD volumes on it. This isn't a recommended setup ofcourse, but it still has value (I used it the other day infact).

So for Ceph it makes equal sense, if you have an existing ceph pool setup that has non-LXD volumes on it and you want to use that for a LXD ceph storage pool, you'd need to set `ceph.osd.force_reuse=true`.

I agree that the statement about `lxd import/lxd recover` should be removed, but don't feel that the `force_reuse` setting should be deprecated as its not only used for recovery.

**Comment by stgraber** [comment]
As mentioned in the PR, I disagree. I can't think of a good reason for ever sharing an OSD pool. Those can be dynamically created without needing any additional hardware (unlike LVM) so there's no good reason for it.

In the LVM case, the reason why we allow sharing is because of systems that come installed with LVM where getting dedicated PVs to get a separate VG isn't feasible. Though even then, the expectation is that they have a fixed set of system LVs to which LXD adds a thinpool and additional LVs, if the user then starts to create more LVs by hand, we can't support it.
