### ISSUE TITLE
OverlayFS and readonly filesystem?

### ISSUE THREAD

**Issue by emilebosch** [lxc/lxd#1068]
Hi,
we're spawning LXD containers quite fast and often for our solution. We are wondering if it was possible to use overlay FS to save disk space and make faster `launch` experiences. 

Do you have any recommendations on how to use this? I've tried searching for it but i can't find anything. Thanks much.

**Comment by stgraber** [comment]
If you're using the API directly, you can ask LXD to create a container without creating its filesystem, then you're free to setup overlayfs yourself.

Note however that overlayfs isn't a very good filesystem to run a full container on at this point, its lack of inotify support tends to break a lot of things (anything which looks for file/directory changes) so that's why we're not directly supporting it in LXD.

Currently our fastest backend is btrfs with LVM being second (a bit longer as it must resize the filesystem of the container). We plan on adding ZFS support soon which should be about as fast as btrfs but be a bit more production-ready.

**Comment by tomposmiko** [comment]
ZFS:

Cool, when?
Will migration be implemented with send/recv?

**Comment by emilebosch** [comment]
Thanks @stgraber! Does btrfs allow the same kind of overlay, and fast cloning/new'ign as overlay fs? That would  be perfect! Thanks.

**Comment by stgraber** [comment]
btrfs doesn't provide you with an overlay per say, but it's copy-on-write at the block level, so when cloning a subvolume, the subvolume copy uses no disk space and the copy itself is instantaneous.

It's actually slightly better than an overlay in the sense that if the source subvolume changes, the target will not change, so no risk of random breakage if the source is modified or removed somehow.

**Comment by stgraber** [comment]
@tomposmiko no clear when yet as it's not a priority for us for Ubuntu 15.10, but it's something we'll have for Ubuntu 16.04. In practice, I expect we'll just land support for it when one of us is bored, so probably in the next month or so.

As for send/receive, yes, our intention is to use native send/receive for both zfs and btrfs.

**Comment by emilebosch** [comment]
@stgraber Thanks for the update. Any pointers on how to setup lxd with btrfs. I'm trying to find it in the manual but can't seem to find it.

**Comment by stgraber** [comment]
lxd will automatically use btrfs if /var/lib/lxd is on a btrfs filesystem.

Assuming your root filesystem isn't, you can do something like this:
 - apt-get install btrfs-tools
 - truncate -s 50G /var/lib/lxd.img
 - mkfs.btrfs /var/lib/lxd.img
 - echo "/var/lib/lxd.img /var/lib/lxd btrfs loop,defaults 0 0" >> /etc/fstab
 - mount /var/lib/lxd
 - restart lxd (if Ubuntu 14.04) or systemctl restart lxd (otherwise)

Note that the above will hide anything that's already in your /var/lib/lxd, so if you have any existing containers, you may want to move that data around too.

**Comment by tomposmiko** [comment]
Awesome, then I will start using LXD and would be happy to provide feedback, if anything notable come up:)

Thanks!

**Comment by emilebosch** [comment]
BTRFS works like a charm. If everyone is fine with this i can close the issue.

**Comment by stgraber** [comment]
Fine with me.
