### ISSUE TITLE
lxc launch with remote prints hash error

### ISSUE THREAD

**Issue by rrva** [lxc/lxd#1083]
lxc remote add images images.linuxcontainers.org
    lxc launch images:fedora/22/amd64

    error: Only full and short (12 chars) hashes are supported by this server

    lxc --version
    0.17

**Comment by rrva** [comment]
Above was on ubunty wily with package lxd-client 0.17-0ubuntu1.

When doing the same with manually built lxc client on OSX from git today:

    lxc remote add myhost myhost:8443
    lxc remote add images images.linuxcontainers.org
    lxc launch myhost: images:centos/7/amd64
    
    error: json: cannot unmarshal array into Go value of type shared.ImageInfo

**Comment by stgraber** [comment]
Hi,

The first error comes from you trying to use an image which doesn't exist "fedora/22/amd64" (the image server doesn't have any fedora image).

The second error comes from you trying to start a new remote container called "centos/7/amd64" on read-only host "images" from an unnamed image stored on "myhost".

I suspect you instead wanted: lxc launch images:centos/7/amd64 myhost:

**Comment by stgraber** [comment]
Note that the error message coming from images.linuxcontainers.org is very generic due to the fact that it's not a real LXD server but instead a static apache2 server doing its best to pretend to be a LXD server. That means returning generic json errors which can be misinterpreted by the client, leading to the confusing errors that you got.

**Comment by stgraber** [comment]
There's however a bug in the client in that:

    lxc launch local: abc

Should fail saying that no image hash or alias was provided, instead of the confusing json error.
