### ISSUE TITLE
user-data gets broken replacing %s with %!s(MISSING) - focal/lxd 4.0.9

### ISSUE THREAD

**Issue by hmlanigan** [lxc/lxd#10951]
Can we please get the fix for #10231 back ported to the 4.0/stable channel?

This is now preventing juju users from bootstrapping juju with focal and lxd 4.0.9. 
https://bugs.launchpad.net/juju/+bug/1990594

Juju is also working on some changes, but they will not help without upgrades.

**Comment by stgraber** [comment]
So this is in LXD 4.0 which is our prior LTS release. Our support policy is that only the current LTS gets bugfixes backported.

Given how trivial this one is, I've pushed a backport to the stable-4.0 branch as well as to 4.0-candidate in the snap package.
However chances are that neither of those will even remotely pass our current CI and it may be a few weeks before we find the time to sort out any issue there and likely a few more weeks after that for us to be confident that we're not causing any regression by pushing this to our users.

Short of a minor miracle (given we haven't touched the 4.0 branch in months) and all tests passing on the first go, I wouldn't expect this to hit stable users until mid-November (mostly due to us not pushing during travel/sprints).

**Comment by tomponline** [comment]
Back port commit: https://github.com/lxc/lxd/commit/2c5b0078a0e84ab62c9494e32e131d0686bb0c18
