### ISSUE TITLE
Root access for joining a cluster

### ISSUE THREAD

**Issue by ru-fu** [lxc/lxd#10990]
Running `lxd init` interactively to join an existing cluster requires root access.
However, when using a preseed file for initialization and running `cat <preseed-file> | lxd init --preseed`, root access is **not** required.

Originally, running `lxd init` needed root access to introspect the available storage engines, but this changed a while ago.
So maybe root access isn't needed for `lxd init` anymore, and the requirement should be removed when running `lxd init` interactively?

**Comment by stgraber** [comment]
Basically when you use the preseed, you feed LXD with all the data needed in one go, including data that would normally require root access to get.

When not using the preseed,`lxd init` will open `server.crt` and `server.key` in order to connect to the prospective target cluster (during a cluster join operation). This cannot be done by non-root users.

**Comment by tomponline** [comment]
Thanks for confirming @stgraber
