### ISSUE TITLE
stable-5.0: Two new dependencies not in 5.0.1 LTS

### ISSUE THREAD

**Issue by gibmat** [lxc/lxd#11266]
I saw that @stgraber added a bunch of commits to stable-5.0 today, so I pulled that branch as of commit 0da53e24664af2ee71a744607d0af7369889cb77 into the Debian packaging to do a test build and see if there were any issues prior to the 5.0.2 release. (I don't know if there are additional commits coming for stable-5.0, but can easily fetch them if there are.)

It appears that there are two new dependencies in LXD 5.0.2 that weren't in 5.0.1:

* github.com/checkpoint-restore/go-criu/v6 (commit 63eb82717a8ed0fe70e8b191e12d3be0c0319081)
* github.com/minio/minio-go/v7 (commit 9758d73d5bc2a6690f352f8ed230814488ada499)

Are those two commits appropriate for a LTS release? Adding a cephobject storage driver looks like a new feature, and while it might be nice to use the criu library rather than custom code, did that commit fix any bug?

The Debian bookworm transition freeze begins on Thursday of this week, so we're pretty much settled on whatever versions of library packages that will be in that release. minio-go/v7 is packaged, and it's trivial to add as a new build dependency, but go-criu is still at v5. (I had previously looked at updating to v6, but there are a few other packages that weren't quite ready for v6 yet.) Thankfully it's trivial to (potentially) revert that one commit, but that would introduce a delta between Debian's packaging and the upstream release which I'd like to try to avoid if at all possible.

Other than that, stable-5.0 builds fine and all its tests pass, so it's looking good.

**Comment by stgraber** [comment]
`minio` isn't actually used in LXD 5.0.1 as we do not backport major features like the object storage support.

However it does show up as a dependency through the `lxd/storage/drivers` package. Those leaf packages are kept in sync with our latest release whenever possible to simplify maintenance and mostly reduce the risk of bad cherry-picks.

In the case of the CRIU change. It's hard to tell if it actually fixes bugs given the general brokeness of our CRIU support in general. It's again a case where this reduces the delta with our current release which means an easier and less risky time backporting other bugfixes.

I wonder if you can easily just build with the older go-criu found in Debian as that would just be a tiny change to go.mod rather than the larger change needed for reverting the commit switching from our own implementation to go-criu's.

Note that the current state of stable-5.0 is broken. We have tests failing on both ZFS and Ceph which we'll be looking into tomorrow and we still have another 350 commits or so to go through before we're ready for 5.0.2. I just decided to push what I had at the end of the day so we could get as much CI as possible running on it, as well as make it easier for @ru-fu and @tomponline to prepare backported versions of some commits I need to unblock the remaining backports.

**Comment by gibmat** [comment]
> However it does show up as a dependency through the `lxd/storage/drivers` package. Those leaf packages are kept in sync with our latest release whenever possible to simplify maintenance and mostly reduce the risk of bad cherry-picks.

OK, so they're basically along for the ride, even if they aren't actually being used. Since the minio library is available, it's not a problem to just add it as a build dependency.

> I wonder if you can easily just build with the older go-criu found in Debian as that would just be a tiny change to go.mod rather than the larger change needed for reverting the commit switching from our own implementation to go-criu's.

Unfortunately the `crit.GetDumpStats(path)` method wasn't added until go-criu version 6.1.0.

> Note that the current state of stable-5.0 is broken. We have tests failing on both ZFS and Ceph which we'll be looking into tomorrow and we still have another 350 commits or so to go through before we're ready for 5.0.2. I just decided to push what I had at the end of the day so we could get as much CI as possible running on it, as well as make it easier for @ru-fu and @tomponline to prepare backported versions of some commits I need to unblock the remaining backports.

Great, I'll keep an eye out for additional commits that land in the stable-5.0 branch!

**Comment by stgraber** [comment]
> Unfortunately the `crit.GetDumpStats(path)` method wasn't added until go-criu version 6.1.0.

Ah, that's annoying. So yeah, I guess a clean revert of that commit will probably be the way to go for now.
We're likely to be doing more CRIU fixes over the next few months as we recently had @mihalicyn join the LXD team, bringing quite a lot of CRIU expertise both in userspace and kernel space, so we're hoping to get our CRIU support back to something vaguely useful at least. Those will most likely be considered bugfixes and so likely to hit a future 5.0.x release.

However as most of our CRIU interactions come through liblxc rather than from LXD directly, except for the incremental dump logic that just go moved to go-criu, it's quite possible that we won't have to touch that chunk of code again.

**Comment by gibmat** [comment]
There was a third additional new dependency in the 5.0.2 release: k8s.io/utils. It's packaged for Debian, so wasn't a problem to add to the build deps.

The lxc/lxcfs/LXD LTS releases from earlier today are currently building in Debian -- thanks!

**Comment by stgraber** [comment]
@gibmat thanks!
