### ISSUE TITLE
Unsetting `features.*` for a project always sets it to false, even if the default is `true`

### ISSUE THREAD

**Issue by ru-fu** [lxc/lxd#11491]
Several `features.*` options have a default value of `true` according to https://linuxcontainers.org/lxd/docs/stable-5.0/projects/.
However, this default value is only used at create time and not when unsetting the respective option.

```
ubuntu@vm10:~$ lxc project show test
config:
  features.images: "true"
  features.profiles: "false"
  features.storage.volumes: "true"
description: ""
name: test
used_by: []
ubuntu@vm10:~$ lxc project set test features.images=false
ubuntu@vm10:~$ lxc project unset test features.images
ubuntu@vm10:~$ lxc project show test
config:
  features.profiles: "false"
  features.storage.volumes: "true"
description: ""
name: test
used_by: []
```

Now I would expect `features.images` to go back to the documented default value `true`, but no:

```
ubuntu@vm10:~$ lxc project list
+----------------+--------+----------+-----------------+-----------------+----------+---------------+---------------------+---------+
|      NAME      | IMAGES | PROFILES | STORAGE VOLUMES | STORAGE BUCKETS | NETWORKS | NETWORK ZONES |     DESCRIPTION     | USED BY |
+----------------+--------+----------+-----------------+-----------------+----------+---------------+---------------------+---------+
| test           | NO     | NO       | YES             | NO              | NO       | NO            |                     | 0       |
+----------------+--------+----------+-----------------+-----------------+----------+---------------+---------------------+---------+
```

**Comment by sri-srikanth** [comment]
Hey!
I am a Computer Science student at the University of Texas at Austin taking a Virtualization course. My two groupmates and I were wondering if we could contribute to resolving this issue. Please let me know if this would be possible and we can get started.

**Comment by ru-fu** [comment]
https://linuxcontainers.org/lxd/docs/latest/reference/projects/#project-features has been updated now to explain this and include an "initial value" column to work around this problem, but having a real default would still be preferrable.

**Comment by stgraber** [comment]
Yeah, it's not very different from say ipv4.address/ipv4.nat or ipv6.address/ipv6.nat in the network case where we similarly have a default value but also inject another value when not initially specified.

**Comment by presztak** [comment]
Can I work on this?

**Comment by stgraber** [comment]
Absolutely!

It should be reasonably straightforward. We want them being unset to be equal to having them set to false.
But when creating a project, any project feature that's not specified should still be added using the default value.

**Comment by presztak** [comment]
@ru-fu @stgraber

I'm a little bit confused :)

"Defaults" from here https://linuxcontainers.org/lxd/docs/stable-5.0/projects/ correspond "initial values" from here https://linuxcontainers.org/lxd/docs/latest/reference/projects/#project-features.

 but the code is working in following way:
 1. When we create project these values are used:
 https://github.com/lxc/lxd/blob/7d42686b86dc293f6157c205bd10205f55983c30/lxd/db/cluster/projects.go#L49-L66
 2. When we unset project feature we set it as empty(false)

The question is what should be right behaviour?

**Comment by stgraber** [comment]
> But this is what we currently have?
> When creating a project, the values are set to the "initial value", not the default value.
> When unsetting any of the keys, it is set to `false`, no matter what the "initial value" is. So the default is actually `false`, and not the initial value - which I find counter-intuitive.

Oh yeah, you're right, it's what we're trying to fix here!

Now thinking about it some more, it's a bit tricky.

Basically, we do have a default set of features that we want new project to have.
However, this may not be the same set of features that we want to impose on existing projects, nor can some of those features even be turned on on existing projects.

So the issue now is that if we introduce `features.foo` in a week and we want it on for new projects but not for existing ones.
It makes it effectively forces us to introduce a DB migration step which injects a `features.foo=false` for all existing projects.
And has the other side effect of having anyone who has so far scripted the creation of additional projects, whether it's our upcoming LXD UI or an API script, to be updated immediately every time a new feature is added, otherwise their logic will result in the feature now being enabled when they may not intend for it to be.


I'm starting to think that the best here may actually be the status quo. Going down that path, we may actually want to just remove the `default` column from that particular doc page, instead only keeping the `initial value` column and add a small paragraph explaining that on new project creation, all features will get their `initial value` unless specified directly and that when a new feature is introduced it only affects new projects.

@ru-fu @tomponline what do you think?

**Comment by tomponline** [comment]
@stgraber I think sticking with the concept of "initial" is a good idea. I find it a lot easier to reason about if the absence of a project feature means its `false` (i.e its "default" is `false), and then any features we feel should be enabled automatically for new projects are explicitly set to `true` initially at creation time.

**Comment by tomponline** [comment]
> I think the docs we have now work, but what we had before was definitely wrong. And I fear we have more places where the concept of a "default value" is used wrongly. So we need to be very clear about default values and initial values in the docs if we use different values for both.

Yes there are some places that good do with clarification in the docs agreed. One such example I can think of is `ipv{n}.address` and `ipv{n}.nat`. These have initial values that are different from their default values.

e.g.

```
lxc network create lxdbr1
lxc network show lxdbr1
config:
  ipv4.address: 10.195.140.1/24
  ipv4.nat: "true"
  ipv6.address: fd42:b218:720:f6db::1/64
  ipv6.nat: "true"
```

**Comment by stgraber** [comment]
Yeah, ipvX.address and ipvX.nat are as far as I can think of the only other place where we inject config the user may not have provided and then behave differently when unset.

In that particular case the logic is:
 - If no address provided on creation, initial value is `auto`.
 - If address is set to `auto` and the matching nat key isn't set, then it will be set to `true`.
 - Default value for nat is `false` and an empty value is the default for address
