### ISSUE TITLE
Better handle filesystem shrink failure on creation

### ISSUE THREAD

**Issue by morphis** [lxc/lxd#11506]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.19.0-35-generic #36~22.04.1-Ubuntu
   * LXC version:
   * LXD version: 5.12
   * Storage backend in use: ZFS

# Issue description

When starting a container based on an Anbox Cloud image with ZFS block mode on the storage pool enabled we get the following error:

```
$ lxc launch test t0 -d root,size=3GB
Creating t0
Error: Failed creating instance from image: Failed to run: resize2fs /dev/zvol/local/containers/t0 2929688K: exit status 1 (resize2fs 1.46.5 (30-Dec-2021)
resize2fs: New size smaller than minimum (1164811)
```

The image `test` was imported with

    lxc image import ~/Downloads/anbox-lxd-jammy-android13_1.18.0-alpha.152+gitd00ea452_amd64.tar.xz --alias test

The output for `zfs list` of the storage pool in question looks after the failed container start as follows

```
local                                                                                               2.31G  94.1G       24K  legacy
local/buckets                                                                                         24K  94.1G       24K  legacy
local/containers                                                                                      24K  94.1G       24K  legacy
local/custom                                                                                          24K  94.1G       24K  legacy
local/deleted                                                                                        144K  94.1G       24K  legacy
local/deleted/buckets                                                                                 24K  94.1G       24K  legacy
local/deleted/containers                                                                              24K  94.1G       24K  legacy
local/deleted/custom                                                                                  24K  94.1G       24K  legacy
local/deleted/images                                                                                  24K  94.1G       24K  legacy
local/deleted/virtual-machines                                                                        24K  94.1G       24K  legacy
local/images                                                                                        2.30G  94.1G       24K  legacy
local/images/4da8f1b742d9476263855f4b761f4fac125bef0029e6b426c27334921b777b45_ext4                  1.63G  94.1G     1.63G  -
local/images/72565f3fbae414d317b90569b6d7aa308c482fdf562aaf0c2eaa6e50fa39747b_ext4                   689M  94.1G      689M  -
local/virtual-machines                                                                                24K  94.1G       24K  legacy
```
Creating the container with a higher default root disk size makes the creation work

```
$ lxc launch test t0 -d root,size=5GB
Creating t0

The instance you are starting doesn't have any network attached to it.
  To create a new network, use: lxc network create
  To attach a network to an instance, use: lxc network attach

Starting t0
```

Trying to reproduce the same with a standard Ubuntu image is not possible and works as expected. I guess the size of the image is one of the reasons we're seeing this here. The used image is around 741MB in size.

**Comment by tomponline** [comment]
@morphis this is caused by the heuristics for minimum size calculation in resize2fs not 100% accurate.

See https://bugzilla.redhat.com/show_bug.cgi?id=506740

> The minimum size calculation has a fair bit of slop in it, as the real answer is fairly hard to get to.  You need to factor in some worst-case scenarios that may not play out, and after you resize to something in the middle, the worst-case is reduced, so a subsequent resize may go smaller. 

In the case of `images:ubuntu/jammy` image, as @monstermunchkin the minimum size we can get to in first pass is 800MiB but if you do that you can then do a subsequent shrink down to 747MiB.

So I don't think there is much we can do here I'm afraid.

**Comment by stgraber** [comment]
@tomponline I thought we once discussed having a standard error for the resize call in such a scenario which on failure would cause us to hit the fill logic again bypassing the parent image.

**Comment by stgraber** [comment]
So basically the driver would throw a ErrShrinkFailure which the backend would then catch, log a warning and then proceed to create an empty volume and call the image filler again, trying to unpack it fresh.

**Comment by stgraber** [comment]
@tomponline I'm keeping this as a bug rather than a new feature as the fact that the same image can fit within the quota if setup differently feels like a bug. But given that fixing that bug would not provide good performance in @morphis's case, I don't think it's urgent to fix.

**Comment by stgraber** [comment]
Other than the fix above, I've been thinking at better ways to handle this whole thing in general but I can't think of anything that'd improve on status quo.

I thought of:
 - When getting ErrShrinkFailure, do a fresh unpack in a new temporary volume, if that succeeds at the lower size, then replace the existing volume for the image with that new smaller one. The issue here is that all image launches that don't specify a size will now trigger a growth operation, allowing a random user on the system to effectively cause every other instance launch to burn additional CPU.
 - Have images defined their desired volume size. In theory that's ideal, but the issue is that this may conflict with a variety of things including `volume.size` being set on the pool, the storage driver requiring a different minimum size, a default profile with a different size, ... that may introduce a bunch of extra confusion in an area that's already quite confusing.
 
Something else that may be interesting is to see if there aren't some ext4 flags or something we can do in the image unpack logic to effectively do a better job packing the data efficiently on the partition, increase the chances of the shrink operation to succeed.

**Comment by tomponline** [comment]
Yes we have support for returning `ErrCannotBeShrunk` from the driver's `CreateVolumeFromCopy` which will then trigger a new empty volume to be created and the image unpacked into it. So the only thing we need to do is somehow detect that specific resize2fs error and translate it into ErrCannotBeShrunk. Looking now...

**Comment by tomponline** [comment]
I've also noticed that there are some other bugs in the ZFS driver related to block mode:

- When resize2fs fails the ZFS volume is left behind on disk.
- When the conflicting volume is then being created, the ZFS command blocks asking a question on stdin, rather than failing.

So will look at those too.

**Comment by tomponline** [comment]
> Something else that may be interesting is to see if there aren't some ext4 flags or something we can do in the image unpack logic to effectively do a better job packing the data efficiently on the partition, increase the chances of the shrink operation to succeed.

@stgraber I found something we've used before with resize2fs to use the `-f` flag which disables some pre-resize safety checks. This allows for getting the filesystem much smaller, and is appropriate to use in this case because if resize2fs fails and leaves the volume inconsistent it doesn't matter as we just delete the volume anyway.

``` 
lxc init images:ubuntu/jammy c1 -s zfs -d root,size=600MiB
Creating c1
Error: Failed instance creation: Failed creating instance from image: Failed to run: resize2fs -f /dev/zvol/zfs/containers/c1 614400K: exit status 1 (resize2fs 1.46.5 (30-Dec-2021)
resize2fs: No space left on device while trying to resize /dev/zvol/zfs/containers/c1
Please run 'e2fsck -fy /dev/zvol/zfs/containers/c1' to fix the filesystem
after the aborted resize operation.)
```

```
lxc init images:ubuntu/jammy c1 -s zfs -d root,size=650MiB
Creating c1
lxc exec c1 -- df -h
Filesystem                   Size  Used Avail Use% Mounted on
/dev/zvol/zfs/containers/c1  558M  514M     0 100% /
none                         492K  4.0K  488K   1% /dev
tmpfs                        100K     0  100K   0% /dev/lxd
tmpfs                        100K     0  100K   0% /dev/.lxd-mounts
tmpfs                        7.7G     0  7.7G   0% /dev/shm
tmpfs                        3.1G  8.1M  3.1G   1% /run
tmpfs                        5.0M     0  5.0M   0% /run/lock
tmpfs                        4.0M     0  4.0M   0% /sys/fs/cgroup
```
