### ISSUE TITLE
Error when list storage volume names for all projects (client)

### ISSUE THREAD

**Issue by markylaing** [lxc/lxd#11607]
`(*ProtocolLXD).GetStoragePoolVolumeNamesAllProjects` fails with `Unexpected URL path "/1.0/storage-pools/default/volumes/container/{containerName}?project={projectName}".

This is because `u.String()` is passed into `urlsToResourceNames` [here](https://github.com/lxc/lxd/blob/f8330b39bba3a1903d2973debe5b96fb3db5f210/client/lxd_storage_volumes.go#L57). Unfortunately `u.String()` contains `all-projects=true` so splitting on this always results in an error.

An easy fix for this issue would be to pass `u.URL.Path` into `urlsToResourceNames` as the `pathMatchPrefix` argument. However, this will still omit the project name from the resulting list of resources.

@tomponline @stgraber when a client method is listing resources for all projects, should we include the project name in the resource? If so, should we add it as a query parameter. For example, `container/{containerName}` will become `container/{containerName}?project={projectName}`

**Comment by tomponline** [comment]
I'll take a look at this tomorrow and come back to you.

**Comment by tomponline** [comment]
I think we need to fix both parts. Changing the return value of `GetStoragePoolVolumeNamesAllProjects` to `map[string][]string` so that the project name can be ascertained, as well as allowing the ability to differentiate between volumes of the same name in different projects.

We can then iterate through the URLs returned from the API, parse them like `urlsToResourceNames` does, but only use the path part of the URLs to prefix match against the path part of the API URL used.
