### ISSUE TITLE
second level nested container has issue with snap, apparmor and permissions

### ISSUE THREAD

**Issue by iamnswamyg** [lxc/lxd#11738]
# Required information
 * Distribution: Ubuntu 22.04 LTS
 * Distribution version: jammy
 * The output of "lxc info" or if that fails:
 ```
Could not execute systemctl:  at /usr/bin/deb-systemd-invoke line 142.
 snapd.failure.service is a disabled or a static unit, not starting it.
 snapd.mounts-pre.target is a disabled or a static unit, not starting it.
 snapd.mounts.target is a disabled or a static unit, not starting it.
 snapd.snap-repair.service is a disabled or a static unit, not starting it.
```
   * Kernel version: 22.04
   * LXC version: 5.13
   * LXD version: 5.13
   * Storage backend in use: dir

# Issue description

I am trying to create a container within container. Please find the repo here which i used to create the scenario. I am able to create an lxd container on my host level and with in the container in the host which is 1 level depth. But the next level I am unable to run lxd successfully since snap is not working because of **AppArmor policy permission** is denied. Lxd has been installed but connection to **http://localhost/v2/snaps/lxd** is getting refused. 

# Steps to reproduce

 1. Step one : pull the repo from [here](https://github.com/iamnswamyg/lxd-infra-hub) 
 2. Step two : within lxd-infra-hub, run ./provision.sh
 3. Step three: once the **infra-nested**  container is launched, go into container bash using `lxc exec infra-nested /bin/bash`
 4. Sep four: got /workdir/lxd-in-lxd within container, and run ./provision.sh
 5. Step five: You would see the error I mentioned above in the level two container. 

The last error that you will notice and evident is:
```
Failed to open connection to "system" message bus: Failed to query AppArmor poli
cy: Permission denied
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
error: cannot communicate with server: Post "http://localhost/v2/snaps/lxd": dial unix /run/snapd.socket: connect: connection refused
```

Finally, I read that we can do container nesting to any level in this [post.](https://ubuntu.com/blog/nested-containers-in-lxd) and I followed the guidelines. You can use the cleaup script both at host level and in container level to remove all the containers and profile attached to it.

**Comment by stgraber** [comment]
The problem is that apparmor namespaces do not support nesting at this point.

So the first level container has a fully functional apparmor allowing for loading of profiles as needed by both snapd and LXD.
The second level container cannot do that and is instead locked into a single apparmor profile.

LXD can kinda cope with this by just re-using the same profile as its parent container but snapd cannot work in such an environment and apparmor also acts a bit weirdly in general as the container doesn't get to run updated version of the profiles for the various commands that should run confined.
