### ISSUE TITLE
VMs shown as stopped after a while, can't get started

### ISSUE THREAD

**Issue by grebennikov** [lxc/lxd#11741]
lxd 5.13 from stable

I had a couple of VMs running, after about a week they shown as stopped.
ps shows the process of the VM running on the hypervisor, consequently if I try to start the VM with lxc I get "vhost-vsock: unable to set guest cid: Address already in use"

Same as in https://discuss.linuxcontainers.org/t/vhost-vsock-unable-to-set-guest-cid-address-already-in-use/6762 (back form 2020)

**Comment by stgraber** [comment]
Can you look at `/var/snap/lxd/common/lxd/logs/NAME/qemu.log`?
The most common case of this happening has been when QEMU crashes for some reason (process still around but hit a panic/assert).

I believe LXD 5.14 has a tweak for that particular case though, so this may not be an issue anymore.
@tomponline do you recall what change in 5.14?

**Comment by grebennikov** [comment]
This is the entire content of the log:

qemu-system-x86_64:/var/snap/lxd/common/lxd/logs/n3/qemu.conf:115: vhost-vsock: unable to set guest cid: Address already in use

**Comment by stgraber** [comment]
Ah, that'd be from when you tried starting it back up again, this likely had qemu overwrite the previous log which is the one we'd have liked to see. If you have any other STOPPED instance that's actually running and which you haven't touched yet, please look at its log as that may tell us what happened to qemu.

**Comment by tomponline** [comment]
What os are the guests running btw?

**Comment by tomponline** [comment]
> I believe LXD 5.14 has a tweak for that particular case though, so this may not be an issue anymore.
> @tomponline do you recall what change in 5.14?

There are a variety of ways that QEMU can crash or stop responding:

- The process ends unexpectedly or the QMP socket disconnects - this will be detected in LXD 5.14 and the host-side device cleanup will trigger, which will then clean up any host-side resources allocated for the VMs (mounts, NICs etc). https://github.com/lxc/lxd/pull/11700
- Sometimes due to an underlying disk I/O error, the QEMU process can be running, QMP can be responding, but not actioning commands, for example not stopping the VM forcefully when requested. In LXD 5.14, if a VM is forced stopped, LXD will give it 30s to disconnect from QMP after the `quit` command has been sent before LXD will forcefully kill the process, triggering the host-side clean up as if it had ended unexpectedly (above). https://github.com/lxc/lxd/pull/11725
- There are other potential scenarios still unhandled, such as a connected, but unresponsive (blocking) QMP socket. For this we would need to contribute to the upstream QMP package to add support for context/timeouts on requests, as these can otherwise block indefinitely.

However in these cases I would expect the VM to be showing in an `ERROR` state rather than a `STOPPED` state. 
VMs in an `ERROR` state can be forced stopped, but those in `STOPPED` cannot.

@grebennikov as @stgraber said above it would be good to see the contents of `/var/snap/lxd/common/lxd/logs/<instance>/qemu.log` after it has switched to `STOPPED` before trying to start it again.

**Comment by tomponline** [comment]
Thanks @grebennikov it would also be useful to see the output of `ls -l /var/snap/lxd/common/lxd/logs/<instance>` along with the output of `ps aux` showing the running QEMU process, and finally the contents of `/var/snap/lxd/common/lxd/logs/<instance>/qemu.pid` to check they all match up.
