### ISSUE TITLE
API endpoint containers files doesn't have an attribute for directory files.

### ISSUE THREAD

**Issue by laikee99** [lxc/lxd#11770]
There is no file attribute like size, modify_date or is the item a file or a dir,
Is it possible for us to get these attribute from the endpoint? Thanks.

**Comment by laikee99** [comment]
I know there is a HEAD method to fetch meta data for one file, but is there any way to make it response all files' meta data in one time to make the response save more effects?

**Comment by stgraber** [comment]
We probably wouldn't refuse a pull request to add more headers for some of that data, so long as it doesn't impact performance and doesn't otherwise change the response content itself.

However, we have introduced a much more comprehensive file API a little while back which will provide you with everything that you need already. It's the SFTP based file API: https://linuxcontainers.org/lxd/docs/latest/api/#/instances/instance_sftp

This allows you to easily perform bulk operations, retrieve all the normal file details, directories, symlinks, ... in a much more efficient and reliable way.

For Go developers, https://pkg.go.dev/github.com/lxc/lxd/client#ProtocolLXD.GetInstanceFileSFTP lets you get a Go `sftp.Client` which then supports all the methods that you'd like. https://pkg.go.dev/github.com/pkg/sftp#Client

Other languages may have similar native SFTP implementations that you can leverage.
