### ISSUE TITLE
. is no longer allowed in container name

### ISSUE THREAD

**Issue by jsimonetti** [lxc/lxd#1184]
I noticed since lxd-0.19 a dot is no longer allowed in a container name.
Is there a specific reason for this? I am used to naming the container after the FQDN of the system inside.

Edit: this was changed in bbf6380acc937bf4df302b3da82088954e428107
I suppose I will have to come up with a naming scheme, but limiting the container name to 63 characters makes it somewhat hard to give them descriptive names, especially if you have multiple containers with an identical function.
For example, I have a webserver01 for domain example.org, what do i call webserver01 for another domain?

**Comment by stgraber** [comment]
That's because the LXD container name is set as the UTSNAME (hostname) of the container on startup. There are also users who generate DNS records in the form of containername.lxd so when implementing container name validation I went with the intersection of the most restrictive definition of an hostname for all the OSes I'm aware of and the most restrictive definition of the beginning of a DNS record.

If we ever split the container hostname from the container name, then we could possibly relax the restriction a bit, but until then we have to apply this restriction to avoid getting bug reports of random breakages on a platform or another depending on exact OS, kernel version and resolver library.

As for your container, you could call it something like "example-webserver01" or "example-org-webserver01", both of which are valid names.

**Comment by jsimonetti** [comment]
OK, that makes sence. Following RFC1123 makes sence in that regard. Thanks for clearing it up.
