### ISSUE TITLE
stopping lxd also stops all containers

### ISSUE THREAD

**Issue by jsimonetti** [lxc/lxd#1223]
When stopping lxd, all containers are also stopped.
This looks to me like unwanted behaviour, though I can understand if it is needed.
This makes upgrading lxd hard and needs to be planned during maintenance hours.

**Comment by stgraber** [comment]
This has to do with distro packaging and some limitations of existing init systems like systemd.

LXD itself will not stop containers on exit, it will only do so when it receives SIGPWR which is what the systemd unit in Ubuntu does.

Ideally we'd have systemd pass SIGPWR during host shutdown and do a regular SIGTERM in other cases, but this doesn't appear to be possible, at least not in any document kind of way...

Closing this LXD issue since LXD itself supports both and does the right thing by default, it's only limitations of the init system which prevents from using this properly :(

**Comment by stgraber** [comment]
You could file a bug against lxc/lxd-pkg-ubuntu where the systemd unit lives. As I said, I'm not aware of any way to distinguish from "systemctl stop lxd" or "systemctl restart lxd" and the same action being triggered at host shutdown, but having an issue for it would be worthwhile nonetheless.
