### ISSUE TITLE
Guide for nesting

### ISSUE THREAD

**Issue by plenderyou** [lxc/lxd#1229]
I watched with interest the talk Stéphane Graber gave demonstrating lxd and would like to use it but I need to set up a test environment where I nest containers in a container.

I've tried all the usual sources and have gotten to the point where I get this error

Creating fred error: Failed to change ownership of: /var/lib/lxd/containers/fred/rootfs

inside the nested container.

I know it's something stupid but I can't figure out how to nest are there any articles/wiki pages etc where this is explained?

**Comment by tych0** [comment]
On Wed, Oct 21, 2015 at 08:28:28AM -0700, Peter Lenderyou wrote:
> I watched with interest the talk Stéphane Graber gave demonstrating lxd and would like to use it but I need to set up a test environment where I nest containers in a container.
> 
> I've tried all the usual sources and have gotten to the point where I get this error
> 
> Creating fred error: Failed to change ownership of: /var/lib/lxd/containers/fred/rootfs
> 
> inside the nested container.
> 
> I know it's something stupid but I can't figure out how to nest are there any articles/wiki pages etc where this is explained?

Have you set the security.nesting=1 flag in your host container's config?

**Comment by plenderyou** [comment]
Yes I have, I read that in one of the issues [#1093]
before that it wouldn't even start lxd.

The main container is unprivileged, and there was also comments about not propagating the /dev system, but it's all a bit of a mystery.

**Comment by hallyn** [comment]
Hi,

Can you show the configuration of the main container, and the root entries in /etc/subuid and /etc/subgid?

My guess is that your main container is unprivileged and with a uid range which is not large enough to encmpass the uid range you hand the child container.

For instance if the main container only has 65k uids, and your main container wants to hand uids 100000-165535 to its nested container, it can't do that because those uids aren't available.

So if this is the case, you can just update the root subuid/subgid entries on the host to increase the last number (the range), i.e. something like

root:100000:200000 (or replacing 100000 with whatever that number is now

**Comment by plenderyou** [comment]
Ok,

I think I've done what you ask but it still doesn't work:

I've tried with security.nesting = 1 and true

my host user is plenderyou and I have these on the subuid/subgid files.

vagrant:100000:65536
odobo_deployer:165536:65536
odobo_deployment:231072:65536
odobo_connect:296608:65536
lxd:362144:65536
root:362144:200000
plenderyou:562144:200000

and these on the remote
ubuntu:100000:65536
lxd:165536:65536
root:231072:65536

I can create an image on the remote machine.

Here's the config on the nested instance 'sublxd1'
name: sublxd1
profiles:
- default
config:
  security.nesting: "true"
  volatile.base_image: 7c583a857c913fc5aca7f7cef7706dd82e9913c4b7fdd65088eeab5eb73a86ac
  volatile.eth0.hwaddr: 00:16:3e:b5:6e:bd
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":362144,"Nsid":0,"Maprange":200000},{"Isuid":false,"Isgid":true,"Hostid":362144,"Nsid":0,"Maprange":200000}]'
devices: {}
ephemeral: false

when I try and start  the instance I get 

lxc start sublxd1:test
error: chown /var/lib/lxd/shmounts/test: invalid argument
Try `lxc info --show-log test` for more info

then again I get 
root@ubuntu:~# lxc start sublxd1:test
error: saving config file for the container failed
Try `lxc info --show-log test` for more info

the logs show
       lxc 1445604645.174 ERROR    lxc_conf - conf.c:chown_mapped_root:3385 - Error chowning /var/lib/lxd/containers/test
            lxc 1445604645.174 ERROR    lxc_container - lxccontainer.c:do_create_container_dir:875 - Failed to chown container dir
            lxc 1445604854.305 INFO     lxc_confile - confile.c:config_idmap:1437 - read uid map: type u nsid 0 hostid 231072 range 65536
            lxc 1445604854.305 INFO     lxc_confile - confile.c:config_idmap:1437 - read uid map: type g nsid 0 hostid 231072 range 65536
            lxc 1445604854.307 WARN     lxc_cgmanager - cgmanager.c:cgm_get:993 - do_cgm_get exited with error
            lxc 1445604854.309 WARN     lxc_cgmanager - cgmanager.c:cgm_get:993 - do_cgm_get exited with error
            lxc 1445604854.311 INFO     lxc_confile - confile.c:config_idmap:1437 - read uid map: type u nsid 0 hostid 231072 range 65536
            lxc 1445604854.311 INFO     lxc_confile - confile.c:config_idmap:1437 - read uid map: type g nsid 0 hostid 231072 range 65536
            lxc 1445605007.418 INFO     lxc_confile - confile.c:config_idmap:1437 - read uid map: type u nsid 0 hostid 231072 range 65536
            lxc 1445605007.418 INFO     lxc_confile - confile.c:config_idmap:1437 - read uid map: type g nsid 0 hostid 231072 range 65536
            lxc 1445605007.420 WARN     lxc_cgmanager - cgmanager.c:cgm_get:993 - do_cgm_get exited with error
            lxc 1445605007.421 WARN     lxc_cgmanager - cgmanager.c:cgm_get:993 - do_cgm_get exited with error
            lxc 1445605007.424 INFO     lxc_confile - confile.c:config_idmap:1437 - read uid map: type u nsid 0 hostid 231072 range 65536
            lxc 1445605007.424 INFO     lxc_confile - confile.c:config_idmap:1437 - read uid map: type g nsid 0 hostid 231072 range 65536

Any Ideas?

**Comment by hallyn** [comment]
Where are you trying to create/start the nested container?  Why does the remote host still have a 65k uid range for root?

Keep the nested container's uid range at 65k.  The nested container's range must fit inside the parent container's allocated range.

**Comment by plenderyou** [comment]
It fails if I try and start it on either the host or the remote.

So you mean that the remote containers root uid/gid setting should start at the same as the user on the host?

so it should be

lxd:562144: 65536
root:562144: 65536

Or is it the setting for root on the host?

**Comment by hallyn** [comment]
Meh, yeah, that changed "recnetly" in lxd source, yes use the lxd user :)

**Comment by hallyn** [comment]
> So you mean that the remote containers root uid/gid setting should start at the same as the user on the host?

No that's not what I mean.

The subuid entries are:

name:start:range

the full uid range between start and start+range must *exist* for you to be able to delegate it to a nested container.  So if you have

lxd:1000000:65536

That will take uids 1000000 - 1065536 on the host, and delegate them to the container as uids 0 - 65536.  The container, then, can only use uids 0-65536.  So in the container you could do

lxd:60000:5000

but not

lxd:60000:65536

because in the latter the top end of the range , 65536-125536, is invalid in that first container.

**Comment by hallyn** [comment]
This weekend I wrote https://github.com/hallyn/uidmapviz as an attempt to help in crafting uid mappings, especially for nested containers.

**Comment by stgraber** [comment]
Ok, so there are two ways to deal with this as a user:

 1. Have a big enough uid/gid allocation on the host so that the containers then have enough uid/gid themselves to nest with a subset of their uid/gid map. That's the safest way but also the most wasteful and tricky to get right. Serge's tool helps you get that done.
 2. Inside the first level container (NOT ON THE HOST!), do "lxc profile set default security.privileged true". This will make sub-containers share the same map as their parent, so they'll effectively still be unprivileged just not with a subset of the uid/gid map of their parent.

I'm closing this as there doesn't appear to be anything we can really do automatically on our end. Setting security.privileged=true by default for nested containers would be wrong and rather risky should the detection code misfire and set the flag inside a privileged container. Increasing the default allocation just leads to a waste of uid/gid for most users and will only help you for one level of nesting.
