### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by hallyn** [lxc/lxd#1237]
There seems to be a memory leak right now.  When I run the script:

```
#!/bin/bash
lxc delete w1 || true
count=0
echo STARTING >> stamp
date >> stamp
while [ $count -lt 1000 ]; do
        lxc launch wily w1
        while !  lxc list | grep w1 | grep 10.0.3.; do
                sleep 0.3
        done
        lxc delete w1
        count=$((count+1))
done
date >> stamp
```

(which was intended to check for lxcfs leaks :)  lxd's memory usage
goes up and up.  Oddly, using the memory profiler and 'top5' only
shows onr 512k allocation by
512.19kB   100%   100%   512.19kB   100%  runtime.malg

Eventually lxd is killed by the OOM killer.

**Comment by tych0** [comment]
On Thu, Oct 22, 2015 at 03:22:37PM -0700, Serge Hallyn wrote:
> There seems to be a memory leak right now.  When I run the script:
> 
> #!/bin/bash
> lxc delete w1 || true
> count=0
> echo STARTING >> stamp
> date >> stamp
> while [ $count -lt 1000 ]; do
>         lxc launch wily w1
>         while !  lxc list | grep w1 | grep 10.0.3.; do
>                 sleep 0.3
>         done
>         lxc delete w1

For future users, this script needs a `count=$(($count + 1))` here.

**Comment by tych0** [comment]
So I've managed to convince myself that for init, start, launch, delete we don't have any leaks (the few bytes RSS you increase is due to the operation, but based on my tests you'd have to start probably millions of operations to add any significant memory).

I think list is still leaky. Even when I comment out the call to `shared.iPsGet`, it's still leaking. Still fiddling more with this...

**Comment by hallyn** [comment]
This is fixed.
