### ISSUE TITLE
lxd hangs when supplying some options

### ISSUE THREAD

**Issue by tchwpkgorg** [lxc/lxd#1246]
To reproduce:

1) first try:

    # lxc config set testct raw.lxc "lxc.network.ipv4=10.0.3.228/24"
    error: problem applying raw.lxc, perhaps there is a syntax error?
    #

2) second try - it never returns:

    # lxc config set testct raw.lxc "lxc.network.ipv4=10.0.3.228/24"
    (hangs here, no prompt)

3) in a different shell - also hangs and never returns:

    # lxc list

Mailing list URL ([lxc-users] set "lxc.aa_allow_incomplete = 1" - where do I add it	for lxd?):

https://lists.linuxcontainers.org/pipermail/lxc-users/2015-October/thread.html#10313

**Comment by hallyn** [comment]
Thanks for filing this.  I'd assign myself right now, but can't start on it
immediately and don't want to hold anyone else back.

**Comment by stgraber** [comment]
I'm pretty sure we should just ban lxc.network.* from being set as we're already doing with a couple of other keys. The reason is that since LXD generates some of those at startup time, the ordering is completely off and in the case of multiple interfaces, additional entries would be set against completely random devices.

**Comment by stgraber** [comment]
I'll send a patch that prevents writing to lxc.network.* through raw.lxc, this will fix this issue.
