### ISSUE TITLE
LXC bridge IP shows up in IPV4 IP info for container

### ISSUE THREAD

**Issue by rcj4747** [lxc/lxd#1247]
The IP of lxcbr0 in the LXD container shows up in the host's `lxc list` output.  This address isn't usable from the host and should not be in the IPV4 column.

```
   $ lxc list
   +------+---------+---------------------+------+-----------+-----------+
   | NAME |  STATE  |        IPV4         | IPV6 | EPHEMERAL | SNAPSHOTS |
   +------+---------+---------------------+------+-----------+-----------+
   | wily | RUNNING | 10.0.3.68, 10.0.4.1 |      | NO        | 0         |
   +------+---------+---------------------+------+-----------+-----------+```
```

**Comment by stgraber** [comment]
That may be true in this case but wouldn't be if you had setup a route to the container on your host. We have simply no way to know.

We also can't just ignore bridged because if you had bridged eth0 into lxcbr0 in the container, then lxcbr0 would be the interface with the IP address.


That's why we simply list all non-loopback addresses in there and let the user figure it out.

Note that the LXD API and "lxc info wily" do tell you what interface the address is on, so if you were to script your containers, you can use that to get the IP only from the interface which you know is reachable.
