### ISSUE TITLE
Relationship Between LXC Containers and LXD Containers on the Same Machine

### ISSUE THREAD

**Issue by srkunze** [lxc/lxd#1310]
Sorry for cross-posting: # lxc/lxc#689

I have a host with both lxc containers and lxd containers:

```
root@mexico:~# lxc list
+--------+---------+------+------+-----------+-----------+
|  NAME  |  STATE  | IPV4 | IPV6 | EPHEMERAL | SNAPSHOTS |
+--------+---------+------+------+-----------+-----------+
| ubuntu | RUNNING |      |      | NO        | 0         |
+--------+---------+------+------+-----------+-----------+
root@mexico:~# lxc-ls -f
NAME      STATE    IPV4  IPV6  GROUPS  AUTOSTART  
------------------------------------------------
lxc-test  RUNNING  -     -     -       NO         
```

It seems lxd and lxc don't know each other. Is that intentional?

Assuming, we had a set of lxc containers running on a machine, I cannot manage those with lxd, right? Is there a way to migrate/import them to lxd?

**Comment by hallyn** [comment]
They are purposely in different lxcpaths.  lxd uses its database rather than the lxc-standard "$lxcpath/$name/config" to store configuration, so they two are not easily compatible.

You could easily write a tool to convert between the two (and in effect lxd does this, as it does create an ephemeral config file every time it actually starts a container), but actually keeping such a tool in sync with lxd development would take some work.

  So yes, it is intentional that lxc and lxd keep their containers in different places.

**Comment by srkunze** [comment]
Alright. Thanks for clarifying this. I couldn't found any note about that relationship in the docs.
