### ISSUE TITLE
changing sysctl settings of container

### ISSUE THREAD

**Issue by ak5** [lxc/lxd#1351]
Was wondering if there is a way to change the values of /proc/sys/kernel/shm*

Since the containers are unprivileged, I can't set it from within.

Thanks!

**Comment by stgraber** [comment]
Ok, so the current situation is:
 - The kernel won't let you write to shmmax in an unprivileged container, that needs to be fixed in the usptream kernel before we can do anything about it.
 - proc:mixed in LXC shouldn't make those files read-only, instead they should be bind-mounted read-write, please file a bug in https://github.com/lxc/lxc about this.

As far as LXD itself is concerned, there's no logic for us to do there. We shouldn't attempt to expose sysctls directly through LXD as we really don't want to have to be aware of the behavior of every single kernel versions (what's namespaced and what's not), the right thing to do is to fix this at the source (kernel and LXC) instead.

As a result, I'm closing the LXD bug.
