### ISSUE TITLE
Why showing internal IP addresses in lxc list?

### ISSUE THREAD

**Issue by srkunze** [lxc/lxd#1356]
After discovering that lxc list can show multiple IP addresses (#1352), I assumed that both IP addresses are publicly available. However, they are not which is quite understandable given that 10.0.3.157 is part of the host lxcbr0 and 10.0.4.1 is not (it's part of the internal container's lxcbr0).

Is it really necessary to show container-internal IP address via `lxc list` in the first place?

Put it differently, why should an external LXD instance care about container-internal LXD instances?

**Comment by stgraber** [comment]
Because we don't know what is and isn't an external IP.

If you had eth0 bridged into lxcbr0 in your container, the lxcbr0 would be an external IP.

Same goes if you have a routed IP that sits on a private interface, if routed from the host, it'd still count as an external IP.

So basically LXD cannot know whether an IP is or isn't reachable from the outside, we also can't check as it's pretty common for the host to be on a different network from the containers and so having "external" IPs that cannot be reached by the host or can only be reached by some other containers sharing a VLAN or something.
