### ISSUE TITLE
Allow lxc config edit if config is invalid

### ISSUE THREAD

**Issue by allquixotic** [lxc/lxd#1407]
There have been multiple updates to lxd that break compatibility with older configs, and it seems there is no process in place to stop this from happening again in the future. Perhaps with version 1.0 it'll stop, but that might be a ways off.

Meanwhile, early adopters of lxd like myself are hitting serious pain points when backwards compatibility gets broken, as in [this](https://github.com/lxc/lxd/commit/799471f75098cf9471f132cc84237d2fcf8fcf59) dubious commit (this functionality was working just fine for me; why disable it because it froze someone else's lxd? Now I have to figure out how to do this without using this functionality.)

The worst part of it all seems to be that I need to manually edit my sqlite database if I want to restore functionality to a container that's been hosed by such an "upgrade" that breaks compatibility with existing configs. Otherwise I can't use any lxc commands whatsoever on the stricken container. I just get the same error message over and over (specifically, the one mentioned in the above git commit).

The design as it stands is very brittle and user-unfriendly. This issue becomes unnecessary if the lxd developers will agree to a stable config file spec and guarantee that backwards compatibility will be maintained in the future, but thus far that seems like it won't happen until lxd is really, *really* stable (which might not even happen in time for Ubuntu 16.04).

**Comment by srkunze** [comment]
> This issue becomes unnecessary if the lxd developers will agree to a stable config file spec and guarantee that backwards compatibility will be maintained in the future

From what I can see, it's all internal stuff after all.

So, I don't think that they need to guarantee old configs are compatible. I could rather imagine a conversion script (from one version to the next one) that can convert/remove inappropriate entries or add necessary ones.

**Comment by stgraber** [comment]
Right, raw.lxc and raw.apparmor come with no guarantee of stability whatsoever.

As for blocking all of lxc.network, that's because the ordering in which things get applied matters and short of having LXD parse raw.lxc and try to figure out what interface you mean those settings to apply to, cannot be done reliably.

Our goal very much is to entirely block raw.lxc and raw.apparmor in the future (probably not 2.0 though).

That being said, configuration should be validated at the time it's set, not every time it's parsed, it's been something that's been on my todo list ever since I rewrote most of the container backend code last week and that I should have time to do this week (along with more comprehensive testing of config values).

So with that fix in place, your container will still start after upgrade (unless your raw.lxc entry does run into a conflict and makes the container crash) but any further config edit or container create will fail until the config has been updated to pass again.

I'll also be adding some extra wording to specs/configuration.md to make it clearer that using the raw stuff may very well break things in non-obvious ways and that we do not guarantee that things set in there will keep working in the future.
