### ISSUE TITLE
LXD stable ppa build failed for 0.25

### ISSUE THREAD

**Issue by IshwarKanse** [lxc/lxd#1449]
The Launchpad repository shows that build failed for LXD 0.25 so those of us who are on the stable ppa haven't received the update yet for the new version.

**Comment by stgraber** [comment]
Nope, 0.25 built successfully in the PPA, the only failed builds are Ubuntu 14.04 for powerpc and ppc64el which never built successfully due to lack of golang support on those architectures.

**Comment by IshwarKanse** [comment]
Hi Stéphane, If I go to the Launchpad page of LXD stable ppa and view package details. The following is the status of lxd 0.25 package.

For Ubuntu 15.10.1
Build failed for amd64 and armhf

For Ubuntu 15.04.1
Build failed for armhf 

For Ubuntu 14.04.1
Build failed for armhf

**Comment by stgraber** [comment]
Ah, you should have said the LXD stable PPA :)

The actual stable PPA at https://launchpad.net/~ubuntu-lxc/+archive/stable does have LXD 0.25 built for all architectures except powerpc and ppc64el on 14.04.

I've asked for a re-try of amd64 in the LXD stable PPA now, it should build fine in the next few minutes. armhf and arm64 there will always fail due to that PPA using virtualized builders instead of the physical builders that the main stable PPA has access to.

**Comment by IshwarKanse** [comment]
Thanks :) Didn't know there were two stable PPA's with LXD.
