### ISSUE TITLE
juju local provider (lxc) not working inside lxd with nesting

### ISSUE THREAD

**Issue by raharper** [lxc/lxd#1459]
Xenial host with LXD attempting to run lxc containers inside failing:

- lxd-images import ubuntu xenial amd64 --alias xenial
- lxc launch xenial nestc1 -c security.nesting=true -c security.privileged=true
- lxc exec nestc1 /bin/bash
- apt-get install juju-local
- su - ubuntu
- juju init
- juju switch local
- juju bootstrap
- juju deploy ubuntu

After some time, juju status shows lxc-start not working on the template container
When running lxc-start manually, error message shows lxc complaining about failing to create 100 new cgroups that already exist.

**Comment by hallyn** [comment]
Thanks.  Turns out we partially addressed this by supporting
lxc.aa_profile = unchanged

This doesn't yet work in xenial package, but is in git (and presumably
ppas).  It requires you changing the container configuration, though,
so I'm going to send a patch to make that the default if (a) no
profile is specified and (b) we are already confined.

**Comment by stgraber** [comment]
Fix pushed to git (other project so no auto-close).
