### ISSUE TITLE
lxc config unset acontainer aninvalidconfigkey doesn't generate an error

### ISSUE THREAD

**Issue by tych0** [lxc/lxd#1477]

**Comment by stgraber** [comment]
That's because the invalid key never actually hits the server, otherwise it sure would generate an error.

What's happening is that the client pulls the current config, then unsets the key and pushes back the config. If the key doesn't exist to begin with, no errors are raised.

So we can't really raise an "invalid key" error, but we can have the client raise a "unsetting a key that's not set" error.

**Comment by tych0** [comment]
On Thu, Jan 07, 2016 at 12:49:08PM -0800, Stéphane Graber wrote:
> That's because the invalid key never actually hits the server, otherwise it sure would generate an error.
> 
> What's happening is that the client pulls the current config, then unsets the key and pushes back the config. If the key doesn't exist to begin with, no errors are raised.
> 
> So we can't really raise an "invalid key" error, but we can have the client raise a "unsetting a key that's not set" error.

Yep, when I looked at writing a patch before filing this it's actually
a little messier than that, because of the way it's handled
internally. Perhaps I'll get ambitious on a plane ride soon and try
and de-messy it.
