### ISSUE TITLE
Default text editor wrong

### ISSUE THREAD

**Issue by kkobashi** [lxc/lxd#1526]
My default text editor is nano (verified by update-alternatives --config editor). When I edit lxc profiles, Vim is launched instead.

**Comment by juanquy** [comment]
I know this is close, but I'm having the same issue here, do you know how to replace the default config editor for containers from vi to nano?

**Comment by stgraber** [comment]
If using the snap, you can't, we have a separate issue to track this https://github.com/lxc/lxd-pkg-snap/issues/9

If not using the snap, either set EDITOR in your environment or run something like `update-alternatives --config editor` (if on Ubuntu or Debian).

**Comment by juanquy** [comment]
I'm using snap, thank you so much for your " pronto" answer!  we'll wait until is fixed, not a big deal.

**Comment by ndunks** [comment]
Also have same issue, fix by this way (may help others):
`
export EDITOR=nano
`
https://lxd.readthedocs.io/en/latest/environment/#client-environment-variable

**Comment by devendor** [comment]
The editor is actually running in the snap container so many options just won't work without some serious messing around to add hostfs/usr/bin to path and modify the ld path. 

This trick works and is generally much better anyway though:

```
lxc config show myContainer >/tmp/myContainer.yml
whatever /tmp/myConatiner.yml
lxc config edit myContainer </tmp/myContainer.yml
```
This also allows you to find and fix annoying yaml errors a little easier. Some of them tend to make the returned config look like a jumble due to a trailing whitespace or some other issue, and the local version is at least not all collapsed and quoted strangely.
