### ISSUE TITLE
lxd cgroup controller warning during start

### ISSUE THREAD

**Issue by arsiesys** [lxc/lxd#1554]
Hello,

I just updated LXD to version 2.0.0.beta1 and reboot my host.
At lxd start, I can read : 
```
lxd
WARN[01-29|15:04:53] Couldn't find the CGroup blkio controller, I/O limits will be ignored. 
WARN[01-29|15:04:53] Couldn't find the CGroup CPU controller, CPU time limits will be ignored. 
WARN[01-29|15:04:53] Couldn't find the CGroup CPUset controller, CPU pinning will be ignored. 
WARN[01-29|15:04:53] Couldn't find the CGroup devices controller, device access control won't work. 
WARN[01-29|15:04:53] Couldn't find the CGroup memory controller, memory limits will be ignored. 
WARN[01-29|15:04:53] Couldn't find the CGroup network class controller, network limits will be ignored. 
WARN[01-29|15:04:53] CGroup memory swap accounting is disabled, swap limits will be ignored. 
```
Is this comportment is normal ? I am running LXD on a up to date ubuntu 14.04. Perhaps theses warnings already exist before, but, I just seen them.

Thanks ! :)

**Comment by stgraber** [comment]
It is normal for a system without /sys/fs/cgroup/* mounted. Systemd does that for you on recent Ubuntu.

For 14.04, if you want those features, you'll have to install the "cgroup-lite" package which will mount those cgroup controllers for you.


The warnings are new because the features requiring those cgroup controllers are new. Those are for cpu, memory, network, storage, ... limits which have all been added in the past 2 LXD releases or so.

**Comment by stgraber** [comment]
Note that even with cgroup-lite installed, swap accounting will still be off as it must be turned on by setting a kernel boot parameter.

**Comment by arsiesys** [comment]
Ok ! Thanks, you got it, again :)...
I will test these lxd capacity soon !
