### ISSUE TITLE
lxd init should modprobe zfs, if necessary

### ISSUE THREAD

**Issue by dustinkirkland** [lxc/lxd#1564]
⟫ sudo lxd init
sudo: unable to resolve host ip-10-16-111-113
Name of the storage backend to use (dir or zfs): zfs
Create a new ZFS pool (yes/no)? yes
Name of the new ZFS pool: lxd
Would you like to use an existing block device (yes/no)? yes
Path to the existing block device: /dev/sdf
Would you like LXD to be available over the network (yes/no)? no
error: Failed to create the ZFS pool: The ZFS modules are not loaded.
Try running '/sbin/modprobe zfs' as root to load them.

**Comment by stgraber** [comment]
LXD isn't the right place to fix this one.

Last time we had a report of this one, I've had the reporter send it to @ColinIanKing to have Ubuntu fixed. The zfs module appears to get auto-loaded at boot time, but isn't at install time which makes the zpool command fail right after install, that's a bad user experience which should be fixed in the zfs package or the zfs tools rather than in all downstream users.

**Comment by stgraber** [comment]
Looks like we were doing it at runtime anyway, so I'll be adding it to init too then.

**Comment by stgraber** [comment]
I still think that needs fixing in Ubuntu in general as otherwise our first use zfs experience is pretty bad...
