### ISSUE TITLE
"temination protection" for containers

### ISSUE THREAD

**Issue by tchwpkgorg** [lxc/lxd#1600]
Containers should have a way to protect them against accidental termination.

Some kind of "lxc config set containername protect=1" and "lxc config set containername protectsnapshots=1" would be very useful (and default to 0):
- "s" is next to "d" on the keyboard, so it's easy to delete a stopped the container with:

`# lxc d-press-tab containername`
- it would feel safer to protect important containers this way (i.e. stopped "base" containers used to create other containers, and important running containers)

**Comment by stgraber** [comment]
LXD 2.0.0.beta2 requests -f to be passed when deleting a running container.

    stgraber@dakara:~/data/code/lxc/lxd (stgraber/master)$ lxc delete blah
    error: The container is currently running, stop it first or pass --force.

Additionally, you can alias "lxc delete" to "lxc delete -i" by putting:

    aliases:
        delete: delete -i

In your LXC config file (~/.config/lxc/config.yml), at which point, you'll be getting this behavior:

    stgraber@dakara:~/data/code/lxc/lxd (stgraber/master)$ lxc delete blah
    Remove blah (yes/no): no
    error: User aborted delete operation.


We've had users feeling pretty strongly both ways (always confirm vs never confirm), so I think the beta2 implementation is the best compromise we could come up with so don't expect things to change much one way or the other.

Your proposal would be reasonable too I think, though it would need defining the exact API behavior for a container that's protected or has its snapshots protected. We wouldn't want the enforcement of this to happen on the client side, instead the server should require an extra force attribute be set on any operation that's protected and all clients would need to be updated to support this or will otherwise fail to interact with the container.

This also brings the question of what would be qualifying as a protected action, delete obviously would, but would restore be too, what about moving the container or doing potentially damaging changes to its config? If the config is to be protected too, then what happens if you modify one of the profiles the container is based on, such a change would affect the container, so should we prevent changing any profile which affects one or more protected containers?

So we quickly get from something that's seemingly pretty simple to something pretty complex and requiring potentially a fair amount of changes to existing clients. I don't see this happening for 2.0 for sure.

Do you think our current compromise of the client-side check we're making now and the -i flag is enough for your needs or would you still like us to investigate your proposal further?

In the former case, I'd close your issue as fixed whereas in the latter I'd target it to the later milestone and tag it as a feature that needs specification work.

**Comment by tchwpkgorg** [comment]
I'm not really sure it works for me.

My main concern are:

1) automation / scripts

Automation scripts will not run interactively, so will never ask questions and wait for them to be answered, won't have the -i flag passed, and will likely always have the --force flag passed


2) new sysadmin with fat fingers removing something important (or, modifying the automation / script in a way that it removes something it shouldn't)

Let's say every day you create lots of new containers, and delete the old ones as well. How do you remove them? Most likely "lxc list | grep something-you-want-deleted | process_it_somehow". It's really easy in my opinion for something to go wrong here and destroy data you don't want to destroy.

Right now, my workaround for the problem is to use LXD for all the automation - and keep the important containers with the old LXC (lxc-start, lxc-stop...). But that's just not ideal.


I'm not so concerned about the config - I'm concerned about the container rootfs. This is also how managing VPS/instances works with hostings like AWS: you can enable "termination protection" for a given system, and then, in order to remove it, you'll have to disable "termination protection" first.
It doesn't protect the config, which might be important in some cases, but IMO is not critical (i.e. you can assign the instance to a wrong bridge, and loose connectivity - but you can reverse it; however, if you delete your database and all its snapshots, you're cooked).


For LXD, I think it would be enough to define functionality which protects the rootfs:

1) lxc protect containername

Would result in the following behaviour when "delete" is used:

lxc delete containername # would exit with error ("container has termination protection enabled") and won't remove the container not its snapshots

lxc delete containername/snap0 # would remove snap0 - because we didn't protect the snapshot
 

2) lxc protect containername/snapshot

Would result in the following behaviour when "delete" is used:

lxc delete containername # would exit with error ("some snapshots have termination protection enabled")

lxc delete containername/snapshot # would exit with error ("snapshot has termination protection enabled")

lxc delete containername/snap2 # would remove snap2, as it's not protected



Of course all your other points remain valid, and others may have better ideas about these / need better design:

- if we should protect against restore by default? I think we should - we don't want to overwrite a protected container with a very old snapshot

- moving the container - it would be still in the pool of containers, and as long as it stays "not removable" somewhere, we are fine

**Comment by tchwpkgorg** [comment]
By the way, I just found out that old LXC has a "similar" feature already:

```
# lxc-snapshot -n testvm011

# lxc-destroy -n testvm011
lxc-destroy: lxccontainer.c: do_lxcapi_destroy: 2417 Container testvm011 has snapshots;  not removing
Destroying testvm011 failed
```


Compare it with LXD, looks like "regression":

```
# lxc snapshot testvm
# lxc delete testvm
# lxc list|grep testvm
```

**Comment by kaneg** [comment]
I world also like to have this feature. We have almost 100 lxd containers in our lab. All the team members can access the environment to manage their containers. Some containers are cheap, can create/delete easily. Some of them are very important, e.g. are templates  of other containers. So far, It is not easy to prevent someone deleting those important containers by mistake. 

So, if we can add some lock/protection flag on these containers, the normal delete operation should be blocked. In order to delete, the lock flag should be cleared first or pass a ignore-lock argument in delete command  for automation purpose.
For example:
lxc lock c1
lxc delete c1
say: c1 is locked, remove the lock or pass --ignore-lock
===========Option 1=====
lxc unlock c1
lxc delete c1
==========Option2=======
lxc delete c1 --ignore-lock

**Comment by n0guest** [comment]
Looks like you're talking about some analog for "terminate protection" from AWS EC2. 

And we tried to solve same problem by adding flag "user.protected: true" to container params and creating a wrapper-script (which checks this param and refuses to delete "protected" containers). But with CLI commands there is one small problem - people, who likes to use commands from history and pressing Enter without reading it.

So, there is a big difference between "terminate protection" in EC2 and mandatory "bypass" flag for CLI. In EC2 scenario - you need to consciously "unheck" flag to terminate instance. But in LXC/LXD scenario - you can just use command from history. 

And this is a problem, that we still didn't solve. Because forcing people to run "lxc config edit ..." (e.g. for removing protection) can cause even greater damage (yep, humans "errors" again).

**Comment by 19wolf** [comment]
Just as a reference in case anybody lands here like I did, version 3.3 added this feature

> Deletion protection for containers
> 
> A new security.protection.delete configuration key can now be set to true on containers that you want to protect from accidental deletion.
> 
> It can be used like this:
> 
> ```
> stgraber@castiana:~$ lxc config set c1 security.protection.delete true
> stgraber@castiana:~$ lxc delete c1
> Error: Container is protected
> stgraber@castiana:~$ lxc config unset c1 security.protection.delete
> stgraber@castiana:~$ lxc delete c1
> ```

**Comment by 19wolf** [comment]
As an aside, tab completion does not include `security.protection.delete` yet

**Comment by 19wolf** [comment]
I don't know where the bash-completion script is, but if you point me to it I can submit a PR.

**Comment by stgraber** [comment]
@19wolf https://github.com/lxc/lxd/blob/master/scripts/bash/lxd-client

**Comment by dulinux** [comment]
Hello, please, what version is required for this important feature to work? I have lxc 3.0.3 and it´s saying there is no security.protection.delete

```
duli@uvm:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

duli@uvm:~$ lxc --version
3.0.3

duli@uvm:~$ lxc config set horde-stable security.protection.delete true
Error: Invalid config: Unknown configuration key: security.protection.delete
```

Thanks!

**Comment by stgraber** [comment]
Should have been introduced around LXD 3.3.

**Comment by ak2766** [comment]
This is one **_cool_** feature - I wish I knew this before yesterday when, as stated above, I fat fingered something silly - :(.  But, no pain no gain, so there's that at least; a setting that I'll never forget.
