### ISSUE TITLE
cannot change where Images and containers are stored

### ISSUE THREAD

**Issue by xistoso** [lxc/lxd#1690]
# Required information

I'm using Ubuntu 16.04 oficial repos.

# Issue description

The problem is i run the following commands:
sudo zfs create tank/foo # tank is my main pool
sudo lxd init # there i set up pool to be tank/foo

then i download ubuntu image with lxd python scrypt (i think it was lxd-image)
and create/start a container with lxc, it all works ok.

the problem is it creates the two folders /tank/foo/containers and /tank/foo/images but they are empty.

sudo lxc config show
outputs: storage.zfs_pool_name: tank/foo

inspecting /var/lib/lxd/ i can see a .zfs in /containers and the /images  with 3 image files occupying space which it was not supossed to.

**Comment by stgraber** [comment]
Do a "zfs list -t all" and you'll see that everything is indeed stored in zfs.

LXD just doesn't use the mountpoint of the dataset it's passed, in fact our documentation clearly tells you to do "zfs create tank/foo -o mountpoint=none" or for a new pool (that's what we document) "zpool create lxd /dev/abc -m none".

So LXD is very much using your dataset but setting the mountpoints to directories within /var/lib/lxd so that things show up where it expects them to be.

**Comment by xistoso** [comment]
You are right it has been good all along, got to pay more atention and learn more about ZFS mount points.
Ty for the help.

**Comment by callegar** [comment]
So, is there a way to instruct lxd not to use /var/lib/lxd or /var/snap/lxd for its storage, but some other place? I really do not like having virtual machine or container images in /var. If a machine is set up with /var not having its own partition this makes way too easy to fill the root partition and risk breaking a machine during critical operations, such as system upgrades. And even if /var is in its own partition, this makes it way too easy to fill /var and break logging.

**Comment by stgraber** [comment]
That's what storage pools do, yes. Your storage pool can have a source that's a separate partition or path (dependent on driver).
