### ISSUE TITLE
handle gzipped userdata correctly?

### ISSUE THREAD

**Issue by tych0** [lxc/lxd#1715]
From some comments in the juju code, I've not verified this myself, but I'm filing it here so we can keep track of it.

```
        // TODO(ericsnow) Looks like LXD does not handle gzipped userdata
        // correctly.  It likely has to do with the HTTP transport, much
        // as we have to b64encode the userdata for GCE.  Until that is
        // resolved we simply pass the plain text.
        //compressed := utils.Gzip(compressed)
```

**Comment by stgraber** [comment]
Hmm, the spec clearly states that all user keys are of type "string", not "blob", so indeed we do not support binary data.

It's also kinda hard to support as LXD itself doesn't parse any of those keys, but it must render them in text form through the template engine, so allowing a user to pass blobs that then go through the template renderer is tricky, not only because of encoding issues, but also because of the risk of code execution inside the template engine.

**Comment by stgraber** [comment]
I'm going to close this as our spec does say we are expecting a string, not a blob. If there is a good reason to allow users to upload binary blobs as config variables, we should have this be its own feature.
