### ISSUE TITLE
Is there a way to add or modify templates without exporting?

### ISSUE THREAD

**Issue by colebrumley** [lxc/lxd#1729]
I've been playing around with a [pet project](https://github.com/colebrumley/lxb) that tries to provide a Dockerfile-like build spec for LXD containers. Like Docker, instead of creating the image tarball from scratch I am attempting to use a base image that has modifications applied to it and then is saved off as a new image.

The concept of templates is one feature that doesn't exist in Docker (well... natively) and I'd love to be able to integrate this into my project. I am not seeing anything in the docs that indicates the ability to add or modify a template on an image that already exists in lxd's store. Is this something that either exists already and I missed, or is planned for implementation in the API?

If you're _not_ planning on implementing modifiable templates, what method would you recommend for this use case? Is there something cleaner than export -> modify tarball -> import? I noticed that the images are stored in `/var/lib/lxd/images` as tarballs, so it's looking like that may be the way to go. Thoughts?

**Comment by stgraber** [comment]
Images are immutable and templates are included in them which means that a change to their metadata or template would cause the hash to change.

So by design, we can't let you change templates of existing images.

However it sounds like you're publishing a container into an image in your case (create a container from a base image, do stuff, turn it into an image). In which case, you can simply edit /var/lib/lxd/containers/NAME/metadata.yaml and any of the templates under /var/lib/lxd/containers/NAME prior to publishing the container as an image.

**Comment by stgraber** [comment]
There is currently no API that allows you to do this changes remotely but it's something that we could add in the future so you can do those changes remotely rather than directly through the filesystem.

**Comment by colebrumley** [comment]
Ah perfect, that makes way more sense than fiddling with the tarball. In regards to your second comment, `more API == more win` and making LXD friendly to Docker users (or converts :D) as well as vanilla LXC users is important but obviously for this use case modifying the files on disk will be perfectly adequate. Feel free to close this unless you want to keep it around for any reason.
