### ISSUE TITLE
lxc 2.0.0~rc9 still thinks it's 2.0.0~rc2

### ISSUE THREAD

**Issue by jameinel** [lxc/lxd#1737]
Installing 2.0.0~rc9 on xenial
dpkg -l lxc
2.0.0~rc9-0ubuntu1

However
$ lxc --version
2.0.0.rc2

$ lxc info
...
  driverversion: 2.0.0.rc9
...
  serverversion: 2.0.0.rc2

So something knows that it is 2.0.0.rc9, but it isn't --version.

**Comment by stgraber** [comment]
The "lxc" command comes from the "lxd-client" package which will no doubt be at the rc2 version.

The "lxc" package you see is a transitional package for lxc1 (old tools and the library that LXD uses).

ii  lxc                                           2.0.0~rc9-0ubuntu1                         all          Transitional package for lxc1

So that's all normal, you have the latest LXC library which is at 2.0.0.rc9 and are using LXD 2.0.0.rc2.

**Comment by stgraber** [comment]
Oh, note that once we kill lxcbr0 (hopefully later this week), you'll be able to install LXD without bringing the lxc and lxc1 packages on your system, you'll just have lxd, lxd-client, liblxc1 and lxcfs.
