### ISSUE TITLE
Properly reject the use of http in remotes

### ISSUE THREAD

**Issue by jameinel** [lxc/lxd#1763]
Using 2.0.0~rc3 from the PPA on Ubuntu Trusty

I don't know if not supporting "http://" sources for image data is intentional or not. If you try to do something like:
$ lxc remote add ciu http://cloud-images.ubuntu.com/releases  --protocol simplestreams --public yes
Then this works:
$ lxc image list ciu:
<lots of items>

However, doing:
$ lxc image copy ciu:trusty/amd64 local:
error: Get https://http://cloud-images.ubuntu.com/releases/streams/v1/index.json: lookup http: no such host

The problem seems to be in connectViaHttp:
	justAddr := strings.TrimPrefix(remote.Addr, "https://")
	c.BaseURL = "https://" + justAddr
	c.BaseWSURL = "wss://" + justAddr
	c.Transport = "https"

Which contrasts with:
		ss, err := shared.SimpleStreamsClient(c.Remote.Addr, shared.ProxyFromEnvironment)

Which means that things that only think of the Remote via client.simplestreams work just fine, but once it goes to copy the actual content it goes to:
 https://http://cloud-images...

**Comment by stgraber** [comment]
It is very much intentional. We don't have any way to validate the index files from simplestreams other than trusting the transport. http is simply not trustworthy and we don't want to risk having our users run backdoored images.

Note however that the simplestreams protocol only fetches the index files over https, the images themselves are then retrieved over http and validated against the SHA-256 hash contained in the index files we retrieved over https. If we detect a man in the middle or some kind of error when retrieving the image files over http, we then fetch them over https.

That gives us the best of both world as we are reading the index files over a safe transport but are then retrieving the big data blobs over a transport which can be cached by proxies.

**Comment by stgraber** [comment]
We probably should be adding some logic to the command line tool to error on http URLs.

**Comment by axw** [comment]
> It is very much intentional. We don't have any way to validate the index files from simplestreams other than trusting the transport. http is simply not trustworthy and we don't want to risk having our users run backdoored images.

If you really want to protect against backdoored images, HTTPS isn't the solution. That tells you there's no MITM, but not whether the index files are legitimate.

The ideal way to do this is by fetching the .sjson files, and validating the PGP signatures. If you don't do that, you're still prone to tampering of files on the official servers. There's code in golang.org/x/crypto for checking PGP signatures.

Once you're checking signatures, whether you're using HTTP or HTTPS doesn't really matter.

**Comment by jameinel** [comment]
There is another use case outside of worrying about MITM. Which is the private cloud case. We've had customers that want to mirror everything into their local network and point Juju and MaaS and all of their cloud instances only at the local mirror.
The simplestreams .sjson files have inline signatures, and use relative paths, which means if you just copy the structure the files remain valid. (As long as you mirror everything you can host the same content wherever you would like, and Juju can still validate the content is correct.)

I don't know if/when this will come back to bite us, but potentially we could see requests from people that don't want to have to host copies on HTTPS inside their own datacenter.
