### ISSUE TITLE
LXD rest API background operation status

### ISSUE THREAD

**Issue by patademahesh** [lxc/lxd#1771]
Hi,

I am trying to create new container using LXD RestAPI. The api returns me the status code as success and operation is created, but no container is created. I want to know the exact status of operation.

Please suggest.

Thanks.

**Comment by jsuwo** [comment]
Further to this, operations that fail seem to be immediately deleted -- GET /1.0/operations returns an empty array and GET /1.0/operations/<uuid> returns a 404.  There seems to be no way to query the status of a past operation.  I'm writing an API client in Ruby and am running into this issue.

**Comment by patademahesh** [comment]
same happened with me , i am trying to write it in PHP. Is there any way to access /events with simple GET call?

Please suggest.

Thanks

**Comment by stgraber** [comment]
/events is a websocket API, so no, you need to do websocket.

Operations are kept around for 5s after they reach their final state, so it's absolutely possible to fetch an operation status, otherwise our own command line client wouldn't work :)

What you typically want to do is either:
 - Connect to /events
 - Do your action
 - Monitor events for operation status

Or the easier:
 - Start operation
 - Immediately connect to /1.0/operations/UUID/wait

This is a blocking call which will return once the operation reaches a final state and will then return all the data that's known about the operation.

**Comment by patademahesh** [comment]
Your second option is much better and it seems to be working for me.

Thanks a lot :)
