### ISSUE TITLE
LXD usage with some kind of overlayfs

### ISSUE THREAD

**Issue by gschoenberger** [lxc/lxd#1878]
With LXC I played around with a base image and containers only storing their deltas via overlayfs.
When I updated the base image, all the containers were updated. I think this is a huge profit, as one must no update/manage each container separately.

Is such a constellation also possible with LXD?

THX, Georg

**Comment by stgraber** [comment]
We currently have no plan to support overlayfs due to the various limitations of overlayfs just not fitting with what LXD supports.

We can't stack snapshots properly and then remove some, we can't live migrate or network migrate them, ...

For now we recommend you use btrfs or zfs and in the case of zfs, you can then configure the filesystem to not sync data, giving similar performance to overlayfs.


We may reconsider this at some point when we add per-container storage configuration and once overlayfs has matured a bit more and works properly (thinking of inotify support at least). But that's unlikely to happen in a while.

**Comment by tych0** [comment]
On Sat, Apr 09, 2016 at 09:19:49AM -0700, Stéphane Graber wrote:
> We currently have no plan to support overlayfs due to the various limitations of overlayfs just not fitting with what LXD supports.
> 
> We can't stack snapshots properly and then remove some, we can't live migrate or network migrate them, ...
> 
> For now we recommend you use btrfs or zfs and in the case of zfs, you can then configure the filesystem to not sync data, giving similar performance to overlayfs.
> 
> 
> We may reconsider this at some point when we add per-container storage configuration and once overlayfs has matured a bit more and works properly (thinking of inotify support at least). But that's unlikely to happen in a while.

You could use container-type: "none" when creating things and manage
it all yourself if you really want to use overlayfs, but zfs is
definitely the best option.
