### ISSUE TITLE
LXD wrong paths on ZFS

### ISSUE THREAD

**Issue by tomposmiko** [lxc/lxd#1889]
```
tank/lxd on /tank/lxd type zfs (rw,noatime)
tank/lxd/containers on /tank/lxd/containers type zfs (rw,noatime)
tank/lxd/deleted on /tank/lxd/deleted type zfs (rw,noatime)
tank/lxd/deleted/images on /tank/lxd/deleted/images type zfs (rw,noatime)
tank/lxd/images on /tank/lxd/images type zfs (rw,noatime)
tank/lxd/images/4c779c2f068cfa819c27e3775f98ec88b098b75053b68dd0ece8630b6ba1278f on /var/lib/lxd/images/4c779c2f068cfa819c27e3775f98ec88b098b75053b68dd0ece8630b6ba1278f.zfs type zfs (rw,noatime)
tank/lxd/images/e9ba98e963c89a5be3e11ab55f0d6eff93cc47e88a75d00fc900c38bc4a5aba4 on /var/lib/lxd/images/e9ba98e963c89a5be3e11ab55f0d6eff93cc47e88a75d00fc900c38bc4a5aba4.zfs type zfs (rw,noatime)
tank/lxd/images/8bc41c8af0a852d674551772a3f0c6afe893b13adfd4ca1c5b9a37a0d90c51e1 on /var/lib/lxd/images/8bc41c8af0a852d674551772a3f0c6afe893b13adfd4ca1c5b9a37a0d90c51e1.zfs type zfs (rw,noatime)
```

Why is not mounted everything under /var/lib/lxd? Is that because ZFS backend was configured (obviously) after lxd get installed?
Why are images mounted by default? With these long hashes the mount output gets ruined.

Anyway, my current problem is that lxc publish does not work, because it intents to write and image file under /var/lib/lxd/images, which is not on zfs and there is no enough space this way.

BTW why does it want to write an image and not create a zfs dateset?

Am I lost in space somehow?

**Comment by tomposmiko** [comment]
My current problem was solved by 
```
zfs set mountpoint=/var/lib/lxd/images tank/lxd/images
```
But it's just a workaround.

**Comment by stgraber** [comment]
It's intentional.

LXD uses a zpool regardless of where it's mounted and just sets mountpoint= as needed.

It keeps the containers and images mounted at all time because that's what the other backends do and having to special case zfs would have made things more difficult. I did write a branch which would do opportunistic mounts/unmounts of zfs but it started hitting a lot of races, including a bunch inside the zfs kernel code when running scale tests with a few thousands containers.

The LXD image hash is the sha256 of the compressed image so we need to produce that compressed image regardless of storage backend, it's also required for further exports or exchange with remote servers.

As to why we don't mount /var/lib/lxd/images or even the whole /var/lib/lxd directly on the zfs pool you provided, it's because we support "upgrading" to zfs, where old containers and images get converted to zfs as they get copied (for containers) or used (for images).

We also plan on supporting the use of multiple zfs pools or mixing storage backends in the future, which will also require that the main LXD directories themselves aren't tied to a specific backend.


Your workaround is perfectly fine so on systems that are similarly space constrained, doing what you did is quite fine. Just make sure you move any existing content over to the zfs filesystem (or do it before you import any image).
