### ISSUE TITLE
lxc delete issues with zfs

### ISSUE THREAD

**Issue by MarkGavalda** [lxc/lxd#1916]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 15.10
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.2.0-35-generic
   * LXC version: 2.0.0
   * LXD version: 2.0.0.rc9
   * Storage backend in use: ZFS

# Issue description

We had hundreds of test containers on the same host machine backed by ZFS and tried to remove them with lxc delete, then after that hanged with a couple of containers we added the --force parameter. This resulted in "_error: Failed to destroy ZFS filesystem: cannot destroy '...': filesystem has dependent clones_". 
After going through one by one with --force and getting the same error _most_ of the time we finally found one on which a few others depended and after deleting that successfully we tried to delete the dependants, however lxd won't let us: "_error: Failed to list ZFS snapshots: cannot open 'lxd/containers/...': dataset does not exist_"

_lxc list_ still lists all of the containers with no obvious way to remove them now completely. Please advise.

# Steps to reproduce

 1. Create a new container with ZFS as storage backend
 2. Clone a lot of new containers from the first one
 3. Try to delete them one by one with the --force flag
 4. After that try to delete them again, you should get the 'dataset does not exist' ZFS error.

**Comment by MarkGavalda** [comment]
@stgraber what would be the best way to completely remove the remains of these "ghost" containers now? I'm wondering about to a manual method like deleting them from /var/lib/lxd/containers/ but then I guess it would cause issues with lxd.db and probably a bunch of other stuff.

**Comment by stgraber** [comment]
Creating the zfs dataset then removing the container should do the trick, something along the lines of "zfs create lxd/containers/NAME -o mountpoint=none && lxc delete NAME"

**Comment by MarkGavalda** [comment]
That did it, thanks Stéphane!

**Comment by stgraber** [comment]
https://github.com/lxc/lxd/pull/1970 includes a commit which should solve the symptoms of this issue, basically letting you remove containers which have been partially removed for some reason.

If your problem was somehow having concurrent delete calls hitting the same container, my commit may actually fix your issue, if not, it should at least make recovering from it easier.

I'm a bit concerned about the "dependent clones" bit you mentioned. Were you using container copies? We do internal tracking of clones to avoid such issues, so I'm a bit puzzled as to how this could even happen.

**Comment by MarkGavalda** [comment]
Yes all of the test containers were clones of (the same) one original container. We kept the original intact, only tried to remove all the derivative, test containers!
