### ISSUE TITLE
lxd init should say how to install zfs tools

### ISSUE THREAD

**Issue by markshuttle** [lxc/lxd#1930]
lxd init nicely walks the user through setup of various back-ends, but it doesn't explicitly say which packages to install.

mark@maas:~$ sudo lxd init
Name of the storage backend to use (dir or zfs): zfs
error: The requested backend 'zfs' isn't available on your system (missing tools).

In this case, the error could say "(try sudo apt install zfsutils-linux)" instead of "(missing tools)".

**Comment by stgraber** [comment]
It's intentional for the upstream code not to mention a package name or distro specific commands.

However I did mean to have a small distro patch in Ubuntu to tell users the right package name. I forgot about it when writing the Ubuntu distro patch so I'll be fixing that in the next SRU.

**Comment by markshuttle** [comment]
Thank you :)

**Comment by markshuttle** [comment]
Dustin tells me the correct package is "zfs" which is a metapackage.

Mark

**Comment by stgraber** [comment]
As this is something we'll be fixing in the Ubuntu packaging rather than in the upstream code, I filed a matching Github issue against our packaging branch and I'm closing this one.

I'm waiting for a few more bugfixes to stack up before preparing a SRU for LXD in 16.04 but I do expect to push one over the next couple of weeks, this change will be part of it.
