### ISSUE TITLE
Automatically probe and try 8443 when adding a remote

### ISSUE THREAD

**Issue by dustinkirkland** [lxc/lxd#1984]
We have a default port already (8443).  Make the <url> optional.  Probe and try to use 8443, before complaining about it.

kirkland@masterbr:~⟫ lxc remote add loft:
Manage remote LXD servers.

lxc remote add <name> <url> [--accept-certificate] [--password=PASSWORD]
                            [--public] [--protocol=PROTOCOL]                Add the remote <name> at <url>.
lxc remote remove <name>                                                    Remove the remote <name>.
lxc remote list                                                             List all remotes.
lxc remote rename <old> <new>                                               Rename remote <old> to <new>.
lxc remote set-url <name> <url>                                             Update <name>'s url to <url>.
lxc remote set-default <name>                                               Set the default remote.
lxc remote get-default                                                      Print the default remote.

error: wrong number of subcommand arguments
1 kirkland@masterbr:~⟫ lxc remote add loft https://loft:8443/
Certificate fingerprint: de68ba620e922e4c19916722995128ae0d212352189652de0df2ca6f56181f77
ok (y/n)?

**Comment by stgraber** [comment]
lxc remote add loft loft

**Comment by stgraber** [comment]
we do default to https and to port 8443, but you have to pass the dns name or IP of the remote.

**Comment by stgraber** [comment]
In most cases, the FQDN or IP of the remote isn't the name you want to use as the remote name, so most folks on their lan will do something along the lines of:

    lxc remote add host2 host2.local

or

    lxc remote add host2 192.168.1.25

**Comment by dustinkirkland** [comment]
I *really* feel *strongly* that you should be able to easily add a remote
using a hostname or IP *only*.

lxc remote add host2.local

or

lxc remote add 192.168.1.2

That should:

 - attempt to connect, over https, to that host (or the ip it resolves to)
on port 8443, and setup an alias that matches your argument (host2.local or
192.168.1.2)

Having to specify the alias should be totally optional.



:-Dustin

**Comment by sean-jc** [comment]
I looked at what it would take to implement this feature, and while it would be trivial to add basic support, there would be a variety of quirks and limitations, many of which were noted above.  Making a quick fix for this issue seems like the wrong thing to do as it would be of limited value and would probably lead to more issues and PRs being submitted.

Main Issues:

- No way to explicitly specify the scheme and/or port outside of the URL.
- Can't specify the scheme or port for the proposed shorthand case as `remote add` will parse the name using the `[remote:]container` syntax, i.e. colons in the name will effectively corrupt the URL.
- If no scheme is specified, `remote add` defaults to the `unix://` scheme if the name creates a valid path.  E.g, if `loft` is a valid path, `lxc remote add loft loft` would fail while `lxc remote add loft loft:8443` or `lxc remote add loft https://loft` would succeed.  Neither of these options is viable for the shorthand case.

Instead of patching the current behavior, what about changing LXC's handling of remote servers to make the URL **the** defining property?  Today's implementation considers `name` and `URL` to be more or less equals, which makes it awkward and difficult to do anything implicitly based on the URL, e.g auto-adding remotes for #1983 or deriving a name from the URL.

I don't think reworking remote server handling would require massive code changes, but it would definitely require breaking backwards compatibility in the LXC (LXD client) API, i.e. changing the order of `remote add` and the behavior of other commands with respect to remotes.  If breaking changes to the LXC API are allowed, then I'll explore this idea further.
