### ISSUE TITLE
lxd containers failing to start after reboot

### ISSUE THREAD

**Issue by battlemidget** [lxc/lxd#2001]
# Required information

 * Distribution: ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version:4.4.0-21-generic
   * LXC version:2.0.0-0ubuntu2
   * LXD version:2.0.0-0ubuntu4
   * Storage backend in use:zfs

# Issue description

half of the containers fail to start after reboot

# Steps to reproduce

`conjure-up openstack`
after deploy, reboot machine, watch as several containers do not start back

# Information to attach
[Archive (1).zip](https://github.com/lxc/lxd/files/252593/Archive.1.zip)

**Comment by battlemidget** [comment]
One of the users were able to stagger the boot delay to get around this issue:

```
This works:

https://bitsandslices.wordpress.com/2015/08/26/autostarting-lxd-containers/


boot.autostart.delay	lxc.start.delay

staggThis works:

https://bitsandslices.wordpress.com/2015/08/26/autostarting-lxd-containers/


boot.autostart.delay	lxc.start.delay

stagger based on the container #

ex 16 has a higher delay than 15..14..13..etc.
```

**Comment by stgraber** [comment]
Hmm, so that would typically indicate that your container depends on some kind of resource which isn't available at the time LXD starts.

Something like a bridge that's not managed by LXD itself, or some mountpoint, ...

**Comment by jradxl** [comment]
That caught me out on Manjaro Linux (ARCH) with the 2.0.3 implementation from AUR.
For me it was that the command "LXD ready" had not been issued, as it does from the "profile-config" script in Ubuntu.

**Comment by stgraber** [comment]
Hmm, but "lxd ready" is only needed if you are in setup mode to begin with, which requires you to touch a file in /var/lib/lxd. So that would only happen if someone only implemented half of that part of the init scripts.

Just starting lxd cleanly on a new distro that doesn't use setup mode shouldn't get you in that state.

**Comment by stgraber** [comment]
@battlemidget is this still a problem for you? If so can you provide the full configuration of an affected container (lxc config show <container> --expanded)?

**Comment by battlemidget** [comment]
Sorry, this isn't a problem for me any longer

**Comment by ibazulic** [comment]
This is still an issue. I have deployed OpenStack on my own Ubuntu 16.04.2 LTS VM witth 23 GB of RAM an 4 cores under VirtualBox to try it out. All containers started normally when conjure-up done but after rebooting only one container started. This is the status now:

`root@tardis:~# lxc list
+----------------+---------+-------------------+------+------------+-----------+
|      NAME      |  STATE  |       IPV4        | IPV6 |    TYPE    | SNAPSHOTS |
+----------------+---------+-------------------+------+------------+-----------+
| juju-9c574d-0  | RUNNING | 10.0.8.238 (eth0) |      | PERSISTENT | 0         |
+----------------+---------+-------------------+------+------------+-----------+
| juju-e097f5-0  | STOPPED |                   |      | PERSISTENT | 0         |
+----------------+---------+-------------------+------+------------+-----------+
| juju-e097f5-1  | STOPPED |                   |      | PERSISTENT | 0         |
+----------------+---------+-------------------+------+------------+-----------+
| juju-e097f5-10 | STOPPED |                   |      | PERSISTENT | 0         |
+----------------+---------+-------------------+------+------------+-----------+
| juju-e097f5-11 | STOPPED |                   |      | PERSISTENT | 0         |
+----------------+---------+-------------------+------+------------+-----------+
| juju-e097f5-12 | STOPPED |                   |      | PERSISTENT | 0         |
+----------------+---------+-------------------+------+------------+-----------+
| juju-e097f5-13 | STOPPED |                   |      | PERSISTENT | 0         |
+----------------+---------+-------------------+------+------------+-----------+
| juju-e097f5-14 | STOPPED |                   |      | PERSISTENT | 0         |
+----------------+---------+-------------------+------+------------+-----------+
| juju-e097f5-15 | STOPPED |                   |      | PERSISTENT | 0         |
+----------------+---------+-------------------+------+------------+-----------+
| juju-e097f5-2  | STOPPED |                   |      | PERSISTENT | 0         |
+----------------+---------+-------------------+------+------------+-----------+
| juju-e097f5-3  | STOPPED |                   |      | PERSISTENT | 0         |
+----------------+---------+-------------------+------+------------+-----------+
| juju-e097f5-4  | STOPPED |                   |      | PERSISTENT | 0         |
+----------------+---------+-------------------+------+------------+-----------+
| juju-e097f5-5  | STOPPED |                   |      | PERSISTENT | 0         |
+----------------+---------+-------------------+------+------------+-----------+
| juju-e097f5-6  | STOPPED |                   |      | PERSISTENT | 0         |
+----------------+---------+-------------------+------+------------+-----------+
| juju-e097f5-7  | STOPPED |                   |      | PERSISTENT | 0         |
+----------------+---------+-------------------+------+------------+-----------+
| juju-e097f5-8  | STOPPED |                   |      | PERSISTENT | 0         |
+----------------+---------+-------------------+------+------------+-----------+
| juju-e097f5-9  | STOPPED |                   |      | PERSISTENT | 0         |
+----------------+---------+-------------------+------+------------+-----------+
root@tardis:~#`

After trying to start a container, this is what I get in the logs:

`root@tardis:~# lxc info --show-log juju-e097f5-1
Name: juju-e097f5-1
Remote: unix:/var/lib/lxd/unix.socket
Architecture: x86_64
Created: 2017/05/19 21:27 UTC
Status: Stopped
Type: persistent
Profiles: default, juju-conjure-openstack-novalx-f5c

Log:

            lxc 20170523170106.107 ERROR    lxc_conf - conf.c:instantiate_veth:2727 - failed to set mtu '9000' for veth pair (vethXT7BB4 and vethAN2F4A): Invalid argument
            lxc 20170523170106.127 ERROR    lxc_conf - conf.c:lxc_create_network:3029 - failed to create netdev
            lxc 20170523170106.127 ERROR    lxc_start - start.c:lxc_spawn:1103 - Failed to create the network.
            lxc 20170523170106.127 ERROR    lxc_start - start.c:__lxc_start:1358 - Failed to spawn container "juju-e097f5-1".
            lxc 20170523170106.648 ERROR    lxc_conf - conf.c:run_buffer:416 - Script exited with status 1.
            lxc 20170523170106.648 ERROR    lxc_start - start.c:lxc_fini:546 - Failed to run lxc.hook.post-stop for container "juju-e097f5-1".
            lxc 20170523170106.648 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:177 - Command get_cgroup failed to receive response: Connection reset by peer.
            lxc 20170523170106.648 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:177 - Command get_cgroup failed to receive response: Connection reset by peer.

root@tardis:~#`

As far as I can see, LXD service is up and running but even it shows errors when starting containers:

`root@tardis:~# systemctl status lxd
● lxd.service - LXD - main daemon
   Loaded: loaded (/lib/systemd/system/lxd.service; indirect; vendor preset: enabled)
   Active: active (running) since Uto 2017-05-23 19:01:05 CEST; 10min ago
     Docs: man:lxd(1)
  Process: 1644 ExecStartPost=/usr/bin/lxd waitready --timeout=600 (code=exited, status=0/SUCCESS)
  Process: 1622 ExecStartPre=/usr/lib/x86_64-linux-gnu/lxc/lxc-apparmor-load (code=exited, status=0/SUCCESS)
 Main PID: 1643 (lxd)
    Tasks: 23
   Memory: 32.4M
      CPU: 16.366s
   CGroup: /system.slice/lxd.service
           ├─1643 /usr/bin/lxd --group lxd --logfile=/var/log/lxd/lxd.log
           ├─1813 dnsmasq --strict-order --bind-interfaces --pid-file=/var/lib/lxd/networks/lxdbr0/dnsmasq.pid --except-interface=lo --interface=lxdbr0 -
           ├─1893 dnsmasq --strict-order --bind-interfaces --pid-file=/var/lib/lxd/networks/conjureup0/dnsmasq.pid --except-interface=lo --interface=conj
           └─2185 [lxc monitor] /var/lib/lxd/containers juju-9c574d-0

Svi 23 19:00:47 tardis lxd[1643]: action=start created=2017-05-19T21:31:47+0000 ephemeral=false lvl=eror msg="Failed starting container" name=juju-e097f5
Svi 23 19:00:48 tardis lxd[1643]: container=juju-e097f5-7 err="Container is already running a start operation" lvl=eror msg="stop hook failed" t=2017-05-
Svi 23 19:00:53 tardis lxd[1643]: action=start created=2017-05-19T21:32:44+0000 ephemeral=false lvl=eror msg="Failed starting container" name=juju-e097f5
Svi 23 19:00:54 tardis lxd[1643]: container=juju-e097f5-8 err="Container is already running a start operation" lvl=eror msg="stop hook failed" t=2017-05-
Svi 23 19:00:59 tardis lxd[1643]: action=start created=2017-05-19T21:37:58+0000 ephemeral=false lvl=eror msg="Failed starting container" name=juju-e097f5
Svi 23 19:01:00 tardis lxd[1643]: container=juju-e097f5-9 err="Container is already running a start operation" lvl=eror msg="stop hook failed" t=2017-05-
Svi 23 19:01:05 tardis lxd[1643]: action=start created=2017-05-19T21:39:23+0000 ephemeral=false lvl=eror msg="Failed starting container" name=juju-e097f5
Svi 23 19:01:05 tardis systemd[1]: Started LXD - main daemon.
Svi 23 19:01:06 tardis lxd[1643]: container=juju-e097f5-1 err="Container is already running a start operation" lvl=eror msg="stop hook failed" t=2017-05-
Svi 23 19:01:11 tardis lxd[1643]: action=start created=2017-05-19T21:27:36+0000 ephemeral=false lvl=eror msg="Failed starting container" name=juju-e097f5
root@tardis:~# 
`
Some more information about the system:
`root@tardis:~# uname -a
Linux tardis 4.8.0-52-generic #55~16.04.1-Ubuntu SMP Fri Apr 28 14:36:29 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
root@tardis:~# free -h
              total        used        free      shared  buff/cache   available
Mem:            22G        1,2G         20G         39M        1,0G         20G
Swap:           21G          0B         21G
root@tardis:~# 
`

Anyone has any idea?
