### ISSUE TITLE
Stranded dhcp addresses

### ISSUE THREAD

**Issue by CalebEverett** [lxc/lxd#2009]
Minor point and not sure if this is intended behavior, but when containers are deleted with the --force flag their dhcp leases aren't released as they are when you stop containers and then delete them.

This ends up being a problem if you've set a specific address in the extra dnsmaq.conf file at LXD_CONF.

```
#!/bin/bash

CONTAINER=c1
lxc launch ubuntu:xenial $CONTAINER
sleep 4s
lxc list $CONTAINER
lxc stop $CONTAINER
printf '\n\nSTOPPED:\n'
cat /var/lib/lxd-bridge/dnsmasq.lxdbr0.leases  # lease has been removed
lxc start $CONTAINER
sleep 4s
lxc delete $CONTAINER --force
printf '\n\nDELETED:\n'
cat /var/lib/lxd-bridge/dnsmasq.lxdbr0.leases # lease remains
```

**Comment by stgraber** [comment]
Yeah, a forced delete doesn't even attempt to do a clean container stop, because, well, you're about to delete it all anyway.

Not very much we can do about this problem though. If you want to force a clean release, you probably should change your script to attempt a "lxc stop" with --timeout set, then do the delete.

**Comment by CalebEverett** [comment]
Ok thanks
