### ISSUE TITLE
Add a "description" field to API objects that don't have one

### ISSUE THREAD

**Issue by CalebEverett** [lxc/lxd#2022]
Would it be possible to use the POST method of the [snapshot endpoint](https://github.com/lxc/lxd/blob/master/doc/rest-api.md#post-4) to be able to add some additional meta-data to the snapshot dict?

I saw comments were possible on 1.0
http://man7.org/linux/man-pages/man1/lxc-snapshot.1.html

Is there another way to add comments or something in the works?

**Comment by stgraber** [comment]
I'm not against adding a comment field to the API which can be updated (through PUT) after the snapshot was created.

**Comment by CalebEverett** [comment]
That would be great - do you think there is a use case for being able to
copy incremental snapshots between remotes?

On Tue, Jul 5, 2016 at 9:25 AM, Stéphane Graber <notifications@github.com>
wrote:

> I'm not against adding a comment field to the API which can be updated
> (through PUT) after the snapshot was created.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lxc/lxd/issues/2022#issuecomment-230529050>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AIiGQ7i-JXaBqIFTPqqBGsUerCwV4KeWks5qSoWQgaJpZM4IdeTM>
> .
>



-- 
Caleb Everett
Career College of California
201 E. 4th Street, Suite 200
Santa Ana, CA 92701
(714) 243-8614 phone and fax
www.careercalifornia.edu

Facebook <http://www.facebook.com/CareerCalifornia> | Twitter
<http://twitter.com/careercalif> |  LinkedIn
<http://www.linkedin.com/company/941062> | G+
<https://plus.google.com/b/104968762557101611990/104968762557101611990/posts>

**Comment by stgraber** [comment]
Possibly though I'd expect this to be very tricky to do right (as in with send/receive) after the fact (after the container itself was copied already). We could of course always do it with rsync. but then it's pretty slow and expensive (in disk usage).

**Comment by CalebEverett** [comment]
What about just with zfs?

**Comment by stgraber** [comment]
That's the thing, we can't do it with zfs or btrfs, we can do it with the rest but then it's very slow (rsync).

That's because when you copy a container to a remote host, we don't copy the snapshots, then the container itself changes as soon as it's copied, so the only zfs filesystem we have at that point no longer matches any of the zfs filesystems on the source host, which prevents us from doing incremental transfers.

Because of zfs also not letting you restore a filesystem to a snapshot which isn't the latest one, it also prevents us from working around the issue by temporarily restoring the container state with rsync and then re-creating the snapshot.

**Comment by stgraber** [comment]
Expanding the scope of this issue for consistency.
Looking at the API right now, we should add a "description" field to the following:
 - container (includes container snapshots)
 - image
 - network
 - storage-pool
 - storage-volume

That way all major API items will have a description field. It's still not a property that's particularly easy for the client to change (requires "edit") but it's mostly useful for folks playing with the API directly.
