### ISSUE TITLE
lxd failed with result 'dependency

### ISSUE THREAD

**Issue by dhammo** [lxc/lxd#2046]
Installing lxd on 16.04 after upgrading from 15.10 (lxc1). lxd daemon does not start, syslog reports "dependency failed for lxd", and running any lxc command fails with permission denied. I checked my user is a member of lxd and followed other issues suggestion (exiting terminal, doing newgrp).

   * Kernel version: 4.4.0-22-generic
   * LXC version: stable release
   * LXD version: stable release
   * Storage backend in use: ZFS

# Issue description
lxd doesn't start after installing.

# Information to attach

 - [ ] any relevant kernel output (dmesg)
 - [ ] container log (lxc info NAME --show-log)
 - [ ] main daemon log (/var/log/lxd.log)
 - [ ] output of the client with --debug
 - [ ] output of the daemon with --debug

-----
May 25 17:40:23 baZinga systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency
May 25 17:40:23 baZinga systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency
May 25 17:40:23 baZinga systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency
May 25 17:40:23 baZinga systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency
May 25 17:40:23 baZinga systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency
May 25 17:40:23 baZinga systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency
May 25 17:40:23 baZinga systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency
May 25 17:40:23 baZinga systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency
May 25 17:40:23 baZinga systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency
May 25 17:40:23 baZinga systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency
May 25 17:40:23 baZinga systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency
May 25 17:40:23 baZinga systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency
May 25 17:40:23 baZinga systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency
May 25 17:40:23 baZinga systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency
May 25 17:40:23 baZinga systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency
May 25 17:40:23 baZinga systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency
-----
lxc list 
error: Get http://unix.socket/1.0: dial unix /var/lib/lxd/unix.socket: connect: permission denied
-----
May 25 17:40:14 baZinga systemd[1]: Dependency failed for LXD - main daemon.
May 25 17:40:14 baZinga systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency'.
May 25 17:40:14 baZinga systemd[1]: lxd-bridge.service: Start request repeated too quickly.
May 25 17:40:14 baZinga systemd[1]: Failed to start LXD - network bridge.
May 25 17:40:14 baZinga systemd[1]: Dependency failed for LXD - main daemon.
May 25 17:40:14 baZinga systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency'.
May 25 17:40:14 baZinga systemd[1]: lxd-bridge.service: Start request repeated too quickly.
May 25 17:40:14 baZinga systemd[1]: Failed to start LXD - network bridge.
-----

I cannot figure out what dependency is missing. My assumption lxd-bridge is not created, running lxd init hangs. 

Thanks

**Comment by stgraber** [comment]
systemctl status lxd-bridge

**Comment by dhammo** [comment]
systemctl status lxd-bridge
● lxd-bridge.service
   Loaded: not-found (Reason: No such file or directory)
   Active: failed (Result: exit-code) since Wed 2016-05-25 17:42:03 CEST; 34min ago
 Main PID: 17895 (code=exited, status=1/FAILURE)

May 25 17:42:03 baZinga lxd-bridge.start[17895]: iptables: Bad rule (does a matching rule exist in that chain?).
May 25 17:42:03 baZinga lxd-bridge.start[17895]: iptables: Bad rule (does a matching rule exist in that chain?).
May 25 17:42:03 baZinga lxd-bridge.start[17895]: iptables: Bad rule (does a matching rule exist in that chain?).
May 25 17:42:03 baZinga lxd-bridge.start[17895]: iptables: Bad rule (does a matching rule exist in that chain?).
May 25 17:42:03 baZinga lxd-bridge.start[17895]: iptables: Bad rule (does a matching rule exist in that chain?).
May 25 17:42:03 baZinga lxd-bridge.start[17895]: iptables: Bad rule (does a matching rule exist in that chain?).
May 25 17:42:03 baZinga lxd-bridge.start[17895]: iptables: No chain/target/match by that name.
May 25 17:42:03 baZinga lxd-bridge.start[17895]: iptables v1.6.0: host/network `10.30.630.1' not found
May 25 17:42:03 baZinga lxd-bridge.start[17895]: Try `iptables -h' or 'iptables --help' for more information.
May 25 17:42:03 baZinga lxd-bridge.start[17895]: ip6tables: No chain/target/match by that name.

**Comment by stgraber** [comment]
Hmm, how did you configure that bridge?

10.30.630.1 sure isn't a valid IP

**Comment by dhammo** [comment]
I ran "sudo dpkg-reconfigure -p medium lxd" hoping that would create the bridge or whatever dependency that is missing. I don't see any lxcbr0. Is it supposed to be created as part of lxd installation?

**Comment by stgraber** [comment]
The reconfigure will create a lxdbr0 bridge when the config is valid.

The IP address of your bridge however is very much invalid which causes it to fail to come up and therefore blocks lxd too.

I'd suggest you re-run "dpkg-reconfigure -p medium lxd" and make sure the values are valid IP addresses.

**Comment by dhammo** [comment]
Reconfigured the bridge to a valid IP and restarted lxd-bridge and lxd. It worked!

Thanks stgraber!

**Comment by stgraber** [comment]
Good to hear!

**Comment by ikit** [comment]
Hi, I have the same problem. I don't understand what do you means by "valid ip". By default the "sudo dpkg-reconfigure -p medium lxd" tools proposed me to set the bridge with "10.168.88.1, with DHCP from 10.168.88.2 to 10.168.88.254. Why these settings are wrong ? What should I do to choose a valid ip ? 


Below my logs:
`➜  tmp sudo service lxd status            
● lxd.service - LXD - main daemon
   Loaded: loaded (/lib/systemd/system/lxd.service; indirect; vendor preset: enabled)
   Active: inactive (dead) since Mon 2017-03-13 10:18:14 CET; 18min ago
     Docs: man:lxd(1)
 Main PID: 968 (code=exited, status=0/SUCCESS)

Mar 13 10:21:36 absgZ systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency'.
Mar 13 10:21:36 absgZ systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency'.
Mar 13 10:21:36 absgZ systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency'.
Mar 13 10:21:36 absgZ systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency'.
Mar 13 10:21:36 absgZ systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency'.
Mar 13 10:21:36 absgZ systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency'.
Mar 13 10:21:36 absgZ systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency'.
Mar 13 10:22:23 absgZ systemd[1]: Dependency failed for LXD - main daemon.
Mar 13 10:22:23 absgZ systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency'.
Mar 13 10:35:59 absgZ systemd[1]: Stopped LXD - main daemon.
➜  tmp systemctl status lxd-bridge        
● lxd-bridge.service - LXD - network bridge
   Loaded: loaded (/lib/systemd/system/lxd-bridge.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2017-03-13 10:22:23 CET; 14min ago
     Docs: man:lxd(1)
 Main PID: 7715 (code=exited, status=2)

Mar 13 10:22:23 absgZ systemd[1]: Starting LXD - network bridge...
Mar 13 10:22:23 absgZ lxd-bridge.start[7715]: dnsmasq: failed to create listening socket for fe80:...:2d99%lxdbr0: Address already in use
Mar 13 10:22:23 absgZ lxd-bridge.start[7715]: Failed to setup lxd-bridge.
Mar 13 10:22:23 absgZ systemd[1]: lxd-bridge.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 13 10:22:23 absgZ systemd[1]: Failed to start LXD - network bridge.
Mar 13 10:22:23 absgZ systemd[1]: lxd-bridge.service: Unit entered failed state.
Mar 13 10:22:23 absgZ systemd[1]: lxd-bridge.service: Failed with result 'exit-code'.
Mar 13 10:36:32 absgZ systemd[1]: Stopped LXD - network bridge.`

**Comment by ikit** [comment]
Ok, the problem was that my server has an instance of bind9 service running and locking the port 53. 
I solved my problem, by stopping bind9 service before restarting lxd. So no issue with the configuration of my bridge in fact. 

Thanks for your job,
regards
