### ISSUE TITLE
lxc file edit changes ownership of remote container file

### ISSUE THREAD

**Issue by CalebEverett** [lxc/lxd#2047]
`lxc file edit <remote>:<remote_container>/<file>` changes ownership to the uid:gid of the user on the host system the command was initiated from.

**Comment by ctrlrsf** [comment]
Confirmed this is happening.

```
vagrant@development:~$ id
uid=1000(vagrant) gid=1000(vagrant) groups=1000(vagrant),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),110(lxd),113(lpadmin),114(sambashare)

vagrant@development:~$ lxc exec c1 -- /bin/bash -c 'echo content > /tmp/file'

vagrant@development:~$ lxc exec c1 -- /bin/bash -c 'ls -al /tmp/file'
-rw-r--r-- 1 root root 8 May 26 19:18 /tmp/file

# Change content of file here
vagrant@development:~$ lxc file edit c1/tmp/file

vagrant@development:~$ lxc exec c1 -- /bin/bash -c 'ls -al /tmp/file'
-rw-r--r-- 1 ubuntu ubuntu 8 May 26 19:19 /tmp/file

vagrant@development:~$ lxc exec c1 -- /bin/bash -c 'stat /tmp/file'
  File: '/tmp/file'
  Size: 16              Blocks: 8          IO Block: 4096   regular file
Device: fc00h/64512d    Inode: 3675766     Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/  ubuntu)   Gid: ( 1000/  ubuntu)
Access: 2016-05-26 19:23:46.976442001 +0000
Modify: 2016-05-26 19:23:54.728442001 +0000
Change: 2016-05-26 19:23:54.728442001 +0000
 Birth: 

```

**Comment by ctrlrsf** [comment]
I'm seeing same behavior with lxc file push. That is, if destination file exists, it changes destination's uid, gid and mode to source file's uid, gid, and mode. Is this intended behavior, or if destination file already exists, should it just leave owner and permissions as is?

```
vagrant@vagrant:~/go/src/github.com/lxc/lxd$ lxc file push testfile c1/tmp/file
vagrant@vagrant:~/go/src/github.com/lxc/lxd$ lxc exec c1 -- ls -al /tmp/file
-rw-rw-r-- 1 ubuntu ubuntu 7 May 27 03:04 /tmp/file

vagrant@vagrant:~/go/src/github.com/lxc/lxd$ lxc exec c1 -- chmod 700 /tmp/file
vagrant@vagrant:~/go/src/github.com/lxc/lxd$ lxc exec c1 -- chown nobody /tmp/file
vagrant@vagrant:~/go/src/github.com/lxc/lxd$ lxc exec c1 -- ls -al /tmp/file
-rwx------ 1 nobody ubuntu 7 May 27 03:04 /tmp/file

vagrant@vagrant:~/go/src/github.com/lxc/lxd$ lxc file push testfile c1/tmp/file
vagrant@vagrant:~/go/src/github.com/lxc/lxd$ lxc exec c1 -- ls -al /tmp/file
-rw-rw-r-- 1 ubuntu ubuntu 7 May 27 03:04 /tmp/file
```

**Comment by stgraber** [comment]
So we should definitely fix "edit" not to change the ownership and permissions.

As for push, it's a bit trickier due to the way the API works. Basically right now the client does give the server a uid, gid and mode, and the server rightfully applies those.

The problem is that there is no good way for the client to know if the path exists ahead of time and only pass the ownership and permission information if it does.

So I think what we can do is:
 - Fix edit not to send permission information, which will cause the server to retain the existing owner and permissions.
 - Add a new option to the API which instructs the server to only apply the provided ownership and permissions if the file doesn't exist.

**Comment by stgraber** [comment]
I'll use this issue to track the bugfix part of this. Feel free to file a new issue for the second part (which will be tracked as a feature and not be included in bugfix releases).
