### ISSUE TITLE
Create container from directory (not image)

### ISSUE THREAD

**Issue by kirgene** [lxc/lxd#2081]
I'd like to migrate my linux VMs from KVM to LXD and wanted just copy root directory of my VM to some place on my host machine to use it as container.
Is there any way to do it?

**Comment by stgraber** [comment]
Kinda. The problem is with the fact that LXD containers are unprivileged by default, so you'd have to do id mapping which isn't very much fun.

Instead you can do:

 - lxc init ubuntu:14.04 blah -c security.privileged
 - Replace /var/lib/lxd/containers/blah/rootfs with the VM rootfs
 - lxc config set blah security.privileged false
 - lxc start blah

**Comment by kirgene** [comment]
Great, thanks!
