### ISSUE TITLE
NFS connection drops on host, as physical interface is added to lxdbr0.

### ISSUE THREAD

**Issue by pulnarayana1** [lxc/lxd#2085]
I am using PXE boot with NFS root bound to eth0 interface. I am using the default lxdbr0 setup to create the network connections for the containers.
When I am trying to add the physical interface which was bound to NFS root to lxdbr0 inorder to get the containers on network, the system hangs up throwing error message as follows

eth0 entered into promiscuous mode
NFS server not responding still trying .

and then the kernel crashes.

Can someone shed some light on how to fix this issue?

I tried other network configuration such as macvlan, and I am able to bring the containers on a network, however, CRIU dump and restore are not working, since they are confined only to veth devices as of now.

**Comment by stgraber** [comment]
So you're attempting to move a configured eth0 device that's used for your nfs root into the lxdbr0 bridge?

I can't see how this would possibly work. Your network config on eth0 would be wiped in the process, this would also expose the DHCP server running on lxdbr0 to the rest of your network, possibly re-addressing a bunch of machines in the process and would also cause your MAC address to appear different, ensuring that things really don't work well anymore :)

If you want to bridge eth0, you have to do it right. Which typically means having a bridge created and eth0 bridged into it before setting up an IP on the bridge so you can communicate with the outside world.


If you want to use lxdbr0, you'd need to do something like:
 - Configure lxdbr0 to not have any IPv4 or IPv6 subnet associated with it and no dnsmasq instance running
 - Copy the MAC address from eth0 to lxdbr0
 - Copy the network configuration of eth0 to lxdbr0
 - Unconfigure the network on eth0 (but don't bring it down!)
 - Bridge eth0 into lxdbr0
 - Re-apply the default gateway as it'll have been lost in the process

You'd obviously need to script the above as network will be unavailable somewhere in the middle of it. Since your root is on NFS, you'll also need to make sure that any command you run from the point where you loose network has been pre-cached in the page cache, otherwise, your kernel will hang and crash when trying to execute it.

**Comment by pulnarayana1** [comment]
Hi Stephane,

Thanks for quick reply.

Yes, I am trying to move a configured eth device that's used for NFS root to lxdbro, since that is the only available physical interface connected to the network.


Is there any other way, I can provide network connectivity to the containers via veth devices or some other which are capable of CRIU restore and dump ?

I tried the steps that you mentioned above, but still no luck.

The modified /etc/network/interfaces file is as follows

auto br0
iface br0 inet dhcp
	ip link set br0 address 90:e2:ba:5a:6d:50
	bridge_ports eth2
	bridge-ifaces eth2
	up ifconfig eth2 up
	bridge_fd 0

iface eth2 inet manual


![image](https://cloud.githubusercontent.com/assets/10556902/15873594/64b9e51a-2ccd-11e6-8d88-011a0a65639b.png)

**Comment by pulnarayana1** [comment]
@stgraber 
I tried the same as you mentioned above, and was able to ping to a network on the network from the macv and also with br0 interface using

ping -i macv 10.16.11.1
ping -i br0 10.16.11.1

However was unable to connect to the network from inside the container.

And debug information is as follows.

ip link is as follows

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether f0:1f:af:e5:1d:70 brd ff:ff:ff:ff:ff:ff
3: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether f0:1f:af:e5:1d:71 brd ff:ff:ff:ff:ff:ff
4: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 90:e2:ba:5a:6d:50 brd ff:ff:ff:ff:ff:ff
5: eth3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 90:e2:ba:5a:6d:51 brd ff:ff:ff:ff:ff:ff
34: macv@eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue master br0 state UP mode DEFAULT group default qlen 1
    link/ether 5a:41:3a:8a:0c:2d brd ff:ff:ff:ff:ff:ff
35: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 5a:41:3a:8a:0c:2d brd ff:ff:ff:ff:ff:ff
42: vethI2MWJD@if41: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br0 state UP mode DEFAULT group default qlen 1000
    link/ether fe:19:07:bd:00:1f brd ff:ff:ff:ff:ff:ff link-netnsid 0


brctl show is as follows

bridge name	bridge id		STP enabled	interfaces
br0		8000.5a413a8a0c2d	no		macv
						                 	vethI2MWJD

sudo lxc list
+------+---------+-----------------------+------+------------+-----------+
| NAME |  STATE  |         IPV4          | IPV6 |    TYPE    | SNAPSHOTS |
+------+---------+-----------------------+------+------------+-----------+
| u1   | RUNNING | 10.200.200.101 (eth0) |      | PERSISTENT | 0         |
+------+---------+-----------------------+------+------------+-----------+

And interfaces file inside the container is

root@u1:~# cat /etc/network/interfaces.d/eth0.cfg 
# The primary network interface
auto eth0
iface eth0 inet static
    address 10.200.200.101
    broadcast 10.255.255.255
    netmask 255.0.0.0
    gateway 10.254.0.48

root@u1:~# ping 10.16.10.1
PING 10.16.10.1 (10.16.10.1) 56(84) bytes of data.
From 10.200.200.101 icmp_seq=1 Destination Host Unreachable

Am I missing something ?
How to connect to the network from the container ?

**Comment by pulnarayana1** [comment]
Can someone comment on this ?

**Comment by stgraber** [comment]
Could be a number of different things, none really relevant to LXD...

 - Your switch may be blocking multiple MAC addresses
 - One of "eth2 on host", "macv on host", "br0 on host" or "eth0 in container" may be down
 - 10.16.10.1 can't talk back to you for some reason (wrong netmask?)

You probably want to triple check everything and if all looks good, then start doing some tcpdump to see where things are getting stuck.

**Comment by pulnarayana1** [comment]
@stgraber 
Thanks :+1: 
Got fixed..
