### ISSUE TITLE
RAM is not properly isolated [glances]

### ISSUE THREAD

**Issue by loru** [lxc/lxd#2109]
# Required information

 * Distribution: Ubuntu 16.04
 * Distribution version: Ubuntu 16.04
   * Kernel version: 4.4.0-22-generic
   * LXD version: 2.0.2
   * Storage backend in use: ZFS

# Issue description

The host server runs with 4 Gigs of ram. The container is set to use only 256MB of ram. Even tho you can find the proper /proc/meminfo, running glances will show the entire RAM:

/proc/meminfo:
```
MemTotal:         262144 kB
MemFree:          173640 kB
MemAvailable:     173640 kB
Buffers:               0 kB
Cached:            58916 kB
SwapCached:            0 kB
Active:           830952 kB
Inactive:         137448 kB
Active(anon):     111448 kB
Inactive(anon):    65648 kB
Active(file):     719504 kB
Inactive(file):    71800 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:                52 kB
Writeback:             0 kB
AnonPages:         89192 kB
Mapped:            77764 kB
Shmem:             87876 kB
Slab:               0 kB
SReclaimable:     101908 kB
SUnreclaim:       701888 kB
KernelStack:       11488 kB
PageTables:         6996 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     1983828 kB
Committed_AS:     640552 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:     26624 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      148068 kB
DirectMap2M:     3971072 kB
```

htop:

![screen shot 2016-06-12 at 12 26 27 pm](https://cloud.githubusercontent.com/assets/19887885/15990633/460435b0-3099-11e6-826e-0445e9d035e0.png)

atop:

![screen shot 2016-06-12 at 12 27 30 pm](https://cloud.githubusercontent.com/assets/19887885/15990636/4ff5ba30-3099-11e6-8b3e-7e5af8e9002e.png)

glances:

![screen shot 2016-06-12 at 12 26 53 pm](https://cloud.githubusercontent.com/assets/19887885/15990638/555e95dc-3099-11e6-82c5-9d53ed04f4ee.png)

# Steps to reproduce

 1. Inside the container, set a hard memory limit, for example 256MB
 2. Install the package glances (available in ubuntu/debian)
 3. Run glances as root (in the container): it will display the entire ram, not the ram you configured earlier

Am I missing something? How am I supposed to know where glances is getting these infos?

**Comment by simos** [comment]
First of all, while the command can show the total size of the host memory, the container cannot touch the memory of other containers or the host.

There has been a discussion at https://fabiokung.com/2014/03/13/memory-inside-linux-containers/ about memory, and the fact that some /proc files like /proc/meminfo are not 'containarized'. That is, they are not adapted yet in the container in order to show the actual limit (and hide the host details).

``glances`` is written in Python and it reads information from /proc. I had a quick glance and it uses information from /proc, probably /proc/meminfo. You can have a look as well by getting the source with ``apt source glances``.

**Comment by stgraber** [comment]
If lxcfs is installed and running, you should have an overlay file mounted on top of /proc/meminfo that shows the right values.

**Comment by loru** [comment]
So it only shows but cannot access. As far as I understand, it is related to the /proc/ management?

In OpenVZ, it is properly handled. I think it is because they have patches in the kernel. I saw the solutions and alternatives, apparently it is hard to fix that.

Wouldn't this cause issues with softwares like MySQL which will never know when to stop as it thinks there is more ram than allowed?

@stgraber: it is installed and running already and the values are shown correctly in htop/atop but not in glances.

**Comment by stgraber** [comment]
Looks like glances is counting memory by looking at the active and inactive fields which lxcfs doesn't set to container values.

So memory limits are definitely active, it's just the reporting that's not correct due to not all fields in meminfo being correct.

Feel free to file a bug at github.com/lxc/lxcfs or even better, send a patch :)

Closing this issue as it's not a LXD problem, the limit was properly set, it's just a reporting issue by lxcfs.
