### ISSUE TITLE
Generate Audit Trail for Events Inside the Container

### ISSUE THREAD

**Issue by chrsigg** [lxc/lxd#2188]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 16.04
 * The output of "lxc info":

  driver: lxc
  driverversion: 2.0.1
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-28-generic
  server: lxd
  serverversion: 2.0.2
  storage: btrfs
  storageversion: "4.4"

# Issue description

User login lifecycle events (login, su, etc.) inside the container don't generate an audit trail in the `audit.log` of the host. Is this a limitation of containers/namespaces, or can it be done?

**Comment by stgraber** [comment]
If an unprivileged container could create audit entries on the host, then any unprivileged user on your system would be able to fake audit entries using the same facility.

I believe the audit folks are working on (or did) implement audit namespacing so that rather than audit messages from containers just going nowhere those could be logged by auditd INSIDE the container.

I don't believe there is any way to have those picked up by the host auditd and that's on purpose.

**Comment by chrsigg** [comment]
Thank you for the explanation. Reading this recent linux-audit [post](https://www.redhat.com/archives/linux-audit/2016-July/msg00000.html) by Richard Briggs, auditing containers is still some time away.

**Comment by Hooloovoo** [comment]
For further background, please see:
[https://github.com/linux-audit/audit-kernel/wiki/RFE-Audit-Container-ID](https://github.com/linux-audit/audit-kernel/wiki/RFE-Audit-Container-ID)
and the various links in there.

There was also a (2016) LWN on this:
[https://lwn.net/Articles/699819/](https://lwn.net/Articles/699819/)
