### ISSUE TITLE
container can change its dns hostname with a dhcp request

### ISSUE THREAD

**Issue by smoser** [lxc/lxd#2244]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: N/A
   * LXC version: 2.0.3-0ubuntu1~ubuntu16.04.2
   * LXD version:2.0.3-0ubuntu1~ubuntu16.04.2
   * Storage backend in use: N/A

# Issue description
As described at Launchpad [bug 1600766](https://bugs.launchpad.net/cloud-init/+bug/1600766), a container can change the hostname that dnsmasq resolves by changing /etc/hostname and then doing a restart (or otherwise putting such a dhcp request out).

This means that asking that dnsmasq for information really can't be trusted as any misbehaving or malicious container can take the dns name of another container.

Instead of letting the container define its hostname, lxd should manage make dnsmasq return the correct host names.

**Comment by stgraber** [comment]
It's typically the expected behavior on a local bridge, you get the exact same thing with libvirt, with lxc and most likely with docker. Any of those basic dnsmasq ran network allow self-registration in DNS through the submitted hostname.

We will soon have LXD and dnsmasq much more tightly coupled so we may be able to make things a bit better, at least for the containers which specify a static lease in their config.

For containers that won't be using a static DHCP lease, there's not a great deal we can do. We can allow to have them self-register as they do today with the same problems or we can prevent any container that doesn't have a static lease from getting into the DNS.

One thing that we can't do reliably is inspect what IP the container has and generate DNS records from those as users in the container can rename their NICs whichever way they want and there is no good API to trace the host side veth device to the container's side veth device when they rename it. For example we would be unable to figure out from the outside that we need to take the IP of a bridge if the container side veth device is inside it.

In theory what we could do is monitor the dnsmasq log and whenever we see a DHCP request coming in, go look in our database for any container that's got that MAC address assigned to one of its NICs, then re-generate the static hosts file for dnsmasq and reload dnsmasq.
Suffice to say, that'd be a very expensive process and one that absolutely wouldn't scale when running hundreds or thousands of containers (way too many requests, would always have to re-check in case we get a DHCP RELEASE and the MAC is re-assigned to another container and bouncing dnsmasq constantly may affect its ability to respond to requests).

**Comment by stgraber** [comment]
One alternative I guess would be to always assign a static address ourselves for every container,  then synthesize the DNS records (IPv4, IPv6, PTR) depending on what's enabled for that given bridge and completely turn off the self-registration feature in such mode. The obvious downside of this one is that the container may have IPv4 or IPv6 disabled, may have a different static IP set, ... in all of those cases the DNS record would be inaccurate.

And obviously, in this mode, the LXD container name would be what's registered in DNS, not the container's hostname.

**Comment by stgraber** [comment]
So we have some plans around bridge management for the next few months. With that work, we should be able to provide some configuration around the way DNS works, most likely the following 3 modes:
 - No DNS records (dnsmasq acts as a forwarder but that's it)
 - DHCP self-registration (current behavior)
 - Static registration (we assign a static lease for IPv4, compute the EUI64 address for IPv6 and generate the matching A, AAAA and PTR records in the DNS, regardless of whether the container is using those addresses)

**Comment by stgraber** [comment]
Marking this as blocked for now. Our network management work which should be scheduled very soon should address this by offering an option to have host-managed DNS.

**Comment by stgraber** [comment]
Fixed by the new network work. A LXD managed bridge can have DNS configured in "managed" mode (default) which will have LXD assign DNS entries to containers. One can still set this to "dynamic" to keep the current behavior or turn off dns registration entirely with "none".
