### ISSUE TITLE
Networking Connectivity issues

### ISSUE THREAD

**Issue by upuvvad1** [lxc/lxd#2377]
Ubuntu Xenial
LXD 2.0.2

Is there any way I can communicate with the container from outside world and also able to live migrate the container across different servers ?

At present, I am using the lxd bridge and was unable to communicate to containers from outside world, however, was able to communicate from inside the container.

**Comment by tych0** [comment]
On Wed, Sep 14, 2016 at 01:23:56PM -0700, upuvvad1 wrote:
> Ubuntu Xenial
> LXD 2.0.2
> 
> Is there any way I can communicate with the container from outside world and also able to live migrate the container across different servers ?

You can set up a bridge to the outside world on the host's interface;
this would mean that the container can get IP addresses from the
same DHCP server the host does. There are details about how to do
this at the end of this blog post:

http://tycho.ws/blog/2016/04/lxdbr0.html

Unfortunately you can't use macvlan right now, because there's not
live migration support for it yet. I posted a patchset for macvlan
support to the CRIU mailing list in May, but I haven't gotten a chance
to revisit it :(. Hopefully soon I will, though!

**Comment by upuvvad1** [comment]
@tych0 
Thankyou.
I am looking forward for macvlan support for CRIU.
Did the patch for macvlan went in for release ?

**Comment by tych0** [comment]
On Thu, Sep 15, 2016 at 09:28:50AM -0700, upuvvad1 wrote:
> @tych0 
> Thankyou.
> I am looking forward for macvlan support for CRIU.
> Did the patch for macvlan went in for release ?

No, it needs rebasing unfortunately. I'm hoping to do it soon, but
there's a few other things in the queue beforehand :(

**Comment by upuvvad1** [comment]
@tych0 
Thank you.

And also 1 more question.

As you suggested in the article,
Creating the bridge and linking the physical interface to the bridge and using this specific bridge in lxc profile in order to communicate to container from the outside world.

Should it necessarily be a physical interface ? Because I am PXE booting my server on the physical interface and also mounting NFS on that.
If I try to add the physical interface to the bridge as you suggested, the system hangs up.

Is there any other alternative I can try ?

I also tried creating macvlan for the physical interface, and adding this macvlan to bridge but it didn't work.
DHCPDECLINE messages were pumping out.

**Comment by tych0** [comment]
On Thu, Sep 15, 2016 at 01:06:51PM -0700, upuvvad1 wrote:
> @tych0 
> Thank you.
> 
> And also 1 more question.
> 
> As you suggested in the article,
> Creating the bridge and linking the physical interface to the bridge and using this specific bridge in lxc profile in order to communicate to container from the outside world.
> 
> Should it necessarily be a physical interface ? Because I am PXE booting my server on the physical interface and also mounting NFS on that.
> If I try to add the physical interface to the bridge as you suggested, the system hangs up.

I think it should be fine to PXE boot on the interface, although you
probably have to wait and mount NFS until after the bridge is up.

> Is there any other alternative I can try ?

Not really since you want to be able to live migrate as well.

> I also tried creating macvlan for the physical interface, and adding this macvlan to bridge but it didn't work.
> DHCPDECLINE messages were pumping out.

What were you running inside the container?
