### ISSUE TITLE
Fails to configure device using lxc config, which were added through profile

### ISSUE THREAD

**Issue by upuvvad1** [lxc/lxd#2462]
LXD 2.4
LXC 2.4
Ubuntu 16.04

lxc config fails to edit/set the device properties which were added from profile.

lxc profile show default:

name: default
config: {}
description: Default LXD profile
devices:
  eth0:
    mtu: "9000"
    nictype: bridged
    parent: br0
    type: nic
  mount-ops:
    path: /var/work/www
    source: /var/work/www
    type: disk
usedby:
- /1.0/containers/es2-xenial

lxc config device list es2-xenial 
root: disk

lxc doesn't list the devices and edit them.

lxc config device set es2-xenial eth0 host_name es2-xenial
error: The device doesn't exist

I am trying to set the interface name on the host side equivalent to container name or some format which identifies the interface to container name.

Is there any way I can use the environment variable in the profile, which can make the task easier ?
something like $lxd_name ??

name: default
config: {}
description: Default LXD profile
devices:
  eth0:
   **host_name: $lxd_name**
    mtu: "9000"
    nictype: bridged

**Comment by stgraber** [comment]
The way devices work is that they belong to a profile or to a container. In your case, the device belongs to a profile and is just inherited by the container which is why you can't see it in edit or modify it with "lxc config set".

To do what you want, you need to override the device for the container with:

    lxc config device add es2-xenial eth0 nic nictype=bridged mtu=9000 parent=br0 host_name=es2-xenial

Since container local configuration is favored over inherited one coming from profiles, this will replace the eth0 device coming from your default profile by one specific to the container.


As for allowing for variables. I'm not opposed to the concept, however I'd recommend against it for this particular case as network interface names are limited to 15 characters (kernel restriction) whereas hostnames can be up to 64 characters long.

It's not uncommon to have names generated by LXD be longer than 15 characters, so this would lead to some rather confusing errors unless you manually assign all your container names.

**Comment by upuvvad1** [comment]
That make's sense.
Thanks @stgraber 

Is there any startup script which will be called before launching the container (pre-start and post-stop) ? 
which makes things easier to config and cleanup after stopping the container.

**Comment by stgraber** [comment]
Unfortunately, no. LXD doesn't have support for calling hooks.

This was a deliberate decision to ensure a consistent environment across hosts, which is critical when we support things like live migration where depending on local scripts which may have their own dependencies makes things a bit tricky.

One thing you could do though is write a small API client which connects to our /1.0/events websocket and then trigger whatever action you want upon receiving a given event. This has the benefit of working remotely too, so you could have one such daemon monitoring several LXD hosts and updating your container's config as appropriate.

**Comment by upuvvad1** [comment]
Hmm..
I realize that support for multiple environments.
Thank you !! :+1:

**Comment by waynegemmell** [comment]
FYI @stgraber , I came across this issue following https://ubuntu.com/blog/network-management-with-lxd-2-3 . Either I'm not following it well or it needs a little clarity there.
