### ISSUE TITLE
lxc launch ubuntu:16.04 foo doesn't create any image aliases

### ISSUE THREAD

**Issue by tych0** [lxc/lxd#2486]
All I end up with is,

```
stock2:~ lxc launch ubuntu:16.04 foo
Creating foo
Retrieving image: 100%
Starting foo
stock2:~ lxc image list
+-------+--------------+--------+---------------------------------------------+--------+----------+------------------------------+
| ALIAS | FINGERPRINT  | PUBLIC |                 DESCRIPTION                 |  ARCH  |   SIZE   |         UPLOAD DATE          |
+-------+--------------+--------+---------------------------------------------+--------+----------+------------------------------+
|       | de051f59f701 | no     | ubuntu 16.04 LTS amd64 (release) (20161011) | x86_64 | 143.12MB | Oct 12, 2016 at 3:19pm (UTC) |
+-------+--------------+--------+---------------------------------------------+--------+----------+------------------------------+
```

**Comment by stgraber** [comment]
That's the expected behavior. When just caching a remote image, we don't have any need for local aliases, in fact those could clash with user added local aliases which would be a problem.

You're free to add aliases to any cached image, which will then be kept when the image is updated though.

The expected workflow for cached images is that the user will keep launching that image by using "ubuntu:16.04" as the source, which will be resolved by LXD through the simplestreams cache (refreshed hourly) and then use the local image.

If you want to copy all the aliases from the remote image server to your local server, you can do so with:

    lxc image copy ubuntu:16.04 local: --auto-update --copy-aliases

**Comment by tych0** [comment]
Oh, sorry, I thought we did with `ubuntu:x` but not with `ubuntu:16.04`, but apparently we don't with either.
