### ISSUE TITLE
Make image import more disk space friendly

### ISSUE THREAD

**Issue by palica** [lxc/lxd#2508]
The process of image import seems to me very disk space inefficient. First it copies the tar 2x into lxd_build, then it extracts it into hash.btrfs/rootfs and it also creates a hash file that is in the images folder that is exactly the size of the image.

**Comment by stgraber** [comment]
Is that "lxc image import" with a file passed as an argument or with a URL or copying an image from a remote server?

**Comment by palica** [comment]
It is "lxc image import"  with file passed as an argument. If the file is a tar containing both the metadata.yaml and rootfs. 
What I also don't understand is why there are the original? archive files left in the images folder. Such as here:

320M    /var/lib/lxd/images/ad6dcf8dc10c57e3eb196724366c100ebcd02865a282ef1b0469ed166b7402ab
1.9G    /var/lib/lxd/images/ad6dcf8dc10c57e3eb196724366c100ebcd02865a282ef1b0469ed166b7402ab.btrfs

funtoo | ad6dcf8dc10c | no     | Funtoo for ARM                     | armv7l | 319.15MB | Sep 24, 2016 at 10:19am (UTC)

LXD 2.4.1
LXC 2.0.5

**Comment by stgraber** [comment]
LXD always keeps the compressed image around in /var/lib/lxd/images as it's the only true source of the image (the only one which actually matches the fingerprint).

We can't reproduce the tarball with the right fingerprint from a btrfs or zfs volume and we need to be able to get to the right tarball again when the image is exported or copied between hosts.

**Comment by stgraber** [comment]
So the expected behavior when importing an image with "lxc image import <tarball>" is:
 - The client reads "<tarball>" from disk and sends it over the API to the daemon
 - The daemon writes it down to a temporary path (otherwise we'll run out of memory)
 - The daemon will then partially extract the tarball to get to metadata.yaml and parse it
 - If a storage backend is used (not "dir"), then the tarball is passed to that storage backend to unpack and create whatever representation it needs (btrfs subvolume in your case)

So as far as copies of the image you should end up with
 - The original tarball that you passed to "lxc image import"
 - An identical copy of this at /var/lib/lxd/images/<sha256>
 - An unpacked tree in /var/lib/lxd/images/<sha256>.btrfs

The copy at /var/lib/lxd/images/<sha256> is supposed to be the same file as the temporary file LXD wrote when processing the upload. That temporary file is moved from its temporary name over to /var/lib/lxd/images/<sha256> once the image is considered as valid (and recorded in the database).

**Comment by palica** [comment]
The end result is acceptable (why do you have to have the original tarball, can't we do some kind of btrfs send, zfs send on btrfs/zfs?, or btrfs/zfs snapshot of imported data to be able to get the fingerprint, or just add the fingerprint to the db and create snapshot @install that would then be used to copy images to remotes).

Temporary files from a rather large image (16GB) with user-data.

```
/var/lib/lxd/images/lxd_build_128542463/:
total 32G
drwx------ 1 root root   70 Oct 17 08:24 ./
drwx------ 1 root root  306 Oct 17 08:16 ../
-rw------- 1 root root  16G Oct 17 08:24 lxd_post_605845074
-rw------- 1 root root  16G Oct 17 08:28 lxd_tar_518506377

```
So at one time the disk contains 16GB tarball that is being added, two (and here I think we could do some space/storage optimizing) temporary images lxd_post_ and lxd_tar_ both containing the same information and the copy of tarball in /var/lib/lxd/images/fingerprint and the extracted rootfs.

So in my case:
* original 16G
* temporary 16 + 16G
* tarball copy 16G
* rootfs extracted 16G
At some time it takes like 3x if not 4x the original image. The end result is then original, tar copy rootfs extracted, where you can delete the original after import so only 2x copies.

What I am trying to say is: do we need two temporary (lxd_post and lxd_tar) copies of the same tar in the temp build folder? Can this be cleaned up after reading the metadata.yaml from the tar, why extract the whole archive, why not extract only the metadata.yaml?

Thank you very much for your explanation and thoughts
Pavol

**Comment by stgraber** [comment]
Hmm, no we shouldn't have two copies of the temporary file. We do extract only metadata.yaml, unfortunately with compressed tarballs, whether you can do so without reading the whole thing is kinda random.

So we do tell tar to extract just that one file, but depending on where it's located in the archive and how the compression messes with all this, tar often has to read it all.

As for not keeping the tarball around, "lxc image export" must be able to give you a tarball and that tarball's sha256 must match the image fingerprint. Similarly, if you copy an image from one host to another, the target host must still be able to export the image as a tarball and have the fingerprint match. So we absolutely do have to keep those around.

I'll take a look at why we've got two temp files since that part is definitely a bug.

**Comment by palica** [comment]
I am using an uncompressed .tar, and creating it with 

tar -cf image.tar metadata.yaml rootfs

so, metadata.yaml should be at the beginning of archive. 

Thanks

**Comment by stgraber** [comment]
It should indeed and I've confirmed that getImageMetadata does ask tar to extract just that one file, so there's not much else we can do on that...

**Comment by palica** [comment]
Is there something else I can do?

**Comment by stgraber** [comment]
I don't think so. I'll be taking a look at why we have two copies of the temp file in a bit, that'll save you quite a few GBs already :)

**Comment by palica** [comment]
Thank you :)
