### ISSUE TITLE
Proposal for optimizing func storageRsyncCopy- rsync's checksum

### ISSUE THREAD

**Issue by nakatadim** [lxc/lxd#2681]
# Required information

 * Distribution: Ubunu 
 * Distribution version:16.04
 * The output of "lxc info" or if that fails:
   * Kernel version:4.4.0.51
   * LXC version:
   * LXD version:2.6.2-0ubuntu1~ubuntu16.04.1~ppa1

Due to the recently introduced dir based containers snapshot- "init rsync->freeze->second rsync->unfreeze" the option "--checksum" in rsync's exec.Command becomes a bit over reinsurance and not needed neither on the first nor the second rsync stage- the frozen state during the second rsync would take care of it- size + time of change on 1 sec granularity(in rsync 3.1.1) is enough guarantee in this case. Because of the fact that it's so slow it leads to often errors in snapshots like for example:
`root@lx1:~# lxc snapshot cms working
error: rsync failed: file has vanished: "/var/lib/lxd/containers/cms/rootfs/var/lib/cloudera-service-monitor/ts/stream/partitions/stream_2016-12-02T18:56:29.683Z/000019.log"
rsync warning: some files vanished before they could be transferred (code 24) at main.c(1183) [sender=3.1.1]
`
Not to mention the extra performance hit.
What if whether to use it or not is a parameter of the storageRsyncCopy func- while using it in dir based containers snapshots is not needed it might be wise to have it elsewhere.

Cheers,
Atanas

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [ ] any relevant kernel output (dmesg)
 - [ ] container log (lxc info NAME --show-log)
 - [ ] main daemon log (/var/log/lxd.log)
 - [ ] output of the client with --debug
 - [ ] output of the daemon with --debug

**Comment by stgraber** [comment]
Hmm, I'm very much not convince that this is safe to do.

Say one of the last files of the first rsync pass was modified immediately before rsync copies it, then changed immediately afterwards without its size changing (say abc -> def), now the second pass will assume that it's unchanged, giving you "abc" on disk instead of "def".

In fact we added that rsync option specifically because our testsuite was tripping this very issue in our snapshot tests where we have a tiny container (few KBs large) and the test file we use for the snapshot contains "abc" changing to "def" (so same size).

**Comment by stgraber** [comment]
Unfortunately the rsync protocol doesn't seem to allow for a file list to be generated on both source & target without checksums and then for checksums to be generated only for files which otherwise look identical.

It is however moderately clever in that it will checksum all the source files, but only checksum the destination files which otherwise look identical, skipping the hashing for any file that's marked as needing transferring for any other reason.

**Comment by nakatadim** [comment]
lets put on test the worst case: 
1. while running the "initial sync" the last file synced from the operation is such a file- "abc" changes on disk to "def" right after the rsync's finish- this doesn't change the size but it does change the modify time. If the second rsync pass run extremely fast right after the first one- say in 1 sec this would lead to your case for sure as we have 1sec granularity
2. What if we add Sleep(1) or Sleep(2)(more safe) between the first rsync pass and say the freeze ot the beginning of the second rsync pass-  in that case the file will be copied due to the changed modificaton time regarding of the same file size. 1 or 2 seconds will be far less than the complications of the "--checksum"

**Comment by stgraber** [comment]
Add a sleep wouldn't change anything. The two version of the files would still have a timestamp that's within 1s of each other and with the same size.

So long as something in the container can write before and after the first rsync, this race is possible. The only way to avoid it would be to freeze the container even for the first rsync but that'd make the snapshot overhead (as far as time), massively bigger.

**Comment by nakatadim** [comment]
Ahh you're right. Shame the patch https://lists.samba.org/archive/rsync/2015-September/030341.html hasn't been committed yet.
