### ISSUE TITLE
lxd --group lxd  error: yaml: control characters are not allowed

### ISSUE THREAD

**Issue by vilagithub** [lxc/lxd#2697]
apt-cache policy lxd
lxd:
  Installed: 2.6.2-0ubuntu3~ubuntu14.04.1~ppa1
  Candidate: 2.6.2-0ubuntu3~ubuntu14.04.1~ppa1
  Version table:
 *** 2.6.2-0ubuntu3~ubuntu14.04.1~ppa1 0
        500 http://ppa.launchpad.net/ubuntu-lxc/lxd-stable/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
     2.0.8-0ubuntu1~ubuntu14.04.2 0
        100 http://nova.clouds.archive.ubuntu.com/ubuntu/ trusty-backports/universe amd64 Packages

$ lxd --debug --verbose --group lxd
INFO[12-06|23:11:24] LXD is starting in normal mode           path=/var/lib/lxd
WARN[12-06|23:11:24] Couldn't find the CGroup network class controller, network limits will be ignored. 
WARN[12-06|23:11:24] Couldn't find the CGroup pids controller, process limits will be ignored. 
WARN[12-06|23:11:24] CGroup memory swap accounting is disabled, swap limits will be ignored. 
INFO[12-06|23:11:24] Default uid/gid map: 
INFO[12-06|23:11:24]  - u 0 1017504 65536 
INFO[12-06|23:11:24]  - g 0 1017504 65536 
DBUG[12-06|23:11:24] Init                                     driver=storage/dir
DBUG[12-06|23:11:24] Applying patch: invalid_profile_names 
DBUG[12-06|23:11:24] Applying patch: leftover_profile_config 
error: yaml: control characters are not allowed

Re-installed from scratch, no containers, no images.

I'm at a loss about where to look to debug further...

**Comment by stgraber** [comment]
That's a rather weird one... Would you mind sharing your /var/lib/lxd/lxd.db as well as "sudo find /var/lib/lxd/".

Hopefully that'll let us reproduce the issue and track down what's causing it.

To reset your system to a working state, since you say you don't have container or images there, removing /var/lib/lxd/lxd.db from disk and restarting lxd (sudo restart lxd) should fix things.

I suspect it's got something to do with running LXD 2.6.2 on 14.04, but it's not clear exactly what that would be.

**Comment by vilagithub** [comment]
lxd.db is empty (rm'ed it), so is /var/lib/lxd

sudo restart lxd hangs, I went down to lxd --group lxd after finding out the error in /var/log/upstart/lxd.log

**Comment by stgraber** [comment]
Tracked down to filesystem corruption of that particular VM, specifically the /var/cache/lxd/simplestreams.yaml file was severely corrupted, not yaml at all and containing content from several other (non-lxd) files.
