### ISSUE TITLE
tor in lxd: apparmor="DENIED" operation="change_onexec"  namespace="root//CONTAINERNAME_<var-lib-lxd>" profile="unconfined" name="system_tor"

### ISSUE THREAD

**Issue by gaetanquentin** [lxc/lxd#2700]
* Distribution: ubuntu
 * Distribution version: 16.10
 * lxc info:
apiextensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses:
  - 163.172.48.149:8443
  - 172.20.10.1:8443
  - 172.20.11.1:8443
  - 172.20.12.1:8443
  - 172.20.22.1:8443
  - 172.20.21.1:8443
  - 10.8.0.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  certificatefingerprint: 3048baa9f20d316f60a6c602452b58409a6d9e2c3218897e8de7c7c72af0179b
  driver: lxc
  driverversion: 2.0.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.8.0-27-generic
  server: lxd
  serverpid: 32694
  serverversion: 2.4.1
  storage: btrfs
  storageversion: 4.7.3
config:
  core.https_address: '[::]:8443'
  core.trust_password: true

Container: ubuntu 16.10

# Issue description

tor can't start  in a non privileged container 
Logs from the container:
--------------------------------
Dec  7 15:03:00 anonymous tor[302]: Configuration was valid
Dec  7 15:03:00 anonymous systemd[303]: tor@default.service: Failed at step APPARMOR spawning /usr/bin/tor: No such file or directory
Dec  7 15:03:00 anonymous systemd[1]: tor@default.service: Main process exited, code=exited, status=231/APPARMOR
Dec  7 15:03:00 anonymous systemd[1]: Failed to start Anonymizing overlay network for TCP.
Dec  7 15:03:00 anonymous systemd[1]: tor@default.service: Unit entered failed state.
Dec  7 15:03:00 anonymous systemd[1]: tor@default.service: Failed with result 'exit-code'.
Dec  7 15:03:00 anonymous systemd[1]: tor@default.service: Service hold-off time over, scheduling restart.
Dec  7 15:03:00 anonymous systemd[1]: Stopped Anonymizing overlay network for TCP.
Dec  7 15:03:00 anonymous systemd[1]: tor@default.service: Failed to reset devices.list: Operation not permitted
Dec  7 15:03:00 anonymous systemd[1]: Failed to set devices.allow on /system.slice/system-tor.slice/tor@default.service: Operation not permitted
Dec  7 15:03:00 anonymous systemd[1]: message repeated 6 times: [ Failed to set devices.allow on /system.slice/system-tor.slice/tor@default.service: Operation not permitted]
Dec  7 15:03:00 anonymous systemd[1]: Couldn't stat device /run/systemd/inaccessible/chr
Dec  7 15:03:00 anonymous systemd[1]: Couldn't stat device /run/systemd/inaccessible/blk
Dec  7 15:03:00 anonymous systemd[1]: Failed to set devices.allow on /system.slice/system-tor.slice/tor@default.service: Operation not permitted

Logs from the host
----------------------------
audit: type=1400 audit(1481119378.856:6950): apparmor="DENIED" operation="change_onexec" info="label not found" error=-2 namespace="root//lxd-anonymous_<var-lib-lxd>" profile="unconfined" name="system_tor" pid=12164 comm="(tor)"

# Steps to reproduce

 1. install ubuntu container 16.10 on a ubuntu 16.10 host
 2. install tor in the container
 3. Launch tor

aa-complain /etc/apparmor.d/system_tor on the host didn't change anything.

How to make it work?

Regards

**Comment by stgraber** [comment]
Ubuntu 16.10 supports loading apparmor profiles from inside a container, which is what tor is doing here. "aa-status" in a 16.10 container on Ubuntu 16.10 does show the system_tor profile being loaded.

Tor then somehow fails to switch to its profile with the kernel denying the change_onexec.

I'd recommend to file a bug on Launchpad, adding a tor task (in case its a missing bit in the apparmor profile) as well as an apparmor task (so that the apparmor folks can look into a potential bug in the kernel implementation).

You can do so at either https://launchpad.net/ubuntu/+source/apparmor/+filebug or https://launchpad.net/ubuntu/+source/tor/+filebug and then add the other package using the "also affects" link.

I'm closing this github issue because this is either an apparmor bug, or a kernel bug (still apparmor) or an issue with the tor profile, but I don't see how it could be a LXD bug in itself.

However, please post the link of the Launchpad bug in here so we can subscribe to it.

Thanks!

**Comment by gaetanquentin** [comment]
https://bugs.launchpad.net/ubuntu/+source/tor/+bug/1648143

**Comment by stgraber** [comment]
Thanks. I've subscribed the ~ubuntu-lxc team to it and pinged our apparmor contact so he can take a look at it.

**Comment by cryptofuture** [comment]
You should be able to run tor in container, if you disable apparmor for tor in systemd unit. aa-disable for tor profile in container or on host will not help.
How to do it (all in container with tor):
```sh
mkdir /etc/systemd/system/tor@default.service.d/
(echo "[Service]"; echo "AppArmorProfile=") > /etc/systemd/system/tor@default.service.d/override.conf
systemctl daemon-reload
systemctl restart tor
```
I can't figure out myself why it works, because you can have enforced and workable tor profile inside container and on host, and tor will work anyway.
