### ISSUE TITLE
Cross-compiling lxd through go build instead of go install

### ISSUE THREAD

**Issue by ffontaine** [lxc/lxd#2740]
When cross-compiling with go, go build must be used instead of go install: https://dave.cheney.net/2015/08/22/cross-compilation-with-go-1-5.

Adding a CROSS_COMPILE variable to the Makefile to change the default "go install" to "go build" would be nice.

What do you think of this proposal? Perhaps, this feature should not only be linked to cross-compilation?

**Comment by stgraber** [comment]
LXD can't be cross compiled due to it using cgo on most platforms.

**Comment by ffontaine** [comment]
LXD can be cross-compiled, we just need to enable cgo an give it a cross-compiler by setting CC_FOR_TARGET. Indeed, I was planning to add it to buildroot. runc and docker have been added recently to buildroot and they both used cgo like LXD. I think it would be nice to also add a buildroot package for LXD. I can made a patch for buildroot only but it would be better to have it upstream.

**Comment by stgraber** [comment]
Ok. Well, send a pull request and we can take it from there.

I'd probably prefer you make two new targets, "cross" and "client-cross" or something like that, rather than have the existing targets do completely different things based on an env variable (since go install will install in $GOPATH/bin whereas go build will dump the binary in the current working directory).

**Comment by stgraber** [comment]
Closing this issue as I don't really think that anyone who's in the business of cross-building will have much of a problem typing "go build -v github.com/lxc/lxd/lxc" instead of "make client-build" and there's also a problem with adding those two Makefile targets. "lxc" and "lxd" are both directories in the git tree. So calling "go build" from within the Makefile's location won't work as the resulting paths already exist.

**Comment by Jackly87** [comment]
Can you please add the  lxd makefile for buildroot environment
