### ISSUE TITLE
feature request: launch from container or snapshot

### ISSUE THREAD

**Issue by smoser** [lxc/lxd#2752]
I have a work flow where I want to modify a pristine image and then launch things from that modified reference.  Right now, that is achievable with:

    lxc init ubuntu-daily:xenial xcontainer-ref
    # some thing to modify that container 
    #   ('mount-image-callback -- lxd:xcontainer-ref' or lxc start...lxc stop
    lxc publish xcontainer-ref local: --alias=ximage-ref
    lxc launch ximage-ref x1

What I'd like to be able to do is avoid the 'publish', which does a full export of the image and then an import.  That is intensive disk and cpu, and also takes considerable time.

One path to solving my work flow would be to allow 'launch' to take a container (and ideally a container/snapshot) as well as an image reference.

What I'd like to do then would be:

    lxc init ubuntu-daily:xenial xcontainer-ref
    # some thing to modify that container 
    lxc launch xcontainer-ref x1 [... normal container flags]

I realize that the 'image' parameter to launch would then have issues if the input existed both as a container and an image, so perhaps `lxc launch container/xcontainer-ref[/snapshot]` might be used to safely extend that syntax.

**Comment by smoser** [comment]
Just remembered, there is another workflow that works and does not need to publish the image, and is closer, but less than perfect.

    lxc init ubuntu-daily:xeniali xcontainer-ref
    # modify reference container
    lxc copy xcontainer-ref x1
    lxc start x1 [... normal start flags]

Now that 'copy' can take `--config` flags, this is largely sufficient.  However, it basically comes down to wanting to use `launch` rather than `copy` and `start`.  Similarly, I always use `launch`, when instead I _could_ just as well use `init` and `start`.

**Comment by stgraber** [comment]
Marking as a maybe because I'm concerned about the confusion that this would then cause to users for what seems like very little gain.

There are actual differences between copying a container and creating a new one from an image:
 - A different set of templates are called
 - The properties of the parent container are kept (except for volatile)
 - In the case of a ZFS backend, the source container will now be unremovable, deleting it will not free any space
 - In the case of a ZFS backend, it will no longer be possible to restore a snapshot on the source container which pre-dates the last container copy
 - Copying a running container may lead to inconsistent filesystem state depending on what's running in the container (we atomically copy the filesystem but it doesn't guarantee that userspace has flushed its buffers).
 - For containers that do not use cloud-init, a copy will typically keep things like ssh keys, dbus UUID, systemd machine ID, ... identical to the source, causing potential conflict on the network afterwards.

Those constraints are easily explainable when launch and copy are two different things. Mixing them together will cause quite a bit of extra, and I think, unneeded, confusion.

**Comment by smoser** [comment]
On Wed, 21 Dec 2016, Stéphane Graber wrote:

> Marking as a maybe because I'm concerned about the confusion that this would then cause to users for what seems like very little gain.
>
> There are actual differences between copying a container and creating a new one from an image:
>  - A different set of templates are called
>  - The properties of the parent container are kept (except for volatile)

Both of these would be a good argument *for* having launch, versus copy
and start, because I assumed it would be the same thing.

>  - In the case of a ZFS backend, the source container will now be unremovable, deleting it will not free any space

Well, that somewhat "makes sense".  But is no different than you'd have
right now with 'copy'.

>  - In the case of a ZFS backend, it will no longer be possible to restore a snapshot on the source container which pre-dates the last container copy

Is there some reason that that oddity is not true with just copy?
I think you're saying:
 lxc snapshot container foo0
 # something to modify
 lxc snapshot container foo1
 lxc copy container/foo0 foo0-copy

does not work?

>  - Copying a running container may lead to inconsistent filesystem state depending on what's running in the container (we atomically copy the filesystem but it doesn't guarantee that userspace has flushed its buffers).

This is not anything new.  you can do that now.

>  - For containers that do not use cloud-init, a copy will typically keep things like ssh keys, dbus UUID, systemd machine ID, ... identical to the source, causing potential conflict on the network afterwards.
>
> Those constraints are easily explainable when launch and copy are two different things. Mixing them together will cause quite a bit of extra, and I think, unneeded, confusion.

I dont know that they're actually easily explainable :).  Its confused me.

**Comment by mark0978** [comment]
I think a lot of this could be solved by having multiple image storage locations as well.  Right now we use a ram drive for containers so that short lived operations in the container are on the fastest possible disk.  But to start a new container requires copying from the spinning disk (in this case on a NAS :-o) can take up to 6 minutes.

If I could create an image storage adjunct on the ram drive, then my zfs ramdrive startup time goes way down.

**Comment by stgraber** [comment]
@mark0978 this should now be possible by using the new `storage.images_volume` option, storing the image artifacts on the same storage pool as the containers.

As for the rest of the issue, I just went through it all and I don't think we're going to be implementing this. The main reason being namespace collision between such containers/snapshots and local image aliases and I don't like the idea of having `launch` effectively do a copy/start for you behind the scenes as it makes it significantly harder to explain what limitations may apply to an image launch vs a container copy when the same command does both.
