### ISSUE TITLE
I would like to add a template to an image...

### ISSUE THREAD

**Issue by SwampFalc** [lxc/lxd#2821]
So I've found myself needing to add a template to an image. Specifically, I would like to set a container's FQDN in the /etc/hosts file, similar to the way the standard ubuntu image sets the /etc/hostname file.

I'm pretty new to lxc, so the very starting state was that my server had one recent image (ubuntu 16.04 LTS amd64 (release) (20170113)), stored on zfs.

I then did:

`lxc image copy ubuntu: local: --alias mytest`

I was slightly surprised to see that this didn't seem to do much on my machine. The new alias was applied to the image that already existed, but nothing else seemed to have happened.

So then I tried to edit the templates. As far as the little available documentation seemed to tell me, I should just edit the metadata.yaml file for the image. It can't be `lxc image edit` because that doesn't show any templates at all, right?

```
cd /var/lib/lxd/images/683cdd3938706deeb66f19854ee27ef0c75e2594ce60ad4525357c3ce46f9772.zfs
nano metadata.yaml
```

But then nano tells me the file is read-only. It takes me a while to figure out why since the file seems to be chmod 644, but it turns out the whole zfs is mounted read-only. Which is not something I chose, I let lxc handle all the zfs stuff.

So I'm left wondering what I did wrong. How can I take the base ubuntu image and add a template to it?

**Comment by stgraber** [comment]
Images are read-only because otherwise their hash would change and you wouldn't be able to know what you have anymore.

Something like so should work fine though:

    lxc init ubuntu: temp
    nano /var/lib/lxd/containers/temp/metadata.yaml
    lxc publish temp --alias mytest

That will generate a new image for you with your changes.

**Comment by SwampFalc** [comment]
Well...

I get the point about images being read-only. I also fully expected that I would end up with a different image.

But having to init a container from the image in order to be able to edit that metadata.yaml so I can turn it back into an image... Something feels wonky about that workflow, especially for templates that trigger at container creation. You need to go through the process of creating the container, before you can change the process you just went through.

I don't doubt that it works, I just feel it's counterintuitive.

Possible alternatives I would like to suggest:

1) `lxc image edit ubuntu: --save-as=new_alias`
=> Allows full editing of the actual image's metadata.yaml (including the templates stanza) and when you leave the editor, a whole new image is created with the new metadata.yaml. Follows existing lxc editing workflow and the existing 'Save as...' concept.

2) `lxc image copy ubuntu: local: --alias=new_alias --workingcopy`
=> Creates a writable copy of the image. Such a writable copy cannot be used to launch containers, you first need to publish it (which turns it back into read-only).



(PS: I'm guessing exporting the image to tarball, editing the tarball contents and reimporting would also work?)

**Comment by stgraber** [comment]
Yes, exporting and editing the tarball before re-importing is fine.

1) Would be an option but we'd first need an API to modify the metadata and templates which we don't right now.

2) Isn't an option because as soon as you modify something in the unpacked image (which is only available on zfs and btrfs), it won't match the tarball anymore and since the fingerprint is generated from the tarball, this becomes pretty messy. Every filesystem change would basically have to trigger a full re-compression of the image so it can be hashed again and the database updated. This is also not going to be possible for zfs as the image is a read-only snapshot that's used by downstream containers, making the original unmodifiable.


Modifying an image at the end of the day will require it to be repacked, compressed and processed again as a new image by LXD. So adding an API for it is pretty impractical. We are in fact likely to move away from having the unpacked image visible at /var/lib/lxd/images in the very near future, except for btrfs where it's required by the filesystem.
I think the best option here is to have a tool which exports an image from LXD, updates the metadata tarball (or single tarball depending on image format) and then uploads the result to the image store.


Having an API which lets you modify the metadata and add/remove templates at a container level also makes sense for people making new images from existing containers. I'll open an issue to track this.

We don't have plans to write that kind of image repacking tools ourselves so I'll be closing this issue. But if you or someone else do write a generic tool which does that kind of thing, we'd certainly be happy for it to live in with our other scripts in extra/
