### ISSUE TITLE
Allow for modification of metadata.yaml and templates over API

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#2823]
As I mentioned in #/2821, we should allow for modification of metadata.yaml and templates through the API at the container level. This will allow users to view/edit/add templates and other metadata to a container prior to copying it or publishing it as an image.

The way I see this being done is through:
 - /1.0/containers/NAME/metadata (GET, PATCH, PUT)
 - /1.0/containers/NAME/metadata/templates (GET, POST)
 - /1.0/containers/NAME/metadata/templates/FILENAME (DELETE, GET, PATCH, POST, PUT)

At the CLI level, I'd just add:
 - lxc config metadata show CONTAINER
 - lxc config metadata edit CONTAINER

**Comment by SwampFalc** [comment]
Reading your last comment on #2821, it became clear to me that I had misunderstood the nature of the tarballs and /var/lib/lxd/images.

Moving on from this gained understanding, I would like to clarify the second method I proposed for editing an image, because I think it would be a valid alternative approach and might just be easier to implement.

- lxc image export IMAGE --unpacked TARGET
- lxc image import FOLDER --unpacked

Basically, the first command would do nothing else than the normal export followed by untarring the tarball(s).

The second command would then start by running some sanity checks, and then tar up the folder and import it.

Both of these would mainly be convenience functions, since you could easily do each of the parts manually, but I feel that wrapping all of this up into an officially approved workflow would be a gain for the project. Especially the option to include some sanity checks before actually building the image feels like it could help out anyone who's doing non-trivial work on images.

**Comment by stgraber** [comment]
Yeah, I'd be fine with a branch that would add support for the client to unpack and pack an image to/from a directory.

**Comment by albertodonato** [comment]
@stgraber can we close this in favor of #2883?

**Comment by stgraber** [comment]
@albertodonato nope, it's different.

This issue is about letting you set the various fields of metadata.yaml and file templates on a running container prior to you running "lxc publish" to have it turned into an image.
