### ISSUE TITLE
Iterative migration question 

### ISSUE THREAD

**Issue by ramy150** [lxc/lxd#2847]
Dear all the community  

know i'm working in the iterative migration and i really have problem to implement this last because there a lack of information and to be honest i'm also a beginner in the lxc/lxd and the CRIU solution didn't work .
if any one can help us it will be a great for us even only with some advice 
thank's a lot

**Comment by stgraber** [comment]
LXD drives liblxc to run the CRIU dump and restore commands with the appropriate flags. This is down in non-iterative mode right now.

The plan for iterative migration as outlined in #1938 is to contribute to and integrate p.haul over a LXD websocket to do the iterative memory transfer.

Our management has recently told us not to spend any more of our paid development time on CRIU and live migration until we find some customers who are willing to pay for the feature, so that work is likely to remain in our wishlist until such time as this changes.

If you want to implement this yourself, your best bet is to learn about p.haul, contribute to that project to make it usable through LXD (separately from its built-in transport) and then look at doing the plumbing for it in lxd/migrate.go. This is likely to be quite a bit of work, which may not make so much sense as standard non-iterative live-migration isn't exactly reliable right now, priority should probably be to fix the known issues with CRIU to make it more reliable, and then look at optimizing things.
