### ISSUE TITLE
How to change the ipv4 address of a container manully?

### ISSUE THREAD

**Issue by one2Ter** [lxc/lxd#2851]
system : ubuntu  16.04
lxd: 2.8

**Comment by ar45** [comment]
You would need to use dnsmasq.conf on the host to statically reserve/assign a specified ip to a given container

In `cat /etc/default/lxd_dnsmasq.conf` give something like
```
dhcp-host=hostname1,10.0.8.2
dhcp-host=hostname2,10.0.8.3
```

Or you can set your interfaces inside the container not to DHCP DISCOVER and use a manually configured static IP.

**Comment by stgraber** [comment]
If actually on LXD 2.8 (and your other issue suggests you're not), then you'd need to do:

    lxc network attach lxdbr0 CONTAINER-NAME eth0
    lxc config device set CONTAINER-NAME eth0 ipv4.address IP-ADDRESS

If on LXD 2.0.x, then LXD isn't in charge of the DHCP server and you'll instead need to create a DHCP configuration file similar to that @ar45 included in his comment, change /etc/default/lxd-bridge so that it uses said configuration file and lastly, restart the lxd-bridge service so that your change is applied.
