### ISSUE TITLE
  Can lxd works well on kernel 4.9?

### ISSUE THREAD

**Issue by one2Ter** [lxc/lxd#2853]
LXD 2.8  Ubuntu 16.04 (I checked the lxd version by lxd --version)

I already installed lxd 2.8 in Ubuntu 16.04.  In the same time, I want to change the default  kernel to 4.9 version manully to enjoy its new features.     But I know that it's a dangerous operation,  so  did you test lxd on kernel 4.9?

Thanks to you all for being enough patient to the newcomers like me.   Thank you.

**Comment by dann1** [comment]
I'm using lxd 2.7 in Archlinux kernel 4.9.6, os far so good

**Comment by niko-daniel** [comment]
@one2Ter you can try latest kernel build from this one, easy to install [http://kernel.ubuntu.com/~kernel-ppa/mainline/daily/current/](url)

**Comment by stgraber** [comment]
The Ubuntu kernels have additional apparmor feature which aren't yet in the mainline kernel. So unless you're building a patched mainline kernel which retains those features, you're in fact likely to regress your system, at least as far as AppArmor is concerned.

Ubuntu is publishing a 4.9 based kernel in the development release (zesty) which you probably could run on a 16.04 system but you'd need to find it on Launchpad and manually download the right packages for this.


Anyway, as far as LXD upstream is concerned, you need a 3.13 or higher kernel with all the namespaces enabled, netfilter enabled, capabilities, cgroups, seccomp and things like multi-instance devpts devices.
You can run a mainline kernel but when doing so on Ubuntu, you'll most likely have to configure LXD so that it allows you to run in a degraded apparmor configuration.

**Comment by stgraber** [comment]
Ah and lastly, yes, we did test LXD with a 4.9 kernel as that's what in the Ubuntu development release, but we only tested it against the Ubuntu 4.9 kernel, which is quite different from a hand built mainline kernel that may have just about any configuration done to it.

**Comment by sequoiar** [comment]
just tried  install  https://launchpad.net/~canonical-kernel-team/+archive/ubuntu/ppa/+build/11894778/+files/linux-headers-4.9.0-15_4.9.0-15.16_all.deb   https://launchpad.net/~canonical-kernel-team/+archive/ubuntu/ppa/+build/11894778/+files/linux-image-4.9.0-15-generic_4.9.0-15.16_amd64.deb , it works well.

**Comment by one2Ter** [comment]
https://github.com/lxc/lxd/issues/2859#issuecomment-278391947

@dann1 @niko-daniel @stgraber @sequoiar

Could you please tell me how do you manage to do it?

**Comment by stgraber** [comment]
@one2Ter We're using an Ubuntu build of the 4.9 kernel which includes the missing apparmor bits. This is exactly what I mentioned in my comment in this thread.

**Comment by one2Ter** [comment]
So how can I use an Ubuntu build of the 4.9 kernel?

I am not lazy and just want your answer, I googled it and asked some experienced but didn't get something useful.  Anyway, thank you for your reply.

**Comment by stgraber** [comment]
@one2Ter @sequoiar gave you the URL to the latest Ubuntu 4.9 kernel, just download it and install it

**Comment by one2Ter** [comment]
https://launchpad.net/~canonical-kernel-team/+archive/ubuntu/ppa/+build/11894778/+files/linux-headers-4.9.0-15_4.9.0-15.16_all.deb

http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.9/linux-headers-4.9.0-040900_4.9.0-040900.201612111631_all.deb

So one is an Ubuntu build of the 4.9 kernel, another is a a hand built mainline kernel, that's why I failed.

Thank you all really much.

**Comment by stgraber** [comment]
@one2Ter hmm, what? @sequoiar gave you two links in his comment:

 - https://launchpad.net/~canonical-kernel-team/+archive/ubuntu/ppa/+build/11894778/+files/linux-headers-4.9.0-15_4.9.0-15.16_all.deb
 - https://launchpad.net/~canonical-kernel-team/+archive/ubuntu/ppa/+build/11894778/+files/linux-image-4.9.0-15-generic_4.9.0-15.16_amd64.deb

The link to the mainline kernels was provided by another commenter so I'm not sure how that could have been confusing...

**Comment by stgraber** [comment]
Anyway, looks like this all got sorted, locking this issue :)
