### ISSUE TITLE
Use a tmpfs to back devlxd and shmounts host directories

### ISSUE THREAD

**Issue by madwizard** [lxc/lxd#2877]
* Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info":
lxc info
apiextensions:
- id_map
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses:
[cut out for brevity]
  architectures:
  - x86_64
  - i686
  certificate: |
[cut out for brevity]
  driver: lxc
  driverversion: 2.0.6
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-62-generic
  server: lxd
  serverpid: 2919
  serverversion: 2.0.8
  storage: zfs
  storageversion: "5"
config:
  core.https_address: '[::]'
  storage.zfs_pool_name: data/openstack
public: false

# Issue description

When running df -h from within the container, /dev/lxd reports Avail as real available size of the host filesystem. While it's not a security risk, it prove to be somewhat confusing to monitoring systems and admins. Sometimes also, for non-technical reasons - administrator would want to not reveal this information. It is more nice to have than have to.

# Steps to reproduce

1. launch container
2. run df -h from within

**Comment by stgraber** [comment]
The current behavior is caused by /dev/lxd being a bind-mount from the host system. Instead we should make it a tmpfs mount point on the host with a rather strict size limit (100K should do), which would then be shown in the container rather than the host's filesystem.

The same should probably be done for shmounts too as that's another one of those paths that leaks some host information by default (only visible with "df -h -a" though).
