### ISSUE TITLE
Allow "lxc image import" from a directory

### ISSUE THREAD

**Issue by audiocricket** [lxc/lxd#2883]
Will it be possible to support importing whole directory to create new image?

This functionality may drastically reduce time and steps needed to create new image. Now we need to create a tarball from that directory and then import it to create new image (correct me if I'm wrong).

Docker already supports this.

**Comment by stgraber** [comment]
This was mentioned in #2823 and would be a reasonable addition to the client.

**Comment by audiocricket** [comment]
Great news, thanks.

Btw, why the image tarball always needs to be transferred into TEMP when importing into LXD? Is this by design?

**Comment by albertodonato** [comment]
The problem I see here is that the client would have to do the packing/unpacking. This means that it would have to run as root (or sudo) to preserve file ownership and be able to create device nodes.

**Comment by stgraber** [comment]
Yeah, I'd say let's just do "lxc image import" as that one will work regardless of who runs it and what tools are present. The export will fail if non-root, will also fail if done inside an unprivileged container and would also need the client to know about squashfs which would all be a bit annoying.

**Comment by stgraber** [comment]
So actually we have the same problem with import as we do with export, you need to be root or you won't be able to read all files that need to be included in the image.

**Comment by stgraber** [comment]
Sorry for flip flopping the title so much, I'm arguing with myself here :)

So I think "lxc image import" of a directory is reasonable and makes things a bit easier for people and doesn't need much code on our side for it. "lxc image export" would require the client to know about squashfs and a bunch of other things I'd rather keep in the server.

So let's just do "lxc image import" of a directory as a simple "tar Jcf" of the provided path as a unified image and upload that to LXD. And put it under a check for root privileges so that we avoid the permission issue.
