### ISSUE TITLE
iterate over lxc containers

### ISSUE THREAD

**Issue by FransM** [lxc/lxd#2966]
If I try
lxc stop a b c

and a b and c are all three running it works as expected.
However if b for whatever reason is already stopped, a will be stopped then a message will be returned stating "error: The container is already stopped"
and c is kept running.

I feel it would be more logical that either:
upfront it is being checked that all containers are running (and can be stopped) and issue an error if not.
or:
the command just proceeds with the next container (and so in the above example both a and c will be stopped).

Similar for other commands (destroy, start, ...).

(I bumped on this because I wanted to stop a few containers on the command line and one of them was already stopped).

**Comment by stgraber** [comment]
So I think that code needs some tweaking to actually do all those actions in parallel and just report errors as they come (if any). So in your case, all running containers would be stopped and the one which is already stopped will cause an error to be printed (and error code to be returned) but without affecting the stop operation for the others.

Would that work for you?

(It would also have the side effect of being much quicker as all containers would stop at the same time instead of in sequence)

**Comment by FransM** [comment]
Sounds great to me!

**Comment by stgraber** [comment]
```
stgraber@dakara:~/data/code/lxc/lxd (stgraber/master)$ lxc start c1 nesting c5
c5: error: not found
nesting: error: The container is already running
nesting: Try `lxc info --show-log nesting` for more info
c1: error: The container is already running
c1: Try `lxc info --show-log c1` for more info

error: Some containers failed to start
```

**Comment by stgraber** [comment]
So I've got that working pretty well. Just need to make the solution a bit more generic so I can apply it everywhere we take multiple arguments.
