### ISSUE TITLE
Curl command to create LXC container failing after upgrade from 2.7 to 2.9.3

### ISSUE THREAD

**Issue by hnagri** [lxc/lxd#2973]
# Issue description
Following command spawned up LXC containers on 2.7

`$ curl -s --unix-socket /var/lib/lxd/unix.socket -X POST --data-binary '@/tmp/B053APP6877940.json' a/1.0/containers`

Where **B053APP6877940.json** is

```
{
"name": "B053APP6877940",
"architecture": "x86_64",
"profiles": ["default"],
"ephemeral": false,
"config": {"limits.cpu": "4",
           "limits.memory": "8GB",
           "boot.autostart": "1"},
"devices": {"shared_log_1": {
        "path": "/DAS",
        "source": "/gluster-compute/das/nginx/B053APP6877940/DAS",
        "type": "disk"
  },"shared_log_2": {
        "path": "/LogBackups",
        "source": "/LogBackups/nginx/B053APP6877940/LogBackups",
        "type": "disk"
  },"root": {
        "path": "/",
        "size": "2GB",
        "type": "disk"
      },"eth0":{
      "host_name": "B053APP6877940",
      "name": "eth0",
      "nictype": "bridged",
      "parent": "br0",
      "type": "nic"
  }
},
"source": {"type": "image",
           "alias": "ubu-17-base-14-q1"}
}
```

Everyhting is still working fine on hosts where LXD/LXC 2.7 is running but on all the hosts that are running LXD/LXC 2.9.3 container never gets created.

`lxd --debug` shows this;

```

DBUG[02-28|13:13:31] handling                                 ip=@ method=POST url=/1.0/containers
DBUG[02-28|13:13:31] Responding to container create 
DBUG[02-28|13:13:31] New task operation: 638a2833-3c89-4f39-90e6-8ffe5f3304ce 
DBUG[02-28|13:13:31] Started task operation: 638a2833-3c89-4f39-90e6-8ffe5f3304ce 
DBUG[02-28|13:13:31] 
    {
        "type": "async",
        "status": "Operation created",
        "status_code": 100,
        "operation": "/1.0/operations/638a2833-3c89-4f39-90e6-8ffe5f3304ce",
        "error_code": 0,
        "error": "",
        "metadata": {
            "id": "638a2833-3c89-4f39-90e6-8ffe5f3304ce",
            "class": "task",
            "created_at": "2017-02-28T13:13:31.33614472+05:30",
            "updated_at": "2017-02-28T13:13:31.33614472+05:30",
            "status": "Running",
            "status_code": 103,
            "resources": {
                "containers": [
                    "/1.0/containers/B053APP6877940"
                ]
            },
            "metadata": null,
            "may_cancel": false,
            "err": ""
        }
    } 
INFO[02-28|13:13:31] Creating container                       ephemeral=false name=B053APP6877940
INFO[02-28|13:13:31] Deleting container                       created=2017-02-28T07:43:31+0000 ephemeral=false name=B053APP6877940 used=1970-01-01T00:00:00+0000
DBUG[02-28|13:13:31] containerDeleteSnapshots                 container=B053APP6877940
INFO[02-28|13:13:31] Deleted container                        created=2017-02-28T07:43:31+0000 ephemeral=false name=B053APP6877940 used=1970-01-01T00:00:00+0000
DBUG[02-28|13:13:31] Failure for task operation: 638a2833-3c89-4f39-90e6-8ffe5f3304ce: The container's root device is missing the pool property. 


```

I have no idea what `The container's root device is missing the pool property.` means.
What am I doing wrong ?

**Comment by brauner** [comment]
@hnagri, you've upgrade to a storage-api capable LXD instance (starting with `2.9`). This means that LXD now has the concept of storage pools and you can maintain multiple storage pools of different storage types on the same LXD instance. For example, you could have your LXD instance administer a:

- ZFS storage pool named "pool1"

and a

- BTRFS storage pool named "pool2"

at the same time.
This also means you can target specific storage pools when creating a container. Furthermore, LXD now needs to know on which storage pool a container is supposed to be created. This can be done in two ways:

a) A profile the container belongs to (usually all containers will belong to the profile `default`) specifies a root disk device that has the `pool` property set to a specific storage pool (e.g. `pool1`).
b) A container creation request is sent with a local root disk device that must also specify a `pool` property.

Case b) is what you are doing but you are missing the `pool` property in your root disk device. So this:

```
  },"root": {
        "path": "/",
        "size": "2GB",
        "type": "disk"
      },"eth0":{

```
needs to become
```
  },"root": {
        "path": "/",
        "size": "2GB",
        "type": "disk",
        "pool":"<name-of-the-pool>",
      },"eth0":{
```
Where `<name-of-the-pool>` is the name of the storage pool you want to create the container on. The names of available storage pools can be gathered by running:

```
lxc storage list
```

which should show you output similar to:

```
> lxc storage list
+-------+--------+----------------------------------+---------+
| NAME  | DRIVER |              SOURCE              | USED BY |
+-------+--------+----------------------------------+---------+
| pool2 | zfs    | /home/chb/mnt/l1/disks/pool2.img | 4       |
+-------+--------+----------------------------------+---------+
```

Since you performed an upgrade you should only see a single storage pool available. So, if you wanted to create a new container on `pool2` via a curl command you'd specify for the root disk device:

```
  },"root": {
        "path": "/",
        "size": "2GB",
        "type": "disk",
        "pool":"pool2",
      },"eth0":{
```

**Comment by hnagri** [comment]
That was really informative. Thank you.
