### ISSUE TITLE
Setting the OOM score for a process isn't permitted

### ISSUE THREAD

**Issue by CarltonSemple** [lxc/lxd#2994]
# Required information

 * Distribution:
 * Distribution version:
 * The output of "lxc info" or if that fails:
```bash
config:
  core.https_address: '[::]:8443'
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 10.121.85.26:8443
  - 169.44.58.130:8443
  - 172.17.0.1:8443
  - 10.0.3.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
  certificate_fingerprint: e43e574962087840046dda1c65295064d124ae163c6def24da242e8734954358
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-45-generic
  server: lxd
  server_pid: 2305
  server_version: 2.9.3
  storage: dir
  storage_version: "1"
```

# Issue description

A brief description of what failed or what could be improved.

# Steps to reproduce

Certain programs, such as Docker/runC or Kubernetes, try to set the OOM score for processes like containers. For example, see `https://github.com/kubernetes/kubernetes/blob/master/pkg/util/oom/oom_linux.go#L89`
The error is a permission denied error upon writing to `/proc/<pid>/oom_score_adj`.

Could access to these files possibly be allowed without compromising security?

**Comment by stgraber** [comment]
It's a hard kernel limit that unprivileged containers may not set an oom score higher than the current value. Otherwise any user could create a user namespace and make unkillable processes.

Numerous projects have been fixed to properly handle this case (upstart, systemd, various daemons, ...). The fix is really quite simple, just check if you're getting EPERM or EACCES back, if you are, move on and don't fail.

systemd's code:
```
        if (context->oom_score_adjust_set) {
                char t[DECIMAL_STR_MAX(context->oom_score_adjust)];

                /* When we can't make this change due to EPERM, then
                 * let's silently skip over it. User namespaces
                 * prohibit write access to this file, and we
                 * shouldn't trip up over that. */

                sprintf(t, "%i", context->oom_score_adjust);
                r = write_string_file("/proc/self/oom_score_adj", t, 0);
                if (r == -EPERM || r == -EACCES) {
                        log_open();
                        log_unit_debug_errno(unit, r, "Failed to adjust OOM setting, assuming containerized execution, ignoring: %m");
                        log_close();
                } else if (r < 0) {
                        *exit_status = EXIT_OOM_ADJUST;
                        *error_message = strdup("Failed to write /proc/self/oom_score_adj");
                        return -errno;
                }
        }
```

**Comment by stgraber** [comment]
Closing this issue since there's nothing LXD can do about a kernel restriction, nor is it likely for this restriction to be lifted on the kernel side. One would need to make the oom_score_adj value be relative to a userns base value (possibly taken from whatever process calls unshare), but I don't think anyone's working on that, nor would it be particularly likely to be accepted (adds overhead).
