### ISSUE TITLE
LXD - more disk-space-efficient image import

### ISSUE THREAD

**Issue by audiocricket** [lxc/lxd#3033]
Hi,

would it be possible to make the LXD import better with regards to disk space usage?

We've noticed that when we try to import an LXD image, it's first copied to temp folder and only after then it's imported to the LXD image pool from temp directory.

This is kind of okay with smaller images (few hundreds of megs), but if you were to import images that are several gigs in size, imagine that if you're on disk space constrained systems then due how the import is working right now you will end up with image import failures. For example:

Imagine situation where you have only 4GB free for temp, the LXD pool has 6GB free space and your 5GB LXD dumped image is residing in another partition which has only 1GB free disk space. And finally, no other partition on the system has at least 5GB+ free disk space left.

Still LXD pool has enough disk space to physically hold the image, but the truth is you cannot simply import it (because it goes first to temp). "Juggling" with adding more physical space to the production system where containers are heavily utilized and running for 24/7 is not an option here either (and neither some cloud providers we utilize allow for physically adding more space to the system).

So, shouldn't direct, in-place import without first copying to temp make much more sense here?

Btw, our experience is that we were unable to import an Gentoo image because of this (several gigs of data), however the LXD pool had enough disk space...

Any suggestions?

Thanks!

**Comment by stgraber** [comment]
Unfortunately that's not possible. Images are uploaded as a MIME multi-part blob which needs to then be cut into pieces, hashed and written as individual files.

We used to avoid that particular problem by doing it in memory, but then people were running out of memory instead... We should however ensure that we are using temp files inside /var/lib/lxd rather than actual /tmp since that latter may be on tmpfs and so severely space restricted.

I'll do a quick grep through our code to make sure that we don't use /tmp when we shouldn't, but I'm afraid we won't be able to do away with using a temp file while importing an image.

**Comment by stgraber** [comment]
Well, that's not entirely true actually, we may be able to skip using a temp file if the image is of the unified format (single tarball) as we don't need to do multipart parsing in that case, but I thought I already did that change a while back.

**Comment by stgraber** [comment]
Just checked all our TempFile calls in the image code and they're under /var/lib/lxd/images so it's not going to fill /tmp at least.

I've also looked at why we can't deal with unified images as a stream rather than dump them into a file and then process them from there. The problem is that we need to read the entire file at least twice. Once to hash the file and once to write it to disk. Since you can't seek through a stream, we need to have a full featured fd that we can seek in.

Any alternative to this would effectively have Go store the entire thing in memory which would run the server out of memory pretty quick on big images. Using disk is therefore preferable.

Things are also optimized there in the sense that for a unified image where the temporary file is the same as the final image file, we don't make a copy of it but instead just move the temporary file into place, using only the disk space once.

**Comment by stgraber** [comment]
I also just checked the client logic. We're seeing the same behavior there. When calling "lxc image import" with a unified image, the file is uploaded as is. It's only with split images that the two files are combined into one and the necessary padding and headers added before uploading. The same reason applies there, if this wasn't done on disk, the whole thing would need to be loaded twice in memory which would run you out very quickly.
