### ISSUE TITLE
What the meaning of code about lxc.mount.auto setting.

### ISSUE THREAD

**Issue by qq690388648** [lxc/lxd#3042]
It is just a puzzle about the code, so I delete all thing of template.

I'm puzzled about the code of [lxc.mount.auto](https://github.com/lxc/lxd/blob/master/lxd/container_lxc.go#L732), I have copy it to below so that you may not need click the link.

    // Set an appropriate /proc, /sys/ and /sys/fs/cgroup
    mounts := []string{}
	if c.IsPrivileged() && !runningInUserns {
		mounts = append(mounts, "proc:mixed")
		mounts = append(mounts, "sys:mixed")
	} else {
		mounts = append(mounts, "proc:rw")
		mounts = append(mounts, "sys:rw")
	}

What make me puzzled is the judgement, does it means privileged's container can not modify the `/proc/sys` (because `runningInUserns` usually be false) and unprivileged container can modify `/proc/sys` ?

What's I thought the code should be is below:

    // Set an appropriate /proc, /sys/ and /sys/fs/cgroup
    mounts := []string{}
	if c.IsPrivileged() || (!c.IsPrivileged() && runningInUserns) {
		mounts = append(mounts, "proc:rw")
		mounts = append(mounts, "sys:rw")
	} else {
		mounts = append(mounts, "proc:mixed")
		mounts = append(mounts, "sys:mixed")
	}

I thought it's a misunderstanding of mine, but I just can not find out the real meaning of this code, anyone can help me?

**Comment by stgraber** [comment]
That's correct, it's fine for unprivileged containers to do anything they want in /proc or /sys because the kernel enforces the security of those through user permissions.

For privileged containers, there is no such protection so additional steps must be taken to make the containers vaguely safe, which involves over-mounting part of /proc read-only to avoid damage to the host.

**Comment by qq690388648** [comment]
Ok, I have totally understood, thanks for your detailed explanation!
