### ISSUE TITLE
Isolation problem ?

### ISSUE THREAD

**Issue by alci63** [lxc/lxd#3049]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 17.04
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.10.0-11-generic
  server: lxd
  server_pid: 3680
  server_version: "2.11"
  storage: zfs
  storage_version: 0.6.5.9-2

# Issue description

 0
down vote
favorite
	

I am playing with LXD containers, and fail to completely understand what is happening with isolation. Here is my scenario:

    create a 16.04 container 
$lxc launch ubuntu:16.04 mycontainer
    install firefox within it 
$lxc exec mycontainer /bin/bash
$apt install firefox
    create a user with the same name as my main system user
$adduser myuser
    ssh-copy-id to that user
$ vi /etc/sshd_config to allow ssh with password, then from main session ssh-copy-id myuser@mycontainer-ip
    ssh -X into the container and launch firefox
$ ssh -X myuser@mycontainer-ip and $firefox

If I have no Firefox opened in my main session, an isolated Firefox pops up: no access to my main session files, no plugin, etc...

But, if Firefox is already running in my main session, launching FF from my ssh -X session in the container opens another FF window that is not isolated and runs as my main user (with my plugins, access to files, etc...).

What is happening ?

**Comment by stgraber** [comment]
I've not used firefox in a long time, but I believe they have code to find and interact with an existing firefox through X properties.

Since you pass "-X", your container has access to your X server and so can query/set X properties, list all running windows, ... which is most likely how firefox detects an existing firefox session and has it open a new window rather than spawn a new process.

I'd expect there to be a command line option to firefox to have it not do that.

**Comment by stgraber** [comment]
```
  --no-remote        Do not accept or send remote commands; implies
                     --new-instance.
```
