### ISSUE TITLE
Compare container contents with upstream

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#3056]
I need to ensure that I can safely kill a container. Is there a way to see what files I modified compared to upstream version? It will also help to see when and what was modified. Any hacks for that? https://www.sleuthkit.org/autopsy/timeline.php is an overkill for quick checks, but gives the necessary details for making decisions about killing stuff.

**Comment by stgraber** [comment]
You need a diff of what? full filesystem compared to another container, package list, .. ?

**Comment by techtonik** [comment]
Filesystem compared to parent container, yes. Ideally handling and filtering system packages correctly updated with `apt`, so that I can find custom modifications on the system. This is how it is done with Winmerge.

![](http://manual.winmerge.org/screenshots/treeview-01.png)

**Comment by stgraber** [comment]
Yeah, so that's not something that LXD is going to do itself. You are absolutely welcome to just run "diff -Nrup /var/lib/lxd/containers/NAME/rootfs/ /var/lib/lxd/containers/OTHER-NAME/rootfs/" and then visualize the diff with whatever tool you'd like (diffstat would be a start).

But LXD doesn't track deltas at all itself and the way deltas may work at the filesystem level will differ between filesystems, most of which will be block based and so not something that's particularly user friendly to display :)

**Comment by techtonik** [comment]
I guess the biggest problem is to get the snapshot of the upstream container for comparison and map it to this `rootfs` structure.
