### ISSUE TITLE
When updating from packages, 'lxc exec' sessions terminate.

### ISSUE THREAD

**Issue by bigjools** [lxc/lxd#3059]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
```
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses: []
  architectures:
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
SNIP
    -----END CERTIFICATE-----
  certificate_fingerprint: SNIP
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: i686
  kernel_version: 4.4.0-65-generic
  server: lxd
  server_pid: 27140
  server_version: "2.11"
  storage: dir
  storage_version: "1"
```

# Issue description
As per title

**Comment by stgraber** [comment]
Yes, there's unfortunately nothing we can really do about this.

Exec sessions just like everything other communication between the LXD client and server is done over our REST API (using websocket for exec), so when the server is updated and its daemon is restarted, that will kill all current exec sessions.

We could have LXD delay going down if there are background operations but that too isn't very practical as exec sessions can last days/weeks and we don't want to held an automated upgrade forever. There are also cases where an API client would spawn a background exec session which would effectively run indefinitely even without any connected websocket client, so that would also hold an upgrade forever...

**Comment by stgraber** [comment]
The work planned for #2294 should make operations internally cancelable, which would then make it possible for LXD to at least properly kill those exec sessions and return a clean error to any attached client telling them that LXD was asked to shutdown.

I left a note in that other issue to be sure to cancel all operations on shutdown and send a clear error back to clients which should cover as much of this issue as can realistically be done.

**Comment by bigjools** [comment]
Ok I understand the issue. Can I suggest that you check to see if the apt
session is interactive and prompt the user about losing active sessions, if
any found.

I'm also wondering if you could detach enough of the api server to spawn a
new one, much like sshd.

Cheers.
