### ISSUE TITLE
lxd.sql checker / verifyier 

### ISSUE THREAD

**Issue by ser** [lxc/lxd#3068]
It would be useful to have a script to check (verify & fix if it possible) lxd.db database, according to the current LXD specification.

**Comment by stgraber** [comment]
what would that fix?

**Comment by stgraber** [comment]
The user is never supposed to directly modify the database, LXD itself handles schema versioning and upgrade and will never mark a change has having been applied without the database schema having been successfully upgraded.

The only bad thing that can happen to the database during "normal" operation would be database corruption due to powerloss or a bug in sqlite3, but if that happens, the database would be entirely unreadable and since it's the only source of information for LXD's state, there wouldn't be anything we could do to recover, unless you had a backup of the binary or sql state of the DB.

I'd much rather we fix #3005 so that should the database get completely corrupted you can at least recover the containers from the dumped state.
