### ISSUE TITLE
Some way to know that lxd has already been initialized

### ISSUE THREAD

**Issue by larryprice** [lxc/lxd#3099]
I "automatically" initialize lxd as necessary, but I've yet to find a way to know whether or not I've already called `lxd init`. Currently I just try to figure out if any containers have been created. It seems that even running a `lxc` subcommand doesn't really know if `lxd init` has been run, since sometimes it will tell me to initialize lxd even though I've already done so.

I'm not sure what the right solution here is. Maybe an additional flag such as `lxd init --check-initizliazed`, which could just return 0 (true - already initialized) or 1 (false - init required) and print a corresponding message.

**Comment by stgraber** [comment]
So "lxd init" has somewhat recently involved a bit and isn't a one time thing anymore. Because users can now create multiple networks and storage pools, choosing to attach them by default or not, you can't rely on the fact that "lxd init" was ran to know that the user configured LXD in a way that's suitable for you.

It also means we're unlikely to provide a --check-initialized kind of mechanism because the definition of "initialized" will very much vary based on the use case. Some require multiple storage pools to be setup, some won't need networking, some need custom profiles, ...

There are two approaches to do what you want:
 1) Just try to create your container, if that fails, show an error message telling the user what you need (sounds like a network and storage pool in your case) and tell them they can configured that through "lxd init".
 2) Since you seem to be relying on the default profile, check that the default profile contains the bits you care about. It can be as simple as validating that "lxc profile device list default" contains a "nic" and "disk" device.

**Comment by Laguna-x** [comment]
@stgraber , with this issue i think that "init" can be removed or remade. if remade - i see this ways:
1 (easy way)) check in 'init' if some of options is setted - if so then say about it and exit (or make choice with reset all config and continue init from start). if none was initiated before - then continue with standard init.
2 (hard way)) implement all configuration options in interactive menu so user can change most of them. And change 'init' to 'config'

**Comment by stgraber** [comment]
@Laguna-x We're going with a mix of both. There is nothing that "lxd init" does that you can't do directly with "lxc storage", "lxc profile", "lxc config" or "lxc network" nowadays. "lxc launch" and "lxc init" do show a warning if starting a container without network (only a warning since there are legitimate use cases for that) and fail if run without a storage pool defined. So that pretty much covers 1)

Moving forward, we want to mostly focus on "lxd init" as a provisioning tool, so as a way to configure most of LXD settings at once. Allowing full preseeding (through a yaml document most likely) and probably reworking the user experience to be a bit more menu like.

We have #2834 to track that.

**Comment by Laguna-x** [comment]
@stgraber was there issue with configuration menu? if no - would it be as feuture (register with issue in github)?

**Comment by stgraber** [comment]
@Laguna-x we haven't yet decided how a reword "lxd init" would look like. We're likely to keep a completely text based approach (rather than using ncurses or similar dialog/menu libraries) as we need it to work from all operating systems making seemingly simple things like color rendering break.

**Comment by Laguna-x** [comment]
@stgraber . i think that init can stay as-is. but add more complexity gui-like menu (what about ncurses in this way?) for full configuration. this only as variant.

**Comment by stgraber** [comment]
We'll look into that when we start working on the "lxd init" rework for #2834 as that will pretty much need a full rewrite anyway.
