### ISSUE TITLE
feature request: configure with menu

### ISSUE THREAD

**Issue by Laguna-x** [lxc/lxd#3102]
returning to end of #3099 conversation:
the reason is that 'init' must initialize config from null. But gui menu - just change current settings.
make gui with something like ncurses or other ways. in any way menu mast contain all of options.
some things about it:
i don't know go - is there any way to use classes like in cpp?
the reason of using class is to list all of options like "tree"
something like:
```
class option{
option * parent;
char * option_name;
char * option_value;
int num_of_suboptions;
option * suboptions[];
...
int return_num_of_subopions();
char * return_option_name(){return *option_name;}
option* return_suboption(char* name);
option* return_suboption(num)
}
```
sorry for most of errors in this code =) but it gives only a way to think. this can help with adding options and list all of them in menu. one problem that can be solved with this - is (for example) list all of containers with fast navigation in menu.
the tree like:
main_menu
```
|network
||lxd0
|||option1_for_lxd0
||||value_for_option1
|||...
||lxdX
|||...
|profile
||profile1
|||option1
||||value
|...
etc
```

every level can represent as list on screen.

**Comment by stgraber** [comment]
Right now we have no intention to implement a ncurses based (or similar display library) configuration menu. We want the LXD client tools to work properly on all supported platforms (Windows, Mac and Linux) and so can't make use of any such display libraries.

Since everything that "lxd init" does or will do is driven through the LXD API, you are obviously welcome to write your own configuration tool that talks the the LXD REST API to apply its changes.

**Comment by stgraber** [comment]
The current plans for LXD init as covered in #2834 are for:
 - Allow for pre-seeding (through yaml) of: daemon, profile, network, storage and initial image set
 - Rework the interactive flow to cover what we allow with that work. It may be rendered as a text menu or be kept as a single linear process as it does today, whatever we find works best with new users to get them up to speed as quickly as possible.
