### ISSUE TITLE
Question: Autostart with delays

### ISSUE THREAD

**Issue by Lisio** [lxc/lxd#3118]
LXD version: 2.12

How can I configure boot.autostart.delay and boot.autostart.priority to implement the following:
1. start containers A, B, C without delay
2. start containers A1, A2 with a 30 secs delay after container A, containers B1, B2 with a 60 secs delay after container B

So I need different autostart strategies for different chains. Is it possible?

**Comment by stgraber** [comment]
Yeah, I don't think you can do that. Your best bet is probably to not have any of your containers auto-started and then have an external script which starts them the way you want.

The closest thing that LXD would let you do I think is:
 - Set a higher priority for A, B and C and no delay for them so that they're started immediately
 - Set a lower priority for everything else
 - Set a delay of 30s for A1
 - Set a delay of 30s for B1

Because container startup is sequential and in alphabetical order after priority sort, that'll do:
 - Immediate start of A, B and C
 - Start of A1 after a wait of 30s
 - Immediate start of A2 after A1 is done
 - Start of B1 after another 30s wait (making it 60s total)
 - Immediate start of B2 after B1 is done

But that's a bit hackish so the external script may be a bit more reliable and would also let you do parallel starts if you want.

**Comment by Lisio** [comment]
Hm, I think you are right, idea with external script is not that bad.
