### ISSUE TITLE
Why does the unix-block/unix-char device can be renamed inner container?

### ISSUE THREAD

**Issue by qq690388648** [lxc/lxd#3125]
This issue is a feature suggestion, so I haven't used the template.
I think the unix-block/unix-char device should add a `target` parameter so that we can use this parameter as the name of device inner container instead the `path` parameter? The `path` parameter now is both the name of device on host and the name of device in container, I think it is a little ambiguous.

**Comment by stgraber** [comment]
So instead of adding a "target" attribute, I think I'd prefer we add a "source" attribute as we should have from the beginning (making things in sync with the "disk" type).

To avoid breaking existing users, I suspect the best is for us to:
 - Introduce the new "source" attribute. That attribute would be an alternative to major/minor so should conflict if set together with them.
 - If source is set without a path, we should assume that path will be the same as source.
 - If path is set without source and major/minor isn't set, we should assume that source will be the same as path.

That should be a pretty straightforward addition, it's still an API extension and not suitable for backport to 2.0, but a pretty simple one of those.

**Comment by qq690388648** [comment]
Yeah, I'd be fine with a branch that would support the `source` attribute.

**Comment by dann1** [comment]
So to be clear, source is device on the host, and path is device in the container. Am I right?

**Comment by qq690388648** [comment]
@dann1 Yes, it will be implemented as that.
