### ISSUE TITLE
[query] Should I ask for LXC or LXD support?

### ISSUE THREAD

**Issue by kwill** [lxc/lxd#3136]
[GNOME Boxes](https://wiki.gnome.org/Apps/Boxes) is a GUI-based manager for virtual machines. It currently supports KVM and QEMU machines. If I were to file a feature request with Boxes (or a similar generic project), should I be asking for LXC or LXD support?

*I couldn't find an existing GUI-based manager for LXD. If I've missed one, please let me know. Or, please mention if there are any obvious feasibility issues.*

**Comment by stgraber** [comment]
@kwill you can certainly ask them if they'd be interested in adding support, but I suspect they'll tell you that Boxes uses libvirt as its backend and that since LXD doesn't have a libvirt driver, they can't do it.

There are a number of web GUI type things for LXD that may or may not do some of what you want:
 - https://github.com/aarnaud/lxd-webui (@aarnaud)
 - https://github.com/dobin/lxd-webgui (@dobin)

I believe both of them are pretty much entirely written in Javascript and have your web browser directly talk to the LXD daemon (after you import a valid client certificate in the browser trust store). I suppose if someone wanted to make those into some kind of standalone app, that should be possible with something like Electron.
