### ISSUE TITLE
Removing lxd snap fails when there are running containers

### ISSUE THREAD

**Issue by thomir** [lxc/lxd#3158]
I was using lxd from the snap, version 2.8, revision 976. Due to issues with the snap not quite working correctly (I'll file a separate bug about that), I decided to revert to the .deb based installation.

I ran `snap remove lxd`, and got the following output:

```
error: cannot perform the following tasks:
- Stop snap "lxd" services ([--root / enable snap.lxd.daemon.service] failed with exit status 1: Failed to enable: No such file or directory.
)
- Remove security profile for snap "lxd" (1743) (cannot find installed snap "lxd" at revision 1743)
- Remove data for snap "lxd" (976) (remove /var/snap/lxd/common/lxd/storage-pools/lxd/containers/snapdeltaservice: device or resource busy)
```

I suspect this is because the 'snapdeltaservice' container was running at the time. My guess is that the snap ought to shut down running containers before attempting to remove them from disk?

I'm not sure if this bug belongs here, or against snapd.

**Comment by stgraber** [comment]
It's one of the many symptoms of a long standing snapd bug...

https://bugs.launchpad.net/snappy/+bug/1632508

Until we get some kind of fix in snapd, there is no way for the LXD snap to properly detect the reason why it's being shutdown, which means we can't do storage cleanup and such as would be appropriate prior to snap removal...

(Closing since that's not a LXD bug, the snapd bits are tracked on Launchpad)
