### ISSUE TITLE
after rebooting a LXD host performance gets many times better

### ISSUE THREAD

**Issue by davereiner** [lxc/lxd#3163]
We've seen this pattern ever since we started using LXD/LXC in production a year ago. The host machine gradually worsens in performance as long as we're adding new containers to it (usually by copying one "base container" and then making modifications to it so that its unique on the system; or by copying snapshots from other LXD host machines) until a reboot becomes inevitable and then everything goes back to "normal" which is a fraction of the load/performance strain before the restart:
![LXC performance](http://i.imgur.com/yHTvzRu.png)

The above screenshot is of a server that immediately restarted all of the same containers (170 of them) that were running before the reboot with the exact same workload.

The fun part is that if we stop adding new containers to this server load stays almost the same indefinitely (with minor variations during the day but that's expected). This is true for ZFS, Btrfs, new and old LXD versions and kernels.
We tried to debug this as much as possible over a period of many months but came up empty. It would be awesome to debug this, please point me in the right direction, I'll gladly provide _everything_ needed to get to the bottom of this issue. Thanks.

**Comment by stgraber** [comment]
Hi,

So a few questions for you:
 - Does 'systemctl restart lxd" help in any way (I don't expect it to)?
 - Do you have resource limits on your containers, if so, do you have CPU limits and if so, what kind?
 - Output of "grep '' /sys/fs/cgroup/cpuset/lxc/*/cpuset.cpus"
 - Output of "lxc list --fast"
 - Output of "find /sys/fs/cgroup"
 - Does "echo 2 > /proc/sys/vm/drop_caches", somehow improve performance?

This should let us confirm that LXD itself isn't the problem, then see if cgroups are a problem, either because of misconfiguration by LXD, or leftover cgroups slowing down the scheduler and lastly see if it's the memory accounting that's maybe causing problems.

If it's none of those, then it could be the kernel keep namespaces active after the container's death. I'm unfortunately not aware of any kernel interface to grab the current namespace count so that makes debugging this a bit more difficult...

**Comment by stgraber** [comment]
Marking as Incomplete for now.

**Comment by stgraber** [comment]
No details were provided, closing for now.

**Comment by davereiner** [comment]
Sorry for the long delay @stgraber since then we changed from ZFS to LVM, however the problem remains. What I noticed is that the VM seems to be stuck with very high `si` (system interrupts) numbers when looking at `top` and that there are a lot of `kworker` and `ksoftirqd` processes running and doing _something_.
1) systemctl restart lxd does not help
2) we tried with both limits and without limits, no effect
3) outputs I'll only be able to provide once we run into this again
4) anything above `echo 1 > /proc/sys/vm/drop_caches` (so 2 and 3) gets hung for hours or days but most of the time infinitely! on all of our LXD host machines after we add a few containers. they don't seem to help at all though.

**Comment by stgraber** [comment]
That's very weird, also is likely to be workload specific as we've not heard anyone else running into such issues. Next time you run into this, I'd recommend you file a bug against the Linux kernel with your distribution. If Ubuntu, you can do so here: https://launchpad.net/ubuntu/+source/linux/+filebug

Then post the link here and I'll make sure we're subscribed so we can provide some additional context based on what the kernel team may ask.
