### ISSUE TITLE
Next lxd stable release

### ISSUE THREAD

**Issue by OmAsana** [lxc/lxd#3180]
Hi!
When can we expect non-thinpool lvm support introduced in https://github.com/lxc/lxd/issues/3160 in stable packages?

**Comment by stgraber** [comment]
Probably next week. Most people get LXD through the Ubuntu archive or PPAs, those for us are generated based on what hit the current Ubuntu development release.

With Ubuntu 17.04 having been released last week, the next development release isn't open yet, so there's nowhere for us to upload a new LXD right now which is why I've been postponing the release of 2.13.
