### ISSUE TITLE
LXD & ZFS backup issues

### ISSUE THREAD

**Issue by stratacast** [lxc/lxd#3207]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

config:
  storage.zfs_pool_name: lxd
apiextensions:
- id_map
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  driver: lxc
  driverversion: 2.0.7
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-71-generic
  server: lxd
  serverpid: 4584
  serverversion: 2.0.9
  storage: zfs
  storageversion: "5"

I'm having a hard time figuring out a good way to back up these containers. My initial attempt was to stop my containers and do a snapshot of my lxd volume like such:

sudo zfs snapshot -r lxd@`date +"%Y-%m-%d"`

Then I have a backup HDD that I hook up called "backups" that I attach then connect to my system using "zfs import backups". Finally, I issue this zfs send/receive command to my external HDD:

sudo zfs send -v -R -i lxd@old_date lxd@new_date | sudo zfs receive -e backups

I later tested this by restoring it to a test machine (with the exact same configurations as my main machine) doing a zfs send from backups | zfs receive to lxd

In my mind, this should take my snapshot copy of my /var/lib/lxd and it should all be sent back that way on my test machine, and things should be fine and dandy. But, this method doesn't work so I would like to know what people do for a simple backup/recovery solution of LXD on the ZFS filesystem? I'm very novice to both and I can't find any useful information on this. I forgot to add, when my send/receives are finished I get this warning:

cannot mount '/var/lib/lxd/containers/backupSamba.zfs': directory is not empty
cannot mount '/var/lib/lxd/containers/nextcloud.zfs': directory is not empty
cannot mount '/var/lib/lxd/containers/reverseProxy.zfs': directory is not empty
cannot mount '/var/lib/lxd/containers/wordpress.zfs': directory is not empty

So it seems its trying to mount my sent/received snapshots for whatever reason

**Comment by stgraber** [comment]
What you did should work though but you may need to pass some extra options to not have zfs attempt to mount the filesystems on the receiving end, since both send and receiver are the same machine, this is bound to wreck havoc.

Note that send/receive will not actually capture everything. The LXD database, certificates, image tarballs, ... are stored directly in /var/lib/lxd and aren't going to be part of your ZFS pool. Backing those up too would be very strongly recommend (the images don't matter so much though) so that on a target host you can:
 - Make sure the daemon is stopped
 - Wipe /var/lib/lxd
 - Restore /var/lib/lxd (certificates, database, ...)
 - Restore the zpool to match the backed up host
 - Mount all the zfs filesystems (since you're using 2.0.x, that step isn't needed if running 2.9+)
 - Start the daemon again

**Comment by stratacast** [comment]
Thank you for being awesome stgraber. To avoid chaos as you say, would it be wise instead to have the zfs utilities on my administrative computer (not the server with LXD) and do zfs send/receive through an SSH tunnel? Will that avoid the conflicts I am having? I set up my ZFS pool using "lxd init", so you're saying that my db, certs and image tarballs are in /var/lib/lxd, but not in the pool correct?

So in addition to my zfs send/receive, I will copy my lxd.db file, images directory and .key & .crt files over, and then later I should be able to follow your process for target restoration, correct?

**Comment by stgraber** [comment]
Yep, that all sounds good. Do the send receive over the network (tunneled over ssh sounds good) and make sure to copy lxd.db, server.crt and server.key. And if you want absolutely everything, include the images too.

**Comment by brauner** [comment]
Note that we also keep a section in our docs on backup strategies in general. But glad this got sorted. Closing for now, we can reopen later if need be. :)
