### ISSUE TITLE
lxc init + launch help message missing architecture selection info

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxd#3215]
Low priority issue.
```
net10 # man lxc
net10 # lxd --version
2.12

net10 # lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
```
```
net10 # lxc launch --help | head -n 1
Usage: lxc launch [<remote>:]<image> [<remote>:][<name>] [--ephemeral|-e] [--profile|-p <profile>...] [--config|-c <key=value>...] [--network|-n <network>] [--storage|-s <pool>]
```
Seems like \<image> might be more descriptively written as \<image[/architecture]> to clarify how to create an architecture specify container.

**Comment by stgraber** [comment]
Nope, the fact that some image aliases contain the architecture after a slash is purely an implementation detail on the part of the image servers, not something that LXD itself handles. So there perfectly could be image servers out there which use "<architecture>/<distro>" or "<distro>-<architecture>", ...

This is very common for people who have images in their local image store, those local aliases almost never have the architecture in their name and if they do people tend to put it after a dash rather than slash.

Also note that the definition of an image is an alias string or a fingerprint or a partial fingerprint. In the latter two cases, there is no architecture selection since the fingerprint will point to a specific image.
