### ISSUE TITLE
Containers Updates Question

### ISSUE THREAD

**Issue by xaoc7** [lxc/lxd#3220]
* Distribution: Ubuntu 
 * Distribution version:16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.8.0-46-generic
   * LXC version:2.0.7
   * LXD version:2.0.9
   * Storage backend in use: ZFS

I have several hosts that are running LXD containers. Since it is recommended to apply security updates on regular basis I would like to understand what are the recommended (best way ) steps to apply updates (on container host and guests). Which one of bellow listed approaches is most suitable:

1. Apply Updates on Container host --> reboot (if new kernel installed) --> apply Updates on containers 
OR
2.  Apply Updates on Containers --> reboot each container (if new kernel installed) --> apply Updates on Container host 
OR
Any other way that you can suggest.

Thanks in advance!

**Comment by brauner** [comment]
So, one thing to note is that containers by design share the same kernel as the host. So your second option does not make much sense. What's probably best is update your host and your containers. The order in which this happens doesn't really matter a lot. Both should be updated if you always want to run the latest fixes for the OS your running. However, to get kernel fixes for all your containers you only need to update the host kernel and reboot the host (If that is possible in your setup.).

**Comment by xaoc7** [comment]
Thanks!
