### ISSUE TITLE
Allow aliases to external commands

### ISSUE THREAD

**Issue by diegolagoglez** [lxc/lxd#3233]
It would be a good idea to support the execution of custom git-like subcommands. For example, I would like a command to launch and execute a shell into the container directly, so I would create an script called "lxc-go" and I would place it at ~/.bin (or somewhere else) and lxc should allow run this command directly with "lxc go".

**Comment by brauner** [comment]
This sounds like a nice feature to have but likely requires some discussion. `git` does this by using the prefix `git-` to recognize such subcommands.

**Comment by stgraber** [comment]
Yeah, we'd certainly not implement this by looking at lxc-* subcommands or similar tricks as that'd directly conflict with existing commands for LXC itself. Also we don't want to look at random fs paths because that makes LXD's behavior unpredictable.

I'm not against adding a way to define additional external subcommands through ~/.config/config.yml but I do question what you really gain by defining a new "lxc blah" command vs just having a lxc-blah script in your PATH.

**Comment by diegolagoglez** [comment]
Using "lxc blah" instead of "lxc-blah" is only for coherence with lxd (2.0) subcommands. And for convenience, obviously (not to remember if we have to write a dash or not depending on the command).

And I think using ~/.config/lxd/config.yaml (or somewhere else) to add custom commands is also a nice idea, like git aliases.

**Comment by stgraber** [comment]
Yeah, we have aliases support already in .config/lxc/config.yml but those won't let you call external binaries, so it'd have to be something similar but for external commands.

**Comment by stgraber** [comment]
Ok, so we have the aliases system right now, lets just extend it slightly to allow aliasing to external commands.

The easiest and most straightforward way to do that is by simply making it so that if an alias points to a value starting with a leading `/`, we'll consider it to be an external command and just run that instead. The rest of the aliases feature will still go like the `@ARGS@` placeholder.

So you would be able to do something like:

    lxc alias add ssh "/usr/bin/ssh @ARGS@.lxd -l ubuntu -i /home/stgraber/.ssh/keys/lxd"

Which would then (assuming you've got your DNS setup accordingly) do `lxc ssh c1`
