### ISSUE TITLE
best way to share ZFS dataset with multiple containers?

### ISSUE THREAD

**Issue by niksfirefly** [lxc/lxd#3247]
I wonder what is the proper/future best way to share ZFS dataset with multiple containers?
for now i do something like that
create and mount ZFS home storage volume to containers
lxc storage volume create lxd-zfs home
lxc storage volume attach lxd-zfs home xenial home /home
lxc storage volume attach lxd-zfs home xenial2 home /home
lxc storage volume attach lxd-zfs home xenial3 home /home
where 
lxd-zfs is my ZFS storage pool for LXD (i got multiple storage pools LVM,ZFS,image based)
xenials - privileged containers

then for detach i use
lxc storage volume detach lxd-zfs home xenial home

I also use sanoid/syncoid to snapshots and backup home storage volume offsite.

Is this the right way?

**Comment by stgraber** [comment]
Hi,

Yes, that's perfectly fine. There are a number of issues when using this approach, especially with unprivileged containers and even more if those containers using security.idmap.isolated but we're working on a few ways to have this sorted out (though kernel work is needed unfortunately).

But yes, this is the approach that we'd like people to use when sharing data between containers and using the new storage functions.

**Comment by niksfirefly** [comment]
thanks for clarification
Can you point me to problems with privileged containers?

regards

**Comment by stgraber** [comment]
For privileged containers you won't have problems because the uid/gid mean the same in all containers.
But then you're using privileged containers so confinement isn't particularly good and you shouldn't run anything untrusted inside them.

When dealing with unprivileged containers, the problem is that now the same uid in two containers or in a container and the host will actually be mapped to a different kuid.
One example is that "chown 0 /home/blah" will result in the path showing as being owned by uid 100000 on the host (or something similar). If sharing a volume with a privileged container, then the unprivileged one would similarly see uid 0 and the privileged one would see 100000. If using security.idmap.isolated, then even sharing between two unprivileged containers will cause similar problems as the same chown will result in uid 100000 in the first container but uid 165536 in the second, ...

The expected way to fix all of this is by using a remapping filesystem overlay, allowing for the on-disk data to be stored unmapped (chown 0 => uid 0) and then have that filesystem remap those uids using the individual map we have for each container. So all containers would see exactly the same thing, as you'd expect and the kernel would take care of all mappings to make it happen.

**Comment by niksfirefly** [comment]
thanks !

I still hear/read that using privileged containers is dangerous but cant find existing/past
vulnerabilities. I am in control of containers in sense - Iam the only one who control containers root users. Is it considered dangerous?

**Comment by stgraber** [comment]
Our official statement is: https://linuxcontainers.org/lxc/security/

We are aware of ways to escape confinement if you get root inside a privileged containers, AppArmor will mitigate most, but not all possible attacks.

Since you say that you control root in the container and presumably won't run untrusted code as root then, things may be fine for you. That container will still be able to fight the host users for resources (due to sharing the same kuid/kgid) but that's rarely a problem.
