### ISSUE TITLE
ZFS continous snapshots integration?

### ISSUE THREAD

**Issue by niksfirefly** [lxc/lxd#3250]
I use sanoid for ZFS continous snapshots
I wonder is it possible to integrate sanoid (or the other existing scripts/solutions)
with lxc snapshot
for example use some sort of callback after snapshot or detect new snapshots for container
and update LXD database?

Is there any info what is doing lxc snapshot beside ZFS clone/snapshot
and why LXD not update info about new snapshots created behind scenes via ZFS snapshot?

**Comment by stgraber** [comment]
LXD snapshots include both the filesystem state and all the container configuration and devices that's in our database. So a filesystem snapshot alone isn't sufficient to reconstruct a LXD snapshot.

**Comment by niksfirefly** [comment]
so I assume that there is no ready script/solution and I must take care by myself right?
I wonder are there any LXD cons with ZFS based container lxc snapshots created
for every 1 
mins
hrs
days
?

**Comment by stgraber** [comment]
I've been using scripts calling "lxc snapshot" on a lot of containers every hour for weeks without seeing any obvious problem. There is the annoyance that ZFS won't let you restore a snapshot without loosing all the ones after it, but you can copy to a new container and that works fine.

You can do snapshots outside of LXD and should your host die, you may be able to restore them through "lxd import" (see doc/backup.md) but it's really more about data recovery than something you'd want to do very often.

Also note that things like copying/moving the container between hosts may get confused if you have non-LXD snapshots of your container. Similarly "lxc restore" may think it can restore a snapshot as it's the latest one that LXD knows about, but if you have snapshots created outside of LXD after that, the restore will fail due to aforementioned ZFS behavior.

**Comment by niksfirefly** [comment]
thank you
I think you are right
I'll use custom lxc snapshot script for containers
and sanoid to do frequent snapshots for data storage volumes

Are there any plans to implement some sort of snashots for volumes?

**Comment by stgraber** [comment]
@niksfirefly not right now as we're still working on fixing a number of issues with storage volumes, but it's certainly something that'd make sense to add.

Feel free to file another issue for this and I'll tag it accordingly.

One thing to note is that we're unlikely to tie container snapshots to volume snapshots. That may seem counter-intuitive at first, but since a volume can be shared with several containers and filesystems like ZFS are a bit picky on restores, it'll be easier and I suspect cleaner, to track snapshots of volumes separately from containers.
