### ISSUE TITLE
howto share storage volume snapshots to container?

### ISSUE THREAD

**Issue by niksfirefly** [lxc/lxd#3314]
There is container with storage volume mounted /home from ZFS dataset pool/lxd/custom/home
I set snapdir=visible for this dataset therefore in host 
I can access snapshots /var/lib/lxd/storage-pools/lxd-zfs/custom/home/.zfs/snapshot

I want to share specific dirs from snapshot so I add device to container 
lxc config device add container snapdir disk source=/var/lib/lxd/storage-pools/lxd-zfs/custom/home/.zfs/snapshot/snap/dir path=/home/dir

Now i can copy files from snapshot /home/dir and then remove device from container
lxc config device remove container snapdir

but on container I still got
pool/lxd/custom/home@snap on /home/.zfs/snapshot/snap type zfs (ro,relatime,xattr,noacl)
which dissapear after some time

I dont understand what happens?

Is there simpler way to share snapshots to container?

**Comment by brauner** [comment]
What do you mean by

> but on container I still got
pool/lxd/custom/home@snap on /home/.zfs/snapshot/snap type zfs (ro,relatime,xattr,noacl)
which dissapear after some time

you mean you still see an entry in the mountable as e.g. shown by `findmnt` or `cat /proc/self/mountinfo` from inside the container? Can you show via output what you exactly mean?

**Comment by niksfirefly** [comment]
well
it is strange - after few minutes
pool/lxd/custom/home@snap on /home/.zfs/snapshot/snap type zfs (ro,relatime,xattr,noacl)
dissapear

IIt is magic to me :)

**Comment by brauner** [comment]
@niksfirefly, *where* does this disappear from?: on the host or on the container?

**Comment by niksfirefly** [comment]
Container.
When I traverse on host snapshots dirs in
/var/lib/lxd/storage-pools/lxd-zfs/custom/home/.zfs/snapshot/...
every snapshot appear as mounted on container so for 10 snapshots
I see 11 mounted resources

**Comment by stgraber** [comment]
Ok, so that's clearly not something that LXD itself is doing. It's a weird interaction between ZFS, mount namespaces and the hidden (and usually not recommended), ".zfs" trick to access snapshots of a ZFS filesystem.

I'm not familiar enough with ZFS internals to know how that stuff works, but it smells like they're dynamically creating mount entries when accessing the snapshots, autofs-style and so those (and any parent needed) will expire after a while.

Closing this issue because there's nothing that LXD itself can do about this. But you may want to raise this issue with ZFS upstream. Lack of mount namespace awareness by ZFS is causing a number of different issues with containers.

**Comment by olegblecher** [comment]
I am having the same issue here, and I do think it has something to do with LXD, so I will try to provide more info.

Some background: I am running and LXD-container called "sambashare", where I'm running Samba on Debian 9, joined to an AD-server.

This machine has a folder called /shared, which was created and attached with `lxc storage volume create`, `lxc storage volume attach`. No problems there.

I've configured Samba so that users can access previous versions of files/folders with the shadow copies-function (via ZFS snapshots). 

Now, to the interesting part:

I can see all snapshots (by going in to .zfs/snapshot) inside the container, but I cannot see any files in them. However, if I manually cd into `/var/lib/lxd/storage-pools/tank1/custom/shared/.zfs/snapshot` on the host machine, and then into any snapshot, and then back, I see that the snapshot's folder has changed owners, from root:root, to 100000:100000, and that the permissions have changed from 555 to 775. After I've done that, I can see the specific snapshot mounted in by running `cat /proc/self/mountinfo`. I can also access previous versions of the folder in Windows Explorer. 

As @niksfirefly has pointed out, this lasts for about 10 minutes. After that it all goes back to the usual owner and permissions. 

So, what I wonder right now is if it's possible to force all snapshots to have 775 as permissions by default? Am I missing something? I find it quite interesting that a simple `cd` can change the permissions of a folder.

**Comment by stgraber** [comment]
@olegblecher That's an interesting behavior from ZFS and certainly pretty odd. I think your best bet is to file an issue against the zfsonlinux project as this is definitely outside of my zfs expertise :)
