### ISSUE TITLE
`file push -r` is slow

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#3317]
* LXC version: 2.13

I am uploading repository with quite a lot of files, and upload is slow. Am I right that `lxc` doesn't reuse existing connection on recursive push, but creates it anew? https://github.com/lxc/lxd/blob/fd69f4bfb500e04a0125d17c47204d8743dd5d9f/client.go#L1760

**Comment by techtonik** [comment]
How to check which HTTP version LXD uses? And if it uses pipelining?

**Comment by dann1** [comment]
Yes i tried it the other day, 4 web pages inside a folder, I copied the folder and it took a lot.

**Comment by stgraber** [comment]
The http client is re-used but I very much doubt that the bottleneck is with the HTTP side of things. Instead I'd expect the fact that we need to spawn a task and attach to the container's namespace for every file you're sending to be where the bottleneck is :)

All the "file" commands are certainly very convenient but they are also very expensive due to LXD having to spawn a subprocess for each of them (as namespace changes can't be done in-process) and then deal with the communication to that subprocess, temp files, ...

If you need a higher throughput, it's usually best to either have some file transfer tool running inside the container itself (sshd, ftp, ...) or you can pipe tar through "lxc exec" which also tends to be much faster.

Something along the lines of:

   tar zcf - somedir/ | lxc exec some-container -- tar zxvf - -C /dest/

Closing this issue as for now at least we're not looking at adding bulk transfer to LXD itself (which would be a way around this issue) and there's little that we can do to optimize the existing approach. The setns syscall is very expensive and every file you transfer will need at least 2 calls to it.

**Comment by techtonik** [comment]
> All the "file" commands are certainly very convenient but they are also very expensive due to LXD having to spawn a subprocess for each of them (as namespace changes can't be done in-process) and then deal with the communication to that subprocess, temp files, ...

1. Where does this happen?
2. Why a subprocess is required for each file?

**Comment by stgraber** [comment]
That all happens on the daemon side. A subprocess is needed because of the setns calls and since there is no bulk file transfer in the API, every file creation that's requested means a separate call to the API.

HTTP pipelining or similar tricks would just let you get more requests into the API endpoints but wouldn't change the way things are handled after that, which is where the bottleneck actually is.

**Comment by techtonik** [comment]
So the solution is to implement `-r` type endpoint on the server side, which will do `for` loop on the input to create multiple files in single thread that already passed through `setns` call, right?
