### ISSUE TITLE
gre and gretap0 host devices visible from with containers

### ISSUE THREAD

**Issue by javacruft** [lxc/lxd#3338]
lxd: 2.0.9 from Xenial
nova-lxd: Xenial-Newton proposed (14.2.2)

as reported under https://bugs.launchpad.net/cloud-archive/+bug/1692545 when running LXD containers using the nova-lxd compute driver for openstack, some host devices are visible from within the container:

```
$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: gre0@NONE: <NOARP> mtu 1476 qdisc noop state DOWN group default qlen 1
    link/gre 0.0.0.0 brd 0.0.0.0
3: gretap0@NONE: <BROADCAST,MULTICAST> mtu 1462 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
12: eth0@if13: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1300 qdisc noqueue state UP group default qlen 1000
    link/ether fa:16:3e:d7:7d:ce brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.21.7/24 brd 192.168.21.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::f816:3eff:fed7:7dce/64 scope link 
       valid_lft forever preferred_lft forever
```

These specifically confuse cloud-init a bit; they relate to the GRE overlay networking being used by the OpenStack Cloud, and should probably not be visible/accessible from within the container.

**Comment by stgraber** [comment]
So what's happening here is that loading the "ip_gre" kernel module makes the "gre0" and "gretap0" devices appear in all network namespaces.

I seem to remember the same happening with sit so it may be a general tunnel thing rather than being gre-specific.

Those interfaces are in fact properly namespaced, that is, the gre0 you see in the container isn't the same gre0 as you see on the host. But since those are an internal requirement of the ip_gre kernel module, you can't remove them and that's why the kernel puts them in every namespaces.

There is nothing we can do about this at the LXD level.
This should be treated as a cloud-init bug since a system that has an initrd which loads ip_gre would cause the exact same behavior in VMs and on metal.

And alternative would be to figure out why those tunneling protocols required those weird virtual interfaces and see whether the tunneling code in the Linux kernel could be made to not do that, but I don't think we have anyone with expertise in that code or the time to get something like that sorted.
