### ISSUE TITLE
storage: allow for drivers selection during build

### ISSUE THREAD

**Issue by brauner** [lxc/lxd#3354]
I think it would be nice for our users to have the option of selecting all drivers they want to have supported as a compile-time flag. For example something like

    make -s btrfs,zfs

which would build LXD with support for the btrfs and zfs driver without support for other drivers. (@stgraber)

**Comment by stgraber** [comment]
What would the benefit of this be?

It sounds like quite a bit of work that would then let people build "snowflake" version of LXD that will miss some particular features and make it more painful for us to debug issues. If the different storage backends were bringing in external packages that would cause LXD to grow significantly or use more memory just because it's been built with those backends, that'd be a reason for this, but it's not the case as we merely shell out to the various tools.

**Comment by brauner** [comment]
Hm, ultimately I was thinking to slowly introduce compile-time switches to disable and enable certain features that might alter LXD quite a bit.

For storage it's about giving people the option of simply disabling certain drivers that they don't want people to use. For example btrfs and it's weird quotas.

Also, what would be cool is if we had a storage module API. Meaning users could implement their own storage backend which doesn't need to ship with LXD itself by just adhering to a more generic interface we expose, e.g. a cleaned-up version of the current storage interface which I plan to do during the next days anyway.

**Comment by stgraber** [comment]
Restricting what kind of storage backend can be used strikes me as something better done as part of the upcoming user ACLs feature, where we'd indeed be able to prevent some users from creating storage pools using some specific storage backends.

I'm also very strongly against external plugins or hooks, especially when integrated within the lifecycle (so not there merely as observer). Supporting those would make it near impossible to predict LXD's behavior and would also make otherwise identical LXDs behave differently because of whatever random plugin was manually dumped on a given machine.


I'd much rather we keep our internal APIs simple and make it easy for contributors to submit additional storage backends to LXD upstream. If some of those do end up being costly to build and only useful in very special environments, we can reconsider making them optional at build time (with applicable API to detect which backends have been built into LXD).

**Comment by brauner** [comment]
Hm, I'm just in favor of modularity but these are certainly valid points.
