### ISSUE TITLE
"vlan" property not available for "physical" interfaces

### ISSUE THREAD

**Issue by BegBlev** [lxc/lxd#3375]
Hi,

Today, "vlan" property is available for "macvlan" NIC type but not for "physical". In my use case, I need it.
Is there any argument not to do it or is it only nobody asked for it before?

**Use case**
I use nested containers.
1 Container per customer. Several "service" containers inside "customer container".
Customer container is connected using VLAN (i.e eth0.100 for customer A and eth0.101 for customer B)
Inside "customer container" several services are connected using a simple bridge.

Regards.
Vincent

**Comment by brauner** [comment]
@stgraber

**Comment by BegBlev** [comment]
Hi Christian,
Excuse my ignorance but what does that mean?
Stéphane will be triggered as you mention him or does that mean I have to write to him directly?

Regards
Vince

**Comment by brauner** [comment]
Oh sorry for the confusion, I was just making @stgraber aware that I couldn't look into this. Hell respond soon, I'm sure. :)

**Comment by brauner** [comment]
s/Hell/He'll/

**Comment by stgraber** [comment]
@BegBlev you need macvlan to do what you mention, that or create a bridge per VLAN and bridge the eth0.ID interface into it.

The reason for that is that eth0 and eth0.100 are tied together at the kernel level, so you can't move eth0.100 into a container without eth0 itself coming alongside it (and any other vlan interface you have).

**Comment by stgraber** [comment]
If there had been a way to implement this without macvlan, that's how I'd have done it in the first place. People usually don't like using macvlan unless they actually have to :)

**Comment by brauner** [comment]
Closing as there is nothing we can do about this restriction currently.

**Comment by BegBlev** [comment]
@stgraber,
Actually this is possible to move only eth0.100 to a container and eth0.101 to an other without moving eth0. This is my current implementation and it works like a charm.
My only problem is that I have to create the VLAN device previously and then attach this device to the container using :
`lxc config device add customer-A eth0 nic nictype=physical parent=eth0.100`

In order to avoid the VLAN interface pre-creation, I would like to be able to do :
`lxc config device add customer-A eth0 nic nictype=physical parent=eth0 vlan=100`

**Comment by stgraber** [comment]
Interesting, so I guess they managed to decouple the two devices at the kernel level somehow.
There is still one pretty big limitation which makes this unsuitable for LXD to offer as it'd confuse users more than anything else:

```
root@lantea:~# vconfig add enp3s0 100
Added VLAN with VID == 100 to IF -:enp3s0:-

root@lantea:~# ifconfig enp3s0.100 up

root@lantea:~# lxc config device add test eth1 nic nictype=physical parent=enp3s0.100
Device eth1 added to test

root@lantea:~# vconfig add enp3s0 100
ERROR: trying to add VLAN #100 to IF -:enp3s0:-  error: File exists

root@lantea:~# ifconfig enp3s0.100
enp3s0.100: error fetching interface information: Device not found
```

So that shows that you can indeed move the VLAN device into the container and keep the parent in the host. But that means you won't be able to create another device for that VLAN even though you can't see the existing one.

**Comment by stgraber** [comment]
So if you are lucky enough to have exactly one container per VLAN and never any more than that, then that may indeed work. Note however that you may run into problems when restarting containers as the kernel will usually cleanup the network namespace in the background, so that VLAN device may end up stuck for a few minutes in a dying network namespace, preventing you from starting the container again.

**Comment by BegBlev** [comment]
So, if I find time to submit a patch, do you think it would have a chance to be merged?

**Comment by stgraber** [comment]
If we were to merge this change, it'd have to come together with a very clear explanation of what's happening there, otherwise people will use "nictype=physical parent=eth0 vlan=100", spawning a container with that just fine. Then try to spawn a second one and wonder why it's not working anymore. They would get further confused by the fact that the parent eth0 interface will exist on the host and that the error will be that eth0.100 already exists, when it actually doesn't on the host.

Things will then likely get even more confusing as the user may then switch to macvlan instead of physical, which will fail in exactly the same way as our macvlan code will similarly fail to create the vlan interface until such time as the container that uses the "physical" vlan interface is shut down.

**Comment by stgraber** [comment]
This has been implemented.

**Comment by dnshs** [comment]
Is there any reason this couldn't work with an OVS bridge too? Using ovs-vsctl set port somebridge tag=1234

**Comment by stgraber** [comment]
So the difficulty here is mostly because of how things are done internally, the first issue is that nictype=bridged doesn't tell us if it's a Linux bridge or OVS, so we can't make it such that we only allow the vlan property on OVS and not Linux bridges. The second, more serious issue is that we configure all this through liblxc and liblxc doesn't support setting a tag on the port in its OVS code, so there's no way for LXD to actually drive that.

**Comment by dnshs** [comment]
Thanks, I'll work around the limitation.
