### ISSUE TITLE
starting the docker service on an lxc/lxd host causes traffic to lxc containers to stop

### ISSUE THREAD

**Issue by mcgoo** [lxc/lxd#3387]
Installing Docker on the same host as lxd causes connectivity to lxc containers to stop. 

According to https://github.com/rkt/rkt/issues/3683 it is because Docker changes the default iptables FORWARD rule to drop. The solution for me is to add forwarding rules as described in that thread.

```
# lxc --version
2.14
~# docker --version
Docker version 17.03.1-ce, build c6d412e
```

I hope this is not a duplicate report - I can't believe that I'm the only person who has seen this, but I was not able to find an issue or any other information about it. Hopefully this report saves someone else from wasting a whole load of time on it.

Thanks for lxd!

**Comment by stgraber** [comment]
Thanks for the report. I'm going to close it since there's no actual LXD issue there. If anything, that'd be a Docker bug.

Changing default table policy on a machine is a very bad idea and will indeed conflict with things like LXD, libvirt, rkt, ... not to mention that if you decide to run Docker on your home gateway, then you'll be in a lot of troubles :)
