### ISSUE TITLE
Memory overcommitment + container limits

### ISSUE THREAD

**Issue by dann1** [lxc/lxd#3402]
Hello, I'd like to know how does LXD manage the RAM over-commitment. KVM uses KSM + ballooning.

Also I'd like to know the limits in terms of how much RAM, CPU, NICs and mounts LXD supports ( I mean max numbers per container, and max numbers per daemon) and the max amount of containers per daemon.

I haven't found that info in the documentation

**Comment by stgraber** [comment]
LXD container will support as much ram, cpu, nics, mounts as your host would. It's all shared kernel objects so the same limits apply.

There are no limits to then number of containers you can run, though it's rare that you can exceed 10000 without getting into some serious slow downs due to the very high amount of kernel objects resulting from that.

To get you past around 500 containers you will also have to bump a number of sysctls, we have those listed in our production setup documentation.

As for memory. There is no need of ballooning for containers. Ballooning is used to prevent VMs from caching data, taking that memory away from the host. With LXD, the containers are just processes on the host, so caching is done for the whole host by the kernel.

**Comment by dann1** [comment]
OK thanks a lot @stgraber
