### ISSUE TITLE
Overview viability to add casync support to lxd

### ISSUE THREAD

**Issue by cryptofuture** [lxc/lxd#3429]
http://0pointer.net/blog/casync-a-tool-for-distributing-file-system-images.html  
I think, it could replace rsync on directory, also it maybe viable to test it speed vs rsync and btrfs-send and overview viability to include it in lxd.

**Comment by brauner** [comment]
That looks like a `systemd` specific binary. I don't necessarily mind using it but we should probably wait how general adoption goes and also it is questionable whether the team can dedicate time implementing this right now. In general, we'd need to discuss whether this is a good fit for us.

**Comment by stgraber** [comment]
It may be a valid alternative to rsync, but until it's as widespread and proven as rsync, it's not something we should really rely on. Lets keep this as a maybe for now and revisit in a few years.

**Comment by stgraber** [comment]
Looked into this one a bit more now. I don't think casync is really getting us anything over rsync and the latter is much more widely available. casync's strength seems to be in delta transfers such as what happens when mirroring a large set of ever changing content. That's not what we use rsync for in LXD.

Our use of rsync is strictly limited to a one or two step sync of a filesystem tree. We don't run continuous update runs and don't normally have any pre-seeded data on the target.

It may be that casync is somehow marginally more efficient than rsync, though that remains to be proven. But given that we use rsync in a fallback scenario only and it's only used for host to host transfers which typically involves gigabit or faster connectivity between hosts, I don't think it's worth the trouble.

If casync somehow manages to reach rsync's level of availability and API stability over the next few years we may reconsider then, but for now that's enough investigation so we can close this issue.
