### ISSUE TITLE
doc/lxd-ssl-authentication.md unclear

### ISSUE THREAD

**Issue by killua-eu** [lxc/lxd#3448]
**This is a documentation ticket.** I noticed that the docs on "LXD REST API's security done right" is a bit sparse, spread over multiple files and still requiring to delve deep to understand its possibilities and caveats. Assuming a server with lxd called **mightyserv** and a devs notebook with lxd called **devnb** and a setup along the following:

```
### setup mightyserv
mightyserv # lxc config set core.https_address 192.168.1.100:48443 # listen on a nonstandard port
mightyserv # lxc config set core.trust_password MYSECRETPASS
### review mightyserv
mightyserv # lxc config get core.https_address
mightyserv # lxc config get core.trust_password
# setup devnb
lxc remote add mightyserv 192.168.1.100:48443
### review devnb
devnb # lxc remote list
devnb # lxc remote list mightyserv:
devnb # lxc list mightyserv:
```

i found it hard(er) to find info on the following:

1. when are certs generated in ~/.config/lxc (on devdb)?
2. how are these certs generated, how can one force their regeneration (i.e. if the used cipher would develop a major vulnerability)
3. where are client certificates stored (on mightyserv)?
4. how do you disable client's (devnb) to mightyserve, when devdb is identified with its specific certificate? **lxc trust remove lxc config trust list**
5. how do you list client certificates? **lxc config trust list**
6. why would one not want to open the api port to the world if access to it is protected with a strong cipher (https://github.com/lxc/lxd/blob/master/doc/lxd-ssl-authentication.md)? why bother with a ssh tunnel (https://stgraber.org/2016/04/12/lxd-2-0-remote-hosts-and-container-migration-612/#comment-235914) if access to the api should be similarly secure as with key-based ssh access to the server? (apart from the obvious reasons such as doubling the security layers and protecting from dos attacks)
7. how does the api server prevent dos attacks? are there i.e. some fail2ban rules that can be used, or is there a way to white-list access from certain ips?
8. what do people actually use in production to secure their lxd-api instances?
9. how do you disable adding new clients (on mightyserv)
10. best practices, or what does the developer team use in production (everything from nonstadanard api port to guarding servers with war elephants)

Maybe additions to https://github.com/lxc/lxd/blob/master/doc/lxd-ssl-authentication.md might be helpful? Or am I missing a document covering the above?

- https://stgraber.org/2016/03/15/lxd-2-0-installing-and-configuring-lxd-212/
- https://github.com/lxc/lxd/issues/1858
- https://github.com/lxc/lxd/blob/master/doc/lxd-ssl-authentication.md

**Comment by stgraber** [comment]
1) The first time you add or interact with a remote server
2) Remove them and new ones will be generated on next connection (obviously they won't be trusted)
3) In the database (certificates table)
4) "lxc config trust remove FINGERPRINT"
5) "lxc config trust list"
6) No real reason why LXD can't be exposed to the internet. Especially if no trust password is set, then there's no risk of even brute force attacks working. The main reason not to expose LXD to the internet would be a lack of trust in the Go TLS stack or company policies.
7) No such thing right now. Fail2ban could probably be used for that, but would need more verbose logging on LXD to find auth failures.
8) Usually, they set core.https_address to a single address, doing their usual firewall rules in front and in general not keeping core.trust_password set after your clients are trusted
9) Just unset core.trust_password
10) All my LXD servers can talk to each other directly over the network, but that's an internal network that's not exposed directly to the internet. I do the exact same for SSH though, so it's not because of a lack of trust in LXD's security :) If I want to connect from the outside, I VPN to my network and then can talk to any host I want.

**Comment by stgraber** [comment]
lxd-ssl-authentication.md would probably benefit from being converted into a more general security.md document. Improving our docs and having them included in our website is part of our planned work for the coming months.

**Comment by killua-eu** [comment]
Thanks for the swift answers @stgraber, they made everything crystal clear to me. Feel free to close the ticket or keep it around opened if it has any meaning for the planned documentation work. Also thanks for the great work on lxd, I really appreciate.
