### ISSUE TITLE
fuidshift doesn't work: what am I doing wrong??

### ISSUE THREAD

**Issue by akarelas** [lxc/lxd#3480]
First I typed:

`fuidshift -t rootfs b:165536:100000:65536`

and got

`Error: "Bad idmap: \"rootfs\""`

(with wrong quotes)

Then I did:

`fuidshift rootfs -t b:165536:100000:65536`

and that worked (What?!)

Then I did:

`fuidshift rootfs b:165536:100000:65536`

and that didn't work. I got:

`Error: "Failed to change ownership of: rootfs"`

Am I wrong here or is there something wrong with this software?

**Comment by akarelas** [comment]
I'm root, and I'm residing inside root@test-vm:/var/lib/lxd/storage-pools/default/containers/test-container

**Comment by akarelas** [comment]
Also I'm getting another line which I just saw:

```
root@test-vm:/var/lib/lxd/storage-pools/default/containers/test-container# fuidshift . b:165536:100000:65536
Invalid path, source (/var/lib/lxd/storage-pools/default/containers/test-container) is outside of basepath (.).
Error: "Failed to change ownership of: ."
```

**Comment by akarelas** [comment]
What does that mean???

**Comment by akarelas** [comment]
basepath??? What is that?

**Comment by stgraber** [comment]
The first issue is because you weren't following the argument ordering that's listed in usage (--help):
```
Usage: fuidshift directory [-t] [-r] <range1> [<range2> ...]
```

"basepath" in the error refers to the path you provided (".") in your case.
The id shifting code must be very careful to follow some symlinks but not all, effectively checking whether a symlink is inside the container or not. If you provide a relative path like ".", it can't do so.

I'd suggest always passing a full path to fuidshift so that it can properly do path comparisons.


fuidshift isn't really a tool users are meant to use unless it's to fix a very specific issue and someone instructs you on exactly how to use it. Running it with the wrong arguments will lead to a partially shifted filesystem that you can't then recover from.

**Comment by stgraber** [comment]
In your case, it sounds like you're doing this as part of the restoration of a backup, which is almost certainly wrong. You should never need to use fuidshift when using "lxd import". The container map is tracked as part of container metadata and LXD should be the one doing necessary remapings.

Remapping the filesystem like this behind LXD's back may cause LXD to then attempt to "fix" the map on an upcoming container start, effectively double shifting everything and leading to a broken container.

**Comment by stgraber** [comment]
Lets close this issue and focus on your "lxd import" issue instead, restoring the container the right way.
