### ISSUE TITLE
LVM thin-provisioning option should check for existence of necessary tools

### ISSUE THREAD

**Issue by SundialServices** [lxc/lxd#3497]
If "lxd init" is tried with the "LVM" thin-provisioning option, but the necessary command-line tools (Linux distro package ...) are not installed on the host computer, the action will fail with a very cryptic message:

`error: Error Creating LVM LV for new image: Could not create thin LV named 7a7f...` 

(where "7a7f..." refers to the random hexadecimal string that was to be used as the LV name.)

This message gives you absolutely no idea what went wrong, nor what to do next.

I suggest that the command should *check for* the existence of the necessary command(s), and stop and issue an informative message if they are missing.  The documentation web-pages should also mention this pre-requisite.

(On Ubuntu, the package-name is `thin-provisioning-tools`.  But, tell us what commands are needed so that if necessary we can search for the right distro package that will contain them.)

**Comment by stgraber** [comment]
@albertodonato can you take a look at this one?
We obviously don't want to look at installed packages because that won't work on other distros, but the error when attempting to create a thinpool lvm storage pool (default) on a system that has LVM but not thin pool support should certainly be clearer.

We should also change the logic in "lxd init" to hide "lvm" as a supported backend if thin pool isn't supported on the system.

And for documentation, we'd want to add a line to storage.md's section on lvm, mentioning that we do thinpool by default and that on some distributions that requires additional packages be installed. If the user doesn't want to use thin provisioning, they can set lvm.use_thinpool=false at pool creation time.

**Comment by stgraber** [comment]
Actually, we could even make "lxd init" more clever and if thinpool support is lacking, ask the user if they wish to continue without thin provisioning, in which case it would set lvm.use_thinpool=false for them.

**Comment by SundialServices** [comment]
I think that it *is* important to provide LVM as a recognized option!  *(Don't make it "mysteriously not appear as a choice," when you've told the user community in documentation that it is.  The user won't know what to do.)*  

I think that it would be a relatively simple thing to look to see if the command is out there ... *e.g.* try a dummy `exec()` with no parameters and see what return-code you get ... and then to terminate with an appropriate error message if the command is unrecognized, i.e. support is lacking.

After all, the super-user who is issuing these sort of commands *does* have the ability to install the necessary support onto the machine, as soon as he becomes aware of the requirement to do so.  Thus, I think that the appropriate action is to inform him of what he needs to do first.

**Comment by stgraber** [comment]
@SundialServices hiding storage options that aren't supported by the system is already what's done by default by "lxd init" so we won't be changing that. It's just that LVM support right now is detected based on the presence of the "lvm" command, which does exist even when thinpool isn't supported.

LXD doesn't actually call any of the commands provided by the thinpool package, those commands are internally called by LVM which is why we're currently unable to detect the lack of thinpool in a trivial way and why we need to find a reasonable cross-distro way of detecting it.

**Comment by brauner** [comment]
I'd be interested if this can actually be done trivially. I suspect you simply fail to create. Maybe the return value is helpful.

**Comment by stgraber** [comment]
The easiest way is probably to add logic to "lxd init" to look for whatever thinpool helper lvcreate calls. That should work for all distros where those tools are on the PATH (hopefully most of them).

That will still let people call "lxc storage create blah lvm" to do manual thinpool if "lxd init" mis-detected. If we can do better error handling for thinpool at that point too, that'd be nice.

**Comment by SundialServices** [comment]
" =I-F=(!) they actually know as much about such things, as you do!"

_"Don't assume.  Don't assume!"_

Please remember(!) that there are a GREAT MANY people out here – such as ME – who actually have no idea whatsoever about "a thinpool package!"  :-)  We simply want to say "lxd init" (or what-have-you) and find that it "works as-promised."  If we know that our environment "supports LVM," then we pure-and-simply expect that "one way or the other, 'it will Work,'" because we have no way to anticipate that we need to have done anything else "in order to make it work."  You must GUIDE US.

In the case at bar, I discovered "the solution" only by "Google happenstance."  Which, of course, is not acceptable at all.  "Those of us who are earnestly following in your footsteps" earnestly need your help. Please give us a clear path forward which does not presume that we have already stepped on the very same river-stones that you did.  Thanks in advance.

**Comment by simos** [comment]
LXD (at least 2.14) has the following CLI options: 

```
$ lxd --help
...
Init options for non-interactive mode (--auto):
    --network-address ADDRESS
        Address to bind LXD to (default: none)
    --network-port PORT
        Port to bind LXD to (default: 8443)
    --storage-backend NAME
        Storage backend to use (btrfs, dir, lvm or zfs, default: dir)
...
```

Currently, the logic as to which storage backends to show when running _lxd init_, is:

1. If it is a vanilla Ubuntu installation, show "dir" and "zfs", and show as default "zfs". Specifying "zfs" will fail, because "zfsutils-linux" is not installed by default. That is the case with Digitalocean and I think it is also the case with desktop/server Ubuntu.
2. If the package "btrfs-progs" is not installed (not installed by default), then _lxd init_ will not show "btrfs" as an option. I think LXD already checks for the presence of the utility "btrfs" to decide whether to show "btrfs" as a storage backend option when running "lxd init".

I think there should be a new option to "lxd", --storage-backend-query, which will query the current system and report back something like the following:

```
Storage backend       Availability
            dir                  Is available.
            zfs                 Requires the installation of ZFS utilities.
            btrfs               Requires the installation of btrfs utilities.
```
            
The test for "zfs" would be the existence of the "zpool" utility (shared.RunCommand("zpool",). LXD already performs a check for the "btrfs" utility in order to decide whether to show it as an option.
