### ISSUE TITLE
lxc start - Failed to mount ZFS filesystem

### ISSUE THREAD

**Issue by Kriskasz** [lxc/lxd#3535]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 17.04 (Zesty Zapus)
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.10.0-26-generic #30-Ubuntu SMP
   * LXC version: 2.12
   * LXD version: 2.12
   * Storage backend in use: zfs

# Issue description

After I start container (this is permanent problem) I get error :

**error:** Failed to mount ZFS filesystem: filesystem 'lxdpool/containers/second' is already mounted
cannot mount 'lxdpool/containers/second': mountpoint or dataset is busy
Try `lxc info --show-log second` for more info

**When I want to see lxc info --show-log I get:** 

Name: second
Remote: unix:/var/lib/lxd/unix.socket
Architecture: x86_64
Created: 2017/07/11 12:06 UTC
Status: Stopped
Type: persistent
Profiles: default
 
Log:

# Steps to reproduce

 1. Only reboot host can help, but it cannot be like that to reboot server when I have 30 lxd running
 2. I tried in two images centos 7 and ubuntu 16.10 and problem is the same

**Comment by brauner** [comment]
This is our dearly beloved zfs bug which is caused by the fact that zfs is not namespace aware. We have a ticket open upstream about this. That being said, you should upgrade to `LXD 2.15` since we handle this bug smarter nowadays. Please report back if you experience additional issues after you have upgraded!

**Comment by Kriskasz** [comment]
this is what I get -> lxd is already the newest version (2.12-0ubuntu3)

**Comment by stgraber** [comment]
Hi, you can get LXD 2.15 using the backports pocket.

    apt install -t zesty-backports lxd lxd-client

That will get you LXD 2.15.

**Comment by stgraber** [comment]
And will get you the latest stable LXD once a month after we've released and tested it.

**Comment by melato** [comment]
I have ran into this problem today, with lxd 3.12, which was automatically updated by snapd today (2019-04-08).  I wanted to add a disk device to a container, via a profile, and when I tried to restart the container (because I could not see the new device), it wouldn't start, because it could not mount another existing zfs storage pool volume.  I don't know if this was caused by the update to LXD 3.12 or not, since the update happened at some random time that I did not know.

My desktop, where I could test things, is still on LXD 3.11, so I have two systems on different versions.

I read at the top that "This is our dearly beloved zfs bug which is caused by the fact that zfs is not namespace aware. We have a ticket open upstream about this."  Could you add a reference to this upstream bug, so we can track its progress?

Is there a way to unmount the zfs volume manually, so I can start the container?

**Comment by mccaddon** [comment]
I too ran into this issue, it came out of no where and took me all day to resolve.  I was running centos 7.7 (two environments borked the same weekend) and the only way to fix was to copy the containers to a ubuntu base environment and start.  I tried restarting the server but that made all my containers STOPPED except the first one I created and that first container was RUNNING but couldn't obtain an IP address.  Any new containers would not start. Really big heart break.

**Comment by bodleytunes** [comment]
I've just had this totally randomly and end up at this thread!

**Comment by bodleytunes** [comment]
It seems to me that the containers that are not starting are not mounted like this:

`var/snap/lxd/common/mntns/var/snap/lxd/common/lxd/storage-pools/zfs1/containers`

The particular non starters are not showing any files in their subfolder

However the zfs is mounted in the usual place according to zfs list and I can see the  files mounted there.

**Comment by bodleytunes** [comment]
![image](https://user-images.githubusercontent.com/619239/73301248-54eac680-420a-11ea-8ee0-24d4fd92f078.png)

![image](https://user-images.githubusercontent.com/619239/73301288-67fd9680-420a-11ea-9177-018d12f4d273.png)

**Comment by bodleytunes** [comment]
I too was only drawn to this when I noticed a handful of my containers didn't have any IP addresses.  After a reboot I then couldn't start them.
