### ISSUE TITLE
 qemu-user-static support seems broken: Requested architecture isn't supported by this host

### ISSUE THREAD

**Issue by 1koval** [lxc/lxd#3557]
It seems a regression introduced around v2.0.10:
lxc containers no longer launch in qemu-user-static environment:
 
```
#l xc version
2.0.10
# lxd --version
2.0.10
```

Steps to reproduce

On x86_64 host: 
```
# sudo apt-get install qemu-user-static
# lxc init ubuntu:16.04/armhf arm1
error: Requested architecture isn't supported by this host
# lxc launch ubuntu:16.04/armhf arm1
error: Requested architecture isn't supported by this host
```

At the same time container created before with older version of lxc/lxd can start under 2.0.10 with qemu user emulation in the same environment.

**Comment by stgraber** [comment]
I'm surprised that you're reporting this as a regression, it's never something which we supported on LXD and the architecture check has been around for a long time. It may have been that a bug in LXD somehow wasn't tripping that check for you, but it sure was never meant to work.

LXD will let you copy images for another architecture but will only ever let you spawn containers for your native architectures. The use of qemu-user-static is something which we had in LXC (for Ubuntu and Debian templates) but which was way too bugy for us to ever consider supporting in LXD.

If you really wanted, you could still produce images that register as amd64 but contain an armhf filesystem, mixed with the needed qemu-user-static binaries in there and with the various network tools and init system coming from the native architecture of the host (as anything using netlink or ptrace will fail under qemu-user-static). Since such an image would register as amd64, LXD would let you run it, but we'd obviously not offer any kind of support on that :)
