### ISSUE TITLE
New LXD Client Package: Access to HTTP client

### ISSUE THREAD

**Issue by jtopjian** [lxc/lxd#3580]
Hello,

I'm trying to rewrite an application which uses LXD to use the new LXD client package. It's been relatively simple (thanks!), but I can't figure out how to access the HTTP client. The reason I want to do this is to provide a custom Timeout value.

Here's the original way I was doing this:

https://github.com/yyyar/gobetween/blob/5c51b0c3a3e63b9d8cfdb58e72bea312904c7771/src/discovery/lxd.go#L57

I see there is an `http.Client` defined here:

https://github.com/lxc/lxd/blob/master/client/lxd.go#L25

But other than what's defined in `ConnectionArgs`, I can't find a way to specify any other type of customizations.

Is this possible to do? If not, would it be possible to regain access to the http client?

Thanks,
Joe

**Comment by stgraber** [comment]
Hi,

Since we're now dealing with interfaces (ContainerServer and ImageServer), you can't easily get to struct members even if we were to make them public.

So this leaves us with two obvious options to deal with this:
 - Allow for an alternate http.Client to be passed through ConnectionArgs which would be used as the base for the connection's http client
 - Add a GetClient function to the ImageServer interface (and ContainerServer through inheritance) which would let you retrieve a pointer to the http client and let you alter it as you want.

It seems to me like the latter will be easiest and should be fine so long as you are fine with a couple of queries going through before you get to do your change (as we do a call to GetServer() internally).

Another option would be to allow for a new Connect function which would entirely rely on a provided http.Client and so not do any of the tls setup itself. But I don't think this one would be particularly useful to you.

**Comment by stgraber** [comment]
My current plan is to send a branch which implements both of the proposals.
So that would be a new function in the ImageServer and ContainerServer interfaces that allows the retrieval of *http.Client as well as a new struct member for ConnectionArgs which will let you provide a base http.Client to be used for the connection.

**Comment by jtopjian** [comment]
@stgraber Thanks for the implementation details!

> It seems to me like the latter will be easiest and should be fine so long as you are fine with a couple of queries going through before you get to do your change (as we do a call to GetServer() internally).

This sounds like a good solution, especially because it allows LXD to begin with an http client it created itself, which is probably safest.

> Another option would be to allow for a new Connect function which would entirely rely on a provided http.Client and so not do any of the tls setup itself. But I don't think this one would be particularly useful to you.

Agreed. 

Thank you for beginning work on this so quickly. I'd be happy to test anything out, but as you can see from the link I gave above, if I can access the `Timeout` setting, that's good enough for me :smile:
