### ISSUE TITLE
Auto generated image server certificate uses short hostname?

### ISSUE THREAD

**Issue by Kramerican** [lxc/lxd#3586]
Hello,

By coincidence I noticed this on one of my client LXD hosts today:

> Jul 24 22:24:24 worf lxd[7683]: err="Get https://krellide.mysite.io:8443/1.0: x509: certificate is valid for krellide, not krellide.mysite.io" fp=4cb79028ab7d82bcfc15cea8646cf2c9151e5ddc2010b1c3614634ffa74dc400 lvl=eror msg="Failed to update the image" t=2017-07-24T22:24:24+0200

Where krellide is my LXD image server. If I do hostname and hostname -f on krellide, I get respectively

```
# hostname
krellide
# hostname -f
krellide.mysite.io
```

Which I think is correct. I do not remember telling LXD to generate a certificate, nor telling it which hosts it should be valid for. 

**Questions:**

1. Is this as critical as the log entry suggest? (i.e. images cannot be updated)
2. If so, how do I generate new certificates for LXD on krellide where the proper full hostname is specified ?

**Comment by stgraber** [comment]
That error is usually an indication of another, often unrelated problem. For communication between LXD servers, a trusted copy of the target server certificate is used rather than the system CA validation mechanism being used.

What LXD version are you using?

Can you paste: "lxc image info 4cb79028ab7d82bcfc15cea8646cf2c9151e5ddc2010b1c3614634ffa74dc400"

This should give us some ideas of what LXD's trying to do with that background image update.

**Comment by Kramerican** [comment]
Howdy

Yes the output on the target system is

```
# lxc image info 4cb79028ab7d82bcfc15cea8646cf2c9151e5ddc2010b1c3614634ffa74dc400
Fingerprint: 4cb79028ab7d82bcfc15cea8646cf2c9151e5ddc2010b1c3614634ffa74dc400
Size: 718.01MB
Architecture: x86_64
Public: no
Timestamps:
    Uploaded: 2017/06/20 20:54 UTC
    Expires: never
    Last used: 2017/07/24 11:31 UTC
Properties:
Aliases:
    - xenial-lamp-php7 (xenial-lamp-php7)
Auto update: enabled
Source:
    Server: https://krellide.mysite.io:8443
    Protocol: lxd
    Alias: xenial-lamp-php7
```
Both on the image server and the target system I am running v2.15

As a sidenote, that image no longer exists on the image server (or well, the alias exists but the image has been updated)

**Comment by stgraber** [comment]
Can you post the output of:
 - sqlite3 /var/lib/lxd/lxd.db "SELECT * FROM images;"
 - sqlite3 /var/lib/lxd/lxd.db "SELECT * FROM images_source;"

I want to see if the server certificate has been properly recorded. The error you're getting suggests that it wasn't. Possibly because it was copied before we fixed that particular LXD bug.

While attempting to debug this, I did find a bug in our current client which would cause such copies to fail to record the source alias. I'm sending a fix for this and validating what happens if the alias changes on the source server.

**Comment by stgraber** [comment]
With my client fix, current LXD from git does seem to connect to the source image server properly.
I've modified the alias on my source server to point to another (public) image and my LXD properly updated my image to match.

So I think this issue can be closed once my fix gets merged. The root of the reported issue here is a bug we fixed some weeks ago where the source server certificate wasn't recorded by LXD, making connections impossible.

Unfortunately your LXD doesn't have enough information to ever update this image. So your best bet is to wait for LXD 2.16 (due tomorrow), then delete the image from your local image store and do a copy again (with "--auto-update --copy-aliases") which will record the needed information and then be able to auto-update your image properly.

**Comment by Kramerican** [comment]
Howdy

Well that's excellent - I'll make sure to upgrade! No problem deleting the image. I however will not be doing --auto-update --copy-aliases as I have just started doing `lxd init krellide:xenial-lamp-php7 foo` when provisioning.

So I guess this issue doesn't affect me really, as it's really just affecting images which have been copied manually with auto-update flagged, so that LXD tries to update on its own (e.g. on system boot, as where I saw that log entry) - right?

Please stop me if I'm wrong here - but yeah - thanks for your time and awesome feedback as always @stgraber !!

**Comment by stgraber** [comment]
Ah cool, and yes, what you're doing now is even better as LXD will automatically check the source image and cache it as needed.
