### ISSUE TITLE
Wrong owner of /proc and /sys

### ISSUE THREAD

**Issue by tomposmiko** [lxc/lxd#3607]
Kernel: Xenial HWE (4.8+)
LXD version: 2.0.10 or 2.16, does not matter.

In unprivileged container the owner of /proc/and /sys/ is nobody:nogroup.
After switching container to privileged it looks OK.

Only higher version of kernels seem to be affected like Xenial HWE 4.8 and 4.10 kernel. On a mchine with the default kernel version (4.4) the issue is not available.

**Comment by stgraber** [comment]
Hmm, I thought the same was true on any kernel. It's the normal way that the kernel has to indicate that it can't represent the owning user and group.

Note that while it's rendered as nobody/nogroup, it's actually -1/-1 which means unmapped. The real owner for both of those paths is real root.

I see the same on 4.4:
```
stgraber@shell01:~$ ls -lh /
total 106K
drwxr-xr-x    2 root   root    152 Jul 28 01:13 bin
drwxr-xr-x    2 root   root      2 Feb 27  2014 boot
drwxr-xr-x    4 root   root      4 Sep 10  2014 data
drwxr-xr-x   10 root   root    520 Jun 13 07:43 dev
drwxr-xr-x  116 root   root    219 Jul 28 01:13 etc
drwxr-xr-x    9 root   root      9 Jan 25  2017 home
drwxr-xr-x   15 root   root     17 Feb  9 05:13 lib
drwxr-xr-x    2 root   root      3 Jun 19 17:13 lib64
drwxr-xr-x    2 root   root      2 Mar 20  2014 media
drwxr-xr-x    2 root   root      2 Oct  9  2016 mnt
drwxr-xr-x    2 root   root      2 Mar 20  2014 opt
dr-xr-xr-x 1722 nobody nogroup   0 Jun 13 07:43 proc
drwx------    7 root   root     16 Jun 25 05:34 root
drwxr-xr-x   22 root   root    820 Jul 31 00:38 run
drwxr-xr-x    2 root   root    141 Jul 28 01:13 sbin
drwxr-xr-x    2 root   root      2 Apr 29 08:38 snap
drwxr-xr-x    2 root   root      2 Mar 20  2014 srv
dr-xr-xr-x   13 nobody nogroup   0 Jun 13 07:43 sys
drwxrwxrwt   16 root   root     23 Jul 31 03:10 tmp
drwxr-xr-x   10 root   root     10 Mar 20  2014 usr
drwxr-xr-x   13 root   root     15 Jul  6 05:03 var
stgraber@shell01:~$ uname -a
Linux shell01 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Anyway, this is expected behavior by the Linux kernel, so not a LXD issue. If specific tools validate that root:root owns those two kernel filesystems, the tools should be changed not to make that assumption.

**Comment by tomposmiko** [comment]
In this case I was the "tool" who thought it really owned by nobody.
Even if it's not really writable, it "seems" like it would be very dangerous issue.

IMO it should emulate the normal layout and avoid confusions.
