### ISSUE TITLE
Automatic rebuild of derived images

### ISSUE THREAD

**Issue by pylorak** [lxc/lxd#3647]
Say I have an LXD image that is built from another image not maintained by me. Something created by starting a new container from the 3rd-party image, making modifications to it then stopping and publishing it.

What is the recommended way / practice of keeping these "derived" images up to date if a new version of the base image gets published by the 3rd party? How do current tools facilitate this task?

**Comment by stgraber** [comment]
Since LXD uses clean Linux distribution images, the recommended way to update those and any derivative image is with the distribution tooling. So that'd be apt/dnf/zypper/apk/... whichever is used by the distro you're running in the container.

Alternatively you can script those changes and just re-generate the image regularly by creating a new container from the base image, apply your changes through "lxc exec" and then publish the result as a new image. This approach can be cleaner but also requires you to have fully scripted your modifications. 

Whereas just updating the existing image and re-publishing it will work even if you manually installed things in it.

**Comment by stgraber** [comment]
Closing as there's no actual LXD issue to fix here.

Best practices discussions tend to be a good fit for our discussion forum: https://discuss.linuxcontainers.org
A number of LXD users are hanging out over there and like discussing their workflows.
