### ISSUE TITLE
lxd zpool disappear

### ISSUE THREAD

**Issue by iyakimavetc** [lxc/lxd#3759]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu 16.04
driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-93-generic
  server: lxd
  server_pid: 2097
  server_version: "2.17"
  storage: zfs
  storage_version: 0.6.5.6-0ubuntu16

# Issue description
After reboot all containers STOPED and doesnt start
root@lxd0:/# lxc start aut
error: no such file or directory
in /var/log/lxd/lxd.log
lvl=eror msg="Failed to mount ZFS dataset \"lxd/containers/aut\" onto \"/var/lib/lxd/storage-pools/lxd/containers/aut\"." t=2017-09-03T17:46:06+0200

root@lxd0:/# zpool list
no pools available
root@lxd0:~# zfs list
no datasets available
dir /var/lib/lxd/disks was empty

When i try to create container
 root@lxd0:~# lxc launch ubuntu: test1
Creating test1
error: Failed container creation:
https://cloud-images.ubuntu.com/releases: Failed to run: zfs create -o mountpoint=none -p lxd/images/58f90cbf68927c3fc43e6ee1386446a04f3d8068c1a75a291339cb2be01dec08: cannot create 'lxd/images/58f90cbf68927c3fc43e6ee1386446a04f3d8068c1a75a291339cb2be01dec08': no such pool 'lxd'

I try to use lxd.db.back as lxd.db and its not work too

**Comment by stgraber** [comment]
Can you paste:
 - "find /var/lib/lxd/"
 - "sqlite3 /var/lib/lxd/lxd.db 'SELECT * FROM storage_pools;'"
 - "sqlite3 /var/lib/lxd/lxd.db 'SELECT * FROM storage_pools_config;'"
 - /etc/zfs/zpool.cache (it's a binary file)

**Comment by stgraber** [comment]
Also, the entire /var/log/lxd/lxd.log (and any rotated file /var/log/lxd/lxd.log.*) would be useful too.

**Comment by iyakimavetc** [comment]
[https://gist.github.com/iyakimavetc/1f38a55abf9ca784c2ec3e564127d89e](url) - find 
1|lxd|zfs| -  storage_pools
6|1|source|lxd
7|1|zfs.pool_name|lxd 
zpool.cache - https://yadi.sk/d/8GAOuWmy3MZqgS

**Comment by stgraber** [comment]
Do you have a file at /var/lib/lxd/zfs.img?

**Comment by iyakimavetc** [comment]
No

**Comment by iyakimavetc** [comment]
https://yadi.sk/i/vt4wJKXp3MZrMe - lxd.log
https://yadi.sk/d/YgLyK98D3MZrMb - lxd.log.1

**Comment by stgraber** [comment]
Based on those logs it looks like you upgraded to 2.17 successfully and your containers were functional, then you shutdown or rebooted the system and ZFS couldn't come back up because its backend file wasn't around anymore.

**Comment by stgraber** [comment]
Sadly those two log files don't give enough historical data to see more of what happened...

Can you paste:

 - sudo sqlite3 /var/lib/lxd/lxd.db "SELECT * FROM patches;"
 - sudo sqlite3 /var/lib/lxd/lxd.db "SELECT * FROM schema;"

**Comment by stgraber** [comment]
That should help fill a bit more of the timeline.

**Comment by iyakimavetc** [comment]
1)
1|invalid_profile_names|1494763860
2|leftover_profile_config|1494763860
3|network_permissions|1496761342
4|storage_api|1496761343
5|storage_api_v1|1496761343
6|storage_api_dir_cleanup|1496761343
7|storage_api_lvm_keys|1496761343
8|storage_api_keys|1496761343
9|storage_api_update_storage_configs|1496761343
10|storage_api_lxd_on_btrfs|1496761343
11|storage_api_lvm_detect_lv_size|1496761343
12|storage_api_insert_zfs_driver|1504455436
13|storage_zfs_noauto|1504455436
14|storage_zfs_volume_size|1504455436
15|network_dnsmasq_hosts|1504455436
2)
1|32|1494763860
2|33|1496761342
3|34|1496761342
4|35|1496761342
5|36|1504455436

**Comment by iyakimavetc** [comment]
Maybe I incorrectly put it. After the reboot, the containers did not turn on state stopped/ sorry for google translate

**Comment by brauner** [comment]
@stgraber, given from what he pasted:
```
1|lxd|zfs| - storage_pools
6|1|source|lxd
7|1|zfs.pool_name|lxd
```
His storage pools is not a loop-based pool so there'd be no disk file around. :)

**Comment by stgraber** [comment]
@brauner the zpool.cache file shows that it was backed by /var/lib/lxd/zfs.img

**Comment by brauner** [comment]
That doesn't make a lot of sense though given that the upgrade succeeded and the containers were functional. If the upgrade wouldn't have detected a `zfs.img` file it would still be in `/var/lib/lxd`. If the upgrade would have detected it it would have been either moved to `/var/lib/lxd/disks` or, if the rename or copy of the file failed, the upgrade would have failed and the file would still be in its old place. So something can't be right here.
If this was indeed a pool backed by `/var/lib/lxd/zfs.img` the likeliest explanation for this behavior is that the file was deleted before the upgrade, i.e. before the `patchStorageApi()` function was run. That would explain the wrong db entry for the storage pool. The error would go unnoticed until the reboot because of how files work in Linux.

**Comment by stgraber** [comment]
Yeah, the DB state is consistent with the fact that /var/lib/lxd/zfs.img had been gone before the upgrade to 2.8+

**Comment by stgraber** [comment]
Based on DB timestamps:
 - Initial install of LXD (between 2.2 and 2.7) on May 14th 2017
 - Upgraded LXD (to something between 2.11 to 2.14) on June 6th
 - Upgraded to LXD 2.17 on September 3rd

That last upgrade ran:

 - 12|storage_api_insert_zfs_driver|1504455436
 - 13|storage_zfs_noauto|1504455436
 - 14|storage_zfs_volume_size|1504455436
 - 15|network_dnsmasq_hosts|1504455436

None of which interact with the storage loop disks. The code that does was run on the 6th of June.

How long was that system online before it got rebooted today?

**Comment by iyakimavetc** [comment]
Uptime ~100d

**Comment by stgraber** [comment]
Hmm, then it's going to be pretty much impossible to figure out what happened...

What we know based on all you provided is that your system was already broken on June 6th, it just wasn't apparent because you didn't reboot your system then.

Because of how files work on a unix system, you can have a ZFS pool be online, backed by a backing file which has been removed from disk. Everything will keep working perfectly fine. Until you reboot and the file is gone forever...

The /var/lib/lxd/zfs.img file which was used to back your LXD daemon went away at some point between the 14th of May and the 6th of June.

**Comment by iyakimavetc** [comment]
Can I say goodbye to my data?

**Comment by iyakimavetc** [comment]
https://github.com/lxc/lxd/issues/3386 mya be file went away in this time

**Comment by stgraber** [comment]
That particular DB fix wouldn't have caused LXD to remove the .img file.
It could be that it's whatever led to the broken database back then which did though... Since the problem would only appear after a system reboot, it's very hard to tell.

You may want to do this for good measure:

    sudo find / -name zfs.img
    sudo find / -name lxd.img

Just to see if maybe those files got moved somewhere else on the system. That's a long shot though as there's certainly nothing in LXD which would cause those to get relocated.

If that doesn't find anything, then depending on how much you used your system since that last reboot, there may be hope for one of the undeleting tools to work. But that depends on what filesystem's backing /var/lib/lxd. For ext4, the "extundelete" tool has been useful to me in the past.

**Comment by stgraber** [comment]
Unfortunately undeleting file gets harder and harder as time passes since the space may already have been reclaimed for something else. It tends to work okay if you realize the problem immediately and re-mount the underlying storage read-only within seconds but in your case we're already talking days, so you'd need to be very very lucky for ext4 not to have written anything over the previously used space.

**Comment by ingobaab** [comment]
https://discuss.linuxcontainers.org/t/zfs-mount-point-disappeared-but-lxc-working/1475
