### ISSUE TITLE
 lxc delete aborts if btrfs subvolume is already absent

### ISSUE THREAD

**Issue by treba123** [lxc/lxd#3775]
Ubuntu 16.04, lxc version 2.17

###

When using `lxc delete` on a container residing in a btrfs storage and the corresponding subvolume does not exist anymore, it failes with the message:

`error: Failed to run: btrfs subvolume delete [...]: ERROR: cannot access subvolume: [...]: No such file or directory `

IMO, lxc should check if the subvolume is already absent and remove the container from its database, atleast with the `--force` option set. Otherwise it could promt the user to decide.

# Steps to reproduce

1. create a lxc storage with btrfs source: `lxc storage create test-storage btrfs source=/mnt/btrfs`
2. create a container in it: `lxc launch ubuntu:16.04 test-container -s test-storage`
3. stop the container: `lxc stop test-container`
4. manually remove the subvolume: `btrfs subvolume delete /mnt/btrfs/containers/test-container`
5. try to remove it from lxc: `lxc delete test-container --force`

Expected behaviour:
lxc deletes the container from its db

Actual behavior:
lxc aborts with the error
`error: Failed to run: btrfs subvolume delete [...]: ERROR: cannot access subvolume: [...]: No such file or directory `

**Comment by brauner** [comment]
So, this is something I thought about as well but if we do something like this we'd likely need to add a new flag since `--force` only mentions running containers and it would be surprising to users if that also wiped the container from the db even if the storage is gone. Maybe they just didn't mount it or forgot to plugin the relevant disk or something. So we have to be careful here. I agree that there's definitely a case to be made for wiping from the db. @stgraber?

**Comment by stgraber** [comment]
@brauner I'd say that if the pool is properly mounted and the thing no longer exists, we should just silently move on.

I ran into that on systems that ran out of disk space, where an image is half-created and I can't remove it unless I first create an empty dataset/subvolume...

**Comment by treba123** [comment]
> I'd say that if the pool is properly mounted and the thing no longer exists, we should just silently move on.
I'd support that and suggest to add two new flags:
 - delete whether storage is mounted or not, something like `ignore-storage-absent` or `ignore-errors`
 - delete from database only. Since containers can get imported, there're cases when people actually don't want to delete the container from storage. Something like `retain-on-storage`. Not that important, though :)

**Comment by stgraber** [comment]
Flags are pretty expensive to add since we're doing everything over a backwards compatible REST API.

So I prefer to just make sure our code does the right thing rather than have a bunch of confusing flags that users will randomly pass in the hope that it will fix things for them.

For the case where you want to re-import a container, "lxd import" already lets you import over an existing container, so there's no need for a way of deleting things from database without deleting things from disk. Allowing such actions would just cause potential errors later (if you accidentally re-use the name for example) and would make our storage code even harder to maintain than it is today.

**Comment by treba123** [comment]
thx @brauner !
