### ISSUE TITLE
Changing volume.block.filesystem causes container creation failures

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#3811]
When changing volume.block.filesystem on a pool with existing images, then creating a container from one of those existing image, you'll get the wrong filesystem and will most likely hit an error as LXD tries to run fs-specific code for the wrong filesystem.

Instead we should add code to the LVM and Ceph backends so that when doing CreateFromImage, we check whether the existing volume's filesystem (block.filesystem) matches the one of the new one, if they don't, then the existing volume should be deleted and a new image import be done.

**Comment by brauner** [comment]
A few more notes here from the irc discussion. The filesystem type can be gathered from the `block.filesystem` property that gets set on creation time for every storage volume that uses a block device based driver. This means that the storage volume's db entry should be retrieved if not already initialized directly via a call to the storage initializers. The correct functions to retrieve storage volume can be found in `db/storage_volumes.go`. The best candidate is `db.StoragePoolVolumeTypeGet()` which should be pretty self-explanatory. The storage volume's config that can be accessed from the return value aforementioned function will contain the filesystem, e.g. `volume.Config["block.filesystem"]`.

Furthermore, changing the default filesystem of a storage pool that uses sparse storage entities for lxd objects should replace the old image with a new image using the new filesystem so that uses still get the benefits of sparse copies.
In case non-sparse pools are used we can simply create a full copy of the already existing image without removing it.
