### ISSUE TITLE
memory usage from lxd api dont show real ram consumed by processes of the container

### ISSUE THREAD

**Issue by alex-left** [lxc/lxd#3825]
# Required information
```
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-79-generic
  server: lxd
  server_pid: 7692
  server_version: "2.17"
  storage: dir
  storage_version: "1"

```
 * Distribution: Ubuntu 14.04
OR
```
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.8.0-58-generic
  server: lxd
  server_pid: 2109
  server_version: "2.15"
  storage: dir
  storage_version: "1"
```
 * Distribution: Ubuntu 16.04

# Issue description

into container you can watch the ram of a process through "top" o "ps". The processes into container consumes more ram than the amount of the output "lxc info [container] or don't match"
for example, I have a container with an elasticsearch process with using > 1G of ram: 
```
elastic+ 10098  0.0  3.9 6773524 1306208 ?     Ssl  16:08   0:34 /usr/bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+AlwaysPreTouch -server -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -Djdk.io.permissionsUseCanonicalPath=true -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Dlog4j.skipJansi=true -XX:+HeapDumpOnOutOfMemoryError -Des.path.home=/usr/share/elasticsearch -cp /usr/share/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch -p /var/run/elasticsearch/elasticsearch.pid --quiet -Edefault.path.logs=/var/log/elasticsearch -Edefault.path.data=/var/lib/elasticsearch -Edefault.path.conf=/etc/elasticsearch
```
but the lxd command shows me...
```
Resources:
  Processes: 299
  CPU usage:
    CPU usage (in seconds): 41130
  Memory usage:
    Memory (current): 558.32MB
    Memory (peak): 3.54GB
```

# Steps to reproduce
1. use for example stress to fill the ram
```
stress --vm-bytes 1000000k --vm-keep -m 1 &
```
2. compare the ram in container: 
```sh
p=0; for n in $(ps aux | awk '{print $6}'); do p=$(( $n+$p )); done echo $p;
```
with the value of "lxc info [container]

**Comment by stgraber** [comment]
The value that gets reported by LXD is what the kernel's memory cgroup is counting as memory use for your container. Running the same thing here on a 4.13 kernel, I'm seeing something that looks closer to the expected value:

```
  Memory usage:
    Memory (current): 1.06GB
    Memory (peak): 1.06GB
```

Anyway, I'm going to close this issue because there's really not much LXD can do about this. We read and return the memory.usage_in_bytes value for the container as it's read directly from the kernel's memory cgroup. If memory accounting is somehow wrong at that level, it's a kernel issue.

I did also try on an up to date Ubuntu 16.04 machine with the 4.4 kernel and the reported memory looked right (was at around 1GB, bumped to 2GB while running the test).

```
  Memory usage:
    Memory (current): 1.03GB
    Memory (peak): 2.00GB
```

One thing you can look at is /sys/fs/cgroup/memory/[container]/memory.usage_in_bytes this should match what LXD is reporting back to you.

**Comment by alex-left** [comment]
At this level, I can't know which could be the kernel's issue, if it exists. I don't know how works the kernel & lxd, But, returning to my "elasticsearch" example, i can see that the value of the memory usage inside the service is correct: 

```
root@ns324631:/sys/fs/cgroup/memory/lxc/mycontainer/system.slice/elasticsearch.service# cat memory.usage_in_bytes
1308020736
root@ns324631:/sys/fs/cgroup/memory/lxc/mycontainer# cat memory.usage_in_bytes 
366342144

```
So maybe the value is correct but don't show their children, or something like, or maybe that is not the correct place to get the total memory

**Comment by stgraber** [comment]
What's the value of /sys/fs/cgroup/memory/memory.use_hierarchy on your system?

**Comment by stgraber** [comment]
It should be "1" and that should then ensure that memory consumption in child cgroups count towards the limit of their parent. The output above seems to show that this is somehow off.

**Comment by alex-left** [comment]
indeed, in my server is "0", do you know which parameter of sysctl manage this value or activate it at startup?
I can not do an "echo" in the file because it is busy, even with the service shutdown
Should not the lxd installer activate this parameter?
thanks!

**Comment by stgraber** [comment]
This needs to be set to 1 before any cgroup is created, so it's usually the job of the init system.

I know that LXC used to have logic to attempt to do that, but that was before init systems started configuring cgroups, at which point it became futile since lxc would never be the first one to setup the controller.
