### ISSUE TITLE
lxc publish does not set hostname in /etc/hosts

### ISSUE THREAD

**Issue by ddag** [lxc/lxd#3836]
lxc publish properly sets the hostname in /etc/hostname, but it there is no corresponding set for /etc/hosts. i.e. 127.0.0.1 `<published name>`. As a result, sudo calls fail with "sudo: unable to resolve host `<published name>`".

**Comment by stgraber** [comment]
Hi,

"lxc publish" itself doesn't actually do any change to the container's filesystem. It's something LXD tries to stay far away from as it's near impossible to get right.

Instead what's doing those changes for you are template files which are part of your generated images.

On LXD 2.16 or higher, you can interact with those through our API using:

 - lxc config metadata show
 - lxc config metadata edit
 - lxc config template list
 - lxc config template show
 - lxc config template create
 - lxc config template edit
 - lxc config template delete

Some more details on those templates can be found here:
https://github.com/lxc/lxd/blob/master//doc/image-handling.md

You could add a template for your /etc/hosts file, or if your container uses cloud-init, then wipe /var/lib/cloud so that cloud-init gets run again when creating a container from the image.

It really all depends on what's in your container and what you want to see changed when someone creates a new container from it.
