### ISSUE TITLE
logging iptables inside container?

### ISSUE THREAD

**Issue by niksfirefly** [lxc/lxd#3838]
What is the proper way to log iptables inside LXC containers?

Rsyslog dont have access to kernel logging
imklog: cannot open kernel log (/proc/kmsg): Permission denied.

**Comment by stgraber** [comment]
Unprivileged containers don't have a /dev/kmsg device and access to /proc/kmsg is blocked by the kernel, but the syslog() syscall usually still works and is what "dmesg" uses.

I don't know enough about how rsyslog works to know whether there's a way to hook it up to the syslog() syscall rather than accessing /proc/kmsg.

I'm closing this issue since the permission issue isn't of LXD's doing, it comes straight from the Linux kernel and appears to be a restriction in place as part of the user namespace.

**Comment by niksfirefly** [comment]
ok i solved it with ulogd2

**Comment by manswizzle** [comment]
I recently ran into this same quandary.  Thanks for the ulogd2 solution.  For anyone else looking for a solution, there was a good post showing the use of ulogd2 and nflog to accomplish the same task here:

[https://lxadm.com/Iptables:_LOG_target_not_working_in_LXD_containers](url)

**Comment by drescherjm** [comment]
I just ran into this trying to get firewalld to log inside a lxc container. The link in the last comment is no longer existing but the Wayback Machine has a copy. I had a little difficulty getting ulogd2 installed in Rocky but managed and the logging of dropped packets worked with a rich rule in the drop zone "rule family="ipv4" source NOT address="192.168.1.0/24" nflog prefix="DROP" drop"
