### ISSUE TITLE
Unable to change /proc/sys/kernel/sem in container 

### ISSUE THREAD

**Issue by sehari24jam** [lxc/lxd#3896]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 16.04.3
 * The output of "lxc info" or if that fails:
   config:
     core.https_address: '[::]:8443'
     core.trust_password: true
   api_extensions:
   - storage_zfs_remove_snapshots
   - container_host_shutdown_timeout
   - container_syscall_filtering
   - auth_pki
   - container_last_used_at
   - etag
   - patch
   - usb_devices
   - https_allowed_credentials
   - image_compression_algorithm
   - directory_manipulation
   - container_cpu_time
   - storage_zfs_use_refquota
   - storage_lvm_mount_options
   - network
   - profile_usedby
   - container_push
   - container_exec_recording
   - certificate_update
   - container_exec_signal_handling
   - gpu_devices
   - container_image_properties
   - migration_progress
   - id_map
   - network_firewall_filtering
   - network_routes
   - storage
   - file_delete
   - file_append
   - network_dhcp_expiry
   - storage_lvm_vg_rename
   - storage_lvm_thinpool_rename
   - network_vlan
   - image_create_aliases
   - container_stateless_copy
   - container_only_migration
   - storage_zfs_clone_copy
   - unix_device_rename
   - storage_lvm_use_thinpool
   - storage_rsync_bwlimit
   - network_vxlan_interface
   - storage_btrfs_mount_options
   - entity_description
   - image_force_refresh
   - storage_lvm_lv_resizing
   - id_map_base
   - file_symlinks
   - container_push_target
   - network_vlan_physical
   - storage_images_delete
   - container_edit_metadata
   - container_snapshot_stateful_migration
   - storage_driver_ceph
   - storage_ceph_user_name
   - resource_limits
   - storage_volatile_initial_source
   - storage_ceph_force_osd_reuse
   - storage_block_filesystem_btrfs
   api_status: stable
   api_version: "1.0"
   auth: trusted
   public: false
   environment:
     architectures:
     - x86_64
     - i686
     driver: lxc
     driver_version: 2.1.0
     kernel: Linux
     kernel_architecture: x86_64
     kernel_version: 4.10.0-35-generic
     server: lxd
     server_pid: 28328
     server_version: "2.18"
     storage: zfs | btrfs
     storage_version: 0.6.5.9-2 | 4.4

# Issue description

Unable to change container's kernel.sem.
Even modifying kernel.sem in host, will not propagated into container.
Value in container looks like consistent set to  `32000  1024000000  500  32000`.

# Steps to reproduce

 1. in host `sysctl -w kernel.sem='250 64000 100 256'"`

 2. `lxc exec container -- sysctl  kernel.sem`
     output: `kernel.sem = 32000  1024000000  500  32000`

 3. `lxc exec container -- sysctl -w kernel.sem='250 64000 100 256`
     output: `sysctl: permission denied on key 'kernel.sem'`

**Expected: container's kernel.sem adhering user setup**

**Comment by stgraber** [comment]
The fact that modifying it on the host doesn't propagate to the container shows that this file is tied to the container's namespaces, which is a very good start.

Unfortunately it looks like the access control implemented by the kernel requires real root to change the files... I don't know if this is intentional (because of security concerns) or an oversight when that kernel code was changed to be namespace aware. In either case, there's unfortunately nothing that LXD itself can do about it since the error is coming straight from the kernel.

Your best bet is to file a kernel bug for your Linux distribution so that someone can go take a look at the kernel code and see whether the access control is behaving this way on purpose or not.
