### ISSUE TITLE
howto load/use kernel module nf_conntrack_ftp in unprivileged container?

### ISSUE THREAD

**Issue by niksfirefly** [lxc/lxd#4006]
Is there a way to use nf_conntrack_ftp in unprivileged container?
Module is loaded on Host
also 
linux.kernel_modules: nf_conntrack_ftp
set in container
but still i get errors like that
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.10.0-38-generic/modules.dep.bin'#012modprobe: FATAL: Module nf_conntrack_ftp
 not found in directory /lib/modules/4.10.0-38-generic

**Comment by stgraber** [comment]
What tool is giving you that error?

Do you see /sys/module/nf_conntrack_ftp in the container?

**Comment by niksfirefly** [comment]
I use firewalld on ubuntu 16.04
Yes I see  /sys/module/nf_conntrack_ftp in container

According to these docs:
https://home.regit.org/netfilter-en/secure-use-of-helpers/
http://www.firewalld.org/2016/10/automatic-helper-assignment
with kernel 4.9 and newer - conntrack helpers are now disabled by default.

I can see nf_conntrack_ftp in lsmod on container
when i enable module with file in /etc/modules-load.d on host.
So for now i tried enable helper
sysctl net.netfilter.nf_conntrack_helper=1
but on container after restart is still
net.netfilter.nf_conntrack_helper = 0
so i got errors in firewalld 
WARNING: public: INVALID_HELPER: 'nf_conntrack_ftp' is not available

**Comment by niksfirefly** [comment]
Additional errors on unprivileged container from firewalld
ERROR: Failed to write to file "/proc/sys/net/netfilter/nf_conntrack_helper"
WARNING: Failed to get and parse nf_conntrack_helper setting

File does not exist /proc/sys/net/netfilter/nf_conntrack_helper

**Comment by stgraber** [comment]
What kernel are you using with 16.04?

I just tried on my system here with the Ubuntu 4.13 kernel and in unprivileged containers the /proc/sys/net/netfilter/nf_conntrack_helper doesn't exist. It does exist on the host and once I set it to 1 on the host, I can use an iptables rule which uses the ftp helper:

```
iptables -A PREROUTING -t raw -p tcp --dport 21 -j CT --helper ftp
```

If I run a privileged container, then I do see the /proc/sys/net/netfilter/nf_conntrack_helper file in the container and I can flip it to 1 for just that one container.

**Comment by niksfirefly** [comment]
I tested it on 2 hosts
ubuntu 16.04 - 4.4.0-93-generic
ubuntu 17.04 - 4.10.0-38-generic

I think your observations are the same as mine so firewalld helpers are not working
due to bad design. Even with privileged containers.

> If I run a privileged container, then I do see the /proc/sys/net/netfilter/nf_conntrack_helper file in the container and I can flip it to 1 for just that one container.

I wonder how do you set
/proc/sys/net/netfilter/nf_conntrack_helper 1
only for one container? 
I must always can change that value from 0 to 1 it is not inherited from host.

**Comment by stgraber** [comment]
Well, you could put a wrapper script for modinfo in /usr/local/bin I guess :)

But the real fix would be to file a bug against firewalld to have it check through /sys/module/NAME rather than attempt to call modinfo. That'd be faster, would work with built-in modules too and remove one of their dependencies.

**Comment by stgraber** [comment]
Closing this issue since there's nothing actionable for LXD here, but if you do end up reporting a bug against firewalld, drop the URL here so that others can find it.

An alternative would be to setup a read-only bind-mount of /lib/modules from your host, that should work so long as the container architecture is the same as the host but would end up exposing information that you may not want an untrusted container to see and should really be unneeded in this case...

lxc config device add CONTAINER modules disk source=/lib/modules path=/lib/modules readonly=true

**Comment by niksfirefly** [comment]
https://github.com/firewalld/firewalld/issues/264
