### ISSUE TITLE
Use --reflink for container copies on btrfs

### ISSUE THREAD

**Issue by yokem55** [lxc/lxd#4011]
It would be nice when copying containers on a btrfs storage pool to optionally use reflink to make the copy using copy on write to reduce the space consumed and speed up the copy. I'm pretty sure that the current behaviour does not do this as deduping the filesystem later results in substantial space savings.

**Comment by stgraber** [comment]
When you run "lxc copy" LXD does a btrfs subvolume snapshot for you which does get you the same benefits as a reflink copy.

**Comment by stgraber** [comment]
That is, when you copy a container, the actual on-disk space used by the new container will be a few KBs (for metadata). Once that container is used it will slowly diverge from the container it was copied from, even more so if that parent container is also running and writing stuff to disk.

In a scenario where those two containers are both running and are both receiving package updates, then they will diverge, causing an increased disk usage and then effectively converge again as the same updates are installed in both containers resulting in the same files being there again.

But since btrfs doesn't have a background hashing and dedup capability (like zfs does), the fact that the files are identical again doesn't get you any reduction in disk usage until you manually run something which scans the files, hashes them and for identical files, does a reflink copy on top to tell the filesystem about the files being identical.
