### ISSUE TITLE
Create operation event not relayed by websocket endpoint

### ISSUE THREAD

**Issue by geodb27** [lxc/lxd#4032]
Github issues are used for bug reports. For support questions, please use [our forum](https://discuss.linuxcontainers.org).

Please fill the template below as it will greatly help us track down your issue and reproduce it on our side.  
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: ubuntu 
 * Distribution version: LTS 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: Linux ubuntu-lts64 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
   * LXC version: 2.19
   * LXD version: 2.19
   * Storage backend in use: DIR

# Issue description

I'm currently working on a javascript REST API client and found a strange behavior : 
On the command line, if you issue : 
$ lxc start [CONTAINER]
in the log file (eg. /var/log/lxd/lxd.log) one can see this written : 
{
"type": "async",
"status": "Operation created",
"status_code": 100,
"operation": "/1.0/operations/831faaa4-4ac0-4de2-9ae5-b5e679d3e2a0",
"error_code": 0,
"error": "" (...) }

However, on the websocket, all we see is the later states : 

when the operation is pending (status 105)
when the operation is running (status 103) 
and then when the operation is completed (status 200).

**Comment by stgraber** [comment]
That's because that "operation created" you're seeing in the log is the raw http reply sent to the client.
This is a logging type message, not an operation status update, so it'd only show if you were looking for type=logging on the events API.

If you monitor /1.0/events?type=operation, then just add to your operations list any operation that you don't already have a status for and remove any operation which reaches a final state, that's what the LXD command line tool does when tracking operations.

**Comment by stgraber** [comment]
When an operation is created in LXD, it's in Pending state, that results in an operation event being sent, when it starts it then gets into Running state and when it ends it gets into Success or Failure state.

I've confirmed with start/stop that I do get all those events properly on /1.0/events so things appear to behave as expected here.
