### ISSUE TITLE
Is there a way to mount /var/lib/lxd/storage-pools/default/containers/sample_container1/rootfs from a remote directory>

### ISSUE THREAD

**Issue by hinkalit** [lxc/lxd#4034]
I want to keep the storage on some remote machine for the container I am using. I can bind my home directory using 
`lxc config device add privilegedContainerName shareName disk source=/home/$USER path=/home/ubuntu`
But this allows to mount only the one of the directories (in this case home directory). I want to bind the whole '/' directory. So is there a way to mount rootfs of a container
`/var/lib/lxd/storage-pools/default/containers/sample_container1/rootfs 
`
from a remote directory?

**Comment by stgraber** [comment]
Not in a supported way, no. Allowing this would be extremely difficult to do while keeping snapshots, file transfers, container migration and container publishing working properly.

That being said, you can workaround this by either using a storage pool with the "dir" backend and manually mounting the container paths on your host before starting the container. Or by directly setting "lxc.rootfs" through the "raw.lxc" config option.
Both of those approach effectively result in a LXD container that we'll be unable to support and that you'll  have to be pretty careful about exactly what API calls you run against (effectively avoiding anything that deals with snapshot, transfers, publish or files).

**Comment by stgraber** [comment]
If you're looking at storing some containers over a remote nfs/cifs type storage, your best bet is probably something along the lines of:

```
mkdir /srv/nfs-lxd
mount -t nfs ... /srv/nfs/lxd
lxc storage create nfs dir source=/srv/nfs/lxd
lxc launch -s nfs ubuntu:16.04 my-container
```

This "should" work so long as your remote filesystem is POSIX compliant. It'd use the "dir" backend of LXD so snapshots and migration will be racy/slow, but otherwise the rest should be fine.

(Obviously rather than manually mounting your nfs/cifs you should use your host's /etc/fstab for this).

**Comment by stgraber** [comment]
Closing as there's nothing actionable for LXD itself here.
