### ISSUE TITLE
chroot showing more CPUS and RAM than allowed in lxd container

### ISSUE THREAD

**Issue by voxsoftware** [lxc/lxd#4068]
My root server: 
Ubuntu 16.04 LTS 3  64 bits 

I have a server with 4 cores (8 threads) and 32GB Ram. I have installed lxd, and with lxd create a container. I limited the container to use 2 cores and 7GB Ram. When I enter to container and open htop shows the correct info of CPUs and Memory, but when I made chroot on folder, and open htop inside the chroot, shows me 8 cores and 32GB Ram. What I can do?

NOTE. My main worry it's that with chroot, can use more resources than allowed in the container and affect my other containers. It's only a visualization error? or are really using all CPUs and Memory inside chroot

**Comment by stgraber** [comment]
It's simply that your chroot doesn't use the lxcfs override files in /proc so you're seeing the host resources rather than the cgroup-aware one. Processes inside your container cannot bypass the limit, they can just end up in a situation where they can't see the limit.

Rather than mount a clean copy of /proc inside your chroot, you could rbind /proc onto /proc in the chroot, that should bring the lxcfs overrides along and get you the same view of used resources.
