### ISSUE TITLE
Infiniband devices without a name get called "ethX" rather than "ibX"

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#4089]
Title says it all, this happens if you set parent=ib0 nictype=physical and then start the container, you end up with eth1 rather than ib0.

**Comment by brauner** [comment]
On Dec 9, 2017 00:21, "Stéphane Graber" <notifications@github.com> wrote:

Title says it all, this happens if you set parent=ib0 nictype=physical and
then start the container, you end up with eth1 rather than ib0


On the host when you unplug or in the container?

**Comment by stgraber** [comment]
In the container

**Comment by stgraber** [comment]
I had two containers that had infiniband added to them and it showed up as eth1 in both of them rather than ib0 as I'd have expected since I didn't specify a name myself.

**Comment by brauner** [comment]
On Dec 9, 2017 00:40, "Stéphane Graber" <notifications@github.com> wrote:

I had two containers that had infiniband added to them and it showed up as
eth1 in both of them rather than ib0 as I'd have expected since I didn't
specify a name myself.

Uhm, isn't that what we do for any physically passed network device
currently?


—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/lxc/lxd/issues/4089#issuecomment-350399784>, or mute
the thread

**Comment by stgraber** [comment]
Yes and that's wrong. It's fine for "nic" type to have the devices called ethX, it's not fine for "infiniband" type to have the devices called "ethX" they should be called "ibX".

**Comment by brauner** [comment]
On Dec 9, 2017 00:47, "Stéphane Graber" <notifications@github.com> wrote:

Yes and that's wrong. It's fine for "nic" type to have the devices called
ethX, it's not fine for "infiniband" type to have the devices called "ethX"
they should be called "ibX".


I mean I'm fine with this and happy to send a trivial fix you could send
too ;) But just for basic understanding: why?


—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/lxc/lxd/issues/4089#issuecomment-350400773>, or mute
the thread

**Comment by stgraber** [comment]
Because pretty much all software that uses infiniband actively looks for ib* interfaces :)

**Comment by stgraber** [comment]
and infiniband isn't ethernet so eth* isn't an appropriate name for those devices.
