### ISSUE TITLE
Display storage usage in human readable form.

### ISSUE THREAD

**Issue by 1koval** [lxc/lxd#4119]
It would be nice to present lxc storage usage in human readable form.
For example "lxc info" provides GB and MB:
> user@ubuntu-stack:~$ /snap/bin/lxc info juju-7ec976-0
> ...
>  Memory usage:
>   Memory (current): 991.43MB
>   Memory (peak): 1.04GB
>  Network usage:
>    eth0:
>      Bytes received: 123.48MB
>      Bytes sent: 1.07MB
>      Packets received: 29307
>      Packets sent: 12837
> ...

"lxc torage show" provides row bytes:
> user@ubuntu-stack:~$ /snap/bin/lxc storage show default --resources
> space:
>  used: 9549971456
>  total: 107374182400

Of cause, you can covert 107374182400 bytes in GB manually, but having it directly on a screen can make it more human-friendly.

Some challenges (discussion points):
 - if special flag e.g. " --human-readable" is needed or not (this can be default behavior similar to "info" command). 
- GB v/s GiB  (if any confusion exist; at least, it should be consistent across lxc commands; e.g "lxc info" and and "storage show" to produce the same\comparable units). 

# Required information
 * Distribution: Ubuntu 16.04.3 TLS
 * Distribution version: snap
   * Kernel version: 4.4.0-104-generic
   * LXC version: 2.21
   * LXD version: 2.21
   * Storage backend in use: brtfs

# Steps to reproduce
 1. Configure default lxd storage with "lxd init".
 2. run "lxd lxc storage show default --resources"
 3. Observe space 'used' and 'total'.

**Comment by stgraber** [comment]
The right way to do this would be to introduce a "info" command, "show" always gets you the raw API object in yaml format, so having it modify the type and rendering of various fields doesn't seem appropriate.

**Comment by dnegreira** [comment]
@stgraber I am interested in picking this one.
What do you think that it should be shown on the `lxc storage info <storage_pool>` command?
 From this ticket I see that we should display the space used / total in human readable format, shall it also display part of the `lxc storage show` commands, if so, which ones?

**Comment by stgraber** [comment]
@dnegreira would probably make sense to see:
 - Name
 - Driver
 - Size
 - Description
 - List of volumes per type (container, images and custom)

That should be reasonable for info I think.

**Comment by dnegreira** [comment]
@brauner @stgraber ,
Question 1: now that I am able to output all the data, I would like to know what shall be the way to output it?
I can think of several ways:
- Same way as `lxc list` for the container with `tablewriter`, also having the possibility to select the columns and output type (json, csv, (yaml?)). In my opinion this is the most useful way of outputing since it gives the users the possibility to gather and see the info easily from the CLI, although it is gonna be a bit more coding to have it done.
- Same way as `lxc info`.
- Maybe YAML only?

Question 2: I will also add a trigger to show free/used space in bytes instead of human-readable, I would like to have this possibility, you guys ok with that? (or the other way round, add trigger to human-readable form if you prefer)

Question 3: With this new method I think we can either deprecate doStoragePoolShow() or maybe move all of this functionality to doStoragePoolShow(), although this might break things for the users if they make use of that command, they need to update/adapt to the new form.

Let me know your thoughts  :)

**Comment by stgraber** [comment]
For 3.0, I'd like us to get:
 - Common code to handle all of our `list` commands (lxc list, lxc remote list, lxc image list, lxc storage list, lxc storage volume list, lxc profile list, lxc network list, lxc config device list, lxc profile device list) with the same supported output modes (table, csv, json and yaml).
 - Common code to handle all of our `info` commands (lxc info, lxc image info, lxc storage info, possibly more at some point) with different output modes (yaml and json).

So for the new `lxc storage info`, I'd say go with yaml for now, we'll standardize on that.
The difference between `show` and `info` is that `show` is the raw API struct, suitable for edit and feeding back to `edit` whereas `info` is a more user friendly view of it, possibly with added info from sub-endpoints which is nice to look at but doesn't have a one to one mapping with the API.
