### ISSUE TITLE
Docs on CPU limits could use some elaboration w/regards to time slicing

### ISSUE THREAD

**Issue by Kramerican** [lxc/lxd#4122]
I have been messing around with CPU limiting and doing a number of tests, and without knowing how this is implemented in LXD started with some assumptions from reading the docs and Stéphane's (now, slightly outdated) blog posts.

The docs are very unclear on how hard slices of CPU time works. That is, when you do the following in a profile:

`limits.cpu.allowance: 50ms/200ms`

This would logically mean that you give the container one quarter - 25% - of CPU time right? Well, yes and no. It turns out that you are then giving the container 25% of real time on a single core, not total CPU time. 

I ran my tests on a Intel® Xeon® E5-1650 v3 CPU which has 12 logical processors. I measured my CPU use in seconds every 30 minutes. I ran a bitcoin address vanity generator, just to run something that maxed out the CPU for long periods of time. For those of us who are too lazy to do math, 30 minutes equals 1800 seconds. From my tests I saw quickly a pattern emerge:

```
50ms/200ms - About 451 CPU seconds / 30 min, or about ~5% use across all cores
200ms/200ms - About 1802 CPU seconds / 30 min, or about ~10% use across all cores
```

So giving a container a slice of CPU time in effect means that you are giving it x seconds off a single processor. Meaning, if I had only had a single logical core this would indeed have equaled 100% CPU time of 1800 seconds pr. 30 min.

So, let's say I have 15 containers on this systems, and I want to give everybody an equal share of CPU time up to the actual maximum. This would then be something like:

```
12 (cores) / 15 (containers) = 0.8 (cores pr. container)
0.8 (core share) x 200ms (total time pr. core) = 160ms (container cpu time)
```

Which then gets you to the "correct" slice / setting of:

`160ms/200ms`

This should then, in theory give my container the correct limit of ~6.6% max. CPU use across all cores.

**Questions:**

- Have I completely misunderstood some fundamentals here, and you are currently snickering at my idiocy? (I would not be surprised) In which case, please enlighten me!

- Is this intended, or unavoidable behavior? I was expecting 100% use across all logical processors when specifying 200ms/200ms from reading the docs, as many others surely would. If this is just how it is, it should really be pointed out in the docs.

Furthermore, as this setting is really just an expression of a percentage of real-time, maybe it would make sense to change how this setting is described in the docs.

- This makes it a bit weird/difficult to try and figure out what slice to give a container, on a multicore system, with x containers. The maths are, well, not apparent until you do these real-life tests and give it a good think.

- It seems it is possible to combine with CPU pinning, i.e. doing something like:

```
  limits.cpu: "1"
  limits.cpu.allowance: 200ms/200ms
```

Which then gets you ... Some CPU use. Again, logically here I would assume this should result in 100% use on this single CPU - but due to this funky way CPU time is applied on a multicore system, you actually get less than that. 

I'm not complaining actually, this is actually perfect for my current use-case, but it is really not apparent what this config actually does until you spend quite a bit of time experimenting with it.

Oh, I was doing all this on Ubuntu Xenial and LXD 2.20

**Comment by Kramerican** [comment]
**Followup question**

This got me thinking about the percentage setting. You write in the docs that you can specify a percentage which then gets applied if the system is under load. If the system isn't under load, the container can use as much CPU as it wants.

That's all fine and dandy, however, does this percentage setting mean percentage CPU across all cores? To be exact, I'm talking about this:

```
config:
  limits.cpu.allowance: 50%
```

What would then happen if I had this high setting across many containers? How would the load distribute? This is a bit difficult to test, but here's a hypothetical:

15 containers on my 12 logical core system. All have allowance set to 50%. One (or two) of these containers start doing something intensive and want 100% CPU time - let's say, they got hacked and some numbnut placed a bitcoin miner on them.

What would happen then? 

I am guessing that the standard answer is probably: _Well that really depends on what the scheduler decides to do, and that can be hard to predict._

Hmm - well, for me as a user, it's a bit cumbersome that I have to do lots of trial and error here. It would be great to get some more clarity here :) Could you at least enlighten me as to what should happen _in theory?_

PS: I am assuming that I should, in real life, set the allowance to an equal percentage share, so in this hypothetical they should really have allowance set to ~7% - which should guarantee that no container uses more than their fair share if the system is under load. But ... That's assuming that percentage is actually total CPU time, and not just for a single core, as is with time slicing. I could worry that this limit actually using time slicing under the hood... Maybe

In real life it is rare that all containers on the system really want a lot of CPU time simultaneously - which makes this setting so attractive as it promises only to set limits if the system is under load - but I must admit it is hard for me to quite grasp how this will work in real life, and what a sane setting here should look like for my example given.

**Comment by stgraber** [comment]
Well, all of this gets pretty complicated pretty quickly as it's really all about how the Linux scheduler works and what knobs it exposes. Different scheduler settings may result in different behaviors.

The cpu.allowance when specified in ms/ms is driving the kernel's cfs_quota, you can find some documentation here: https://www.kernel.org/doc/Documentation/scheduler/sched-bwc.txt

That does indeed confirm that 50ms/50ms means 50ms of 1 CPU over a 50ms period, so if you wanted two CPUs, you'd want 100ms/50ms.

The percentage value works very differently, it's instead a score based mechanism where a container that has twice the score of another will get twice the CPU. LXD simply turns the provided percentage value into a score, so that would apply to all the CPUs. Unless the container is pinned onto a particular CPU or set of CPUs, in which case that container will share CPU time based on the percentage value with other containers that use those same CPUs.

I couldn't find any good kernel documentation for cpu.shares...

RedHat does seem to have some documentation that refers to both cpu.shares and to the cfs knobs that we use here: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/resource_management_guide/sec-cpu

I'll add a short paragraph about those particular limits to doc/containers.md to make it a bit clearer what we actually drive behind the scenes, at least until we switch over to cgroupv2 and we switch to a different enforcement mechanism.
