### ISSUE TITLE
lxd re-install remembers previous networking info

### ISSUE THREAD

**Issue by ddag** [lxc/lxd#4153]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.03
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0.108-generic
   * LXC version: 2.0.11
   * LXD version: 2.0.11
   * Storage backend in use: dir

# Issue description

Removing lxd and re-installing it remembers the previous networking information when lxd init is run. Have tried apt-get --purge remove lxd and it still happens. Is there a way to completely remove lxd including configuration for previous installs ?

# Steps to reproduce

 1. sudo apt-get remove lxd
 2. sudo apt-get install lxd
 3. sudo lxd init. Fill out information, choose subnet for bridge etc.
 4. Repeat steps 1 - 3 and see that networking information previously entered is populated.

A related issue on re-install is getting: Permission denied, are you in the lxd group?

**Comment by ddag** [comment]
Oh, I previously opened this issue -- https://github.com/lxc/lxd/issues/3922. The one thing I did do as well here is rm -fr /var/log/lxd and /var/lib/lxd and removal of /etc/default/lxd-bridge. But lxd somehow still remembers previously entered data.

**Comment by stgraber** [comment]
I tried here:

 - lxd init
 - apt remove --purge lxd
 - rm /etc/default/lxd-bridge
 - apt install lxd
 - lxd init

And got different network settings.

**Comment by stgraber** [comment]
LXD 2.0.11 gets its network configured through packaging, in Ubuntu that's done through debconf which keeps the settings stored both in the debconf database and on disk at /etc/default/lxd-bridge.

Removing the package causes the debconf database entries to be cleared, but those will be restored from the on-disk config file upon re-installation. Similarly, removing /etc/default/lxd-bridge prior to removing the lxd package, will just have it be re-generated by debconf from the database information.

So the steps above are I believe the only reliable way to flush things, other than directly interacting with debconf through debconf-communicate (as we do in cloud-init and some other places).


LXD networking configuration is much nicer and easier to understand in more recent LXD releases.
LXD 2.0.x is special because LXD itself didn't manage networks back then, so its default network is managed with distro-specific packaging scripts and patches applied to LXD to try and piece things together.

We don't intend to change any of that logic for LXD 2.0.x as it's extremely brittle and while not ideal in its current state, it's certainly functional and consistent.

**Comment by ddag** [comment]
The steps mentioned work using apt instead of apt-get. But, performing the lxd init the second time hangs. It works after reboot and I get a random subnet.

**Comment by stgraber** [comment]
apt vs apt-get shouldn't matter. I didn't get any hang here, though it's certainly not impossible that systemd's socket unit would have gotten into a funny state during removal...

**Comment by ddag** [comment]
yes, so a reboot solves the problem for sure. so, the following steps work for me:

lxd init
apt remove --purge lxd
rm /etc/default/lxd-bridge
apt install lxd
# reboot for sanity
reboot 
lxd init

thanks
