### ISSUE TITLE
Allow querying leases through /1.0/networks

### ISSUE THREAD

**Issue by geodb27** [lxc/lxd#4155]
# Required information

 * Distribution: ubuntu 
 * Distribution version: 16.04 LTS

   * Kernel version: 4.13.0-21-generic
   * LXC version: 2.21
   * LXD version: 2.21
   * Storage backend in use: DIR

Hi ! I'm still writing my own application to manage my lxd containers and fail on getting some information from the rest api.
From what I've read in the documentation, the ipv4.address key value is used to set "An IPv4 address to assign to the container through DHCP". This is great and works fine.
However, aside this information is available on a per-container basis (1.0/containers/name) in the device section, there is no information at all on the /1.0/networks endpoint.
There are some informations, however, when getting /1.0/networks/lxdbr0 like the list of the containers that are linked to this network.
Could it be possible to add some more informations, then. 
For example, instead of returning a dict with only the containers name (and api endpoints), the container names that uses this network bridge along with the endpoint, the ip address (be it ipv4 or ipv6) and maybe some more informations.
Aside this, there is also a dict with some interresting keys : 
ipv4.dhcp  "true"
ipv4.dhcp.ranges  "192.168.220.1-192.168.220.240"
It would be great to have also the ipv4.dhcp.fixedAddresses or the like, corresponding to the static leases that are setup.

Hoping this is a good idea to add these informations.
Kindly.

**Comment by stgraber** [comment]
The dict with `ipv4.dhcp` and the like, is the `config` dict and is made of configuration keys, so not suitable for read-only dnsmasq state information.

I'm not sure exactly what you're missing, if you want to get the requested static IPv4/IPv6 leases, it's pretty easy to extract from /1.0/containers?recursion=1. What's not exposed is what the dynamic leases are at a given time, but LXD itself doesn't know that since it's managed by dnsmasq behind the scenes.

So if all you're looking for is the requested ipv4.address or ipv6.address of containers on a particular bridge, I'd recommend just doing:

 - GET /1.0/containers?recursion=1
 - Iterate over the containers
 - Iterate over expanded_devices
 - Look for type=nic, nictype=bridged parent=BRIDGE-NAME
 - Grab ipv4.address and/or ipv6.address if set

That's a single pretty quick API call and pretty trivial parsing on top.

**Comment by geodb27** [comment]
Hi @stgraber :-)
As a matter of fact, I don't actually want to fetch the ip associated to running containers, but the static leases that are defined. To me, this was a subset of the configuration given to a network (like the address of the network, the ip associated to the bridge and the ip range associated, for example), but I might be missing something.

**Comment by stgraber** [comment]
The logic I described above is about getting the static IP that's assigned to the container not its current IP.

**Comment by stgraber** [comment]
ipv4.address and ipv6.address in a type=nic nictype=bridged device in expanded_devices IS what's been configured as the static IP by the user (and will only be present on those containers where it's been set).

**Comment by geodb27** [comment]
I completely agree with your last posts.
I only wanted to have a "simple" way to get the overall configuration set up for the bridge without having to parse the whole tree resulting of a get on /1.0/containers?recursion=1
The explanation I copied from the doc probably lead me to a wrong understanding of what the parameters ipv4.address and ipv6.address did in term of configuration. I expected this information to be centralized as one would get from a pure dhcpd.conf with dynamic range and fixed leases.
I've ended up with parsing the whole tree anyway, but this is somehow overkill just to get the last fixed address to calculate one new for a new-to-be container.

**Comment by stgraber** [comment]
I don't expect us to change things much as far as the API is concerned.
One thing we may add is "GET /1.0/networks/NAME/leases" which would get you some structured data about all current leases and static assignments but we'll need to think about how to even do that as dnsmasq doesn't exactly make reading that stuff so easy.
