### ISSUE TITLE
Is setting volatile.eth[n].hwaddr the best way to set a preassigned mac address?

### ISSUE THREAD

**Issue by MikeStankavich** [lxc/lxd#4157]
I'm setting the mac addresses preassigned by hosting provider OVH to secondary IP addresses on an OVH server by setting volatile.eth[n].hwaddr. This isn't currently supported in the terraform lxd provider, so I'm thinking of adding it. But I wanted to confirm before I do that there isn't a more correct way to set a preassigned mac address for an lxd container virtual network interface. Thanks in advance for any clarification. 

https://github.com/sl1pm4t/terraform-provider-lxd/issues/123

**Comment by stgraber** [comment]
That works but it's not officially supported and the name of the key may change in the future.

The supported way would be to add a `nic` device directly to your container's config (rather than inherit from profile) and then set the `hwaddr` property of that device.

**Comment by MikeStankavich** [comment]
@stgraber ohhhh, I didn't think of that. Great idea, works perfectly. Thanks! I'll update the documentation over in the terraform provider accordingly.

**Comment by pcouderc12** [comment]
Mmm, certainly I do not understand well the answer, but I do not want to add a nic, I just want to modify the MAC address of the container.
I use a bridge declared with : 
lxc network attach-profile br0 default eth0
The  interest of modifying MAC address is that the container receives all parameters from the DHCP server.

**Comment by tomponline** [comment]
@pcouderc12 all instances require at least 1 NIC device (https://linuxcontainers.org/lxd/docs/master/instances#type-nic) to have network connectivity. These devices can be added directly to the instance via the `lxc config device add` command or they can be implicitly added to the instance via the profile(s).

In your case when you do `lxc network attach-profile` LXD is adding a `bridged` (https://linuxcontainers.org/lxd/docs/master/instances#nic-bridged) NIC device to the profile which is configured to connect to the `br0` bridge. When you create an instance using that profile it will get a NIC that is connected to that bridge.

When such a NIC device is added, each instance will generate a random static MAC address to use on that bridge, but because it doesn't have the NIC device config added directly to the instance (but rather at the profile level) then it needs somewhere to store that MAC address so that it will use the same one next time. This is what the `volatile.{nic_name}.hwaddr` key is used for in the instance config.

You can manually change this using `lxc config set <instance> volatile.<nic_name>.hwaddr=<MAC>` or you can override the profile's NIC config directly and use the documented `hwaddr` setting using:

```
lxc config device override <instance> <nic_name> hwaddr=<MAC>
```

This latter approach is preferred as it doesn't rely on modifying an internal config variable, as volatile keys should not normally be modified manually.
```

**Comment by pcouderc12** [comment]
Thank you very much for this very clear information, that fully answers my question : 
1 :  I have not to add a nic but to modify the soon existing one
2 : to do that, stop using unrecommended :
lxc config set <instance> volatile.<nic_name>.hwaddr=<MAC>
but use documented :
lxc config device override <instance> <nic_name> hwaddr=<MAC>

**Comment by tomponline** [comment]
Yes that's the preferred way of specifying a static MAC address for a NIC.
