### ISSUE TITLE
Live Migration fails 

### ISSUE THREAD

**Issue by upuvvad1** [lxc/lxd#4212]
Hi @stgraber  @tych0  ,
Live migration fails on the container, when a process with sleep function is being run in the process inside container.

lxc exec <container> -- sleep 10m
lxc move <container> <dest_container>

Can you provide some insight on this, and is there a way we can fix this?

**Comment by stgraber** [comment]
Yes, that's normal and no, there's no way to fix it.

CRIU can only dump things that are in the container's process tree. Attached processes are in a separate process tree in the same PID namespace (your process isn't a child of PID 1) and so CRIU can't dump/restore it.

You'd need to ssh into the container or use the container's init system to spawn your process rather than manually starting it through an exec session. At least until someone finds a clever way of having CRIU restore such a process.
