### ISSUE TITLE
LXD fails to `zfs import`

### ISSUE THREAD

**Issue by spacekookie** [lxc/lxd#4222]
# Required information

The LXD daemon fails to start so I can't give any of the `lxc` commands

 * Distribution: Arch Linux
 * Distribution version: `rolling`
 * The output of "lxc info" or if that fails:
   * Kernel version: `Linux icarus 4.14.4-1-userns #1 SMP PREEMPT Sun Feb 4 23:53:53 CET 2018 x86_64 GNU/Linux` (has USER_NS enabled)
   * LXC version: 2.21
   * LXD version: 2.21
   * Storage backend in use: zfs

# Issue description

I rebooted my server because of some kernel updates. And apparently something didn't shutdown correctly because now it's telling me 

```

error: ZFS storage pool "default" could not be imported: cannot import 'default': pool was previously in use from another system.
Last accessed by icarus (hostid=d4ad37e3) at Mon Feb  5 11:16:40 2018
The pool can be imported, use 'zpool import -f' to import the pool.

```

when I try to start the daemon. I have failed to find any documentation on how to force import the ZFS pool here. `zpool [status|list]` yields no pools

# Steps to reproduce

 1. Use LXD with ZFS
 2. Reboot? (I've had other system restarts before though, no idea why it's acting up now)

# Information to attach

Not sure what is relevant here. One line from `dmesg` seemed important

```
[    4.415782] ZFS: Loaded module v0.7.0-1, ZFS pool version 5000, ZFS filesystem version 5
```

**Comment by stgraber** [comment]
So ZFS seems to think the hostid changed somehow and so won't allow it to be auto-imported by LXD...
I think your best bet is to run the suggested command "zpool import -f default" which should bypass that check.

**Comment by spacekookie** [comment]
Well, when I run that I get `cannot import 'default': no such pool available`

Either as `sudo zpool import -f default` or `zpool import -f default` or

```
newgrp lxd
[sudo] zpool import -f
```

It seems to not be properly scoping something it seams?

**Comment by stgraber** [comment]
Can you try:

    sudo zpool import -f -d /var/snap/lxd/common/lxd/disks/ default

If using the snap, or if using the native package, then:

    sudo zpool import -f -d /var/lib/lxd/disks/ default

**Comment by spacekookie** [comment]
omg thank you! Yes, the second command worked. I was trying to play around with zpool but didn't know about the `-d` option :P

**Comment by stgraber** [comment]
Yeah, that part of zfs is pretty obscure :)

**Comment by mcgrathd** [comment]
Perhaps a good note for others, but I stumbled on here while trying to troubleshoot a non-starting lxd, as well. For starters, thanks for the path hint. It wasn't exactly my problem, but it got me on the right path.

Seems that when I just upgraded to 18.04 from 16.04, as suspected, the zfs features were out of date, and in my case the juju-zfs pool was missing features, and considered to be from "another system". A manual `losetup -f /var/snap/lxd/common/lxd/disks/juju-zfs.img ; zpool import -f juju-zfs ; zpool upgrade juju-zfs ; zpool export juju-zfs ; losetup -d /dev/loopXXX` seems to have solved it!

For the logs/search engines:
```
DBUG[08-05|07:46:53] Initializing and checking storage pool "juju-zfs"
DBUG[08-05|07:46:53] Initializing a ZFS driver        
DBUG[08-05|07:46:53] Checking ZFS storage pool "juju-zfs"                 
DBUG[08-05|07:46:53] ZFS storage pool "juju-zfs" does not exist, trying to import it    
EROR[08-05|07:47:05] Failed to start the daemon: ZFS storage pool "juju-zfs" could not be imported: cannot import 'juju-zfs': pool was previously in use from an
other system.                                                                    
Last accessed by wks (hostid=7f0101) at Sat Aug  4 15:21:45 2018                 
The pool can be imported, use 'zpool import -f' to import the pool.
```
Perhaps it would be a good idea to check for such things in future versions. I only realised it due to FreeBSD ZFS upgrade experience, and luck on finding this post! ;p

Anyways, cheers! o/
