### ISSUE TITLE
Misc issues configuring an image server

### ISSUE THREAD

**Issue by maikeueule** [lxc/lxd#4246]
Hello team,

While trying to setup an image server for LXD, I am facing a couple of issues i'd like to report in this thread. I am using the latest snap lxd v.2.21.

I have an Apache server serving images though simplestreams (with proper directory structure and json files). I have previously validated this configuration.

The problem occurs when having a SSL only server (option SSLRequireSSL in Apache2). Note that I am using my own CA. I am currently not using any client authentication, which will be my next step.

# Trusted roots

Side question:  how to configure a trusted root with LXD ? So far I added my CA system-wide. The first surprising result is that after adding the CA, i could list images previously raising this error:

lxc image list XXX:
error: Get https:/XXX/streams/v1/index.json: x509: certificate signed by unknown authority

but not issue a launch command, which raised this error until I reloaded LXD.

# Adding a remote

I am using the following command,
lxc remote add XXX https://XXX --protocol=simplestreams

Any --public or --auth-type argument has no impact, the remote is always listed as public, and the authenttication empty. Also, I could not check the impact of --accept-certificate at this stage.

# Launching container

With this in place, I can successfully list images on the remote, however, upon launching a container:

lxc launch XXX:XXX
Creating test
error: Failed container creation:
 - https://XXXX: Get https://XXXX/images/XXX/lxd.tar.gz: local error: tls: no renegotiation

I notice this is due to LXD trying to connect on port 80. Apache gives the following error:
AH02219: access to /var/www/html/XXX/lxd.tar.gz failed, reason: SSL connection required

This is confirmed with TCPdump showing lxd connecting on port 80, before doing some other activity on port 443 as expected. I tried adding port numbers in the remote configuration but this did not change anything. None of the JSON of the image server indicate any http protocol or port 80.

Any idea of what might cause this behaviour ?

Thanks in advance for any insight configuring the image server.

**Comment by maikeueule** [comment]
The same issue can be reproduced with canonical servers:

# tcpdump src port http or dst port http

In another window:

$ lxc remote add us https://us.images.linuxcontainers.org/ --protocol simplestreams
$ lxc launch us:debian/10 test

5:23:30.238647 IP6 [...]> gible.canonical.com.http: Flags [S], seq 2258189037, win 28800, options [mss 1440,sackOK,TS val 436910045 ecr 0,nop,wscale 7], length 0
[...]

**Comment by stgraber** [comment]
Ok, so there's quite a lot in here :)

1) LXD certificate handling only works after restarting the daemon.
I suspect this can be blamed on the way the system CA certs work with the snap. In the snap environment we run with our own very limited copy of /etc. On startup we attempt to read and import the system certificates from the host system and get those into our /etc. This would explain why the restart fixed it.

2) --public and --auth-type don't do anything with simplestreams remotes
That's intentional. Simplestreams remotes are always treated public (as they can only provide images, not containers) and no authentication is provided (TLS or macaroon). You can however use basic authentication by encoding the username and password in the URL, that's been confirmed to work.

3) https & http behavior
The expected behavior for simplestreams image download is to fetch the indices (all the json stuff) over https, then download the image over http and validate its hash with what was retrieved over https.
That's so that the bulk of the data download happens over http which can be properly cached by transparent proxies.

That being said, the code does have a fallback where if http download fails it should fallback to https to retrieve the data anyway. There may be a bug in that logic which I'd have to investigate.

**Comment by maikeueule** [comment]
Hi, and thanks for the prompt answer.

1. The funny thing was that the certificate was accepted to access the JSON file to list images, not to download it. It seems there are two ways to getting those system-wide CA certs.

Alternatively, is there a way to add CA specifically for LXD  ?

2. Since simplestreams use https and LXD has a certificate, i was expecting to be able to replace them by certificates signed by my CA and use them to authenticate the download of images. Are you anticipating this won't work ?

3. This should be easy to reproduce in Apache2 with the setting SSLRequireSSL for the folder where images sit. I will be happy to help debugging this.

**Comment by stgraber** [comment]
1. That's because "lxc image list" doesn't talk to the LXD daemon, it does a direct connection to the image server. "lxc launch" will instead tell the LXD daemon what image to fetch and the daemon will be the one connecting then. So it's a case where the "lxc" process could see your certificate but the "lxd" process couldn't.

2. We do have a "PKI" mode in LXD that may or may not cover this already. In this mode it's expected that all client and server certificates are issued from your own CA with the CA certificate placed in both the client and daemon directories. I'm just not sure whether we also put that CA in the truststore for simplestreams.

Simplestreams should be made to attempt connecting to the remote server and do the same fingerprint prompting as we do for the others if encountering a remote server that's not part of the local trust store, that should make it easier to just add such a remote server (though these days letsencrypt makes this case less common) and would also let you dump the expected certificate into place in the config dir to ensure it's the right remote server.

3. Yeah, I'll try some combinations there. I suspect that just plain not answering on port 80 will trigger our fallback fine, it's when redirect or forcing a TLS handshake that things go bad.

**Comment by maikeueule** [comment]
Everything is clear. I'll continue investigating 2. Among the reasons why i am not using Let's Encrypt:  last time I checked it did not allow for issueing certificates for IPs without DNS entry.

**Comment by stgraber** [comment]
Confirmed that just blocking tcp/80 causes the expected fallback. I also tested with a standard http to https transition through server side redirect (302) and that's working fine too.

I can't easily test SSLRequireSSL because of the way my web servers are setup (it's scoped only for htaccess and directory sections which doesn't work for my setup).

**Comment by stgraber** [comment]
Looking at the documentation for SSLRequireSSL, it's really only meant as protection against bad configuration rather than a way to tell the client to upgrade to TLS, it looks like the latter should still be done with a good old 302 preferably.

**Comment by stgraber** [comment]
Hmm, so the error you first reported doesn't seem to be caused by LXD attempting to download over http. It does do that indeed and then falls back to https download and that's when it hits the error.

Any chance you can make such a server remotely accessible so that I can figure out what's going on?

**Comment by maikeueule** [comment]
Sure let's look at that out of band.

**Comment by stgraber** [comment]
Ok, managed to get to the bottom of this with @maikeueule's help.

It turns out the problem hits when talking to a server which attempts to perform TLS renegotiation.
Go has that particular TLS feature disabled by default due to fear of security issues in their TLS state machine when undergoing renegotiation during a TLS connection.

Go 1.7 and higher does have an option to turn it on at least, but that's not recommended right now and as we very much rely on Go's TLS implementation being safe throughout LXD, I'm not inclined to take any risk here.

For the record, the LXD "fix" would be:

```go
stgraber@castiana:~/data/code/lxc/lxd (lxc/master)$ git diff
diff --git a/shared/network.go b/shared/network.go
index 2ccb7dc8..eeb57a41 100644
--- a/shared/network.go
+++ b/shared/network.go
@@ -53,6 +53,7 @@ func InitTLSConfig() *tls.Config {
                        tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
                        tls.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,
                },
+               Renegotiation: tls.RenegotiateOnceAsClient,
                PreferServerCipherSuites: true,
        }
 }
```

For anyone else hitting this, there should be reasonably straightforward configuration knob that you can change on your web server's side to not actively attempt such TLS renegotiation, fixing this particular problem. Also worth noting that anything else written in Go which doesn't specifically opt into this new TLS config option will similarly fail.

**Comment by m-ueberall** [comment]
@maikeueule: Could you provide me/others with a few pointers regarding your setup/toolchain (maybe in the form of a short gist)? The process of setting up an image server using simplestreams unfortunately cannot be considered documented at all despite the protocol being around for quite some time already. Thank you very much in advance!

**Comment by GavrielNsof** [comment]
@m-ueberall @maikeueule can you please share if you managed to host a unified tarball on a simplestreams server?
If so, how did you write the index.json and the image.json?
Thanks

**Comment by GavrielNsof** [comment]
Perfect, thank you
