### ISSUE TITLE
Propagate dhcp/dns entries

### ISSUE THREAD

**Issue by oms-kauz** [lxc/lxd#4278]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-116-generic
   * LXC version: 2.1.1
   * LXD version: 2.21
   * Storage backend in use: dir

# Issue description

I've installed lxd(8) via snap(1). I'm trying to propagate my LXC containers hostnames/IP addresses via a home-grown script, but dnsmasq(8) cannot find my script.

# Steps to reproduce

Configure dnsmasq dhcp-script via the raw.dnsmasq LXD configuration entry:

$ lxc network set lxdbr0 raw.dnsmasq
dhcp-script=/usr/local/sbin/yeah.sh

Create a script in /usr/local/sbin/yeah.sh:
$ cat /usr/local/sbin/yeah.sh
#!/bin/bash
logger --id=$$ "$0 $@"

But it fails with the following error message in /var/log/syslog:

Feb 22 17:00:34 admin dnsmasq[1138]: failed to execute /usr/local/sbin/yeah.sh: No such file or directory

Configuring logger(1) works though (even if it is renamed in /usr/bin/):

$ lxc network get lxdbr0 raw.dnsmasq
dhcp-script=/usr/bin/logger

**Comment by simos** [comment]
You installed the snap version of LXD. This means that you may be stumbling on some confinement issues. Here is how to deal with them.

The LXD-in-a-snap runs as a account with restrictions. You can get a shell into that account with

      $ snap run --shell lxd
      bash-4.3$ /usr/local/sbin/yeah.sh
      bash: /usr/local/sbin/yeah.sh: command not found

This happens because the specific LXD snap does not have access to /usr/local/*

So, where can you put files for LXD to find?
Here is the documentation, https://docs.snapcraft.io/reference/confinement

    Strict confinement gives you the following readable and/or writable paths:

    /snap/<snap>/<revision> (read-only, snap install path)
    /var/snap/<snap>/<revision> (read/write, per-revision data)
    /var/snap/<snap>/common (read/write, common data)
    /home/$USER/snap/<snap>/<revision> (read/write, per-revision user data)
    /home/$USER/snap/<snap>/common (read/write, common user data)

Therefore, you can put the script in **/var/snap/lxd/common/**

**Comment by stgraber** [comment]
Right, as @simos said, the snap can't see that path due to confinement.
The cleanest solution is to put your script somewhere under /var/snap/lxd/common/

If you absolutely need to access the host filesystem, you can do so through /var/lib/snapd/hostfs/usr/local/sbin/yeah.sh but I really wouldn't recommend it.

Note that your script will be running in the snap's environment so will be limited by what's in there as far as available commands and the like. If it needs to access some files from the host, it will need to do so through /var/lib/snapd/hostfs/ as regular paths like /etc and /var will be those of the snap rather than your system.
