### ISSUE TITLE
Feature Request: Please add a Web-GUI

### ISSUE THREAD

**Issue by michacassola** [lxc/lxd#4298]
I thought it might be useful to have a Web-GUI for LXD. (Like this [https://github.com/dobin/lxd-webgui](https://github.com/dobin/lxd-webgui))

Some advantages/features I can think of:
 - Easier control for non-tech Users (It might make LXD interesting to them in the first place)
 - User Management for LXC-Container Hosters (Like granting them access only to their Containers)
 - Monitoring of Containers

Thanks for considering!

**Comment by stgraber** [comment]
As you pointed out, there are some existing projects that do this already, interfacing with LXD using its REST API.

I can find at least 3 such projects on Github right now:
 - https://github.com/AdaptiveScale/lxdui
 - https://github.com/dobin/lxd-webgui
 - https://github.com/aarnaud/lxd-webui

For large scale deployments, you can also use OpenStack combined with the nova-lxd plugin.

All of those are fine options that build on top of LXD's API which is the way we always imagined such user interfaces would be built. I don't see a need for us to come up with another one and think LXD itself should focus on the lower level container management and API rather than on web design (which we have no experience with).
