### ISSUE TITLE
Add support for primitive/derived containers

### ISSUE THREAD

**Issue by geodb27** [lxc/lxd#4339]
* Distribution: Ubuntu
 * Distribution version: LTS-16-04
   * Kernel version: 4.13.0-37-generic
   * LXC version: 2.21
   * LXD version: 2.21
   * Storage backend in use: DIR

Hi, 
Could it be considered to add support for one main primitive container that could be derived into as many containers as wanted. Let me explain : 
I use many containers that are exactly the same, save for some well-known folders (/var and /etc). 
So, in this use case, I have many containers that use much disk space for... nothing else than using disk space.
The idea would be to have one container, a "main" one, that could be ran only to achieve software updates for example and that would mount all disks it requires read-write. Then, I would like to have the ability to create derived containers that would bind-mount all from this first main container read-only, and have what is specific out of the rootfs mounted as specified in it's configuration. 

For example, I have ~50 containers that serves each apache2 sites (spip-ones).
The idea would be to have something like this : 
One main container (spip-main) that would have it's rootfs in /lxd/spip-main/rootfs
And each of these spip-xx containers be configured this way : 
/lxd/spip-xx/rootfs -> bind mount (ro) of /lxd/spip-main/rootfs
/lxd/spip-xx/etc -> bind mount (rw) of /lxd/devices/spip-xx/etc
/lxc/spip-xx/var -> bind mount (rw) of /lxd/devices/spip-xx/var 

I've searched a way to achieve this, but apart from hacking what is done after a container creation, I haven't seen a native way. This could save much space (each of my spip-xx container is ~1.2 Gb) and would help have things centralized.

Hoping that this idea could be useful.

**Comment by stgraber** [comment]
Read-only rootfs rarely works the way you'd expect with modern distros. Read-write overlays is the usual way around those issues, but they come with their own problems (mostly breaks inotify which breaks part of the init process and anything that performs inode tracking).

LXC itself (C library and tools) lets you do things like that, but we've made the conscious decision not to carry that "feature" when we designed LXD as we noticed it was doing more harm than good and would also make some of LXD's features near impossible to implement properly, thinking of things like snapshot, publishing and containers copy and move between machines.

In your scenario, you could save a lot of space by using anything but the "dir" backend as all other backends get you copy-on-write copies of your container. So when copying from your initial container, only what changes will use disk space rather than doubling the entire disk usage on copy.

To save even further, you could use ZFS with online deduplication enabled. This will trade some memory usage for significant disk savings by hashing every file that's written in any of your containers and making sure that only a single copy is ever kept on disk. With this, you can have containers temporarily diverge, taking more space and when they converge again, their files are deduplicated and you get your disk space back.
