### ISSUE TITLE
Per-remote HTTP Proxies

### ISSUE THREAD

**Issue by dshcherb** [lxc/lxd#4397]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
  driver_version: 3.0.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.16.0-041600-generic
  server: lxd

# Issue description

There is currently no way to set per-remote HTTP proxies.

Using http_proxy, https_proxy, no_proxy at a process level isn't flexible as one has to exclude everything local via a list of hostnames or ip addresses.

Solving this https://github.com/golang/go/issues/16704 (https://go-review.googlesource.com/c/75730/) would be a workaround but the idea is to steer traffic on a per-destination basis which only requires one proxy URL to be set (no need for http type or no-proxy in this case).

`lxc remote set-proxy <remote> <proxy-url>`

Right now if you need to set no_proxy for a large prefix you can go over [min(1/4 of the max stack size, 3/4 of _STK_LIM)](https://elixir.bootlin.com/linux/v4.16/source/fs/exec.c#L244) for small stack sizes. And [the default stack memory limit is fairly small](https://elixir.bootlin.com/linux/v4.16/source/include/uapi/linux/resource.h#L66).

About 1 MiB of strings for a /16:
```
echo $(( `printf '%s,' 100.100.{0..255}.{0..255} | wc -c` / 1024))
969

```
A few more /16s and you have to increase your stack memory limit.

You may also need to use wildcards for hostnames and you cannot currently do it in no-proxy - so every hostname has to be included too.

There is a way to set a proxy URL per HTTP Transport - this is how set-proxy could be implemented:
https://golang.org/pkg/net/http/#ProxyURL

**Comment by stgraber** [comment]
So the problem here is that remotes are a client construct, the server has no such concept whatsoever.
Then there is the problem that the client and server may be two different machines with different proxy configurations, so we can't just send along the proxy config to the server and expect it to work there.

As the exact same problem is likely to hit a whole bunch of other applications and services on your system, I believe the best approach would be for you to run a tiny non-caching proxy on the machine itself with a dispatcher config to send things to whatever the relevant proxy is (or directly out if not proxied).

That'd let you avoid the crazy env variable configuration by just pointing everything to a localhost port and would let your client and server have different proxy configurations if they happen to run on different networks.
