### ISSUE TITLE
lxc query Error: unknown shorthand flag: 'X' in -X

### ISSUE THREAD

**Issue by lcherone** [lxc/lxd#4406]
# Issue description

As title, I'm getting `Error: unknown shorthand flag: 'X' in -X` when running the following cmd on **Ubuntu 18.04**

`/usr/bin/lxc query -X GET -d '' /1.0/images`

Ignore the fact I could do `/usr/bin/lxc query /1.0/images` which works fine.

The same cmd works fine on `16.04`

Has that flag been removed, if so where is the documentation?

# Required information

 * Distribution: Ubuntu 18.04
 * lxc info:
  driver_version: 3.0.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.13.0-37-generic
  server: lxd
  server_pid: 2965
  server_version: 3.0.0
  storage: dir
  storage_version: "1"

# Steps to reproduce

 1. Install LXD on 18.04
 2. Run aforementioned cmd

**Comment by lcherone** [comment]
Also --all flag seems to be missing:

```
root@18-04:/var/lib/lxd/images# lxc help --all
Error: unknown flag: --all
```

**Comment by stgraber** [comment]
Thanks for the report, those look like a few more issues from porting to the cobra command line parser in 3.0. The `lxc query` one should be pretty easy to fix as it's just the parser being silly and converting those to `--X` and `--d` instead of the expected `-X` and `-d`. I'll also add a test so we don't regress that.

The help one is a bit trickier as this is a built-in command from the parser so I may have to be creative in finding a way to have it respect `--all`. `lxc --help --all` should do what you want though, it's only the subcommand that's misbehaving.

**Comment by stgraber** [comment]
Sent a fix
