### ISSUE TITLE
LXD should be more verbose about potentially long-running operations

### ISSUE THREAD

**Issue by palica** [lxc/lxd#4447]
# Required information

 * Distribution: gentoo
 * Distribution version: current
 * The output of "lxc info" or if that fails:
```
  driver: lxc
  driver_version: 2.1.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.14.12-2
  server: lxd
  server_pid: 28418
  server_version: "2.21"
  storage: zfs
  storage_version: 0.7.5-r0-gentoo

```
# Issue description

Could LXD be more verbose by default about potentially long-running operations?
For example id-remap when changing security.idmap.isolated for (all) containers.
It would be nice if LXD would print a clear messages on console and log so you can see what step it is doing.

I think it needs a new state frankly
STOPPED and RUNNING are not enough
STOPPED <-- UIDMAP --> RUNNING
or STOPPED <-- PREP --> RUNNING

It says container STOPPED, when in reality LXD is working fine just doing a time-consuming operation.

# Steps to reproduce

 1. change idmap.isolated
 2. restart container(s)
 3. watch IO explode :)

lxc operation list is not very helpful and also info about operation through its id doesn't say much.

**Comment by stgraber** [comment]
So the reason why things are this way right now is because:
 - Shifting is handled by LXD not by LXC so it can't be a status as statuses come from underlying liblxc
 - It would make sense for it to be an operation status message as happens with image downloads, but the plumbing for this would be very tricky due to a number of different code paths that can lead to a remapping, all of which would need a reference to the background operation (and none of them do at the moment)
 - We expect this entire thing to go away through a kernel solution that'd entirely eliminate the need for remapping

**Comment by stgraber** [comment]
We can investigate plumbing the ref to the operation through some of the functions, making just the remap on startup case work shouldn't be too bad.

**Comment by palica** [comment]
thank you for clarifications.
