### ISSUE TITLE
network dependent systemd services starting before lxd bridge ready

### ISSUE THREAD

**Issue by stub42** [lxc/lxd#4477]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-15-generic
   * LXC version: 3.0.0
   * LXD version: 3.0.0
   * Storage backend in use: zfs

# Issue description

I think systemd services dependent on the network (After=network.target) are being launched before the lxd bridge has been setup. This means that after a fresh reboot, network services are not bound to the bridge address. This is particularly problematic for Debian packages such as apt-cacher-ng or squid-deb-proxy, as after a fresh reboot lxc containers are unable to access the local apt proxy for updates.

Restarting the affected services manually after a restart is a workaround. There is also likely a systemd override that could be added, but I don't know what it is.

# Steps to reproduce

 1. sudo apt install apt-cacher-ng
 2. edit /etc/apt-cacher-ng/acng.conf, adding the lxd bridge address to BindAddress
 3. systemctl restart apt-cacher-ng
 4. confim the proxy is contactable from inside an lxc container, lxd bridge address, port 3142
 5. restart the machine
 6. confirm the proxy is no longer contactable from inside the lxc container.

This is not a regression; I saw the same behavior under 16.04 with deb packaged lxd.

**Comment by stgraber** [comment]
So I'm not sure how this can be fixed without you putting specific overrides in place to force those units to start after lxd itself is online.

The problem here is that LXD itself depends on the network being online and so requires network-online.target putting it at the same spot in the boot sequence as all your other services without a clean way for it to generically make them all hold.

And even if it could, you'd still run into problems as LXD is socket activated, so the LXD daemon and its bridges will only come online at boot if your have autostarted containers or have configured LXD to listen to the network.

**Comment by stgraber** [comment]
I'm also unclear as to why this ends up being a problem for you, things that listen on all interfaces should bind "0.0.0.0" or "::" which will bind all IPs on all interfaces, even those that don't exist yet.

**Comment by stgraber** [comment]
Closing as I can't see a way for LXD to resolve this with the way distributions are doing boot ordering.
On your local system, I'd axpect adding After=lxd.service as an override for the relevant units should fix it, that or configure those daemons to bind 0.0.0.0/:: instead of per-interface addresses.
