### ISSUE TITLE
LXD service fails to start with "failed to handle BEGIN request: FSM out of sync: timed out enqueuing operation"

### ISSUE THREAD

**Issue by TheSeven** [lxc/lxd#4485]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04 beta amd64
 * Kernel version: at least 4.15 through 4.17
 * LXC version: 3.0.0
 * LXD version: 3.0.0
 * Storage backend in use: btrfs 4.15.1 (separate disk from root FS)

# Issue description

The LXD service fails to start (on boot, after a package update, or when started manually for some reason) more often than not, due to a database timeout:
`failed to handle BEGIN request: FSM out of sync: timed out enqueuing operation`
When observing the daemon behavior, there is high random write activity (averaging ~10MB/s to the SSD) for tens of seconds before the daemon fails with the error above.
The lxd waitready process continues to wait until the 600 second limit expires, then systemd tries to start the lxd daemon, usually succeeding after 2-4 attempts.
This started to happen after upgrading from Ubuntu 16.04 to 18.04 beta.

# Information to attach

 - [X] Any relevant kernel output (`dmesg`) [journal.txt](https://github.com/lxc/lxd/files/1939839/journal.txt)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
(Note that some container names have been replaced with "SOME_CONTAINERNAME" in the log above for privacy reasons. I also killed the waitready process after the daemon had failed to speed up the restart.)

**Comment by stgraber** [comment]
What does `du -sch /var/snap/lxd/common/lxd/raft` show?

**Comment by stgraber** [comment]
I'd normally expect the DB to be tiny so the 10MB/s for a while seems very weird.

**Comment by stgraber** [comment]
That's going to be one for @freeekanayaka as I'm not aware of what those contain exactly and what's safe to cleanup... Unfortunately he's off until Friday so unless he pops in, it may take a little while...

**Comment by freeekanayaka** [comment]
Hi,

the error that you've seen (``failed to handle BEGIN request: FSM out of sync: timed out enqueuing operation``) happens if a database transaction can't be started within a minute, which is the (for now) hard-coded timeout for waiting for the database raft-based engine to replay the raft logs in the store (which is logs.db file plus the most recent snapshot in the snapshots/ dir).

I've tried to locally replay your logs using the raft.tar.gz file that you attached and it takes less then 300ms on my laptop, so clearly there is something else going on.

If you could, I'd suggest to:

0) Migrate from the LXD deb package to the LXD snap. That will get you a more recent build that would rule out some fixed issues that are not yet included in the 3.0.0-0ubuntu4 deb from Ubuntu 18.04. The snap will also keep LXD binary you more up-to-date than the deb, since it's generally released more frequently and faster (without loss of stability).

1) Stop the LXD systemd service (``systemd stop lxd; systemd stop lxd.socket``), make sure that the LXD daemon process is really gone (``ps aux | grep lxd``) and then start the LXD daemon from the console in debug mode with ``sudo lxd --group lxd --verbose --debug". Try to do that a few times to see if it gets stuck (once started you can check that is functional by just running ``lxc list`` from another console. If hit any problems, please attach the output of the daemon to this issue. If you don't hit anything and it works all the times, it most probably means that there is a bug somewhere in the interaction between ``lxd waitready`` and the daemon. If you are not depending on the lxd daemon to be fully ready when the systemd unit is started (e.g. you don't have systemd-triggered scripts that run lxc commands after the lxd unit), the best workaround for now would be probably to create a custom systemd service file for LXD that does not run waitready: just copy /lib/systemd/system/lxd.service to /etc/systemd/system/lxd.service and remove the waitready line. On a normal system the LXD daemon should be ready after a few milliseconds after the systemd unit is started, and so blocking on waitready might not be an issue for you.

**Comment by TheSeven** [comment]
I'll need to figure out what using that snap implies for the rest of the system - additional btrfs subvolumes might confuse the backup solution of that system, so I'm not sure if I can use snaps without screwing something up.
Maybe I can reproduce this on a box where that doesn't matter, I'll have a look.

This is not just an interaction between LXD and waitready, waitready is just what's delaying the auto-restart 10 minutes after LXD failed.
LXD keeps hammering that database file for a minute and then dies, leaving the waitready behind.

Why is that logs.db file so huge in the first place? What is it even storing?

**Comment by freeekanayaka** [comment]
There still could be some bad behavior in the daemon that is triggered by waitready and wouldn't be triggered otherwise, so trying without it (first by hand from the console and then perhaps tweaking the systemd unit) would still be worth.

Re the size of logs.db, it shouldn't really be a concern, it's a boltdb store which allocates buckets beforehand (and doubles allocation when short of buckets), it's used to store raft logs which in any case will be compacted at regular intervals (although boltdb won't shrink, it will just mark those buckets as unused). What matters mostly is the size of bin.db, which is just a SQLite database generated from the raft logs (and this is why we suffixed it with ".bin", to signal that you should not touch it).

**Comment by stgraber** [comment]
Ok, so for anyone who's stuck, those are temporary instructions to get you back to a running state.
Note that this will not persist on reboot and that this will no longer be needed after you run a fix LXD.

```bash
set -eu

# Find the database
for db in /var/snap/lxd/common/lxd/raft /var/snap/lxd/common/lxd/database/global /var/lib/lxd/raft /var/lib/lxd/database/global; do
    [ ! -e "${db}" ] && continue
    DB="${db}"
    break
done

[ -z "${DB}" ] && echo "Couldn't find database" && exit 1
echo "Database found at ${DB}"

# Safety check
if mountpoint -q "${DB}" || mountpoint -q "${DB}.mnt"; then
    echo "temporary mounts already setup, aborting"
    exit 1
fi

# Stop LXD
systemctl is-enabled -q lxd 2>/dev/null && systemctl stop lxd lxd.socket
systemctl is-enabled -q snap.lxd.daemon 2>/dev/null && systemctl stop snap.lxd.daemon

# Backup
rm -rf "${DB}.orig"
cp -r "${DB}" "${DB}.orig"

# Setup temporary mount
[ ! -e "${DB}.mnt" ] && mkdir "${DB}.mnt"
mount --bind "${DB}" "${DB}.mnt"
mount --make-private "${DB}.mnt"

# Cleanup unused files
rm -f "${DB}"/db.bin*

# Setup tmpfs
mount -t tmpfs tmpfs "${DB}" -o mode=0750
[ -e "${DB}.mnt/snapshots" ] && mkdir "${DB}/snapshots" && mount --bind "${DB}.mnt/snapshots" "${DB}/snapshots"
touch "${DB}/logs.db" && mount --bind "${DB}.mnt/logs.db" "${DB}/logs.db"

# Start LXD
systemctl is-enabled -q lxd 2>/dev/null && systemctl start lxd lxd.socket
systemctl is-enabled -q snap.lxd.daemon 2>/dev/null && systemctl start snap.lxd.daemon

echo "Done"
```

You probably want to put that in a file and then run it with "sh". This needs to be run as root.

**Comment by freeekanayaka** [comment]
@TheSeven when I posted earlier that it only took 300ms on my laptop to replay the raft logs you attached, I was misled by the fact that I was performing the test under /tmp, which of course is tmpfs here. I tried again this morning and it actually to ~25s on non-tmpfs. The workaround in #4518 should solve the issue for now, although we'll also want to fix the db engine in a better way.

**Comment by TheSeven** [comment]
The timestamps of those snapshots are before my "run lxd manually" tests, and during the first manual start of lxd I have also observed a phase with heavy reading (1MB/s from HDDs) for tens of seconds. That just goes away once it's cached.

**Comment by freeekanayaka** [comment]
I see, then there might be a read problem too. We'll have to do more testing with non-SSD storage, since I didn't see any problem with the read part here, even on non-tmpfs. The PR I linked above should solve the heavy read part on startup too, tho.

**Comment by stgraber** [comment]
Going to close this as the main fix is in place now in master and the rest of the fix will come through dqlite rather than LXD.
