### ISSUE TITLE
Rework lxc-to-lxd (Go, 3.0 liblxc, storage backends, ...)

### ISSUE THREAD

**Issue by borutmrak** [lxc/lxd#4496]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-20-generic #21-Ubuntu SMP
   * LXC version: 3.0.0-0ubuntu2
   * LXD version: 3.0.0-0ubuntu4
   * Storage backend in use: ZFS

# Issue description

I wanted to convert a LXC container (copied from another host that is running 16.04) to LXD on a Ubuntu 18.04 machine.
lxc-to-lxd script only seems to support the old deprecated LXC configuration options, therefore I was unable to do this.
Running the script on a (non-working) deprecated LXC config returns "Invalid container configuration, skipping..."
Updating the container configuration with lxc-update-config (thus making a working LXC container) and running lxc-to-lxd on that chokes on lxc.uts.name, lxc.rootfs.path etc.

I tried fixing the script for the simple cases (ustname, rootfs), but when it came to the network configuration it became too involved for a quick fix, therefore i'm submitting this issue.

Is there another way to convert an LXC container to LXD that i'm not aware of?

If I were to fix this myself (and submit a pull request), does the script have to support the deprecated configuration at all or is it OK if it only supports the new keys? That would be much simpler.

best regards,
Borut Mrak

**Comment by stgraber** [comment]
We have a roadmap item to completely rewrite the script so that it works again.
The main issues right now are:
 - Doesn't support the new config keys (as you've noticed)
 - Doesn't support storage backends other than `dir`
 - Doesn't support unprivileged containers

We also intend to rewrite it in Go since it's the only bit of python in our code tree at this time.

An alternative way to migrate your containers would be to build `lxd-p2c` and run it inside the container you'd like to move to LXD, then tweak the configuration afterwards to keep its MAC address and any other bit of configuration you care about.
