### ISSUE TITLE
Unable to use unix-char devices after re-enumeration/rescan

### ISSUE THREAD

**Issue by sharm294** [lxc/lxd#4513]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-119-generic
   * LXC version: 2.0.7
   * LXD version: 2.0.9
   * Storage backend in use: dir

# Issue description

I'm having an issue with needing to re-add unix-char devices to containers. There are two cases I observed: 

**Case 1**: I need to add USB devices to my containers. To avoid path issues with USB re-enumeration, I made a udev rule on the host to create a symlink with a constant path. Then, I added this symlink to the container as a unix-char device. In the container, this approach works until I reinsert the USB device. On the host, the symlink is in the same location but it points to a new location. After the reinsertion, I can use the symlink on the host but it doesn't work in the container. Re-adding the symlink fixes it.

**Case 2**: I'm also passing through a PCI device. I can't use the PCI device after removing the device and doing a rescan, unbind and bind of the PCI driver. I can read correct values from it on the host immediately after but I need to remove and re-add the devices to the container before it will be able to access them again.

In both cases, the character devices appear in /dev/ but I can't actually use them. Is this expected behavior?

# Steps to reproduce

See the cases above

**Comment by stgraber** [comment]
1) Is perfectly normal. LXD uses bind-mounts and bind-mounts resolve any symlinks, so the device in the container will be whatever the symlink was pointing at when the container started, changing it on the host will have no effect at all.

2) If that's using a similar symlink which changes target, then yes, that'd be expected. You can't pass symlinks cross-namespaces so everything is getting resolved at container startup time.

It may be best to have your udev rule directly add/remove LXD devices on your container instead of updating a symlink.

On more recent LXD, 1) would likely be handled just fine with a usb-type device. For 2) the required=false option we now have on unix-char might work for you, if not, then you'd need #1750

**Comment by sharm294** [comment]
Okay, that addresses the USB then. The PCI ones aren't symlinked though. Do you know what might be going on there?

**Comment by stgraber** [comment]
/sys should be identical on both host and container.

What are you looking at exactly and what's /sys like in host and container.

**Comment by sharm294** [comment]
Here's the full setup: I'm using an FPGA which has a PCI subsystem. I loaded the PCI driver kernel module which creates a number of xdma* devices in /dev. I added a number of these to the container.

The need to rescan arises because when programming the FPGA, the PCI device disappears on the system for a short time. To rescan, I remove the device at /sys/bus/pci/device/ADDR, then rescan, then bind, and unbind the drivers. The physical PCI slot is not changing so it should get enumerated to the same PCI address I believe.

And yes, as far as I could tell with a cursory glance, /sys is the same in the host and container. I see the PCI device at the right path in both.

**Comment by stgraber** [comment]
Can you show "ls -lh /dev" before and after the reset?

**Comment by stgraber** [comment]
in the host and in the container

**Comment by stgraber** [comment]
I suspect the major/minor will change or the device will turn into a plain file when unplugged from the host.

**Comment by sharm294** [comment]
Here you go. I added (selected) output of /dev/ and the output of attempting to read via the PCI device for each of the different steps of the process. 

## Initial

### Container
crw-rw-rw- 1 root   root    231,  36 Apr 30 18:45 xdma0_c2h_0
crw-rw-rw- 1 root   root    231,  32 Apr 30 18:45 xdma0_h2c_0
crw-rw-rw- 1 root   root    231,   0 Apr 30 18:45 xdma0_user
Read 32-bit value at address 0x00080000 (0x7f9a639e8000): 0x00000000

### Host
crw------- 1 root   root      231,  36 Apr 30 14:38 xdma0_c2h_0
crw------- 1 root   root      231,  32 Apr 30 14:38 xdma0_h2c_0
crw------- 1 root   root      231,   0 Apr 30 14:38 xdma0_user
Read 32-bit value at address 0x00080000 (0x7f1b491d0000): 0x00000000

## After Programming the FPGA

### Container

No change in /dev/
Read 32-bit value at address 0x00080000 (0x7f7c210eb000): 0xffffffff

### Host

No change in /dev/
Read 32-bit value at address 0x00080000 (0x7f7f744ac000): 0xffffffff

## After removing the PCI device

### Container

No change in /dev/
Error at line 85, file reg_rw.c (6) [No such device or address]

### Host

No xdma0 devices in /dev/
Error at line 85, file reg_rw.c (2) [No such file or directory]

## After rescanning PCI

### Container

No change in /dev/
Error at line 85, file reg_rw.c (6) [No such device or address]

### Host

crw------- 1 root   root      230,  36 Apr 30 15:16 xdma0_c2h_0
crw------- 1 root   root      230,  32 Apr 30 15:16 xdma0_h2c_0
crw------- 1 root   root      230,   0 Apr 30 15:16 xdma0_user
Read 32-bit value at address 0x00080000 (0x7fae1035f000): 0x00000000

## After unbinding the drivers

### Container

No change

### Host

<no xdma0 devices in /dev/>
Error at line 85, file reg_rw.c (2) [No such file or directory]

## After binding the drivers

### Container

No change

### Host

crw------- 1 root   root      230,  36 Apr 30 15:16 xdma0_c2h_0
crw------- 1 root   root      230,  32 Apr 30 15:16 xdma0_h2c_0
crw------- 1 root   root      230,   0 Apr 30 15:16 xdma0_user
Read 32-bit value at address 0x00080000 (0x7fae1035f000): 0x00000000

## After re-adding the devices to the container

### Container

No change in /dev/
Read 32-bit value at address 0x00080000 (0x7f5348a9c000): 0x00000000

### Host

No change

**Comment by stgraber** [comment]
Ok, so your major is in fact changing from 231 to 230 during this time.

**Comment by stgraber** [comment]
So the device in the container points to a major which is no longer in use, explaining the problem.

**Comment by stgraber** [comment]
Getting you on LXD 3.0 would get you out of all of those problems, so assuming you're not completely tied to 2.0.x for some reason, I'd recommend you do:

1) Get you on the latest bugfix release for LXD 2.0.x (2.0.11):
 - apt update
 - apt install lxd lxd-client

2) Install the LXD snap
 - snap install lxd --channel=3.0

3) Move your data over to the snap and cleanup:
 - lxd.migrate

Once done, you can remove your existing unix-char devices and udev hacks and instead just do:
 - lxc config device add NAME fpga-usb usb vendorid=VENDORID
 - lxc config device add NAME fpga-c2h unix-char path=/dev/xdma0_c2h_0 required=false
 - lxc config device add NAME fpga-h2c unix-char path=/dev/xdma0_h2c_0 required=false
 - lxc config device add NAME fpga-user unix-char path=/dev/xdma0_user required=false

With that, everything will be hotplug and will appear/disappear in the container as they change on the host.


If you need to stick to 2.0.x for some reason, then you should just use udev rules to manage all those devices, doing the relevant `lxc config device add` and `lxc config device remove` calls for all of them so that they get deleted and recreated as needed.

**Comment by sharm294** [comment]
Ah, yes I see that. I wasn't paying attention to the major/minor numbers for PCI because the path stayed the same unlike in the USB case. Hypothetically, if the major/minor numbers also stayed constant, would you expect any problems in passing the device through to the container, even though it disappears and comes back?

I've been eyeing 3.0 since it came out, in particular the hot-plugging! Unfortunately, I can't upgrade yet because of dependencies in OpenStack and nova-lxd.

Okay, I'll add some udev rules to run scripts on the host. Thanks for your help!

**Comment by stgraber** [comment]
if they stayed constant, things should work fine.

**Comment by stgraber** [comment]
Closing the issue as I think we've gotten to the bottom of it now :)
