### ISSUE TITLE
Container name-ip resolution on the host (and guests too)

### ISSUE THREAD

**Issue by killua-eu** [lxc/lxd#4625]
I'm looking for a simple/stable way how to enable the host to resolve containers by their name.

```
root@lxdhost02:/# lxc list
+------+---------+----------------------+------+------------+-----------+----------+
| NAME |  STATE  |         IPV4         | IPV6 |    TYPE    | SNAPSHOTS | LOCATION |
+------+---------+----------------------+------+------------+-----------+----------+
| c1   | RUNNING | 240.102.0.129 (eth0) |      | PERSISTENT | 0         | kai02    |
+------+---------+----------------------+------+------------+-----------+----------+
root@lxdhost02:/# ping c1
ping: c1: Temporary failure in name resolution
```

parsing the ip from lxc list and adding it to /etc/hosts doesn't feel right, so I suppose I'm not seeing something obvious. The same would be a nice-to-have inside containers as well. Thanks for any advice.

Running lxd 3, ubuntu 18.04.

**Comment by stgraber** [comment]
More of a question for https://discuss.linuxcontainers.org than a bug report against LXD.

So you seem to be using LXD with clustering and a FAN bridge, that makes things somewhat annoying because you technically have one DNS/DHCP server per server which doesn't know about anything that's on the others.

So you'd want to configure dnsmasq or resolved (whatever you use on your system) to query DNS records for the `lxd` domain against the `.1` address of each of your servers.

For your c1 container, the DNS server of the host it's connected to will be at 240.102.0.1 so if you had that setup for the `lxd` domain in your resolver, `c1.lxd` would then resolve to 240.102.0.129.

(You can confirm that part with `host c1.lxd 240.102.0.1`)

Unfortunately LXD can't make this magically sync between machines because it itself has no idea what the IP addresses of the various containers are. `lxc list` shows you that information, but it's literally pulled out of the containers network stack as you run the command and there's no guarantee that the container won't change its address a few milliseconds later nor is there any kernel notification mechanism that'd directly tell LXD should that happen.
