### ISSUE TITLE
LXC Cluster - Remove Nodes - LXC unresponsive

### ISSUE THREAD

**Issue by rauvolaj** [lxc/lxd#4646]
# Required information

 * Distribution: 
 **Welcome to Ubuntu 18.04 LTS (GNU/Linux 4.15.0-23-generic x86_64)**
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version: **3.0**
   * LXD version: **3.0** 
   * Storage backend in use: **zfs**

# Issue description

**Setup clustering host on machine A with two other machines (B & C) joining the cluster and working perfectly. Removed machines B & C from network. Now machine A is unresponsive to all lxc commands**

# Steps to reproduce

**1) create cluster host
2) add two machines to cluster
3) Remove added machines from network**

# Information to attach
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
**lvl=info msg="LXD 3.0.0 is starting in normal mode" path=/var/lib/lxd t=2018-06-13T14:10:44+0000
lvl=info msg="Kernel uid/gid map:" t=2018-06-13T14:10:44+0000
lvl=info msg=" - u 0 0 4294967295" t=2018-06-13T14:10:44+0000
lvl=info msg=" - g 0 0 4294967295" t=2018-06-13T14:10:44+0000
lvl=info msg="Configured LXD uid/gid map:" t=2018-06-13T14:10:44+0000
lvl=info msg=" - u 0 100000 65536" t=2018-06-13T14:10:44+0000
lvl=info msg=" - g 0 100000 65536" t=2018-06-13T14:10:44+0000
lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2018-06-13T14:10:44+0000
lvl=info msg="Initializing database gateway" t=2018-06-13T14:10:44+0000
lvl=info msg="LXD is socket activated" t=2018-06-13T14:10:44+0000
lvl=info msg="Starting /dev/lxd handler:" t=2018-06-13T14:10:44+0000
lvl=info msg=" - binding devlxd socket" socket=/var/lib/lxd/devlxd/sock t=2018-06-13T14:10:44+0000
lvl=info msg="REST API daemon:" t=2018-06-13T14:10:44+0000
lvl=info msg=" - binding Unix socket" socket=/var/lib/lxd/unix.socket t=2018-06-13T14:10:44+0000
lvl=info msg=" - binding TCP socket" socket=192.168.0.128:8443 t=2018-06-13T14:10:44+0000**

 - [ ] Output of the client with --debug
**lxc info --debug
DBUG[06-13|14:29:25] Connecting to a local LXD over a Unix socket
DBUG[06-13|14:29:25] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0
HIt Ctrl+C after 8 mins of nothing**      

- [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
**sudo lxd --debug --group lxd                                                                                                                        DBUG[06-13|14:49:42] Connecting to a local LXD over a Unix socket
DBUG[06-13|14:49:42] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0
INFO[06-13|14:50:45] LXD 3.0.0 is starting in normal mode     path=/var/lib/lxd
INFO[06-13|14:50:45] Kernel uid/gid map:
INFO[06-13|14:50:45]  - u 0 0 4294967295
INFO[06-13|14:50:45]  - g 0 0 4294967295
INFO[06-13|14:50:45] Configured LXD uid/gid map:
INFO[06-13|14:50:45]  - u 0 100000 65536
INFO[06-13|14:50:45]  - g 0 100000 65536
WARN[06-13|14:50:45] CGroup memory swap accounting is disabled, swap limits will be ignored.
INFO[06-13|14:50:45] Initializing database gateway
INFO[06-13|14:50:45] LXD isn't socket activated
DBUG[06-13|14:50:45] Connecting to a local LXD over a Unix socket
DBUG[06-13|14:50:45] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0
again sent interupt after about 8 mins**

**Comment by rauvolaj** [comment]
I am really just after the images I created on Machine A. Is there a manual way to export images? Just a simple scp from /var/lib/lxd/images to same folder on another LXD instance?

Or move them out of /var/lib/lxd/images, reinstall lxd with snap, and place images back in folder?

**Comment by freeekanayaka** [comment]
Unfortunately you can't just remove nodes from the network without declaring them as removed in the cluster database (since they're needed for a quorum). So the workflow to remove a node is:

lxc cluster delete <node name>

(possibly with the --force option if the node has dead or is unresponsive).

See also https://github.com/lxc/lxd/blob/master/doc/clustering.md#managing-a-cluster

**Comment by freeekanayaka** [comment]
As for recovery, I think what you described should work, but it might depend on the storage backend you used. @brauner and @stgraber might be able provide more info.

**Comment by rauvolaj** [comment]
Thank you for the quick reply! Yeah, I noticed the lxc cluster delete after the fact. 

When I try to run that command 'lxc cluster delete --force' as it sits now; is just met with no response.

If I just copy the images from /var/lib/lxd/images where would I place them on the SNAP version of lxd for them to be recognized?

Again, thank you for the responses

**Comment by freeekanayaka** [comment]
The fact that lxc cluster delete is unresponsive is expected, because you lost the majority of your nodes and the remaining node can't reach a quorum to perform the state change. Eventually we should introduce some disaster recovery tooling, but we haven't yet. For now, we assume that your cluster always have a quorum of nodes, and that if you remove nodes you do so with 'lxc cluster (--force) delete'.

**Comment by rauvolaj** [comment]
Sounds good, I’m going to try the copying of images and post results before I close issue. Just incase someone stumbles on this.

**Comment by stgraber** [comment]
@rauvolaj

**Comment by danmur** [comment]
I hate to reopen an old issue but this is the closest thing I can find to my problem - can I just ask, what is supposed to happen if you lose enough nodes to not have a quorum? I've had this twice now, seemingly due to snap auto upgrades, and I just can't find any way to recover apart from starting over from scratch. I'm just testing in my home network, so not super concerned, but I feel like I'm missing something. Most other software I've worked with has some way to force a surviving node into being the master, and then I would add new nodes to bring the cluster back to normal. Is there no way to do this?

**Comment by stgraber** [comment]
@freeekanayaka
