### ISSUE TITLE
LXD cross compilation build failure for ARM machines.

### ISSUE THREAD

**Issue by satishnaidu** [lxc/lxd#4667]
# Required information

 * Distribution: Ubuntu ( Build environment)
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-1061-aws
   * LXC version:  from master branch
   * LXD version:  from master branch

# Issue description

I am trying to build LXD for ARM machine using GO cross-compilation. I followed all the steps in README of https://github.com/lxc/lxd, and try to build the source using the following command.

$ sudo GOOS=linux GOARCH=arm make

Build failed with following error:

ubuntu@ip-10-0-8-37:~/go/src/github.com/lxc/lxd$ sudo GOARCH=arm GOOS=linux make
go get -t -v -d ./...
go install -v   ./...
github.com/gosexy/gettext
go build github.com/gosexy/gettext: build constraints exclude all Go files in /home/ubuntu/go/src/github.com/gosexy/gettext
github.com/lxc/lxd/shared
github.com/CanonicalLtd/go-sqlite3
-#github.com/CanonicalLtd/go-sqlite3
../../CanonicalLtd/go-sqlite3/sqlite3_go18.go:18:10: undefined: SQLiteConn
-# github.com/lxc/lxd/shared
shared/archive_linux.go:79:15: undefined: DeviceTotalMemory
shared/network_linux.go:20:9: undefined: ExecReaderToChannel
Makefile:21: recipe for target 'default' failed
make: *** [default] Error 2

# Steps to reproduce

 1. Step one: go get -d -v github.com/lxc/lxd/lxd
 2. Step two: cd $GOPATH/src/github.com/lxc/lxd
 3. Step three: sudo GOOS=linux GOARCH=arm make

Can you help to build LXD for ARM-based machines, currently I want to run this LXD binary on RaspberryPi with OpenWRT operating system build using Yocto.

**Comment by stgraber** [comment]
I don't believe the LXD daemon can be cross-compiled, at least it's not something we support.

The reason why that is is because LXD makes extensive use of CGo and so requires headers and linking against external libraries. I suspect you'd need a full copy of those libraries and all dependencies for the target architecture and then find a way to tell Go to include and link against those, which would then get you past those errors.

All the errors you see above are related to you using a Go compiler with CGo disabled.
