### ISSUE TITLE
Receiving 'container-shutdown' event instead of 'container-stopped'

### ISSUE THREAD

**Issue by rmescandon** [lxc/lxd#4691]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 16.04.4 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.13.0-38-generic
   * LXC version: 3.1
   * LXD version: 3.0.0.beta7
   * Storage backend in use: zfs

# Issue description

I'm listening for container events, as described here https://github.com/lxc/lxd/issues/4322. When I execute `lxc stop <thecontainername>` i receive "container-shutdown" instead of "container-stopped". Is that correct? I see in the source code that there are different methods Stop or Shutdown for a container. What's the difference?

# Steps to reproduce

 1. Create a websocket client and listen for LXD cluster events
 2. Stop a container with `lxc stop <containername>`
 3. Trace received event and see that metadata.action value is "container-shutdown" when "container-stopped" is expected

**Comment by brauner** [comment]
You would get a `container-stopped` event on `lxc stop -f <container-name>` if I'm not misremembering. From LXC's perspective the difference is between initiating a clean shutdown of the container's init system by sending it an appropriate signal it can respond to (e.g. `SIGRTMIN+3` for `systemd`) which will result in `container-shutdown` vs sending a deadly signal that the init system in the container cannot handle which will instantaneously kill the container, i.e. sending `SIGKILL`. The latter method is usually only used when the container's init system is not responsive anymore and the container needs to be forced to stop or when a near instantaneous stop is needed and the user is not worried about potential data loss caused by this.
