### ISSUE TITLE
Can not start lxd due to non existent storage pool

### ISSUE THREAD

**Issue by noalphakamp** [lxc/lxd#4710]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-23-generi
   * LXC version: 3.0.1
   * LXD version: 3.0.1
   * Storage backend in use:zfs

# Issue description
Can not start lxd due to non existent storage pool (juju-zfs).  I had started a conjure-up install (kubernetes), that failed, and I removed all relative containers and pools.  I also have existing storage-pools and containers sitting on plain lxc/lxd.  Where the problem has begun, my computer lost power and now when booting up the local.db must still have reference to juju-zfs zpool.  

I dont think this is a realistically reproducible scenario. I just need help cleaning my db to remove the juju-zfs reference   I am familiar with sqlite3 or sqlitebrowser, but with the introduction to raft/dqlite...

**Comment by stgraber** [comment]
Easiest way out of this is usually to just create a temporary pool, that'll unstick LXD, then you can delete the various objects through the LXD CLI and then destroy your pool.

```sh
truncate -s 1GB /tmp/zfs.img
zpool create juju-zfs /tmp/zfs.img
```

Then start LXD (`systemctl start lxd.service`).

Delete any containers with `lxc delete`, then look for any volume left in the pool with `lxc storage volume list juju-zfs`, for any of those, delete them with `lxc storage volume delete`, once all clean, you can do `lxc storage delete juju-zfs`.

After that LXD cleanup, remove the temporary pool with:

```sh
zpool destroy juju-zfs
rm /tmp/zfs.img
```

Closing as there's no actual bug to fix in LXD here. It's intentional that LXD will refuse to start if it can't find storage pools as those occasionally require manual admin intervention to appear and starting things without the pool being mounted may caused data corruption.

Let us know if the instruction above aren't sufficient.

**Comment by noalphakamp** [comment]
Thank you, that worked, I appreciate it.
