### ISSUE TITLE
USB device appears partially in the container

### ISSUE THREAD

**Issue by rajil** [lxc/lxd#4742]
# Required information

 * Distribution: Gentoo
 * Distribution version: 
 * The output of "lxc info" or if that fails:
   * Kernel version:4.9.95-gentoo
   * LXC version: 3.2
   * LXD version: 3.2
   * Storage backend in use: ZFS

# Issue description

A webcam added to the container does not create /dev/video0 in the container.

# Steps to reproduce

 1. Step one
`lxc config device add zmvm webcam0 usb vendorid=045e productid=076d required=false
` 
2. Step two

Probing the device details in the container does not show all the details.

```
$ lxc exec zmvm /bin/bash
root@zmvm:~# udevadm info --name /dev/bus/usb/004/002
P: /devices/pci0000:00/0000:00:14.0/usb4/4-10
N: bus/usb/004/002
E: BUSNUM=004
E: DEVNAME=/dev/bus/usb/004/002
E: DEVNUM=002
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb4/4-10
E: DEVTYPE=usb_device
E: DRIVER=usb
E: MAJOR=189
E: MINOR=385
E: PRODUCT=45e/76d/103
E: SUBSYSTEM=usb
E: TYPE=239/2/1
```

With the container running the same device shows up more information on the host.
```
# udevadm info --name /dev/bus/usb/004/002 
P: /devices/pci0000:00/0000:00:14.0/usb4/4-10
N: bus/usb/004/002
E: BUSNUM=004
E: DEVNAME=/dev/bus/usb/004/002
E: DEVNUM=002
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb4/4-10
E: DEVTYPE=usb_device
E: DRIVER=usb
E: ID_BUS=usb
E: ID_MODEL=Microsoft®_LifeCam_HD-5000
E: ID_MODEL_ENC=Microsoft®\x20LifeCam\x20HD-5000
E: ID_MODEL_FROM_DATABASE=LifeCam HD-5000
E: ID_MODEL_ID=076d
E: ID_REVISION=0103
E: ID_SERIAL=Microsoft_Microsoft®_LifeCam_HD-5000
E: ID_USB_INTERFACES=:0e0100:0e0200:010100:010200:
E: ID_VENDOR=Microsoft
E: ID_VENDOR_ENC=Microsoft
E: ID_VENDOR_FROM_DATABASE=Microsoft Corp.
E: ID_VENDOR_ID=045e
E: MAJOR=189
E: MINOR=385
E: PRODUCT=45e/76d/103
E: SUBSYSTEM=usb
E: TYPE=239/2/1
E: USEC_INITIALIZED=6635511
```

The container does not create the /dev/video0 device for the webcam.

**Comment by brauner** [comment]
This is pretty difficult to figure out as the device is created in the hosts's `devtmpfs` and `/dev/video0` is an additional device node created on device hotplug. You can add the `/dev/video` device manually though.

**Comment by rajil** [comment]
Is it acceptable for udevadm to show less information in the container?

**Comment by stgraber** [comment]
Yeah, I suspect that's because udevd in the container never received the full uevent in the first place and so never created a proper database entry. That's something that recent kernel work should improve as we should soon be able to forward uevents into the container as usb devices are added and removed.

Closing the issue as LXD is working as expected here. A `usb` device only refers to the /dev/bus/usb entries to be used by libusb. For other devices, unix-char and unix-block are a better fit.

In this case: lxc config device add name video unix-char path=/dev/video0 required=false
