### ISSUE TITLE
Use configurable path for ebtables

### ISSUE THREAD

**Issue by geaaru** [lxc/lxd#4918]
On gentoo/sabayon distro ebtables command is now directly supplied by >iptables-1.6.1 package with name ebtables-compat.

Could be fine change *lxd/container_lxc.go* to use command ebtables from a configurable parameter.

WDYT ?

I try to do a pr for this if is ok ?

**Comment by stgraber** [comment]
That doesn't really make sense, the package should just ship a symlink so that all existing scripts and software keeps running properly.

**Comment by geaaru** [comment]
Yeah, I agreed with this but could be correct use a configurable absolute path of ebtables path ? Or also on this case you think to fix this eventually through initialization of PATH environment variable before start LXD ?

I think that symlink is not present because binary for nftables integration are now with that suffix. If it is enable nftables integration probably team create these binaries to help maintainer on migration to nft:

https://manpages.debian.org/testing/iptables-nftables-compat/ebtables-compat.8.en.html

So, probably the right question is how you want handle with LXD nftables integration ? With directly handler with different interfaces based of user option configuration or with tools for now compliants with classic ebtables/iptables binary ?

Thanks for your time.

**Comment by stgraber** [comment]
So LXD doesn't call those tools using hardcoded paths and so respect PATH. I'd expect a compatibility package to actually be compatible with what it replaces, that doesn't seem to be the case here and so I believe is a bug of that particular package and not something we should fix in LXD.

So far for nftables, we've decided not to spend any time working on directly driving the new tools until Ubuntu and Debian decide to begin the transition, do the needed security reviews, ... Since there are compatibility tools, those that are already running nftables should be able to just install those and have LXD work as normal.
