### ISSUE TITLE
Cannot stop debian stretch container

### ISSUE THREAD

**Issue by cquike** [lxc/lxd#4939]
# Required information

 * Distribution: Ubuntu 
 * Distribution version:18.04
 
apt packages: 

ii  liblxc-common                         3.0.1-0ubuntu1~18.04.2               amd64        Linux Containers userspace tools (common tools)
ii  liblxc1                               3.0.1-0ubuntu1~18.04.2               amd64        Linux Containers userspace tools (library)
ii  lxcfs                                 3.0.1-0ubuntu2~18.04.1               amd64        FUSE based filesystem for LXC
ii  lxd                                   3.0.1-0ubuntu1~18.04.1               amd64        Container hypervisor based on LXC - daemon
ii  lxd-client                            3.0.1-0ubuntu1~18.04.1               amd64        Container hypervisor based on LXC - client

# Issue description

I am trying to use a debian stretch container but it fails to stop, since the lxc stop command hangs indefinitely . The only way to stop is using lxc stop -f. The image is one of the official images from images.linuxcontainers.org.

# Steps to reproduce

 1. lxc init images:debian/stretch/amd64 test-debian
 2. lxc start test-debian
 3. lxc stop test-debian

**Comment by cquike** [comment]
[lxc_info.txt](https://github.com/lxc/lxd/files/2297720/lxc_info.txt)
[lxc_stop_debug.log](https://github.com/lxc/lxd/files/2297738/lxc_stop_debug.log)

[lxc_config_test_debian.txt](https://github.com/lxc/lxd/files/2297713/lxc_config_test_debian.txt)

**Comment by cquike** [comment]
I have attached some logs in case that's useful.

Also, I have tried to execute a shell while the stop command is hanging and I can see the following messages from journalctl:

Aug 17 15:12:53 test-debian systemd[1]: systemd-networkd.service: Failed to reset devices.list: Operation not permitted
Aug 17 15:12:53 test-debian systemd[1]: systemd-networkd.service: Failed to set invocation ID on control group /system.slice/systemd-networkd.service, ignoring: Operation not permitt
ed
Aug 17 15:12:53 test-debian systemd[1]: Starting Network Service...
Aug 17 15:12:53 test-debian systemd[1]: Stopped Load Kernel Modules.
Aug 17 15:12:53 test-debian systemd-networkd[140]: Could not connect to bus: Connection refused
Aug 17 15:12:53 test-debian systemd[1]: systemd-networkd.service: Main process exited, code=exited, status=1/FAILURE
Aug 17 15:12:53 test-debian systemd[1]: Failed to start Network Service.
Aug 17 15:12:53 test-debian systemd[1]: systemd-networkd.service: Unit entered failed state.
Aug 17 15:12:53 test-debian systemd[1]: systemd-networkd.service: Failed with result 'exit-code'.
Aug 17 15:12:53 test-debian systemd[1]: systemd-networkd.service: Service has no hold-off time, scheduling restart.
Aug 17 15:12:53 test-debian systemd[1]: Stopped Network Service.
Aug 17 15:12:53 test-debian systemd[1]: systemd-networkd.service: Failed to reset devices.list: Operation not permitted
Aug 17 15:12:53 test-debian systemd[1]: systemd-networkd.service: Failed to set invocation ID on control group /system.slice/systemd-networkd.service, ignoring: Operation not permitt
ed
Aug 17 15:12:53 test-debian systemd[1]: Starting Network Service...
Aug 17 15:12:53 test-debian systemd-networkd[141]: Could not connect to bus: Connection refused

Those messages get repeated a handful of times.

**Comment by stgraber** [comment]
And sid isn't affected, so I think it's a systemd bug that's since been resolved.

Closing this issue as it doesn't appear to be anything that we can fix directly in LXD and systemd itself appears to have already been fixed in more recent versions. The masking of systemd-networkd is probably a good enough workaround for now.

**Comment by iuridiniz** [comment]
You can also switch to sysvinit 
But lxc stop will not work If /etc/init.d/powerfail os missing

**Comment by T-X** [comment]
I was also running 

> And sid isn't affected, so I think it's a systemd bug that's since been resolved.
> 
> Closing this issue as it doesn't appear to be anything that we can fix directly in LXD and systemd itself appears to have already been fixed in more recent versions. The masking of systemd-networkd is probably a good enough workaround for now.

I was also running into this issue with Debian Stretch/stable here. With just masking systemd-networkd, container startup would take 2 minutes (journalctl -b: "Startup finished in 2min 1.810s"). The reason was a waiting and then failing "systemd-networkd-wait-online.service" which other services wait to finish for first.

After masking systemd-networkd-wait-online.service, too, I generally could reduce the startup time to about 8 seconds (journalctl -b: "Startup finished in 7.725s.").

However, sometimes it would take a bit longer due to dev-aux-custom_data.seafile.device failing:
<pre><code>$ journalctl -u dev-aux-custom_data.seafile.device
Jan 23 02:55:52 seafile systemd[1]: dev-aux-custom_data.seafile.device: Job dev-aux-custom_data.seafile.device/start timed out with result 'timeout'.
Jan 23 02:55:52 seafile systemd[1]: Timed out waiting for device dev-aux-custom_data.seafile.device.
Jan 23 02:55:52 seafile systemd[1]: dev-aux-custom_data.seafile.device: Job dev-aux-custom_data.seafile.device/start failed with result 'timeout'.

journalctl -b: "Startup finished in 1min 30.862s."
</code></pre>

However, this device seems to get mounted successfully nevertheless. So despite the longer boot time, seemingly no other issues.
