### ISSUE TITLE
Gettext Build Error

### ISSUE THREAD

**Issue by systmkor** [lxc/lxd#496]
## Environment ##

 * Alpine Linux 3.1.19
 * musl-1.1.5 (libc)
 * gettext-0.19.3 (gnu)
 * go-1.3.3
 * lxd commit lxc/lxd@75a7f053c2e981dc1ca5cf5ebdc5fa49bfcf7ade

## Error ##
After running make or trying to just run go get github.com/lxc/lxd . The gettext errors are produced as shown below.

```shell
go install -v ./...
github.com/gosexy/gettext
# github.com/gosexy/gettext
/tmp/go-build282493908/github.com/gosexy/gettext/_obj/gettext.cgo2.o: In function `_cgo_b28bc486a664_Cfunc_bind_textdomain_codeset':
../../gosexy/gettext/gettext.go:61: undefined reference to `libintl_bind_textdomain_codeset'
/tmp/go-build282493908/github.com/gosexy/gettext/_obj/gettext.cgo2.o: In function `_cgo_b28bc486a664_Cfunc_bindtextdomain':
../../gosexy/gettext/gettext.go:72: undefined reference to `libintl_bindtextdomain'
/tmp/go-build282493908/github.com/gosexy/gettext/_obj/gettext.cgo2.o: In function `_cgo_b28bc486a664_Cfunc_dcgettext':
../../gosexy/gettext/gettext.go:85: undefined reference to `libintl_dcgettext'
/tmp/go-build282493908/github.com/gosexy/gettext/_obj/gettext.cgo2.o: In function `_cgo_b28bc486a664_Cfunc_dcngettext':
../../gosexy/gettext/gettext.go:100: undefined reference to `libintl_dcngettext'
/tmp/go-build282493908/github.com/gosexy/gettext/_obj/gettext.cgo2.o: In function `_cgo_b28bc486a664_Cfunc_dgettext':
../../gosexy/gettext/gettext.go:111: undefined reference to `libintl_dgettext'
/tmp/go-build282493908/github.com/gosexy/gettext/_obj/gettext.cgo2.o: In function `_cgo_b28bc486a664_Cfunc_dngettext':
../../gosexy/gettext/gettext.go:124: undefined reference to `libintl_dngettext'
/tmp/go-build282493908/github.com/gosexy/gettext/_obj/gettext.cgo2.o: In function `_cgo_b28bc486a664_Cfunc_gettext':
../../gosexy/gettext/gettext.go:143: undefined reference to `libintl_gettext'
/tmp/go-build282493908/github.com/gosexy/gettext/_obj/gettext.cgo2.o: In function `_cgo_b28bc486a664_Cfunc_ngettext':
../../gosexy/gettext/gettext.go:155: undefined reference to `libintl_ngettext'
/tmp/go-build282493908/github.com/gosexy/gettext/_obj/gettext.cgo2.o: In function `_cgo_b28bc486a664_Cfunc_textdomain':
../../gosexy/gettext/gettext.go:177: undefined reference to `libintl_textdomain'
collect2: error: ld returned 1 exit status
Makefile:15: recipe for target 'default' failed
make: *** [default] Error 2

```

**Comment by stgraber** [comment]
Hmm, that issue should probably have been filed against gosexy/gettext rather than here since it's not code we own.

Looking at it quickly, it looks like musl doesn't implement libintl at all so none of the gettext functions are present for musl users. That means that there's nothing gosexy/gettext can do about it since that go project is a straight libc binding, if the underlying libc is incomplete, then it'll just fail to build.

As for LXD, translation support for our client is much more important to us than supporting a less common (and apparently incomplete) C library, so unfortunately, short of switching to glibc or some other more complete C library, you're out of luck.

**Comment by stgraber** [comment]
So still the wrong place for this bug, but the error still suggests that you had a C header for those functions, it's just the linker failing somehow.

I wonder if adding -lintl as a linker flag would solve that. I'll give it a quick try (I can't test it since I don't use musl, but I can make sure it still builds with glibc at least).

**Comment by stgraber** [comment]
Hmm, unfortunately that's not very fixable with Go...

Passing -lintl on a glibc system makes the build fail (because it's built-in). And Go doesn't support any kind of detection for the cgo LDFLAGS...

However it looks like you can set CGO_LDFLAGS in the environment to get cgo to use extra flags.

Can you try running:

env CGO_LDFLAGS=-lintl go install -v ./...

See if that somehow helps?

**Comment by systmkor** [comment]
### Thank You ###
Thank you for your very prompt reply. After reading your reply, I agree this isn't the right place for requesting a fix. I just wanted to post a notice that I ran into an issue of trying to compile and let the developers make of the information of what they wish. :smile: 

### Compile Success ###
I tried your suggestion and it compiles! Thanks :smile: 

### Runtime Error ###
Despite the successful compile, now I'm getting a malloc error. No need to re-open or for me to post a new issue until I investigate this further.

```shell
fatal error: runtime: C malloc failed

goroutine 16 [running]:
runtime.throw(0xf17908)
	/usr/lib/go/src/pkg/runtime/panic.c:520 +0x69 fp=0xc208065d28 sp=0xc208065d10
runtime.cmalloc(0xffffffffffffffff)
	/usr/lib/go/src/pkg/runtime/cgocall.c:185 +0x5d fp=0xc208065d50 sp=0xc208065d28
github.com/lxc/lxd/shared._Cfunc__CMalloc(0xffffffffffffffff, 0xffffffffffffffff)
	github.com/lxc/lxd/shared/_obj/_cgo_defun.c:42 +0x27 fp=0xc208065d60 sp=0xc208065d50
github.com/lxc/lxd/shared.GroupName(0x3e9, 0x0, 0x0, 0x0, 0x0)
	/home/admin/gocode/src/github.com/lxc/lxd/shared/util.go:416 +0x9e fp=0xc208065e30 sp=0xc208065d60
main.init·1()
	/home/admin/gocode/src/github.com/lxc/lxd/lxd/main.go:32 +0x33 fp=0xc208065ef8 sp=0xc208065e30
main.init()
	/home/admin/gocode/src/github.com/lxc/lxd/lxd/response.go:205 +0x99f fp=0xc208065f50 sp=0xc208065ef8
runtime.main()
	/usr/lib/go/src/pkg/runtime/proc.c:240 +0xda fp=0xc208065fa8 sp=0xc208065f50
runtime.goexit()
	/usr/lib/go/src/pkg/runtime/proc.c:1445 fp=0xc208065fb0 sp=0xc208065fa8
created by _rt0_go
	/usr/lib/go/src/pkg/runtime/asm_amd64.s:97 +0x120

goroutine 17 [runnable]:
runtime.MHeap_Scavenger()
	/usr/lib/go/src/pkg/runtime/mheap.c:507
runtime.goexit()
	/usr/lib/go/src/pkg/runtime/proc.c:1445

goroutine 18 [runnable]:
bgsweep()
	/usr/lib/go/src/pkg/runtime/mgc0.c:1976
runtime.goexit()
	/usr/lib/go/src/pkg/runtime/proc.c:1445

goroutine 19 [runnable]:
runfinq()
	/usr/lib/go/src/pkg/runtime/mgc0.c:2606
runtime.goexit()
	/usr/lib/go/src/pkg/runtime/proc.c:1445

goroutine 20 [runnable]:
os/signal.loop()
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:19
created by os/signal.init·1
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 17 [syscall]:
runtime.goexit()
	/usr/lib/go/src/pkg/runtime/proc.c:1445

```
