### ISSUE TITLE
LXD Image Storage using /var/lib/lxd when default storage is zpool

### ISSUE THREAD

**Issue by elbrinke** [lxc/lxd#4984]
# Required information

 * Distribution: **Ubuntu** 
 * Distribution version: **18.04**
 * The output of "lxc info" or if that fails:
   * Kernel version: **4.15.0-32-generic**
   * LXC version: **3.0.1**
   * LXD version: **3.0.1**
   * Storage backend in use: **zfs**

# Issue description

I created a zfs zpool from an LVM logical drive and called it **lxd**.  When i store lxd container images, it seems to go to the /var/lib/lxd on /root and not the zfs  zpool. 

# Steps to reproduce

 1. Created zfs pool called: **services** with dataset: **lxd**
 2. I setup LXD storage to point to existing zfs zpool/database
`lxc storage create containers zfs source=services/lxd`
 3. This setup the following zfs file structure:
```
services                                                                                                                                              
services/lxd                                                                         
services/lxd/containers                                                              
services/lxd/containers/jupyterhub                                                                                                     
services/lxd/custom                                                                  
services/lxd/deleted                                                                 
services/lxd/images                                                                  
services/lxd/snapshots                                                               
services/lxd/snapshots/jupyterhub    
```                                                                                                     
However, when i send container images to this server, i see the **/root** directory being used. 

How can i get container images to store on the zpool that was specified?

**Comment by stgraber** [comment]
So that's expected behavior, LXD stores the original image files under /var/lib/lxd/images regardless of storage pool configuration. The storage pools then get fed an optimized version of the image (in ZFS's case a dataset) as needed for container creation.

What you can do in your case is something like:
 - systemctop stop lxd
 - mv /var/lib/lxd/images /var/liblxd/images.tmp
 - zfs create services/lxd-images -o mountpoint=/var/lib/lxd/images
 - mv /var/lib/lxd/images.tmp/* /var/lib/lxd/images
 - rmdir /var/lib/lxd/images.tmp

So effectively creating a new dataset, outside of the one used for your storage pool (as you should always be able to delete a storage pool without deleting the image store), mounting that in place and moving any existing content over.
