### ISSUE TITLE
LXD ZFS Storage Issue

### ISSUE THREAD

**Issue by elbrinke** [lxc/lxd#4999]
# Required information

 * Distribution: **Ubuntu** 
 * Distribution version: **18.04**
 * The output of "lxc info" or if that fails:
   * Kernel version: **4.15.0-32-generic**
   * LXC version: **3.0.1**
   * LXD version: **3.0.1**
   * Storage backend in use: **zfs**

# Issue description
Lxd does not store **_images_** and **_snapshots_** into the configured zfs zpool by default. 

# Steps to reproduce

 1. Install ZFS on Ubuntu 18.04
 2. Created zfs pool "**services**". 
 3. Created zfs dataset "**services/lxd**"
 4. Use the existing ZFS dataset "**services/lxd**".

`lxc storage create containers zfs source=services/lxd`

### ZFS Ouput:
```
services/lxd                                                                          30.0G  39.2G    96K  none
services/lxd/containers
services/lxd/containers/rstudio                                                       23.7G  39.2G  13.6G  /var/lib/lxd/storage-pools/containers/containers/rstudio
services/lxd/custom                                                                     96K  39.2G    96K  none
services/lxd/deleted                                                                    96K  39.2G    96K  none
services/lxd/images                                                                    712M  39.2G    96K  none
services/lxd/snapshots                                                                 384K  39.2G    96K  none
services/lxd/snapshots/rstudio                                                          96K  39.2G    96K  none
```
As you can see there is no snapshot and no images mount-points. Currently these images and snapshots are stored inside the **"/"** root partition under /var/lib/lxd/images or /var/lib/lxd/snapshots. 

### Question: 
How can we get all the data inside **/var/lib/lxd** to be stored inside the **zfs zpool** configured in lxd? Meaning, that both images and snapshots will also be mounted for external storage? Maybe I am just understanding it wrong. Because the whole idea was that all LXD data would reside inside the zfs pool and NOT inside of root except the standard /var/lib/lxd folder.

**Comment by stgraber** [comment]
This is normal, LXD doesn't mount the images or snapshots so you will not see them in /var/lib/lxd and they will not have mountpoints set.

Snapshots do get mounted for very specific operations, when that happens it gets temporarily mounted under /var/lib/lxd/snapshots.

Image tarballs are always stored in /var/lib/lxd/images on the main partition, that's expected behavior as you should be able to delete storage pools without also loosing all your images. Storage pools only hold "optmized" version of those images (in the ZFS case, a read-only snapshot on a dataset).
