### ISSUE TITLE
Documentation formatting issue: Container Configuration key/value table is too wide.

### ISSUE THREAD

**Issue by jk-1** [lxc/lxd#5031]
# Required information

 * Distribution: 
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version:
   * Storage backend in use:

# Issue description

Please fix the Container Configuration documentation page, key value table:
It is too wide, cannot be printed or saved into pdf even on landscape paper size.
https://github.com/lxc/lxd/blob/master/doc/containers.md

# Steps to reproduce

 1. Go to https://github.com/lxc/lxd/blob/master/doc/containers.md
 2. Print the page
 3. Try to read the last column.

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by simos** [comment]
Hi!

You can get a decent PDF if you use a service like http://www.markdowntopdf.com/
Their workaround is to use smaller font size just for the table so that it fits properly.
Then, the rest of the document has their standard font size. 

In general, the printing of online content that has tables is a difficult task when those tables get too big.
The ReadTheDocs.org service is a service that you point your Github repository and they auto-convert the markdown documentation into online HTML.
They used to offer ZIP files with those HTML files, but they do not do this anymore. They used to support the PDF output, but again they do not do that anymore because there are technical issues that can get the PDF output to fail. And they do not want to support a feature that fails often.

An alternative would be to figure out a way to show the table in a different way. Such as splitting it into two tables. It is more work to keep the tables in sync and it's up to the developers whether to go to that direction.

**Comment by stgraber** [comment]
So we don't have any control over the CSS used by the various websites trying to render our documentation. Injecting line breaks in the middle of markdown tables doesn't work so isn't something we can really do either.

I'd recommend finding a different markdown to PDF converter which treats tables in a way that works better for you. Our goal is for it to remain readable on screen and so far horizontal scrolling has been coping with this reasonably well.

As @simos said, an alternative would be to rework all the documentation to move away from tables and use a different structure, but all the ways I can currently think of would actually make things less readable for users on computers (by making things much longer and much harder to have an overview of all keys).
