### ISSUE TITLE
Suboptimal CPU pinning

### ISSUE THREAD

**Issue by zrav** [lxc/lxd#5055]
I found that the current implementation of CPU assignment/pinning to containers is suboptimal. I'm aware this is probably heavily intertwined with the kernel scheduler, but maybe this is a reasonable feature request.

Currently, after setting a number of CPU cores to a container via limits, the actual cores assigned to a container are randomly pinned during container start. After starting, the assignment does not change (it is randomized with each container startup, though). At the same time, multiple containers are sometimes given the same cores. Since the pinning does not dynamically change depending on load, this leads to situations where some cores are overbooked and running at capacity while others are idling.

Take the following scenario: Assuming a server with 24 cores, if we create and launch three containers with 8 cores each and generate CPU load on them (with the `stress` util, for instance), we can typically see some idle cores on the host side. It would be beneficial to have the scheduler spread the container to all cores, just as it would a regular process. Of course it is possible to manually pin specific cores to containers, but that too is suboptimal, given how typically multiple containers share a core and how loads change dynamically.

Going further, ideally the scheduler would be NUMA-aware, trying to minimize the number of NUMA nodes a given container is spread over.

**Comment by stgraber** [comment]
Re-balancing the containers is pretty costly since a lot of processes need to be moved between CPUs by the scheduler, that's unlike VMs where as far as the kernel is concerned, it usually deals with a single process.

We've found the current scheduler to work well enough at least on systems where CPU isn't heavily over-committed, though NUMA is indeed one of the shortcomings of the current approach (and I'm not sure it's one we're particularly likely to tackle soon).

For more complex cases, you can either do pinning to specific cores yourself, or more likely, you can just allow all cores be used but reduce the amount of CPU time that can be provided to a given container.

Those scheduling budgets usually provide you with the amount of CPU you'd expect, without the downside of being locked to a particular set of cores, the main downside is that userspace in the container may mistakenly think it's got more CPU time available than it actually does.

**Comment by zrav** [comment]
In our particular use case it would be nice if re-balancing happened at all, it doesn't have to be frequent. Maybe provide a parameter to configure re-balancing interval (milliseconds to seconds range) so users can tune it to their loads?

**Comment by stgraber** [comment]
LXD balancing never accounts for load so that wouldn't really help.

The built-in scheduler only tries to spread containers equally between cores and so triggers when containers are started, stopped or when cpus are added or removed.

**Comment by stgraber** [comment]
In your case, I suspect the best course of action is actually to not use direct pinning but instead to use `limits.cpu.allowance` to limit the total CPU time of the container to be 1/3rd of the host.

The percentage based allocation would let you control the behavior when the system is under load while the time based allocation would let you restrict the time even when the machine isn't loaded.
