### ISSUE TITLE
Improved backup & disaster recovery documentation

### ISSUE THREAD

**Issue by akarelas** [lxc/lxd#5113]
I am under the impression that the most efficient method of backing up one's containers would be copying the underlying zfs filesystems (not the entire pool, but the ones relating to each container).

I think that would be efficient, because it allows to "zfs send" only the changes, every few hours, to another server.

It would be nice if that option would be mentioned briefly in the backup doc page of lxd, together with a few very important details such as which directories to "zfs send", and how to then restore the backup after a disaster.

**Comment by stgraber** [comment]
That's what https://github.com/lxc/lxd/blob/master/doc/backup.md#container-backup-and-restore covers, though in pretty generic terms.

Note that we consider this to be mostly disaster recovery and not something we actually recommend.
That's mostly because the usual tooling around ZFS snapshots and send/receive will typically create their own snapshots which may then interfere with LXD's normal operation (copying containers, publishing, migration, delete, ...).

So yes, we do have the backup.yaml file in the container storage, meaning that you can backup just the container storage and then mostly re-create the DB artifacts through `lxd import`, that's what our documentation mentions and that's true for all storage backends. Though relying solely on this for your backups isn't a good idea as you'd still be missing all images, any custom storage volume, profile configuration, network configuration, ... all of which would at least require a DB backup + extra datasets and other on-disk artifact.

So short answer is that we'd rather not document a partial backup solution that may give you mixed results on restore :)
We do know of a number of users that do use such automated zfs backup scripts and depending on what you do with your containers and what LXD features you use, it may be perfectly fine, but it's not something we'd recommend in general.

**Comment by stgraber** [comment]
Actually going to recycle this issue to improve the backup documentation.

The things I think we should cover are:
 - What to backup (database, containers, custom storage volumes)
 - Complete LXD host backup
 - LXD backup host (remote copy of containers and storage volumes)
 - One time container backups (`lxc export` & `lxc import`)
 - Container disaster recovery (`lxd import`)

**Comment by akarelas** [comment]
Thank. These additions you mention to the documentation, would all be very welcome.

**Comment by hyperpress** [comment]
Thanks for addressing these in finer details. Great addition.
