### ISSUE TITLE
LXD does not support RSA-derived ciphers for container image download

### ISSUE THREAD

**Issue by phvalguima** [lxc/lxd#5124]
LXD works with TLS v1.2  with the ciphers defined on:  https://github.com/lxc/lxd/blob/master/shared/network.go#L53

However, some proxies may not have ECDHE-derived ciphers implemented and demand alternatives, such as: TLS_RSA_WITH_AES_256_GCM_SHA384

Is it possible for LXD to be extended to offer RSA-derived ciphers as well?

**Comment by stgraber** [comment]
That's intentional, we do want perfect forward secrecy for all our communications and allowing non-PFS ciphers would allow a MITM downgrade attack to force us to a non-PFS cipher.

We have no plan on relaxing our cipher list (and usually plan on going towards a narrower selection rather than larger).
