### ISSUE TITLE
Enable pipe target on "lxc export" [Feature request]

### ISSUE THREAD

**Issue by ThomasLeister** [lxc/lxd#5174]
Currently I'm looking for a way to easily create backups of my containers (using [Restic](https://github.com/restic/restic)). Usually "lxc export" can be used to create a tarball of an existing container. Unfortunately my LXD host does not have sufficient storage capacity to create a full tarball and then process this tarball with Restic.

A solution to my storage problem would be pipelining: I could tell LXD to pipe the tarball to Restic (instead of writing it to a file). Then Restic could use the pipe input, apply encryption and optimization / chunking on it and save it to a remote backup storage server. 

Unfortunately LXD does not support piping the tarball. I've tried using a named pipe:

```
root@lxd1:~/backup# mkfifo mypipe
root@lxd1:~/backup# lxc export nextcloud mypipe --container-only

Error: Failed to rsync: rsync: write failed on "/var/snap/lxd/common/lxd/backups/lxd_backup_323205951/container/rootfs/storage/nextcloud/data/appdata_ocpnrgehjkop/preview/529623/2300-4096-max.jpg": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(393) [receiver=3.1.1]
: Failed to run: rsync -a -HAX --sparse --devices --delete --checksum --numeric-ids --xattrs --bwlimit 0 -q /var/snap/lxd/common/lxd/storage-pools/default/containers/nextcloud925463442/ /var/snap/lxd/common/lxd/backups/lxd_backup_323205951/container: rsync: write failed on "/var/snap/lxd/common/lxd/backups/lxd_backup_323205951/container/rootfs/storage/nextcloud/data/appdata_ocpnrgehjkop/preview/529623/2300-4096-max.jpg": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(393) [receiver=3.1.1]
```

But the above error appeared. 

My current approach is to skip LXD backup functionality and just save a copy of my ZFS container volume via ```zfs send```. (Container properties need to be saved separately). It does work, but also it adds some complexity, because the backup consists of multiple parts.

It would be nice to have LXDs native "all in one" export working with pipes and Restic :-) 

e.g. 

```lxc export nextcloud --container-only --piped```

... which outputs the tarball contents on stdout (just as ```zfs send``` would do).

**Comment by stgraber** [comment]
You're running out of space on the server side, not on the client side as `lxc export` uses the backup API which creates a backup file in /var/snap/lxd/common/lxd/backups and then allows you to retrieve it when needed (which export does immediately).

You could mount a larger storage volume at `/var/snap/lxd/common/lxd/backups` which would avoid this issue.

We can't support piping because of the way the API is designed and even if the API was made so that you can export a container bypassing the backup storage, we'd still need to move files around from the original container filesystem structure to the backup structure, which isn't something we can do with streaming tar.

**Comment by ThomasLeister** [comment]
Oooh, too bad! But thanks for clarifying!
