### ISSUE TITLE
lxd does not use -z option for rsync, resulting in excessive bandwidth usage

### ISSUE THREAD

**Issue by danielrobbins** [lxc/lxd#5215]
Currently, when migrating containers using rsync, lxd does not specify the -z option, which results in excessive bandwidth usage when migrating containers, and potentially slows down migrations significantly when link speed is a limiting factor.
Solution: Add -z option to rsync as a reasonable bandwidth-saving default.

**Comment by stgraber** [comment]
Going to have to play with --compress-level a bit because the default (6) is causing some extreme slowdown on gigabit links (going from 90MB/s down to 5MB/s).

The standard case for container migration is local network, so some compression to avoid sending duplicate data is worth it, but we don't want to sacrifice throughput for it.

**Comment by stgraber** [comment]
Testing with a standard Ubuntu container, I'm seeing:

 - No compression: 13s
 - Level 1 compression: 15s
 - Level 2 compression: 15s
 - Level 3 compression: 15.5s
 - Level 4 compression: 16.5s

So looks like we can tolerate a compress level of 2 with minimal excess transfer time.
In my case it means 144.75MB vs 368MB, so that's still significant bandwidth savings.
