### ISSUE TITLE
jenkins: Failed to prepare loop device: device or resource busy

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#5246]
```
+ /lxc-ci/build/tmp.I8h5uKv6TO/go/bin/lxc storage create lxdtest-rm8-pool-btrfs lvm volume.block.filesystem=btrfs volume.size=200MB --verbose
INFO[11-05|22:48:24] Creating LVM storage pool "lxdtest-rm8-pool-btrfs" 
Error: Failed to prepare loop device: device or resource busy
```

 - https://jenkins.linuxcontainers.org/job/lxd-github-commit/2955/arch=amd64,backend=lvm,compiler=golang-1.10,restrict=lxd-priv/console
 - https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5215/arch=i386,backend=lvm,compiler=golang-1.11,restrict=lxd-priv/console

It's kinda unclear what call is getting us an EBUSY but I think it'd be worth going through our cgo code there and see what calls may get us EBUSY and add a retry loop if that makes sense (either in cgo or in go).

**Comment by brauner** [comment]
This can only happen when
```
ioctl(fd_loop, LOOP_SET_FD, fd_img);
```
fails. Which means that the loop device we detected in `get_unused_loop_dev()` has been stolen in between detecting it and setting it up. That seems especially plausible since
```
+ /lxc-ci/build/tmp.WZlKeADwLc/go/bin/lxc storage create lxdtest-jKSaH2H3J-pool13 lvm source=/dev/loop12 lvm.vg_name=lxdtest-jKSaH2H3J-pool13-dummy_vg_4 volume.size=25MB --verbose
```
references a specific loop device. I'm not sure there's a need for a loop around this which would just stall. But I can send a POC pr.
