### ISSUE TITLE
Build from source 

### ISSUE THREAD

**Issue by ingtarius** [lxc/lxd#5326]
# Required information

 * Distribution: Debian
 * Distribution version: 9.5
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux
   * LXC version: -
   * LXD version: -
   * Storage backend in use: -
    * Go version: go1.11 linux/amd64
# Issue description

Building form source failed.

# Steps to reproduce

 1. Download source files
 2. make deps
 3. make

# Information to attach

make deps running well, but make fail with
`go get -t -v -d ./...`
`github.com/lxc/lxd (download)`
`package github.com/lxc/lxd/lxd/debug: cannot find package "github.com/lxc/lxd/lxd/debug" in any of:
	/usr/lib/go-1.11/src/github.com/lxc/lxd/lxd/debug (from $GOROOT)
	/root/go/src/github.com/lxc/lxd/lxd/debug (from $GOPATH)`
`Makefile:18: recipe for target 'default' failed`
`make: *** [default] Error 1`

**Comment by stgraber** [comment]
That's a Go path issue, the source needs to be at $GOPATH/src/github.com/lxc/lxd for the import paths to work properly. In your case, that'd be /root/go/src/github.com/lxc/lxd.

Otherwise you end up with some code coming from the tarball or branch you downloaded and some code downloaded by Go from the master branch, the combination of which being very unlikely to work.

**Comment by ingtarius** [comment]
Thanks for your reply!
Working like charm
