### ISSUE TITLE
LXD Container migration failed under load: Error Rsync send failed files vanished

### ISSUE THREAD

**Issue by adityacloud1** [lxc/lxd#5334]
Respected all,
Greeting of the Day !!!. I am trying to live migrate container ‘c1’ between 2 LXD servers, with apparmor security feature disabled and experimental setup is:

Physical machine OS: Ubuntu 16.04
lxc --version 3.7 (installed from source using: https://github.com/lxc/lxd)
lxd --version 3.7 (installed from source)
criu --version: 3.11 (installed from source)
kernel --version: 4.15.0-29-generic
rsync --version
`rsync  version 3.1.2  protocol version 31
`
To test container migration under load,  following benchmark is run:

i) Kernel compile benchmark: To represent system-call intensive workloads https://github.com/knurd/kcbench,

Container migration using `lxd move` always gives error:

`EROR[12-05|16:06:20] Rsync send failed: /var/lib/lxd/containers/c1/: exit status 24: file has vanished: "/var/lib/lxd/containers/c1/rootfs/tmp/kcbench.vg5v843gf/drivers/acpi/acpica/.psxface.o.d"
file has vanished: "/var/lib/lxd/containers/c1/rootfs/tmp/kcbench.vg5v843gf/drivers/acpi/acpica/.psxface.o.tmp"
rsync warning: some files vanished before they could be transferred (code 24) at main.c(1196) [sender=3.1.2]
`

i). lxc.log
[lxc.log](https://github.com/lxc/lxd/files/2648412/lxc.log)

ii) dump.log
[dump.log](https://github.com/lxc/lxd/files/2648413/dump.log)
I check solution like `-ignore-missing-args,` but not getting way to implement.

Please do the needful help!!.

 *

**Comment by stgraber** [comment]
So the core of the problem here is the us of the directory backend which as it's simply rsync based will not provide a way to get an atomic view of the filesystem during migration.

A number of other operations on the dir backend comes with freezing the container during the transfer, I suspect that's probably the way out of this. Ignoring changing and vanishing file will just end up with potential data corruption.

**Comment by adityacloud1** [comment]
Thanks Sir,
