### ISSUE TITLE
MySQL very low Disk IO through LXD Containers

### ISSUE THREAD

**Issue by elbrinke** [lxc/lxd#5344]
# Required information

 * Distribution: **ubuntu** 
 * Distribution version: **18.04**
 * The output of "lxc info" or if that fails:
   * Kernel version: **4.15.0-34-generic**
   * LXC version: **3.0.2**
   * LXD version: **3.0.2**
   * Storage backend in use: **zfs**

# Issue description

We are having a very slow disk IO with MySQL through an LXD container. This however effects the time our jobs takes to finish from 18 hours to 36 hours. 

The MySQL data is stored on the host inside of /dev/sdb which is mounted as /active on the host. This /active is them mounted into the MySQL container to allow MySQL Service access to the Databases. These jobs requires a very high Disk IO. 

However when we run the jobs, we can see that MySQL has a very slow disk IO. Please note that the /dev/sdb (/active) disk is an **ext4** formatted disk. 

Can you please assist us with this? We moved to LXD containers because to try to containerise our solutions, but this is a big problem for us. 

MySQL running the same jobs on a host seems perfectly fine.

Kind Regards
Eddy

**Comment by stgraber** [comment]
Can you show `lxc config show --expanded NAME` for the container you're running this in?

**Comment by elbrinke** [comment]
Hi @stgraber , 

Thanks for your response. Find info requested below:

```architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 16.04 LTS amd64 (release) (20180912)
  image.label: release
  image.os: ubuntu
  image.release: xenial
  image.serial: "20180912"
  image.version: "16.04"
  security.privileged: "true"
  volatile.base_image: bf49cef91a4122d9c8aacb9b6629078036a73798af1662b86a234081e3a355e9
  volatile.eth0.hwaddr: 00:16:3e:34:db:5b
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
devices:
  active:
    path: /databases/active/
    source: /active/mysql/
    type: disk
  etc:
    path: /etc/mysql/
    source: /lxd/persistent/mysql-db-5-6/etc/
    type: disk
  eth0:
    name: eth0
    nictype: bridged
    parent: br0-eno1
    type: nic
  root:
    path: /
    pool: containers
    type: disk
  sbtemp:
    path: /databases/tmp/
    source: /lxd/persistent/databases/
    type: disk
  var:
    path: /var/lib/mysql/
    source: /lxd/persistent/mysql-db-5-6/var/
    type: disk
ephemeral: false
profiles:
- system
stateful: false
description: ""
```

**Comment by stgraber** [comment]
And running the exact same version of MySQL with the same configuration and storage path but outside the container gets you the expected performance?

You don't have any block I/O limits or any other kind of limit in place here and aren't using an unprivileged container so there's no shifting overhead or blocked syscalls, performance in this case really should be identical to a straight chroot environment...

**Comment by elbrinke** [comment]
Hi @stgraber , 

Running the same MySQL on host

**Comment by davidfavor** [comment]
I finally had to give up on using ZFS, as all sites I host are LAMP Stacks, many with high database i/o.

As an experiment, spin up a SoYouStart machine using...

```
lxd init --auto --storage-backend=dir
lxc network create lxdbr0
lxc network attach-profile lxdbr0 default en0/eth0/eno1/rename4 (your physical interface)
```
Now test mysql throughput using sysbench at machine level + container level.

My containers are unprivileged + testing I've done shows same speed at machine level + container level, when using ext4.

If you run the above tests, be sure to add your results here.

**Comment by elbrinke** [comment]
Hi @davidfavor , 

Are you referring to the storage-backed of the container? Even if the databases directory is mounted inside of the container is a ext4 mount?

**Comment by stgraber** [comment]
I'm closing this issue for now as so far this hasn't been linked to anything that LXD itself does.

The discussion is very interesting though, so please keep updating this issue and we will be re-opening it if we track this down to something that LXD does and that we can improve there.

**Comment by davidfavor** [comment]
If your backend storage for /var/lib/mysql is ext4, I'd think this would resolve speed problems.

My guess is something else is amiss, like your running with /tmp on disk (ZFS or whatever), rather than tmpfs... or you're running with bin logging enabled which will write /var/log/mysql files at a ferocious rate to disk (ZFS or whatever). Could be your applications are getting i/o bound just writing to /var/log/whatever.log files too.

If you're trying to run a hybrid of ZFS (or whatever) then have your data run on ext4... this is complex. Best test is to spin up a purely ext4 container + retest.

If speed problems resolve, you know there's some sort of i/o bound processing involved.

If speed problems persist, time to get rid of bin logging + run mysqltuner to fix glaring problems + then get into SQL statement analysis.

None of this is really an LXD related problem, thought the problem does show up on LXD.

For example, if you load a machine up with ZFS for the file system + then try running a database... at least last time I tested MariaDB... the i/o speed reduction was massive.

Nothing to do with LXD. Everything to do with ZFS.

**Comment by whataboutpereira** [comment]
Here are some pointers for MySQL on ZFS.

http://assets.en.oreilly.com/1/event/21/Optimizing%20MySQL%20Performance%20with%20ZFS%20Presentation.pdf
