### ISSUE TITLE
SAR inside LXD containers

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxd#5356]
Machine: Running Ubuntu Bionic + SNAP LXD with all updates applied.

Containers: Running Ubuntu Bionic with all updates applied.

It appears SAR data is more for machine wide processes, rather than just inside container.

Someone let me know (URL to docs or article would be great)...

1) If SAR inside containers captures only container data or machine wide data.

2) Any difference between privileged + unprivileged containers data capture.

3) If there is a problem with machine level data leaking through, if there's some sort of fix, no matter how complex.

4) URLs to any related projects to capture container scoped data.

Thanks.

**Comment by simos** [comment]
This is [sar](https://linux.die.net/man/1/sar) and it uses `/proc` to capture the activity of a Linux installation.
The question is therefore really about what activity is encapsulated in `/proc` for a container. 
But since it's an open-ended question, it should indeed be discussed first at http://discuss.linuxcontainers.org/

**Comment by stgraber** [comment]
Ok, so yeah, I'd expect such a tool to run into some problems:
 - In containers in general, not all of /proc is well namespaced, that's why we made lxcfs but we may be missing some bits
 - In unprivileged containers, some files may not be accessible even by root in an unprivileged container

So in theory, we'd like something like this to only see activity from the container, when that's not the case, lxcfs may be able to help, other cases may be fixable in the kernel, depends on what's going on.

For privileged vs unprivileged, some APIs will certainly not be available in the unprivileged case, that may be fixable in the kernel in some cases, if we can determine that it'd be safe for an unprivileged user to have access to.

I'm not aware of any project that does exactly that though sysdig may be similar in some ways? It does use its own kernel module though and is mostly planned for host to container inspection rather than running inside the container itself.

**Comment by stgraber** [comment]
(Closing as a forum post seems like a better fit for this)
