### ISSUE TITLE
lxc copy to remote incorrect volume size, ceph.

### ISSUE THREAD

**Issue by CyrusTheVirusG** [lxc/lxd#5362]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
  driver: lxc
  driver_version: 3.0.3
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-42-generic
  server: lxd
  server_pid: 38725
  server_version: "3.7"
  storage: ceph
  storage_version: ceph version 10.2.10 (5dc1e4c05cb68dbf62ae6fce3f0700e4654fdbbe)
  server_clustered: true

This should all be 3.8, kinda weird output.

# Issue description

Copying a container to a cluster with a ceph remote configured as the only data store fails (in the default configuration) because the volume defaults to 9GB instead of creating a volume with an appropriate size for the incoming data.

Perhaps if 9gb is the default sane value, consider adding 9gb until there is enough space to fit the data or whatever you think is best.

This is easily averted by upping the default volume size in the storage pool configuration.

As a side note the documentation simply says 0, it is unclear if this value should be in bytes or a human readable although human readable 32GB for example works.

# Steps to reproduce

 1. Setup cluster with CEPH backend.
 2. Copy a large container from an old lxd instance to the new cluster.
 3. Watch it fail at 9gb. rsync error code: 11

**Comment by stgraber** [comment]
Can you show the output of `lxc copy` with `--debug` passed?

As you mentioned, you can bump the default size on the storage pool of the target, but I would also expect LXD to allocate a storage volume of the right size if the source container had a disk quota set in its configuration (size property on root disk in container config).

If it doesn't have that property set, then there's unfortunately no way for LXD to guess how much space to allocate as we don't know how much data rsync is going to transfer (which is why we don't give you progress information either) and even if disk usage was part of the migration protocol (it's not), it would still vary widely based on target filesystem, whether compression is enabled on source/target and behavior of sparse file through rsync.

Realistically here, I think what we need to make sure is:
 - If the container config sent as part of the copy includes a size property, then use that when allocating the storage volume, that `--debug` output will let us check whether that was the case here
 - Do a better job at detecting such out of space issues and report a clear error (not `rsync exit with code 11`)

**Comment by CyrusTheVirusG** [comment]
No special configuration value/quota was set on the source container.

The error code isn't a huge deal since it's easy enough to look up what it means.

The message could point to a possible solution: 'Destination storage volume size insufficient to complete transfer... Increase storage pool volume.size on destination or specify volume size or quota in source container configuration.'

Maybe even include a link to some documentation. Of course it would be sweet to get that automagical disk size allocation working, when I get some free time maybe I'll give it a shot.

**Comment by stgraber** [comment]
Sorry for the delay, I'm testing this now, will attempt migration from standalone LXD with ZFS to standalone LXD with CEPH, first with a container which fits in the default 10GB then one which doesn't so I can look at whether the receiving LXD considers the information available (quota) to size the new volume.

**Comment by stgraber** [comment]
So in my tests, if the source container has a suitable `size` property set, this is used as the basis for the newly allocated rbd volume, which means that LXD is making use of the information it has available.

That means that in your case, something like this should have worked:
 - lxc config device override NAME root size=50GB

**Comment by stgraber** [comment]
And looking at rsync, it only surfaces file I/O error, instead of a unique error code for ENOSPC which unfortunately makes it impossible for us to differentiate running out of space to say an actual ATA error on the underlying disk, so my plan of intercepting the error and showing something prettier to the user won't work :(

As a result, closing this issue as based on the information that the receiving LXD is getting, it's doing the right thing with volume allocation, using the size property when available.
