### ISSUE TITLE
Document KiB/GiB suffixes

### ISSUE THREAD

**Issue by janmuennich** [lxc/lxd#5393]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * LXD version: 3.0.3
 * Storage backend in use: ZFS

# Issue description

Setting a disk size for a container root device results in a ca. 7% smaller ZFS refquota. I think this bug was introduced with LXD 3.0.3.

# Steps to reproduce

```
# lxc config device set test root size 100GB
# zfs get refquota pool/lxc/containers/test
NAME                      PROPERTY  VALUE     SOURCE
pool/lxc/containers/test  refquota  93.1G     local
```

**Comment by stgraber** [comment]
I suspect it's the usual 1024 vs 1000 definition of a kB which differs between backends.

LXD fixed the way this is handled by treating all values in GB to be the 1000 type and GiB to be 1024, so changing your device to be 100GiB should improve things.

Though testing here, I'm not seeing us land to exactly 100G according to ZFS, so I'd need to check exactly what ZFS is using as far as units and see if there's any more internal conversion we need to do so that 100GiB does end up as 100G (assuming ZFS uses the 1024 bytes definition, if it uses the 1000 bytes definition, then 100GB needs to end up as 100G).

**Comment by stgraber** [comment]
So actually, looking at our conversion logic and at the raw quotas in bytes, our logic is correct:

```
root@vorash:~# lxc profile device set default root size 5GB
root@vorash:~# zfs get refquota internal/lxd/containers/rbac01 -H -p
internal/lxd/containers/rbac01	refquota	5000000000	local
root@vorash:~# lxc profile device set default root size 5GiB
root@vorash:~# zfs get refquota internal/lxd/containers/rbac01 -H -p
internal/lxd/containers/rbac01	refquota	5368709120	local
```

5GB gets you 5000000000 bytes
5GiB gets you 5368709120 bytes

Which are the normal definition of both units and as we feed the quota in raw bytes to ZFS, the values we provide ZFS are correct.

So I think the issue in your case is simply that your quota is provided in GB rather than GiB which is what you actually seem to want in this case.

**Comment by stgraber** [comment]
(Yes, the fact that those two are different units is annoying and has been a source of pain for decades thanks to shady marketing by disk manufacturers...)

**Comment by janmuennich** [comment]
Thanks for the clarification. That's what I suspected but didn't know I could configure GiB. Maybe that should be added to the documentation?

Description for size is currently: "Disk size in bytes (supports kB, MB, GB, TB, PB and EB suffixes). This is only supported for the rootfs (/)."
https://lxd.readthedocs.io/en/latest/containers/#devices-configuration

**Comment by stgraber** [comment]
Yeah, the documentation is a bit annoying for that, we should just mention that we support suffixes in those locations and then have a paragraph explaining what's supported.
