### ISSUE TITLE
lxd starting container failed

### ISSUE THREAD

**Issue by pxcluster** [lxc/lxd#543]
Trying to start a lxd container with trhe command :

lxc start seafile --debug -v

Output is :

2015/04/27 00:23:56 fingering the daemon
2015/04/27 00:23:56 raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"api_compat":1,"auth":"trusted","config":{"trust-password":false},"environment":{"backing_fs":"ext4","driver":"lxc","kernel_version":"3.19.0-15-generic","lxc_version":"1.1.2"}}}
2015/04/27 00:23:56 pong received
2015/04/27 00:23:56 putting {"action":"start","force":false,"timeout":-1}
 to http://unix.socket/1.0/containers/seafile/state
2015/04/27 00:23:56 raw response: {"type":"async","status":"OK","status_code":100,"operation":"/1.0/operations/4db68203-527c-4453-9ac5-bce503e19677","resources":null,"metadata":null}
2015/04/27 00:23:56 1.0/operations/4db68203-527c-4453-9ac5-bce503e19677/wait
2015/04/27 00:24:01 raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"created_at":"2015-04-27T00:23:56.15638766+02:00","updated_at":"2015-04-27T00:24:01.202688119+02:00","status":"Failure","status_code":400,"resources":null,"metadata":"starting the container failed","may_cancel":false}}
error: starting the container failed

Tail -20 of /var/log/lxd/seafile/lxc.log :

lxc_container 1430087036.174 DEBUG    lxc_start - start.c:__lxc_start:1137 - Not dropping cap_sys_boot or watching utmp
  lxc_container 1430087036.176 INFO     lxc_start - start.c:lxc_check_inherited:221 - closed inherited fd 3
  lxc_container 1430087036.176 INFO     lxc_start - start.c:lxc_check_inherited:221 - closed inherited fd 4
  lxc_container 1430087036.176 INFO     lxc_start - start.c:lxc_check_inherited:221 - closed inherited fd 5
  lxc_container 1430087036.176 INFO     lxc_start - start.c:lxc_check_inherited:221 - closed inherited fd 6
  lxc_container 1430087036.176 INFO     lxc_start - start.c:lxc_check_inherited:221 - closed inherited fd 7
  lxc_container 1430087036.176 INFO     lxc_start - start.c:lxc_check_inherited:221 - closed inherited fd 8
  lxc_container 1430087036.176 INFO     lxc_start - start.c:lxc_check_inherited:221 - closed inherited fd 9
  lxc_container 1430087036.176 INFO     lxc_start - start.c:lxc_check_inherited:221 - closed inherited fd 10
  lxc_container 1430087036.176 INFO     lxc_start - start.c:lxc_check_inherited:221 - closed inherited fd 12
  lxc_container 1430087036.176 INFO     lxc_start - start.c:lxc_check_inherited:221 - closed inherited fd 13
  lxc_container 1430087036.176 INFO     lxc_start - start.c:lxc_check_inherited:221 - closed inherited fd 14
  lxc_container 1430087036.178 INFO     lxc_start - start.c:resolve_clone_flags:848 - Cloning a new user namespace
  lxc_container 1430087036.180 ERROR    lxc_conf - conf.c:instantiate_veth:2660 - failed to attach 'vethKW155N' to the bridge 'lxcbr0': Operation not permitted
  lxc_container 1430087036.184 INFO     lxc_monitor - monitor.c:lxc_monitor_sock_name:177 - using monitor sock name lxc/92ea7555d42fc75c//var/lib/lxd/lxc
  lxc_container 1430087036.196 ERROR    lxc_conf - conf.c:lxc_create_network:2943 - failed to create netdev
  lxc_container 1430087036.196 ERROR    lxc_start - start.c:lxc_spawn:914 - failed to create the network
  lxc_container 1430087036.196 ERROR    lxc_start - start.c:__lxc_start:1164 - failed to spawn 'seafile'
  lxc_container 1430087036.196 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_init_pid failed to receive response
  lxc_container 1430087036.197 WARN     lxc_cgmanager - cgmanager.c:cgm_get:963 - do_cgm_get exited with error

Ifconfig only shows a 'virbr0' and no 'veth*'...

I've checked that the libvirtd daemon is running... and really don't know what else I can do to investigate. 

The system was freshly installed with an ubuntu 15.04. I'd think that lxc wasn't properly installed/configured by the lxd. Also, and strangely, I always need to start the lxd daemon manually after each reboot... (systemctl start lxd).

**Comment by hallyn** [comment]
On Sun, Apr 26, 2015 at 04:01:23PM -0700, pxcluster wrote:
>   lxc_container 1430087036.180 ERROR    lxc_conf - conf.c:instantiate_veth:2660 - failed to attach 'vethKW155N' to the bridge 'lxcbr0': Operation not permitted
...
> Ifconfig only shows a 'virbr0' and no 'veth*'...

So there is no lxcbr0?  lxd uses that bridge by default.

I've had some trouble with lxc-net under systemd as well.  Can you do

ifconfig -a
sudo systemctl stop lxc-net
sudo systemctl start lxc-net
ifconfig -a

and see if lxcbr0 shows up in the second ifconfig output?

(I sometimes have to do it several times...)

**Comment by pxcluster** [comment]
On dim, 2015-04-26 at 19:32 -0700, Serge Hallyn wrote:

> So there is no lxcbr0? lxd uses that bridge by default.

I know, this is what I found strange...

> I've had some trouble with lxc-net under systemd as well. Can you do
> 
> ifconfig -a
> sudo systemctl stop lxc-net
> sudo systemctl start lxc-net
> ifconfig -a
> 
> and see if lxcbr0 shows up in the second ifconfig output?
> 
> (I sometimes have to do it several times...)

Yes, it works !

Is there anything I can do, test, or what so ever, to help you find the
problem ? 

My system is currently not in production and I can still use it a few
days to run some tests...

Thanks for the info

Daniel Cordey

**Comment by stgraber** [comment]
I have reworked the lxc-net script in upstream LXC to make it a bit more robust, hopefully this is now resolved there (current upstream git though, so you'd only get it if you use daily builds from ppa:ubuntu-lxc/lxc-git-master).

Closing the issue as there's nothing we can do on the LXD side of this and we believe the LXC side of it has been resolved upstream.

**Comment by tealeg** [comment]
FWIW, I've seen this on Ubuntu 15.10 when dnsmasq is not installed.

**Comment by pxcluster** [comment]
On 25. 06. 15 09:38, Geoff Teale wrote:
> FWIW, I've seen this on Ubuntu 15.10 when dnsmasq is not installed.

Thanks for the tip.

I finally decided to go back to Ubuntu 14.10 since I started to have too 
many problems with 15.04. It seems that 'systemd' is not fully 
operational with lxc on 15.10 (something in between upstart and 
systemd...) Some pieces are missing and it doesn't make sense to 
implement horrible hacks while it's supposed to work. We probably just 
need to wait a bit longer before everything is in sync :-)

Daniel Cordey

**Comment by jrwren** [comment]
FYI: I get this error because lxc-net fails to start. I run bind and it listens on ipv6.

I was able to better configure bind by using `  listen-on-v6 { 2601::/16; }; ` in my `named.conf.options` file.

Once in place, I can restart bind, restart lxc-net and start instances.

**Comment by stgraber** [comment]
Ah yeah, anything which binds port 53 on all interfaces will interfere with lxc-net. There's unfortunately nothing we can do about this, besides telling people to configure such daemons to only bind the interfaces the service is actually needed on.

**Comment by steverding** [comment]
I found out, that this could be a timing problem in the lxc-net startup script 
/usr/lib/x86_64-linux-gnu/lxc/lxc-net in Ubuntu whily.
There was a problem setting the ip address in the ifup() function. I added two sleeps before and after the "ip addr add" line and now it works without any problems every time.

Here is my changed ifup() function:

ifup() {
    MASK=`_netmask2cidr ${LXC_NETMASK}`
    CIDR_ADDR="${LXC_ADDR}/${MASK}"
    sleep 2
    ip addr add ${CIDR_ADDR} dev $1
    sleep 2
    ip link set dev $1 up
}

**Comment by micheal** [comment]
>I was able to better configure bind by using listen-on-v6 { 2601::/16; }; in my named.conf.options file.

Thanks! I did this and once I restarted bind and restarted lxc-net, lxcbr0 showed up in ifconfig.

**Comment by rvanlaar** [comment]
I have this same problem with Ubuntu 15.10 (Willy). It recently (december 2015) showed up. 
For reference, this was the error I got: 
There was an error executing ["sudo", "/usr/local/bin/vagrant-lxc-wrapper", "lxc-start", "-d", "--name", "aa_default_1449926068132_45691"]

**Comment by cpaelzer** [comment]
I've had the same issue today.
Happens with 15.10 as is but also with the code from ppa:ubuntu-lxc/lxd-stable.
As Stephane already pointed out that is actually a lxc (and not lxd) issue.
I found steverdings workaround with the sleeps working for me.

If not applying the workaround I can see this in lxc-net
sudo systemctl status lxc-net
● lxc-net.service - LXC network bridge setup
   Loaded: loaded (/lib/systemd/system/lxc-net.service; enabled; vendor preset: enabled)
   Active: active (exited) since Mo 2016-02-15 16:17:56 CET; 3s ago
  Process: 32179 ExecStop=/usr/lib/x86_64-linux-gnu/lxc/lxc-net stop (code=exited, status=0/SUCCESS)
  Process: 32192 ExecStart=/usr/lib/x86_64-linux-gnu/lxc/lxc-net start (code=exited, status=0/SUCCESS)
 Main PID: 32192 (code=exited, status=0/SUCCESS)

Feb 15 16:17:56 paelzer-ThinkPad-X1-Carbon-3rd systemd[1]: Starting LXC network bridge setup...
Feb 15 16:17:56 paelzer-ThinkPad-X1-Carbon-3rd lxc-net[32192]: dnsmasq: failed to create listening socket for 10.0.3.1: Cannot assign requested address
Feb 15 16:17:56 paelzer-ThinkPad-X1-Carbon-3rd lxc-net[32192]: Failed to setup lxc-net.
Feb 15 16:17:56 paelzer-ThinkPad-X1-Carbon-3rd systemd[1]: Started LXC network bridge setup.

It instead should look like this (with the sleeps)
Feb 15 16:20:02 paelzer-ThinkPad-X1-Carbon-3rd systemd[1]: Starting LXC network bridge setup...
Feb 15 16:20:08 paelzer-ThinkPad-X1-Carbon-3rd dnsmasq[32696]: started, version 2.75 cachesize 150
Feb 15 16:20:08 paelzer-ThinkPad-X1-Carbon-3rd dnsmasq[32696]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify
Feb 15 16:20:08 paelzer-ThinkPad-X1-Carbon-3rd dnsmasq-dhcp[32696]: DHCP, IP range 10.0.3.2 -- 10.0.3.254, lease time 1h
Feb 15 16:20:08 paelzer-ThinkPad-X1-Carbon-3rd dnsmasq-dhcp[32696]: DHCP, sockets bound exclusively to interface lxcbr0
Feb 15 16:20:08 paelzer-ThinkPad-X1-Carbon-3rd dnsmasq[32696]: reading /etc/resolv.conf
Feb 15 16:20:08 paelzer-ThinkPad-X1-Carbon-3rd dnsmasq[32696]: using nameserver 127.0.1.1#53
Feb 15 16:20:08 paelzer-ThinkPad-X1-Carbon-3rd dnsmasq[32696]: read /etc/hosts - 7 addresses
Feb 15 16:20:08 paelzer-ThinkPad-X1-Carbon-3rd systemd[1]: Started LXC network bridge setup.

Seems to need some hardening against racing several parts of the initialization.
Due to the ppa I have 2.0.0~beta2-0ubuntu2 installed as is current for xenial atm.
As it is lxc package Is there a related lxc bug already known?

**Comment by Recydywa** [comment]
I'm on Xenial with newest lxc and it also fails to create lxcbr0.

>$ sudo systemctl status lxc-net
● lxc-net.service - LXC network bridge setup
   Loaded: loaded (/lib/systemd/system/lxc-net.service; enabled; vendor preset: 
   Active: active (exited) since czw 2016-03-31 19:12:34 CEST; 3min 52s ago
  Process: 2840 ExecStop=/usr/lib/x86_64-linux-gnu/lxc/lxc-net stop (code=exited
  Process: 2915 ExecStart=/usr/lib/x86_64-linux-gnu/lxc/lxc-net start (code=exit
 Main PID: 2915 (code=exited, status=0/SUCCESS)
>
mar 31 19:12:34 mateusz-desktop systemd[1]: Starting LXC network bridge setup...
mar 31 19:12:34 mateusz-desktop lxc-net[2915]: dnsmasq: failed to create listeni
mar 31 19:12:34 mateusz-desktop lxc-net[2915]: Failed to setup lxc-net.
mar 31 19:12:34 mateusz-desktop systemd[1]: Started LXC network bridge setup.

&nbsp;

>$ apt-cache policy lxc
lxc:
  Zainstalowana: 2.0.0~rc14-0ubuntu2
  Kandydująca:   2.0.0~rc14-0ubuntu2
  Tabela wersji:
 *** 2.0.0~rc14-0ubuntu2 500
        500 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        500 http://archive.ubuntu.com/ubuntu xenial/main i386 Packages
        100 /var/lib/dpkg/status

**Comment by Recydywa** [comment]
So I installed dnsmasq and after reboot I could start the container without problems.
