### ISSUE TITLE
LXD doesn't start automatically

### ISSUE THREAD

**Issue by randall-ubuntu** [lxc/lxd#550]
Environment: 
Ubuntu 15.04 (running in VirtualBox)

Following the instructions here: https://insights.ubuntu.com/2015/03/20/installing-lxd-and-the-command-line-tool/

I installed lxd with the following commands:
`add-apt-repository ppa:ubuntu-lxc/lxd-git-master`
`apt-get update`
`apt-get install lxd`

I then issued the command:
`lxd-images import lxc ubuntu trusty amd64 --alias ubuntu`

And received the following output:
`LXD isn't running.`

Expected result: LXD should already be running. I had to invoke it manually using the command:
`sudo -E /usr/bin/lxd --group lxd`

**Comment by stgraber** [comment]
Note that being on 15.04, you don't need the PPA.

It looks like there's something wrong with the systemd unit, which explains why LXD starts fine under upstart (pre-15.04) but must be manually started under systemd (systemctl start lxd).

systemd lists the unit as disabled, so we'll have to investigate if that's because it thinks a dependency isn't met or because the package somehow doesn't enable the unit...

**Comment by hallyn** [comment]
Adding the following to the bottom of debian/rules seems to fix it for me:

+override_dh_installinit:
+       dh_systemd_enable -plxd --name=lxd
+       dh_installinit -plxd --name=lxd

**Comment by stgraber** [comment]
Yeah, I'll do that in the next upload.

**Comment by stgraber** [comment]
Fix applied to packaging branch.
