### ISSUE TITLE
Make it possible to store images and backups on a storage pool

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#5515]
Right now, the original image artifacts and the container backups are stored on the main system storage, not on any of LXD's storage pools.

This is surprising to users who may then run themselves out of disk space despite having a lot of storage directly assigned to LXD.

I believe we should introduce two new configuration options (daemon level):
 - storage.images_volume
 - storage.backups_volume

Syntax being `<pool>/<volume>` where `<volume>` is an existing, unused custom volume.

When not set, we store things directly in the directory as we used to.
If set, we create a lxd_images or lxd_backups directory on the selected storage pool and turn the images or backups directory into a symlink to the relevant location.

Those settings may be changed and data will be moved around as needed.

Those storage volumes must be adequately protected so that they may not get attached to a container and may not be deleted or renamed while in use.

We also need to disallow the use of CEPH for this as CEPH+cluster would fail miserably.
We may re-visit this with CEPHfs when we add it but for now, we should just ban CEPH.

**Comment by gpatel-fr** [comment]
> Right now, the original image artifacts and the container backups are stored on the main system storage, not 
> on any of LXD's storage pools.
> This is surprising to users who may then run themselves out of disk space despite having a lot of storage directly assigned to LXD.
> 
Indeed this has happened to me. It's nice to see a project manager so responsive that he see the need to solve my problem before  I have it :-)

But is it a real problem for images ? Images are usually 150-200 mb  and only one at a time is stored temporarily on the file system 
For backup, yes, the actual container data can be quite larger (see below). But is is necessary to actually manage new special volume classes ? Add new objects is nice when you have a still growing project, but later you can consider them as making it to heavy, in short overengineering. 
Why not just add the possibility to enter a specific path for storing backups ? Simpler, lighter, leaving the actual management to system administrators (that's what I did once I understood the reason for the crash; BTW a man page for lxc-export could be useful, explaining what happens and what to do with the remaining data hogging the available space, this data that seems to be automatically cleaned when restarting a successful export, something not totally obvious and I have no idea how about doing it safely otherwise). 

There is the problem of snap adding 'protection' to file accesses for people using lxd with snapcraft, though. Maybe that's the reason you want to add all this stuff.

From what I see, export does on the file system a full copy of all container data AND a tarball AND the gzipped tarball, needing so about 2,5 times the actual container size.  Probably for the best, but lxc-export doc (if it actually existed)  should say clearly that you need at least that on the temporary workspace. Many people would assume that 50% over the biggest container should be more than enough. Possibly the container copy could be zapped *before* creating the gzipped tar from the tarball. I don't quite see why it's needed at this point. I'd dare to say that efforts to make this more efficient could be actually useful.

**Comment by stgraber** [comment]
@monstermunchkin can you check why we'd be keeping the temporary backup directory after we've tared it (and before we compress it)? Seems like an obvious waste of space.

**Comment by tchwpkgorg** [comment]
> But is it a real problem for images ? Images are usually 150-200 mb and only one at a time is stored temporarily on the file system

While this is true that most of the images are quite small (lets say even around 1 GB, which shouldn't cause any space issues for most environments) - I routinely create images for backup purposes, for containers which are even 100 GB large:

- lxd container is a MySQL slave or mongo secondary, with lots of data (i.e. 100 GB)

- one stops the slave and creates an image for "mysql-2019-07-20-11h-11m-11s" and sends it to a large backup server

- developer requests the restoration of database from YYYY-MM-DD (or a range of dates) to a separate environment, to debug when some issue was introduced - very handy debugging option for developers, and very nice to script with features lxd offers
