### ISSUE TITLE
slow I/O for default.img file  in duplicity

### ISSUE THREAD

**Issue by uocxp** [lxc/lxd#5524]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04 
 * Storage pool : zfs
 * lxd version: 3.0.3

# Issue description
I am using duplicity to backup my hosts and the  lxd containers on my hosts which are using a zfpool disk (default.img) for storage. On one of these hosts i am running gitlab in an lxd container and exactly on this host  duplicity is very slow on I run `pv -d "$(pgrep -u $USER duplicity)"` I am getting an I/O speed of max 400KiB/s for the file default.img[0] while on the other hosts the I/O speed for this file is about 40 MiB/s[1]. I tested the I/O performance on the host, it's actually very good and seems to be same speed as on the other hosts. I done a test on a separate Host so i ran duplicity before installing gitlab in an lxd container and a test after installing gitlab and I had the same issue on this host. I don't really know how to debug this problem. Any help?

note: actually the installation process of gitlab inside lxd container using `curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | sudo bash` takes unusual long time about 20 min.

[0]
![screenshot_28](https://user-images.githubusercontent.com/8387383/53348485-6a30e400-391b-11e9-9fbb-e881b09e0726.png)

[1]
![screenshot_27](https://user-images.githubusercontent.com/8387383/53348493-6e5d0180-391b-11e9-97fb-6844401c3420.png)

# Steps to reproduce

 1. install lxd 3.0.3
 2. install gitlab in an ubuntu18.04 container
 3. run duplicity to backup the host

**Comment by stgraber** [comment]
Closing as not really something LXD can do anything about, we just tell ZFS to run with a disk-based pool file, we don't directly write or read from that file.

Throughput is just one thing, assuming you're not using SSDs, sustained IOPs would definitely cause the kind of behavior you're seeing. Duplicity is likely trying to sequentially read the entire file while Gitlab is (through ZFS) trying to actively read and write all over that same file.

You should be able to get a better sense of that by using something like `iotop`.

Another thing to not is that the very fact that `default.img` is being actively written to while you're making that backup, effectively makes your backup useless as the file will be severely corrupted by the time you're done with it.

Instead you probably should be running your backup tooling inside your containers or have it backup stuff mounted under `/var/lib/lxd/` rather than attempting to backup the disk itself.

What you're currently doing here would be similar to making a compressed file out of /dev/sda on a running system, doesn't make much sense.

**Comment by uocxp** [comment]
I actually backup the snapshots of the containers and the directory /var/lib/lxd(because of configurations). The zpool disk `default.img` is stored under /vat/lib/lxd/disks/. Can i exclude it from the backup? What will happen if the the default.img file got lost/damaged but i still have the snapshots?Can i create a new storage pool and move the snapshots to it or do the snapshots depend on this disk file?

**Comment by stgraber** [comment]
The container rootfs are easy to restore in case of failures, the snapshot contents are a bit harder as you'd need to effectively dump the first snapshot, create a zfs snapshot, then dump the next one, ... until all snapshots are re-created, then dump the rootfs last and your dataset will be back to normal.

An option would also be to use `lxc export --optimized-storage` on your various containers, that will get you a backup file which can easily be re-imported with `lxc import` should something bad happen.
The --optimized-storage will keep the size very low but that means the container will have to be re-imported on ZFS.
