### ISSUE TITLE
Allow for some clustered database reconfiguration

### ISSUE THREAD

**Issue by innerspacepilot** [lxc/lxd#5550]
Hello!
I have 2 node LXD 3.10 cluster. 
One node is offline (shutdown), and the second node is restarted, so cluster is in split-brain state.
How do I force cluster to start, knowing that offline node will never be available?
I have found no information about this situation.

Thank you.

**Comment by stgraber** [comment]
So there's no easy way to force this. @freeekanayaka may be able to provide instructions on DB surgery which would unblock this.

To be able to survive a node loss, you need a cluster of >= 3 nodes, as covered in documentation:
```
It is recommended that the number of nodes in the cluster be at least
three, so the cluster can survive the loss of at least one node and
still be able to establish quorum for its distributed state (which is
kept in a SQLite database replicated using the Raft algorithm).
```

Short of that, it's impossible for any node to reach quorum, causing the database to remain online specifically to avoid a split brain situation.

**Comment by freeekanayaka** [comment]
Unfortunately you can't do that easily, see the relevant [doc](https://github.com/lxc/lxd/blob/master/doc/clustering.md#forming-a-cluster):

```
It is recommended that the number of nodes in the cluster be at least three, so the cluster can survive the loss of at least one node and still be able to establish quorum for its distributed state (which is kept in a SQLite database replicated using the Raft algorithm).
```

To solve the situation you'd have to manually change the cluster configuration committed in the raft logs, which is non-trivial. If recovering is absolutely critical to you we might be able to assist, on a best-effort basis.

**Comment by innerspacepilot** [comment]
Well, this is a test cluster, so no problem with it at all.
But I think this will be a common situation when LXD become popular.
for example in disaster recovery solution, when the second data center is destroyed.
There should be some simple set of commands to make it start.

Is there a way to convert it back to non clustered node to keep containers and configs?

**Comment by innerspacepilot** [comment]
I think there should be a special flag for lxd daemon, to make it start as primary node in cluster.
Then we can "lxc cluster remove --force <broken node>"
Let's make it a feature request.

Thanks.

**Comment by stgraber** [comment]
Yeah, we discussed that on IRC a bit yesterday with @freeekanayaka, the API isn't available at that point so no `lxc cluster` commands can work at that stage.

I'll update the issue with some of the ideas that were brought up then.

**Comment by stgraber** [comment]
So I think the ideal solution here would be:
 - Add a new /internal endpoint to query the RAFT setup
 - Add a `lxd` (not `lxc`) command using the internal API, letting you see the list of nodes, their status and an overall status (likely `ONLINE`, `DEGRADED` or `WAITING` with this case being `WAITING`)
 - The same command should let you forcefully remove a node when it's "safe" to do so (that is, we're in `WAITING` state). This should effectively only be allowed when the new quorum would become 1, any other case shouldn't be allowed for now.
 - When forcefully removing a node that way, the quorum should be reset to 1, the database brought online and then the node be removed from the local raft_nodes table as well as removed from the global database (similar to a normal forceful node removal)

@freeekanayaka does that sound about right?

**Comment by freeekanayaka** [comment]
@stgraber I'm a bit confused about the API returning the overall status of the cluster, with per-node information.

As far as I can tell, the solution for this issue would be something like:

```
$ lxc cluster recover
You should run this command only if you are *absolutely* certain that this is the only node left in your cluster AND that other nodes will never come back.

This will make this node the only member of the cluster, and delete information about all other nodes.

Do you want to proceed? [yes/no]
```

This could hit a ```/1.0/cluster/recover``` endpoint that would roughly do what said above. This endpoint would be available even if the node can't open the cluster database because there's no succeeding election (since all other nodes are died). This would be basically the "WAITING" state that you describe, afaiu.

Also, I'm not sure why you wish to run the procedure via the ```lxd``` command as opposed to ```lxc```.

Note that once a node is in WAITING state (to use this term), it has absolutely no information about the state of the other nodes, so it can't return any list or whatever.

**Comment by stgraber** [comment]
@freeekanayaka The problem with `lxc` in this case is that it may be talking remotely over the network making it not super obvious what system is being selected. Using the `lxd` command is what we've been doing for most disaster recovery cases and guarantees that 1) you're root 2) you're on the affected system.

So what you describe sounds reasonable but I'd do it in the `lxd` binary and using a `/internal` endpoint rather than advertising this in the public API.

**Comment by stgraber** [comment]
From https://discuss.linuxcontainers.org/t/solved-wait-for-other-cluster-nodes-to-upgrade-their-versions/4526

Another case where manual changes would be needed is when a cluster is upgrading but one member is offline and will not come back to life. In such cases, all other daemons are waiting for it to update before allowing requests. We would need `lxd` to offer a way out of this by allowing to kick such a member out of the cluster (equivalent to `lxc cluster remove --force`) so that the remaining members can go online.

**Comment by xrobau** [comment]
As I mentioned in the forums, @freeekanayaka 's concept would be the correct one for the end user (regardless of using `lxd` or `lxc` to trigger it).  There are plenty of ways that LXD can get itself confused, and a destructive 'blow everything away' would be the correct way to handle this.

In my situation, I had lost a backing store, and two (out of 5) LXD hosts were missing. I'd restored from backups and had the containers running on non-clustered hosts. The solution to simply force-start the remaining 3 as standalone clusters would be the only workable solution.
