### ISSUE TITLE
Lxd in clustered configuration: lxc copy makes full copy on same machine with btrfs

### ISSUE THREAD

**Issue by vvolas** [lxc/lxd#5613]
From https://discuss.linuxcontainers.org/t/lxd-in-clustered-configuration-lxc-copy-makes-full-copy-on-same-machine-with-btrfs-is-it-normal/4437

 * Distribution:Ubuntu 18.04
   * LXC version: 3.11
   * LXD version: 3.11
   * Storage backend in use: btrfs
# Issue description

Lxd in clustered configuration: lxc copy makes full copy on same machine with btrfs backend.

Tested on virtualbox on new ubuntu installation and with single cluster node, no weird mounts nothing, everything defaults except cluster=yes and lxc copy does full copy, and doesnt use btrfs snapshoting features.

# Steps to reproduce

 1. lxd init everything defaults except clustered mode yes.
 2. lxc launch ubuntu
 3. lxc copy ubuntu uu. Uses btrfs send/receive on local machine. (machines btrfs snapshot parent/child UUIDS doenst match = waste of lots of bytes :)

# Expected behaviour 
Uses btrfs snapshoting features.

**Comment by stgraber** [comment]
Reproduced the issue on a test cluster

**Comment by stgraber** [comment]
Ok, so I just pushed a change to our client library which adds a bit more smart into the mix.

I pretty much had two choices to handle this:

1) Just always pick the same node as the source container
2) Optimize the copy if selecting the same node it's on

1) isn't in line with the other placement work we do inside LXD and may cause overloads for some existing users, so I prefer not to change the default behavior for that. 2) was straightforward enough to implement.

Unfortunately as the client doesn't know where something is headed ahead of time, it can't automatically select the cheap local copy API call unless it's told where you want things.

So in the single node cluster case, you'll still need to pass `--target NAME` even though there's only a single target so that the client library can make detect that the current source container location lines up with the location you want for the copy and can select the cheap copy API.

The only way around this would be for us to query the list of cluster nodes, detect that you only have one and then have the client pick the right option. But that would cause an API + DB roundtrip for every copy for everyone, so given that single node clusters don't really make sense in general, the cost doesn't seem worth it.

**Comment by stgraber** [comment]
Short version is, with this change, if you pass a `--target` which matches the value show in `Location` in `lxc info`, the full migration API will be skipped, instead using the local copy API that's significantly faster on most storage backends.

**Comment by vvolas** [comment]
That was very quick :+1: 
Will this fix be backported to stable 3.0 series?

**Comment by stgraber** [comment]
Yeah, it will.
