### ISSUE TITLE
Add ability to get terminating signal from API

### ISSUE THREAD

**Issue by benjamincburns** [lxc/lxd#5619]
# Issue description

In the [REST API documentation](https://lxd.readthedocs.io/en/latest/rest-api/#10containersnameexec) it appears that the control channel can be used to _send_ a signal to a process ran by `/1.0/containers/<id>/exec`, however it doesn't appear to be possible to receive the details about signals which terminated this process. Would it be possible to add the last received signal alongside the `return` field in the operation metadata?

In the case that I am misunderstanding the docs and `signal` messages are in fact sent _to the client from the lxd API_, I'll be happy to submit a PR that updates the docs to make this more clear.

**Comment by stgraber** [comment]
The control socket is only used for the client to send signal to the running remote process, no messages are sent back about signals.

Per standard, the exit code when a process dies due to signal is going to be 128 + signal number, so if your exit code is 137, that means SIGKILL. Internally LXD sees this as the child process (forkexec) having exited with exit code 137, LXD doesn't know for sure that this was caused by a signal or not so it feels like a bit of a stretch to put it in the API.

Most likely, you can just have your client look at the recorded exit code and interpret based on standard values: https://www.tldp.org/LDP/abs/html/exitcodes.html

**Comment by benjamincburns** [comment]
Thanks for this, though now I'm having another problem fetching the exit code (can't fetch operation after exec completes, 404s). I'll raise another issue for this or comment on one if it already exists.

**Comment by benjamincburns** [comment]
Looks like #2797 is the issue I'm having now.
