### ISSUE TITLE
lxd-3.11 and nvidia-container-cli -- nvidia hook doesn't succeed -- good workaround?

### ISSUE THREAD

**Issue by danielrobbins** [lxc/lxd#5625]
So, I am able to get nvidia graphics working inside a container as long as I `chmod 666 /dev/nvidia*` on the host. Otherwise, `nvidia-container-cli` call in `/usr/share/lxc/hooks/nvidia` fails as follows:

 I0401 03:37:29.684130 28010 driver.c:133] starting driver service
 I0401 03:37:29.686296 28008 driver.c:233] driver service terminated with signal 15

Here is the strange thing. On the command-line, as root, I can work around this issue by passing `--user=root:video` to the `nvidia-container-cli` call as follows:

~~~~
# nvidia-container-cli --user=root:video info
NVRM version:   410.93
CUDA version:   10.0

Device Index:   0
Device Minor:   0
Model:          GeForce GTX 1060 6GB
Brand:          GeForce
GPU UUID:       GPU-948a9029-0271-3fc7-c9c2-8bb42f92b3b0
Bus Location:   00000000:08:00.0
Architecture:   6.1
~~~~

However, the exact same call will not work properly from the nvidia hook. I suspect this is due to lxc dropping some necessary capabilities?

In any case, while I can work around this by making the device nodes world-readable, I'd like to find a solution that is better than this. Any ideas?

(using lxc-3.0.3, lxd-3.11, Funtoo Linux.)

**Comment by danielrobbins** [comment]
Also, as you might have guessed, in Funtoo/Gentoo the device nodes are owned by `root:video` and are 660.

**Comment by stgraber** [comment]
I can't really think of a way around this. The `nvidia` hook is run as root in the container's user namespace, which is effectively a nobody user as far as /dev on the host is concerned. If that user cannot access the device node, the call to nvidia-container-cli will fail causing the hook to fail.

There's nothing we can do about that from the hook and it also feels wrong to have LXD itself (which does run as real root) to start mangling the permissions on those device nodes.

So you pretty much have two options:
 - Mangle the device nodes to be 666 as is apparently the case on other distros
 - Don't use nvidia.runtime and instead manually install things in the container as LXD's gpu devices themselves should be fine regardless of mode on the host side device.

Closing this issue as this is due to distribution configuration and not something that LXD itself can do much about. Maybe the LXD packager on Gentoo can put a udev hook in place to set more permissive permissions on those devices?

**Comment by danielrobbins** [comment]
Well, I definitely want to use the nvidia.runtime stuff as it makes things so much easier for users.

I have seen some approaches where /etc/subuid is used to make a user id that has access to the video device subordinate to root -- see here: https://blog.simos.info/how-to-easily-run-graphics-accelerated-gui-apps-in-lxd-containers-on-your-ubuntu-desktop/

Could an approach like this be leveraged to allow access to the device nodes without opening up permissions on the device nodes to everyone?

**Comment by stgraber** [comment]
No because the hook always runs as root in its user namespace and root isn't (and shouldn't) be mapped to an existing user.

Another alternative would be for you to figure out the mapped uid of root for all your containers (possibly the same if you're not using security.idmap.isolated) and then add a POSIX ACL to your /dev/nvida* devices so that this uid can access them.

**Comment by danielrobbins** [comment]
Ah, I see. So I could just add an acl to allow the first UID in the mapping range of that container, and that should likely do it? I suppose I should still be able to create containers, just not start them until the acl is added -- so even with isolated I should be able to extract the UID of the root user. I may look into that and then fall back to opening up the device nodes if that seems problematic.

**Comment by stgraber** [comment]
Yeah, the first uid will be the root uid and that's what the hook will run as.
