### ISSUE TITLE
Allow setting the NAT source address (SNAT instead of MASQUERADE)

### ISSUE THREAD

**Issue by K-os** [lxc/lxd#5648]
I have LXD running on a machine with multiple addresses on the same interface. Currently the `iptables` NAT rule created by LXD uses the MASQUERADE target. This is perfectly fine as a default, but I would like to specify the source address used for packets originating from containers attached to a specific bridge. Currently I do that by manually setting an `iptables` rule with `-j SNAT`  on the host for the LXD subnet instead of the default `-j MASQUERADE` rule.

It would be nice if LXD had a configuration option to set the external source address used for a specific bridge. For example like this:
```
lxc network set testbr0 ipv4.nat.address <EXTERNAL_IP>
```
which would result in a rule like this:
```
Chain POSTROUTING (policy ACCEPT)
SNAT       all  --  10.59.67.0/24       !10.59.67.0/24        /* generated for LXD network testbr0 */ to:<EXTERNAL_IP>
```

Edit:
Naturally the same feature should exist for IPv6.

**Comment by stgraber** [comment]
Adding `ipv4.nat.address` and `ipv6.nat.address` shoudl be easy enough to do.
In the meantime you can set `ipv4.nat` to false and have a regular firewall script do it.

**Comment by stgraber** [comment]
@tomponline giving you that one too, should be an even easier one than the other.

**Comment by K-os** [comment]
> Adding `ipv4.nat.address` and `ipv6.nat.address` shoudl be easy enough to do.
> In the meantime you can set `ipv4.nat` to false and have a regular firewall script do it.

That is exactly what I am currently doing, but having the config all in one place in LXD would be much nicer.

Thank you for accepting the feature suggestion.

**Comment by rbressers** [comment]
If you can add this functionality to the NAT option in the proxy too, that would be awesome. Right now, the config of a NAT "proxy" is:
```
proxy-ssh:
  bind: host
  connect: tcp:10.0.167.53:22
  listen: tcp:111.222.333.444:22
  nat: "true"
  type: proxy
```
If we can specify the NAT address for SNAT, that would be great.

**Comment by stgraber** [comment]
@rbressers oh, so you'd want the source address to also be rewritten? But in this case, there's only really a single IP that can be used and that's the IP of the lxd bridge itself, so 10.0.167.1 in your case as all others would lead to broken communication.

So that'd be something like `nat.source=true` which causes masquerading for that traffic to happen too.

Is that what you're after?

**Comment by rbressers** [comment]
Right now, I'm doing port forwarding by using the proxy feature with nat=true in the config for specific ports. What I'm after is a feature, preferably in the proxy, to translate the local IP address (10.0.167.1) from the container to the outside IP address (111.222.333.444). That way, traffic is sourced from the IP address I specify instead of what the default lxdbr0 config is specifying. Does that make sense or am I possibly hijacking an issue here?

**Comment by rbressers** [comment]
The more I think about it, the less it makes sense. Configuring it on the container makes a lot more sense indeed. Excuse me.

**Comment by tomponline** [comment]
Looking into this, these seem like the relevant section to modify:

- https://github.com/lxc/lxd/blob/1a18568b53957782a737012e66f6dd35b5b3a90a/lxd/networks.go#L1279-L1289
- https://github.com/lxc/lxd/blob/1a18568b53957782a737012e66f6dd35b5b3a90a/lxd/networks.go#L1448-L1458

Then adding the new `ipv4.nat.address` and `ipv6.nat.address` to the config validation using the `networkValidAddressV4` and `networkValidAddressV6` validation callbacks respectively:

- https://github.com/lxc/lxd/blob/de7b0b42f2247d41c0296cf1cd0356baf0fc9597/lxd/networks_config.go#L66
- https://github.com/lxc/lxd/blob/de7b0b42f2247d41c0296cf1cd0356baf0fc9597/lxd/networks_config.go#L85
