### ISSUE TITLE
LXD deletes the container after the storage space is not released

### ISSUE THREAD

**Issue by ma3252788** [lxc/lxd#5690]
# Required information

 * Distribution:Ubuntu
 * Distribution version:16.04
 * The output of "lxc info" or if that fails:
   * Kernel version:4.13.0-36-generic
   * LXC version:3.0.1
   * LXD version:3.0.1
   * Storage backend in use:zfs

# Issue description

One day, the system prompts me that there is not enough space left. Then I used the df -h command to check the storage space. I found that the zfs file of lxd is very large, so I plan to delete the unwanted container to free up the space, but after I delete the container, Use the df -h command again to check the remaining storage space and find that the space is not released.

# Steps to reproduce

 1. Step one
df -h 
 2. Step two
lxc delete somecontainer
 3. Step three
df -h

the space is not change!
![](http://filessl.machunjie.com/blog/file/20190422101346.png)

# Information to attach
The container was deleted . there is no more informations.

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
ZFS loop files never shrink, that's why our default allocation is pretty conservative to avoid filling your underlying partition and is why we recommend using a dedicated partitions for production environments.

Your best bet is to either find something else to clear from your /. If you want to actually shrink that ZFS, you may be able to temporarily set it up as a RAID1 with another loop file that's fully sparse, let it replicate then remove the original file and rename the other one, but that'd require as much space as is currently in use in your zpool which seems unlikely to be available at this time.

An alternative is to create another LXD storage pool, then move containers between pools and finally delete the original pool entirely. This will similarly require you have as much extra free space as you're currently using in your zpool.


Closing as not a LXD issue but a ZFS setup one.
The LXD logic for creating the loop is to be at least 15GB and at most 100GB with the default set to 20% of disk space.

**Comment by ma3252788** [comment]
What do you mean, when I use lxd init to set the size, will lxd immediately occupy the same amount of space?

**Comment by stgraber** [comment]
No, it creates a sparse file. Sparse files grow as they're written to but will normally not shrink once they've been written to.

So deleting a container frees space for ZFS to use in that file but will not release that disk space to be used on the underlying filesystem.

**Comment by ma3252788** [comment]
I see, this file will only increase and not decrease, right? But isn't there really any way to reduce the volume? Or is there a way to limit the size of ZFS?

**Comment by lhorace** [comment]
I've been following this thread with interest, typically you call TRIM though LXD ZFS is new to me that I haven't tried, my question to @stgraber, can you call trim inside a CT?

**Comment by lhorace** [comment]
> ZFS loop files never shrink

Is this raw file on ZFS or there is mechanic called ZFS Loop files ? Excuse my ignorance.

**Comment by stgraber** [comment]
ZFS doesn't yet support discard/TRIM. 0.8 gets support for it on block devices, not sure if the same will work on loop files.

**Comment by lhorace** [comment]
@stgraber You said ZFS Loop files, so to avoid endless googling what ZFS loop files are, because my impression is that ZFS Loop files is not the same as loop virtual devices?

**Comment by lhorace** [comment]
It's a technology of ZFS?

**Comment by stgraber** [comment]
@lhorace zpools which are backed by files rather than block devices indeed do not use the normal loop block devices you normally find on Linux, that is, they do not allocate /dev/loopX devices nor show up in any device mapper listing or `losetup -a`.

**Comment by lhorace** [comment]
Pretty much BTRFS subvolumes
