### ISSUE TITLE
Rough experience upgrading from ubuntu 18.04 to 19.04

### ISSUE THREAD

**Issue by dankegel** [lxc/lxd#5752]
* Distribution: ubuntu
 * Distribution version: 19.04
 * The output of "lxc info" or if that fails:
```
  certificate_fingerprint: f7580e6dbb6306b26ea3cbc85fbf57c2f31c63b7cbb2e19db9a095a7bf7764ea
  driver: lxc
  driver_version: 3.0.3
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 5.0.0-13-generic
  server: lxd
  server_pid: 1867
  server_version: 3.0.3
```
# Issue description

Upgraded from 18.04 to 18.10 and then 19.04.  Saw error in upgrade log about lxd.  Could not start lxd.

# Steps to reproduce
Install 18.04.  Use lxd happily.  Upgrade to 19.04.  Upgrade fails at end with
some warning about lxd.  Ignore it, uninstall the flailing package, and continue:
```
$ sudo apt remove --purge lxd lxd-client
$ sudo snap remove lxd
$ sudo snap install lxd
$ lxc launch ubuntu:18.04 demo-ubu1804
Creating demo-ubu1804
Error: Failed container creation: No storage pool found. Please create a new storage pool
$ lxd init
Error: Failed to create storage pool 'default': Failed to create the ZFS pool: cannot create 'default': pool already exists
$ echo [!&*#`1!>@!'
$ sudo apt install zfs-utils
$ sudo zpool list
NAME      SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
default  13.9G   938K  13.9G         -     0%     0%  1.00x  ONLINE  -
$ sudo zpool status
...
	  /var/snap/lxd/common/lxd/disks/default.img  ONLINE       0     0     0
$ sudo zpool destroy default
$ sudo zpool list
no pools available
$ sudo ls -l /var/snap/lxd/common/lxd/disks/default.img
-rw------- 1 root root 15000000000 May 13 06:33 /var/snap/lxd/common/lxd/disks/default.img
```

wat.  That was harder than I expected; I had to look up howtos like
https://blog.simos.info/how-to-initialize-lxd-again/
and I had to guess that it was ok to leave default.img dangling.
There seems to be a nice shim apt package that installs the
snap but the roughness I ran into shows it may need some polish still?

**Comment by stgraber** [comment]
The upgrade process from 18.04 to 18.10 is supposed to install the snap and perform data migration for you. This apparently failed in your case, though unfortunately your actions after that have since made it impossible to unblock the clean upgrade or recover any useful data or log out of it :(

Anyone who hits such issue, please, before purging the packages (which will destroy any data you may have and will potentially leave your system in a bit of a confused state), file your issue then, so we can figure out what failed and give you instructions to manually unblock you.

That makes it possible to fix the issue you ran into so that others don't get it in the future and it would get you back online with all your configuration and containers intact.

The other errors above come from the fact that the ZFS pools remain on your systems when LXD is forcefully removed, LXD then fails to create that ZFS pool because it already exists. The naming there may get a bit confusing as the zfs tools talk about the zfs pools and lxd talks about its storage pools, but the error is accurate given the state of your system at the time.


Closing this issue as there's unfortunately not much we can do to track down what happened in this case and ensure that it doesn't happen to someone else. All we can really do is hope that the next person who hits that upgrade issue reports it before continuing on with another upgrade or package removal.
