### ISSUE TITLE
Unattended complete removal of lxd is hard

### ISSUE THREAD

**Issue by dankegel** [lxc/lxd#5782]
Looking at 
- https://discuss.linuxcontainers.org/t/how-to-remove-lxd-from-my-system/2336/4
- https://discuss.linuxcontainers.org/t/how-to-remove-an-unused-network-bridge/72
- https://blog.simos.info/how-to-initialize-lxd-again/
- https://discuss.linuxcontainers.org/t/reliable-script-to-set-up-and-tear-down-a-demo-of-lxd-was-hard-to-write/1931/4

it seems that one has to either do a fair number of manual commands,
or a fair amount of complicated scripting, 
to completely remove lxd and return system to original state.

Is that still the case?

(And there seem to be many ways to fail; on one ubuntu 18.04 machine, lxd 3.0.3 refused to
create a container, saying
"Error: Failed container creation: Create LXC container: LXD doesn't have a uid/gid allocation. In this mode, only privileged containers are supported"
possibly because it was interrupted on first run.
Comparing to other systems, it seems /etc/subgid and /etc/subuser are incomplete on this machine.
I was considering reformatting just to fix that one problem, but then realized that maybe lxd
wanted rebooting after I made those two files look the same as on other systems, and that worked.
I'd *never heard* of those files before.  lxd is like C++: it has so many nooks and crannies
you have to know about that you're bound to shoot yourself in the foot at some point...)

**Comment by stgraber** [comment]
Yeah, there are probably a few things we could do better, if only putting some more documentation in this repo.

The issue that most packagers hit with tools like LXD is to find the right balance between cleaning things up and also limiting accidental data loss.

If simply removing the LXD package was enough to cause all containers/images/storage to be deleted, then one broken package in the package archive of your distro could cause LXD to be automatically deleted along with all your data. For that reason most distros have a separate `purge` mode that removes a different set of files.

Though that kind of file removal still isn't enough for something like LXD which also drives quite a few kernel APIs, for storage, network and containers.

If LXD itself is responsive, then you can clean things up by deleting all container, images and storage volumes, then deleting all storage pools and all networks. At that point all kernel objects would be gone and wiping the filesystem entries of LXD will get you back to a pristine state.

Failure to do so, either because LXD can't be reached or because its database got reset/deleted somehow would require you to manually cleanup everything. This usually involves going through your entire process list, identify anything that may be related to LXD or one of your previous containers and killing that. Then delete any network interface/bridges that were leftover from those, then locate and delete the storage pool used (relevant for zfs, lvm and ceph).

A reboot usually will take care of all of that for you, so it tends to be a good shortcut if you don't mind the short interruption.

As for the /etc/subuid and /etc/subgid thing, that one is very distro specific. The LXD snap doesn't use those files (which come from the `shadow` package) at all, but the deb on Ubuntu still does.

I think you can get in the situation you're describing when removing LXD from your system and having its subuid/subgid entries removed, then re-installing it. That's because those entries get added when the `lxd` user and group is first added to the system (it's part of the system user addition process, outside of LXD). When removing lxd, that user/group remain on the system to avoid potential data be left on your filesystem without an owner. Installing lxd again therefore skips the user creation stage (as the user already exists) and so no new entries are generated for subuid/subgid.

The whole subuid/subgid is very confusing to users, even more so when you consider isolated mode and uid/gid passthrough which is why this isn't something we recommend our distributors do anymore and why the LXD snap doesn't use that mechanism at all. It's however not a behavior we'd want to see change in a minor bugfix upload to Ubuntu as it may have side effects, so instead you're getting the new behavior when moving to the snap.

**Comment by dankegel** [comment]
I understand there's a distinction between stuff the package does on install and uninstall (e.g. the subuid stuff) and the more persistent data.  I'm mostly worried about the latter.

The core of this issue is that "you can clean things up by deleting all container, images and storage volumes, then deleting all storage pools and all networks" involves either a) understanding lxc in detail and issuing a number of complex commands, or b) running a script which somebody wrote which does that for you.  And that script doesn't exist, as far as I know.  How hard would it be to write?  Would it have to be turing-complete?

**Comment by dankegel** [comment]
Hot damn.  I'll give that a shot, thanks.

**Comment by dankegel** [comment]
On one system, running that and then initializing lxd gives the error
```
==> Deleting all containers for project: default
==> Deleting all images for project: default
==> Deleting all profiles for project: default
==> Deleting all networks
==> Deleting all storage pools
...
Error: Failed to create storage pool 'default': Requested BTRFS subvolume exists but is not empty
$ sudo ls /var/lib/lxd/storage-pools/default
containers  images
```

Hrm.  The storage pool didn't get deleted?

**Comment by dankegel** [comment]
FWIW, the queries it uses seem to not work reliably in lxd 3.0.3, is that expected?
```
buildbot@rbb-ubu1904-2:~$ lxc query "/1.0/storage-pools/default/volumes/custom?recursion=1"
[]
buildbot@rbb-ubu1904-2:~$ lxc storage volume list default
+-----------+------------------------------------------------------------------+-------------+---------+
|   TYPE    |                               NAME                               | DESCRIPTION | USED BY |
+-----------+------------------------------------------------------------------+-------------+---------+
| container | quick                                                            |             | 1       |
+-----------+------------------------------------------------------------------+-------------+---------+
| container | touchy-ubu1904                                                   |             | 1       |
+-----------+------------------------------------------------------------------+-------------+---------+
| image     | 7f1802898b5560285d838df7aa37a376352c6027440e536f543f5ff1471d46e6 |             | 1       |
+-----------+------------------------------------------------------------------+-------------+---------+
| image     | d1ee0732edc89f83b2328691aacb3f41b808782ca6517554fae04ac5538c720e |             | 1       |
+-----------+------------------------------------------------------------------+-------------+---------+
buildbot@rbb-ubu1904-2:~$ lxc --version
3.0.3
```
This causes script failure.

**Comment by stgraber** [comment]
The query is specifically for custom volumes, so it's correct.
The container volumes are deleted when containers are deleted, same goes for images.

If you have the above volume list while at the same time having an empty `lxc list` and `lxc image list`, then that's likely due to bad error handling in those storage paths in the past (which I believe we've since fixed) so a quick bit of DB surgery may be needed for that one.

**Comment by dankegel** [comment]
Thanks, I'll not worry about it then.  Workaround was something like:
```
$ lxc ls
$ lxc rm ... whatever that found ...
$ lxc image list
$ lxc image delete ... whatever that found ...
$ echo '{}' | lxc profile edit default
$ lxc storage delete default
```

Your assistance has been very helpful.
