### ISSUE TITLE
Use cluster heartbeats to notify of needed LXD update

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#5824]
Right now LXD uses a task run every minute (I think) to query the database's nodes table to check if any other node has a version or API extension count higher than the local node, if that's the case, a refresh is triggered.

While not super expensive, this does add a bit of overall load and delay when updates are happening.

Instead I think it'd make sense to use the heartbeat mechanism and have the leader include the current maximum version of `schema` and `api_extension`. The leader already grabs the content of that DB table, so the query is free and it already communicates with all nodes more regularly than our current background task.

So this feels like a cheap win we can do, reducing the refresh time.

**Comment by stgraber** [comment]
@freeekanayaka I think we discussed this in Lyon when discussing the dqlite upgrade story, any concerns?

If not, @monstermunchkin would you be interested in doing this, in the spirit of getting everyone on the team to touch a bit of the clustering code :)

**Comment by freeekanayaka** [comment]
It sounds ok, however I'd recommend to wait for the dqlite-1.0 branch to be merged, to avoid introducing conflicts that could be a bit hard or time consuming to solve. I believe the plan was to merge that after the coming release (which would be next week), so we don't need to wait too much.

**Comment by stgraber** [comment]
@freeekanayaka @tomponline 
So this may end up needed to solve #5823 without introducing a whole separate set of internal API endpoints just for that, if we're going that way then we'd want to change the data sent for the heartbeat already.

Not sure where you see a likely conflict with the dqlite 1.0 work, is it in the refresh/update handling specifically due to the new code to handle protocol changes? If so, we can indeed wait before we use heartbeats to trigger the refreshes but already switch the heartbeat content to including everything we need.

I'd expect us to want a struct kinda like:

```go
type apiHeartbeatMember struct {
    ID int64
    Address string
    Raft bool
    Online bool
}

type apiHeartbeatVersion struct {
    Schema int64
    APIExtensions int64
}

type apiHeartbeat struct {
    Members []apiHeartbeatMember
    Version apiHeartbeatVersion
    Timestamp Time.Time
}
```

This covers the existing Raft node list use case and provides the information needed for all cluster members to easily detect new members joining/leaving/going offline by keeping that struct in memory and comparing it when a new one comes in.

**Comment by freeekanayaka** [comment]
Yeah, the conflicts will likely come from the new code to handle protocol changes. Plus assorted conflicts that will inevitably happen more or less randomly because the code in those files has changed quite a bit (although these ones should not be too hard to solve). But that's fine if we really need to modify heartbeats now.

I did not yet look closely to what additional information needs to be included in the heartbeat in order to solve #5823. Is the full picture across all nodes really needed? For the purpose of triggering upgrades, just information about the latest Schema/APIExtensions found across all nodes would be enough, without including a detailed list of all the nodes.

I guess that for the purpose of fixing #5823 you want a full list of all the nodes with relevant information because you might need to reconfigure networking, as consequence of nodes joining/leaving.

I'm only slightly concerned that the heartbeat becomes effectively a watch system were we progressively add stuff that needs to be notified across all nodes. I presume we might have other cases like this (if we don't have already, without even realizing it).

Just to have a more complete picture, what would the new set of internal API endpoints look like in order to fix #5823? And what would be the mechanics there?

**Comment by tomponline** [comment]
@freeekanayaka for #5823 I am looking to remove this part of the the network start up code that spawns forkdns https://github.com/lxc/lxd/blob/master/lxd/networks.go#L2066-L2096 and stop passing the other node addresses to forkdns as command line arguments.

Instead I was thinking of setting up a periodic task (or event driven if possible) that will write out the same addresses to a text file that forkdns is watching (probably via inotify) and will then mutate its internal config so that it will relay DNS requests to the correct nodes.

So it appears (I am unfamiliar with the cluster feature) to:

1. Get a list of cluster nodes (https://github.com/lxc/lxd/blob/master/lxd/networks.go#L2053)
2. For each non-local node, connect to the API (https://github.com/lxc/lxd/blob/master/lxd/networks.go#L2053)
3. Retrieve info about the equivalent network being started on the remote node (https://github.com/lxc/lxd/blob/master/lxd/networks.go#L2082)
4. Filter to only get IPv4 addresses of the node on that network (https://github.com/lxc/lxd/blob/master/lxd/networks.go#L2088-L2089)

I presumably could just do all of this in a periodic loop via a separate go routine in LXD (or is the preferred approach to use a task runner?). However if we want this to be event driven then we would need to include all of the local network addresses of the LXD node in the heartbeat message.

**Comment by tomponline** [comment]
@stgraber are you thinking that we should use the new raft members events to trigger the existing code to connect to it and query the API to get the node address on the named network? Would there be a potential to miss existing nodes who are already joined to the cluster but later on have fan networking added?

**Comment by freeekanayaka** [comment]
@tomponline just as quick note about any event-driven approach: we always need to account for the situation that the event is not actually fired because of network disruption. So I believe that some sort of periodic task-like logic will always be needed regardless.

**Comment by tomponline** [comment]
@freeekanayaka OK that makes sense, for now I will implement a polling mechanism, is there a preferred way do kick off a go routine in LXD at regular intervals? Or shall I just start a go routine with an internal ticker?

**Comment by freeekanayaka** [comment]
@tomponline yeah it's best to use lxd/task, look at daemon.go where other tasks are started too. The reason is that (among other things probably not relevant for this use case) the task package as support for stopping the periodic goroutine and do any cleanup work that is needed for a graceful shutdown of the daemon. You might want to start the task only if clustering is enabled, we already have other tasks that run only for clustering, again see daemon.go

**Comment by stgraber** [comment]
Yeah, another task for this fan thing is probably fine for now, but I think we should really switch to using the heartbeat for that kind of stuff in the near future.

The reason being that it's data which we already pull from the database every 10s and we already send part of that data to all cluster members, including the entirety of the data then allows for a very cheap way for all cluster nodes to know 1) if they need to update and 2) if the set of online cluster members has changed. This eliminates two cases where we need polling the database every minute or so which when we're talking > 100 cluster members, means multiple DB queries per second.

**Comment by tomponline** [comment]
@stgraber @freeekanayaka I've added the additional task that polls each cluster member every 30s. https://github.com/lxc/lxd/pull/5823

**Comment by stgraber** [comment]
Okay, hopefully we can get rid of that in 3.15, I'd like to get to a case where an idle LXD doesn't end up hitting the cluster database dozens of times every minute as that makes scaling very problematic.

**Comment by tomponline** [comment]
@stgraber please can you point me in the direction of the task the case refers to: 

"Right now LXD uses a task run every minute (I think) to query the database's nodes table to check if any other node has a version or API extension count higher than the local node, if that's the case, a refresh is triggered."

Is it this one? https://github.com/lxc/lxd/blob/master/lxd/cluster/upgrade.go#L63

**Comment by stgraber** [comment]
Yep, that's the one. Apparently we have it every 5 minutes instead.
