### ISSUE TITLE
lxd 3.14 release artifact contains both dist/ and vendor/

### ISSUE THREAD

**Issue by cyphar** [lxc/lxd#5858]
I just hit this when bumping the openSUSE LXD version. It appears that the most recent release artifact has both a `dist/` and `vendor/` directory. In our build scripts we assumed that `dist/` was the complete source of the `vendor/` tree and so we just do `mv -v dist/src vendor` but this obviously doesn't work as easily when you have an existing `vendor/`.

As far as I can tell this is a mistake because LXD has all of this special handling around the `dist/` generation and building using it.

**Comment by stgraber** [comment]
So not something we're going to be fixing in our Makefile as `vendor` will be gone in 3.15 following the switch to dqlite 1.0.

However for anyone packaging LXD 3.14, you'll want to move the content of vendor/ over that of dist/src which will get you the right versions of the few broken raft bits we had to vendor.

Sorry about that, I completely forgot about `dist/` when I had to land the vendoring bits to get out of a mess caused by breaking raft changes upstream, if I had thought of it, I'd have updated the Makefile to copy vendor on top of dist during tarball generation.
