### ISSUE TITLE
LVM Storage info always shows zero space used

### ISSUE THREAD

**Issue by datablitz7** [lxc/lxd#5868]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.5 LTS
 * The output of "lxc info" or if that fails: 
[lxc_info.txt](https://github.com/lxc/lxd/files/3315068/lxc_info.txt)
   * Kernel version: 4.4.0-151-generic
   * LXC version: 3.0.3
   * LXD version: 3.0.3
   * Storage backend in use: LVM

# Issue description

LVM Storage info always shows zero space used

# Steps to reproduce

 1. Create an LVM thinpool storage
 2. Launch a container on LVM storage
 3. Check storage usage using "lxc storage info <POOLNAME>"
 4. Reported "space used" is 0B, as per attached
[lxc_storage_info.txt](https://github.com/lxc/lxd/files/3315067/lxc_storage_info.txt)

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [X] Container log (`lxc info NAME --show-log`)
[lxc_info_show-log.txt](https://github.com/lxc/lxd/files/3315065/lxc_info_show-log.txt)
 - [X] Container configuration (`lxc config show NAME --expanded`)
[lxc_config_show_expanded.txt](https://github.com/lxc/lxd/files/3315097/lxc_config_show_expanded.txt)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [X] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
[lxc_monitor.txt](https://github.com/lxc/lxd/files/3315066/lxc_monitor.txt)
Actual LVM Storage Usage: [lvs.txt](https://github.com/lxc/lxd/files/3315100/lvs.txt)

**Comment by tomponline** [comment]
Recreated this issue

```
lxc storage info lvmpool
info:
  description: ""
  driver: lvm
  name: lvmpool
  space used: 0B
  total space: 43.00GB
used by:
  containers:
  - c3
  images:
  - 1ee31e5f12f654209c22b55e61b8c25f05f7e8a6435a2fa827243bebc4ce719d
```

**Comment by tomponline** [comment]
@stgraber there is a comment in the code about this already:
https://github.com/lxc/lxd/blob/master/lxd/storage_lvm.go#L2181-L2182

```
// Thinpools will always report zero free space so no use in calculating
// a used count. It'll be useless information for the user.
```

This is true, for the volume group,as 100% of it is allocated to the thinpool LV.

```
sudo vgs  -o vg_name,lv_name,data_percent,vg_free,lv_size,vg_size,vg_free
  VG      LV                                                                      Data%  VFree LSize  VSize  VFree
  lvmpool LXDThinPool                                                             2.42      0  38.04g 40.04g    0 
```

However in principle some sort of usage value could perhaps be derived from looking at the thinpool LV and its LSize and data usage % value. This would only represent how many blocks had been allocated to thin volumes, not whether they are actually used by the file system (and they are not normally released by the OS unless fstrim is run).

What do you think?

**Comment by stgraber** [comment]
@tomponline agreed that we won't get useful data from LVM itself, but we could report the disk usage by looking at Path() so long as it's mounted, effectively reporting the filesystem data instead of the LVM data.

So effectively the same logic we have for the dir backend, but returning 0 if Path() isn't mounted.

**Comment by tomponline** [comment]
@stgraber I just created a dir pool to test that and it shows some weird figures:

```
lxc storage create dirpool dir
lxc init ubuntu:18.04 c1 -s dirpool
```

```
lxc storage ls
sudo du -h /var/lib/lxd/storage-pools/dirpool
685M
lxc storage info dirpool
info:
  description: ""
  driver: dir
  name: dirpool
  space used: 125.43GB
  total space: 234.69GB
used by:
  containers:
  - c4
```

I'm a bit confused where those figures come from, I assumed they were the equivalent output of `df` for my "/" mount.

It comes from here: https://github.com/lxc/lxd/blob/60dc9b769ac3377d0aa2ab6d90e2921e6a05b417/lxd/storage_utils.go#L366-L383

But my "/" is only 219GB in size and 117GB free. Its ext4.

```
df -h
/dev/sda2                   219G  117G   91G  57% /
```

For LVM, I would then need mount each container's LV that use that storage pool and run the equivalent process in order to get total usage for the storage pool. Is that what you meant?

**Comment by tomponline** [comment]
@stgraber Ah, so I think its to do with the different way `df` calculates space,taking into account space reserved for root user. https://stackoverflow.com/questions/4965355/converting-statvfs-to-percentage-free-correctly

**Comment by stgraber** [comment]
Could also be a GiB vs GB issue, most tools report GiB, we report GB.
In any case, the values you're seeing for your dir pool look reasonable enough.

And I know that when you have project quotas enabled we report the proper per-container data, so that logic must be called properly in that case, the only real difference with LVM is that we'll want to ensure that the mount is present, if it got ripped out for some reason, then 0 is better than showing the host disk usage.
