### ISSUE TITLE
Copying Container Issue

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#5912]
Im trying to perform a copy of a stopped container with the LXD api but I come accross the error 

```
Error transferring container data: x509: certificate is valid for o, not b
```

**Comment by stgraber** [comment]
Please fill the issue template, this issue report doesn't contain anything helpful for us to track it down.
We at the very least need `lxc info` on both source and target and either the output of `lxc copy --debug` or since you're doing it directly through the API, the exact API request you sent.

It sounds like the certificate provided as part of the request to the target server doesn't match the certificate of the source server

**Comment by turtle0x1** [comment]
This was caused by me sending the source to migrate the image as localhost and i think it resolved to itself, changing the source to the ip address fixed the issues (sorry its been a long day)
