### ISSUE TITLE
Building LXD 3.15 from tarball fails with dependency issue

### ISSUE THREAD

**Issue by fguitton** [lxc/lxd#5965]
# Required information

Distribution: Ubuntu
Distribution version: 18.04.2

# Issue description

Trying to build from tarball lead to the following error message:

```
root@:/tmp/lxd-3.15# go get -t -v -d ./...
github.com/cpuguy83/go-md2man (download)
package github.com/cpuguy83/go-md2man/v2/md2man: cannot find package "github.com/cpuguy83/go-md2man/v2/md2man" in any of:
        /usr/lib/go-1.10/src/github.com/cpuguy83/go-md2man/v2/md2man (from $GOROOT)
        /root/go/src/github.com/cpuguy83/go-md2man/v2/md2man (from $GOPATH)
github.com/russross/blackfriday (download)
package github.com/russross/blackfriday/v2: cannot find package "github.com/russross/blackfriday/v2" in any of:
        /usr/lib/go-1.10/src/github.com/russross/blackfriday/v2 (from $GOROOT)
        /root/go/src/github.com/russross/blackfriday/v2 (from $GOPATH)
Makefile:18: recipe for target 'default' failed
make: *** [default] Error 1
```

# Steps to reproduce

 1. Clear GO cache
 2. Download and extract 3.15 tarball
 3. make deps; export ... ; make

**Comment by stgraber** [comment]
I'm not sure why your version of Go would fail to download those packages, but when building from the release tarball, it's usually best to see your GOPATH with what's in `dist/src` so that you're building with the exact versions we included. One way to do that is:

```
tar zxf lxd-3.15.tar.gz 
cd lxd-3.15
mv dist _dist
export GOPATH=$(pwd)/_dist/
cd _dist/src/github.com/lxc/lxd
make deps
<follow instructions for export>
make
```

I'm pushing a branch which will simplify this process quite a bit too. So far mostly distributions have been dealing with our dist/ directory and clearly worked around the rough edges on their side :)

**Comment by stgraber** [comment]
My fix effectively removes that awkward `mv dist _dist` and also changes the way we ship the C deps so that they don't get re-downloaded during `make deps`.

**Comment by fguitton** [comment]
Wonderful, this is working like a treat !
