### ISSUE TITLE
Race condition in transparent image caching (concurrent launch)

### ISSUE THREAD

**Issue by benbooth493** [lxc/lxd#599]
After creating upwards of 20 images I have now started the receive the following error:
UNIQUE constraint failed: images.fingerprint

**Comment by benbooth493** [comment]
Appears is could be related to 2 instances of lxc launch <remote>:<image> running at the same time trying to pull the same image.

**Comment by hallyn** [comment]
> Appears is could be related to 2 instances of lxc launch <remote>:<image> running at the same time trying to pull the same image.

Interesting - thanks for the report.  It sounds like we should check
for that error, accept that we raced, and proceed rather than failing.

Now if we kept a global mutexed list of fingerprints which we are currently
downloading, we could avoid doubling network traffic in such caess.  That
may well be worthwhile.
