### ISSUE TITLE
Consider using Go Modules to ease build process

### ISSUE THREAD

**Issue by sr229** [lxc/lxd#5992]
Go 1.11 introduces Go Modules which should defeat the need for `$GOPATH`, making the entry point for Go much more easier. I think LXD should follow this route to make the project more easy to onboard into.

**Comment by stgraber** [comment]
GOPATH management hasn't really been a thing for a while now. If it's not set, it defaults to the `go` directory in your home directory and things usually work just fine there.

We've done the needed work to make it possible for our downstreams to use the LXD packages inside a go mod project, so in that regard we're good already.

As for using gomod ourselves, we currently have no plan on pinning our dependencies or in significantly increasing the on-disk size needed to build LXD. Switching to gomod would also make our CI quite a bit slower due to not using the shared GOPATH anymore and we wouldn't really get anything out of it.

The gomod pinning features are nice if you do want pinning, but given the lack of security release management in the Go ecosystem and LXD's obvious interest in security, pinning mostly ends up having you stay on vulnerable packages without any ability of getting notified when a security issue is discovered. That's why LXD has always been built against the latest version of all packages and if any of those repeatedly breaks us due to API changes, we'll just switch to a more reliable one (or write our own).

So long way of saying that these days a straight:
 - go get github.com/lxc/lxd/lxd

Works just fine, without ever messing with GOPATH and whether gomod are involved or not doesn't change that. We care about our downstreams' ability to vendor LXD and so test that the `client` package can be used with gomod but we don't have plans to have LXD itself make use of gomod in the near future.

**Comment by Foxboron** [comment]
>The gomod pinning features are nice if you do want pinning, but given the lack of security release management in the Go ecosystem and LXD's obvious interest in security, pinning mostly ends up having you stay on vulnerable packages without any ability of getting notified when a security issue is discovered. 

This doesn't make a lot of sense. You are explicitly pinning dependencies as you are distributing the release archives in LXD with all the dependencies under `_dist`. You are currently pinned to whatever you distribute and there is no clear way to know which dependencies you are distributing LXD with. To demonstrate this you can try figure out which released archive contains a copy of vulnerable copy of `golang.org/x/net` with CVE-2018-17847.

>That's why LXD has always been built against the latest version of all packages and if any of those repeatedly breaks us due to API changes, we'll just switch to a more reliable one (or write our own).

Given LXD cares about security, should you care about [reproducible builds](https://reproducible-builds.org/)? Using `go get github.com/lxc/lxd/lxd` would give you N number of different builds and there would be no clear way to actually figure out what was distributed where. It seems like snap also pulls in whatever was present at the time of building and would make it hard to debug issues introduced by a random commit in a dependency.

The release archive could in practice have `_dist` with the pinned sources for `dqlite`, `raft` and so on but also provide `vendor/` which would have the vendored sources for go  mod.

**Comment by vuori** [comment]
lxd 3.0.4 appears to be pretty much impossible to build at the moment even with the distribution tar, apparently due to changes in dependencies-of-dependencies: go get blows up with more spew than a C++ compiler. Please reconsider modules and complete vendoring as suggested in the previous comment.

**Comment by vuori** [comment]
Please reconsider modules as suggested in the previous comment. Getting lxd 3.0.4 to build from the distribution tar was a beast, though in the end this had more to do with lacking documentation [1]. With modules and proper vendoring, there wouldn't be need for the homebrew vendoring system.

[1] Running `make` inside the `dist` GOPATH worked, running it from the top level of the distribution tar exploded with confusing errors.

**Comment by s3rj1k** [comment]
+1 for go modules with vendoring

**Comment by sr229** [comment]
Looks like the community wants this change @stgraber, maybe you guys should reconsider.

**Comment by ydcool** [comment]
Since go 1.16, go tools has changed , as well as  the commands like  `go install` and `go get`,  and go module is enabled as default, and the `GOPATH` is going to deprecated sooner or later.

> See https://blog.golang.org/go116-module-changes

**Comment by tomponline** [comment]
As of https://github.com/lxc/lxd/pull/9142 we now support Go Modules on LXD.

**Comment by Foxboron** [comment]
That is great news. Thank you so much :)

I'll build an RC for Arch and verify there isn't any regressions in the `Makefile` for downstream packagers!
