### ISSUE TITLE
Evaluate Container Network Interface - CNI

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#601]
I just saw this initiative to draft a standard for defining network interfaces. Is it something that LXD is involved with? I mean if there are any intersections with the way how LXD config/profiles work, does it worth to share expertise? 

https://github.com/appc/cni

**Comment by stgraber** [comment]
It looks like a very interesting standard for application containers where the container isn't expected to configure its own networking and where the application developer may want a specific configuration.

It however doesn't appear to align with what we're doing in LXD where we treat containers as a black box, similar to a VM and where we expect the container to take care of bringing up its network using DHCP.


So I'm going to close this, not because it's not interesting but because we're currently not in the business of configuring anything for the container, network included. Should we ever revisit that, we'll definitely consider this spec.
