### ISSUE TITLE
"lxc file pull" of huge file continues to write the file to /tmp even after killing the command

### ISSUE THREAD

**Issue by melato** [lxc/lxd#6062]
Client version: 3.15
Server version: 3.15
snap lxd   3.15     11437  stable    canonical✓  -
Host: Ubuntu 18.04
uname -r:  4.15.0-55-generic

Steps to reproduce:
- create a large file "/var/log/file.log" in a container "a".  The file should be large enough so that you can do the rest of the steps before it finishes copying.  I used 16GB.
- from the host, run: lxc file pull a/var/log/file.log {dest}/file.log" # where {dest} is a directory in a non-root filesystem
- CTRL-C the above command
- sudo ls -l /tmp/snap.lxd/tmp/
- sudo ls -l /tmp/snap.lxd/tmp/ # again
Result:  There is a tmp file in /tmp/snap.lxd/tmp that keeps growing.

Expected Result:  When I stop the "lxc file pull", the server should stop copying the file and clean up.  Even better, the file should not be copied to an intermediate temporary file at the root filesystem, but copied directly to the destination directory (perhaps with a temporary name first and then renamed).

I ran "lxc file pull ..."  to move a 16G log file from a container to the host filesystem.
While waiting for the file to get transfered, I noticed that the free space of the root filesystem was getting lower, and I decided to stop the transfer with CTRL-C and do it with ssh cat, so I could compress the file in the process.  But I noticed that the root filesystem was continuing to get filled.  I noticed that the file was continuing to get copied to /tmp/snap.lxd/tmp/lxd_forkgetfile_207953117

**Comment by stgraber** [comment]
Aborting on ctrl+c isn't doable for that particular command as you're dealing with a REST API, killing the client has no affect on the server which will only notice the client connection having gone away AFTER it's done fetching the file and attempts to write it to the now dead http connection.

We "may" be able to skip the usage of the temporary file by having the C subprocess pipe the data to the main process rather than using the intermediate file temporary file but we'll need to jump through some hoops to retrieve the expected file size as this must be returned to the client ahead of the file content, making it always pretty tricky with streaming which is likely why we're using the temp file right now.

**Comment by stgraber** [comment]
Just spent a couple of hours poking around our logic to see what can be done with streaming.

We can pretty easily get our subprocess (`forkfile`) to receive a PIPE and stream the data to that, the problem is what happens afterwards. To return the proper http response, we need to know the file size, the file type and its modification time. That's data we could have the C process return separately through a separate communication channel, the issue is that to then stream this out, the http functions in Go that we use expect an actual File, not a PIPE. Feeding them a PIPE doesn't let us pass that side information.

I made an attempt at faking all this by creating an intermediate struct which can then return the expected data, the problem is that because the underlying functions expect to deal with a file, they also expect being able to seek through it, which isn't possible with a PIPE. When dealing with streaming like a PIPE, everything must get out in order. The only way around this I could do was to effectively buffer things in memory.

That's obviously not going to work as your 16GB log file would now not cost you any temporary space, but would cost you 16GB of RAM, which is much much worse :)

So I think the best way to handle this for now is to have `file pull` wrapped in the client as an un-cancelable action, meaning that pressing ctrl+c wil not exit and will show you a message telling you that this cannot be canceled. Forcing it will work and will kill the client, but at least it will have been pretty clear that something is still going on on the server side.

As mentioned earlier, the server side will fail as soon as it will try to send the data, causing the temporary file to get deleted. Or in the running out of disk case, will fail because of that, similarly causing the file to get deleted.

**Comment by stgraber** [comment]
(Oh, and in case someone is wondering, we can't just access the file directly from the container's filesystem and have the file transfer code use that, as accessing files inside a container without properly joining its namespace as our `forkfile` subprocess does is the source of HUGE security problems without would allow a user in the container to attack the host.)

**Comment by melato** [comment]
This is not a high priority issue for me.  I will just know to not use lxc file pull/push for large files. Perhaps it suffices to document this in "lxc file pull -h" and/or ask for confirmation if the file is larger than a certain size (e.g. 1MB or 0.1% of current RAM).

I mainly use "lxc file push" to push small initialization/installation scripts to a new container, typically to setup an account with my .ssh/authorized_keys.  After that, I can use scp.

If I need to regularly access large container files from the host or from another container, I would put these files in a shared device, so that I wouldn't have to transfer anything at all and so the files would not add to the size of the container.
