### ISSUE TITLE
Documentation about PKI is incomplete

### ISSUE THREAD

**Issue by akarelas** [lxc/lxd#6063]
In page https://lxd.readthedocs.io/en/latest/security/, we can read that to enable PKI mode you need to add a client.ca file inside ~/.config/lxc . The document forgets to mention where we are going to find this 'client.ca' file (or how we are going to create it).

Could you please fill-in this information? Because I really would like to use PKI with LXD. Thank you,

**Comment by stgraber** [comment]
That's the CA file from your PKI. The administrator of your corporate PKI should provide that to you.

If you use something like easy-rsa to generate your own, it will similarly give you a ca.crt as well as public/private pairs for every server/client you add to your PKI.

We don't go in details on where to find it because that's completely dependent on the PKI that you use. Most of our users for this feature use some kind of corporate PKI which provides those files through some kind of web interface or through management tools like Active Directory.

For a manual setup you can take a look at what we do to test the feature:
https://github.com/lxc/lxd/blob/master/test/suites/pki.sh
