### ISSUE TITLE
Add routed network mode

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#6175]
Add support for LXC's router network mode to LXD.

https://github.com/lxc/lxc/pull/2921

Propose the follow:

- New network nic type called `routed` (to align with existing `bridged` type).
- Have it require a `parent` property and one or more of `ipv4.address` or `ipv6.address` (support comma delimited for multiple addresses like ipvlan).
- If >0 IPv4 addresses supplied, then check for the same sysctls that LXC does and then configure router mode and l2proxy, with an IPv4 gateway value of "auto".
- If >0 IPv6 addresses supplied, then check for the same sysctls that LXC does and then configure router mode and l2proxy, with an IPv6 gateway value of "auto".

**Comment by zzlinwq** [comment]
1111111111

**Comment by najeal** [comment]
This issue is assigned on github but is marked has "not assigned" on the forum (https://discuss.linuxcontainers.org/t/lxd-contribution/5792/4). If it's still not assigned, I would like to pick it

**Comment by stgraber** [comment]
Have assigned it to you, I'm sure @tomponline will be happy to help with any question you may have, given he did the liblxc side of this work.

I think this should lead to about 5 commits, roughly doing:
 - Add a `device_routed` API extension to doc/api-extensions.md and shared/version/api.go
 - Extend the list of `lxcExtensions` in `lxd/daemon.go` to cover `network_veth_router` as needed for this feature
 - Add the implementation as `lxd/device/nic_routed.go` and hook it up in `nic.go`
 - Update the documentation in `doc/containers.md`
 - Add a testsuite as `test/suites/container_devices_nic_routed.sh` and hook it up in `main.sh`

`nic_ipvlan.go` is probably your best starting point as a template of how to add such a device, since both ipvlan and routed rely heavily on liblxc to do the setup.

The logic in `nic_routed.go` should be checking for that `network_veth_router` extension and fail environment validation if missing.

**Comment by tomponline** [comment]
@stgraber yep sounds good. Any questions @najeal let me know.

**Comment by najeal** [comment]
Thank!

**Comment by tomponline** [comment]
Hi @najeal, how are you getting on with this change, did you manage to get LXC up and running? If not then you could try using the "edge" channel of LXD via snap (which comes with the latest version of LXC inside it) and then sideload your LXD binary into it:

```
move lxd binary to /var/snap/lxd/common/lxd.debug
systemctl reload snap.lxd.daemon
```

**Comment by najeal** [comment]
I will try to catch you on IRC :)

**Comment by tomponline** [comment]
@najeal great, let me know any questions you have.
