### ISSUE TITLE
[3.17 regression] lxc consuming stdin breaks existing scripts

### ISSUE THREAD

**Issue by paride** [lxc/lxd#6188]
# Required information

 * Distribution: Ubuntu
 * Distribution version: any running the latest snap
 * Kernel version: any
 * LXC version: 3.17
 * LXD version: 3.17

# Issue description

LXD 3.17 allows the container configuration to be passed in YAML format to the standard input of the `lxd init` and `lxc launch` commands ([release notes](https://discuss.linuxcontainers.org/t/lxd-3-17-has-been-released/5679)). This change can break existing scripts calling `lxc` but not expecting it to consume stdin. In the most likely case `lxc` will be fed an unexpected input and fail.

This happened in practice with [ctool](https://github.com/CanonicalLtd/uss-tableflip/blob/master/scripts/ctool), a lxc frontend used by the Ubuntu Server team.

This issue is easily worked around by adding a `</dev/null` to the commands, but still finding out that `lxc` now consumes all standard input without being explicitly told so was an unexpected change, especially so in a minor version upgrade. I understand it's late, but I'd suggest adding a `--yaml <file>` flag where `<file>` can be `-` for stdin.

**Comment by stgraber** [comment]
Sorry that this feature addition broke your workload.

I see that doing something like `cat blah | (lxc launch ubuntu:18.04 c1 ; lxc exec c1 -- some-command)` would have worked, but I'd still argue that passing stdin data to commands that you don't want to have consume it is usually a bad idea and might bite you.

Specifically, `lxc init` and `lxc launch` both could already consume `stdin` in some cases, specifically to handle interruption of download in some cases. So it would have been mostly luck that your particular use case didn't run into us consuming stdin already.

Having our commands consume YAML as stdin is also a pattern that's already been used for a number of them, which is why we didn't consider putting this under a flag argument since none of the others currently do that.

As for your comment about releases. LXD `3.17` is a feature release, that means, feature addition do happen, API is extended, ... This kind of change is absolutely out of scope for a bugfix release like 3.0.x though.
What we won't do without a major version change is drop/rename a command or arguments, drop an API endpoint or function from our client library, but this change was considered to be purely  a feature addition, following an existing pattern and so suitable for a normal feature release.

**Comment by paride** [comment]
Thanks for the additional details @stgraber.

**Comment by marc-etienne** [comment]
This also broke my Vagrant provisioning scripts that had `lxc launch [...]` in them. I'm not sure exactly what Vagrant is piping there but here is the error I had for the record (and maybe help someone else searching for the error online):

```
    default: ++ lxc launch [...]
    default: Error: yaml: unmarshal errors:
    default:   line 1: cannot unmarshal !!str `exit` into api.InstancePut
```

Adding `< /dev/null` to the `lxc launch` and `lxc init` lines worked for me.

**Comment by vrubiolo** [comment]
Hi there, I confirm I got the same issue w/ Vagrant using the shell provisioner to start an lxc container. I am looking into whether the `</dev/null` workaround fixes things for me.
