### ISSUE TITLE
lxc init command doesn't work anymore with java ProcessBuilder 

### ISSUE THREAD

**Issue by Spital14** [lxc/lxd#6208]
# Required information

 * Distribution: snap
 * Distribution version: 3.17
 * Version :
   * Kernel version: 4.15.0-60-generic
   * LXC version: 3.17
   * LXD version: 3.17
   * Java version: 1.8.0_212
   * Linux version: Ubuntu 18.04.3 LTS

# Issue description

We are facing a bug when we try to use an lxc init command with ProcessBuilder. 
For example, when we try to use "lxc init ubuntu:18.04", it will run endlessly without return and without create container.

If we use the command "lxc init ubuntu:18.04" in console, that works perfectly fine.

We didn't have this bug in lxd snap 3.16. What should we do to fix this problem ? 

# Steps to reproduce

 1. You have to compile this java code : 
        ProcessBuilder builder = new ProcessBuilder("lxc", "init", "ubuntu:18.04");
        builder.inheritIO();
        Process process = builder.start();
        process.waitFor();

**Comment by stgraber** [comment]
The problem is your standard input (`stdin`). LXD 3.17 now reads from stdin for YAML data during `lxc init` and `lxc launch`.

Your hang is most likely because Java or your application is setting up /dev/stdin to a blocking file, LXD tries to read from it and gets stuck.

You'll want to instead set your stdin to something like /dev/null or the java equivalent.

(Note that this effectively shows a bug in your application as your shouldn't pass a stdin that you don't intend the application you're calling to read at some point, but you got away with it until now as LXD would only read from it and very limited cases prior to 3.17).
