### ISSUE TITLE
Add support for Ceph RBD erasure coded pools

### ISSUE THREAD

**Issue by maran** [lxc/lxd#6293]
Since Ceph Luminous it's possible for RBD volumes to be created in erasure backed pools. LXD currently can't work with these pools since the command line arguments to create a image in an ec pool is a tiny bit different. (requires the `--data-pool` flag)

Is there any interest in supporting erasure coded pools that already exist in a Ceph cluster? I'm going to assume creating erasure coded pools through LXD is a bit outside the scope. 

Willing to submit a PR if this is something you would considering merging.

**Comment by stgraber** [comment]
Should be fine, especially if this can be detected somehow. If not, then we'd need a `ceph.XYZ` config option added to the storage pool config.

Also worth noting that this would only apply to manually built/installed LXD for the next couple of months at least as the LXD snap is still built from Ubuntu 16.04 an so only has CEPH 10.x.

Moving to a 18.04 base is planned and the work already done, but switching over now would break a lot of our users due to a bug in snapd, we need to wait for all distributions we care about to be on snapd 2.40 or higher prior to making the switch.

**Comment by stgraber** [comment]
So anyway, if you're interested in doing the work and you understand what needs to be done, go ahead, it's fine with me :)

**Comment by maran** [comment]
I took a stab at it in #6297. 

I'm fine with building it from source, I was more worried about having to keep my fork and mainline in sync if you wouldn't want this added to the official code.

**Comment by stgraber** [comment]
Thanks @maran for implementing this!

**Comment by maran** [comment]
Hi @stgraber sorry for the necro on this but it seemed like the best place to discuss it.

I just upgraded my cluster from a local build LXD to the latest snap 9.20 release but it seems CEPH 10.x is still bundled with that. Hence the `--data-pool` feature is not working. 

Was this meant to be solved by now (upgrading to a newer Ceph) or is there some other way to use a non-bundled Ceph version with the snap?

**Comment by stgraber** [comment]
The `edge` channel is now built on 18.04 and so has a newer version of Ceph.
We're waiting to synchronize with some other snaps before we switch candidate/stable over too.

**Comment by stgraber** [comment]
We're hoping to have this sorted over the next month.

**Comment by maran** [comment]
Great, for now I will continue to try and build a version from the release source. Thanks.
