### ISSUE TITLE
lxc profile show lists vms under 1.0/containers

### ISSUE THREAD

**Issue by brauner** [lxc/lxd#6491]
Not sure if this is intended behavior but likely not. When I do:
```
> lxc profile show default
config: {}
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by:
- /1.0/containers/e1
- /1.0/containers/b1
- /1.0/containers/b1-32
- /1.0/containers/b2-shiftfs
- /1.0/containers/b3
- /1.0/containers/e3-vm
- /1.0/containers/kernel-compiler
```
and I have vms (e.g. `e3-vm`) attached to that profile they get listed under `1.0/containers` when they should likely be listed under the corresponding vm API endpoint.

**Comment by tomponline** [comment]
@brauner @stgraber it looks like this is hardcoded into the initial fresh DB schema that is created:

https://github.com/lxc/lxd/blob/c41ec9e3bbaac1633658134ccd0ea82ed75438db/lxd/db/cluster/schema.go#L387-L392

Should we update the query (does that need a DB patch) or should we modify the output to strip that and replace for VM types in the code?

CC @freeekanayaka

**Comment by stgraber** [comment]
oh, that's an interesting way to do this :)

So I think we'll need to change all of the views which use `/1.0/containers` to instead give us the instance name, project name and instance type.

We can then have the LXD code generate the URL based on the type and URL it's been accessed from (so that /1.0/containers/blah gives you a /1.0/containers URL but /1.0/instances/blah gives you a /1.0/instances URL).

**Comment by stgraber** [comment]
And yeah, we'll need a DB patch to delete and re-create those views and code change to deal with the different columns.

**Comment by freeekanayaka** [comment]
So yeah this was a bit of a hack in the db code generator, to avoid adding extra complexity. It will require a bit of work, essentially because now we'll have to change:

```go
type Profile struct {
        // ...
	UsedBy      []string
}
```

to something like:

```go
type Profile struct {
        // ...
	UsedBy      []struct{
            Project string
            Name string
            Type int
        }
}
```

but more importantly we'll have to do the same with the ```api.Project``` struct, which right now is used directly in database code. We'll have to introduce a specific ```db.Project``` struct whose ```UsedBy``` field will be a slice of structs instead of a slice of strings, which in turn we need to render into strings when returning ```api.Project``` objects in the API.

Hope the plan is clear.

PS: alternatively we could keep on with the hack and still have the view return aggregated strings, except that we would use some special separator so the consuming code can split it into the original components (project, name, type) and do whatever rendering it wants. E.g.:

```
CREATE VIEW profiles_used_by_ref (project,
    name,
    value) AS
  SELECT projects.name,
    profiles.name,
    printf('%s|%s|%d',
    instances.name,
    instances_projects.name,
     instances.type)
```

where ```|``` is used as separator.

@stgraber I don't think you'll want this hack, but if you prefer it for sake of getting it done cheaply and asap, I'll go for it.

**Comment by stgraber** [comment]
@freeekanayaka we can go with the hack but use slash as separator as that's a character we prevent our users from using for both instance and project names

**Comment by freeekanayaka** [comment]
> So I think we'll need to change all of the views which use `/1.0/containers` to instead give us the instance name, project name and instance type.
> 
> We can then have the LXD code generate the URL based on the type and URL it's been accessed from (so that /1.0/containers/blah gives you a /1.0/containers URL but /1.0/instances/blah gives you a /1.0/instances URL).

Actually thinking about this, I'm not totally sure what do you mean. Currently return /1.0/containers in the used_by API field that we fill for profiles and projects: so you would see that what you hit something like GET /1.0/profiles/blah, or GET /1.0/projects. There's no way there to decide whether to render the URL as /1.0/containers or as /1.0/instances.

Am I missing something?

**Comment by stgraber** [comment]
When querying something under /1.0/containers or /1.0/virtual-machines, we'll make sure to return URLs that match. For other endpoints we should return the generic /1.0/instances.

So if UsedBy is only present outside of instances, fixing this may in fact be much simpler.

**Comment by freeekanayaka** [comment]
Yeah it's only present outside instances indeed.

**Comment by freeekanayaka** [comment]
Should I just ```s/containers/instances/``` in:

```
 SELECT projects.name, 
     profiles.name, 
     printf('/1.0/containers/%s?project=%s',
```

then?

**Comment by stgraber** [comment]
Yeah, that should do it. Sorry for the waste of time :)

**Comment by freeekanayaka** [comment]
Hehe, no worries. I changed the PR accordingly.
