### ISSUE TITLE
FTBFS, possibly related to changes in libcap

### ISSUE THREAD

**Issue by CameronNemo** [lxc/lxd#6727]
* Distribution: Void
 * Distribution version: libcap 2.30.0
 * LXD version: 3.19

# Issue description

In November, libcap implemented some changes to support shared capability state across threads. The release notes specifically mention Go. Oddly enough, LXD 3.18 did not seem to take issue with these changes. But on 3.19 I am seeing a build error.

libcap release notes: https://sites.google.com/site/fullycapable/release-notes-for-libcap/releasenotesfor228pending

LXD build error:

```
cd /builddir/lxd-3.19/_build-lxd-xbps/src/github.com/lxc/lxd/lxd
pkg-config --cflags -- lxc libcap
pkg-config --libs -- lxc libcap
go build github.com/lxc/lxd/lxd: invalid flag in pkg-config --libs: -Wl,-wrap,pthread_create
```

**Comment by Foxboron** [comment]
Experiencing the same issue on Arch Linux.

**Comment by Foxboron** [comment]
Turns out this is a security measure in the cgo compiler. It operates with a whitelist where only some flags are allowed in `LDFLAGS`, `CFLAGS` [and so on](https://golang.org/cmd/cgo/). 

It seems like `-Wl` is not allowed by default, so the flag has to be whitelisted before compilation with `CGO_LDFLAGS_ALLOW='-Wl,-wrap,pthread_create'`. I don't think this is something that lxd should be whitelisting and however be mentioned as the other flags currently are. 

`libcap` recently included this flag, which is probably why this issue is only limited to distros shipping the newer versions of the library.

**Comment by grawlinson** [comment]
Hey @Foxboron, I ran into this issue while building 3.19 last night (I maintain my own pacman repository) so I’m interested in seeing this solved. Are you using the [AUR](https://aur.archlinux.org/packages/lxd/) package, or a private fork?

**Comment by Foxboron** [comment]
@grawlinson I'm preparing lxd for inclusion into Arch Linux. Current packaging files can be found here; https://github.com/Foxboron/lxd-repo

**Comment by stgraber** [comment]
Can one of you send a PR that tweaks our Makefile to export this?

Hopefully there's a way to just set the variable once in the Makefile and call it done :)
I'd do it but we haven't yet been hit by this on Ubuntu, so would be best if done with someone who can confirm the change works.

**Comment by Foxboron** [comment]
@stgraber Pushed and added some documentation :)

**Comment by Foxboron** [comment]
I discovered that `libcap` has dropped the dependencies which would introduce the need for the `ALLOW` flag. I *think* they can be safely dropped these days, but might be worth to have them in case people encounter this.


https://git.kernel.org/pub/scm/libs/libcap/libcap.git/commit/?id=f9d1c5ee19c96547fad2c807270e82abc9426ff8
