### ISSUE TITLE
Link/redirect to contributing guidelines doesn't work

### ISSUE THREAD

**Issue by comradekingu** [lxc/lxd#6764]
![bilde](https://user-images.githubusercontent.com/13802408/73045271-7f84fa00-3e6d-11ea-9b6b-e252120a5b6b.png)

links to 
https://github.com/lxc/lxd/blob/master/contributing.md
when it should be
https://github.com/lxc/lxd/blob/master/doc/contributing.md

I skimmed through https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors and hypothesized the redirect only works with `/docs`.

**Comment by stgraber** [comment]
I'm not seeing any logic specifically for doc vs docs. Gihub just isn't following symlinks much.

Unfortunately because CONTRIBUTING is a page on our website, it must be in doc/ so short of duplicating its entire content we don't really have much we can do here.

Anyone cloning the repo will get the right behavior, as will they if they view the documentation at https://linuxcontainers.org/lxd/docs/master

For Github, the issue is described here https://github.com/isaacs/github/issues/348 and has apparently been present ever since the feature rolled out. It'd be nice if Github could either improve the rendering of symlinks or just plain support following them for such cases.
