### ISSUE TITLE
Copy containers with different BTRFS storage and docker

### ISSUE THREAD

**Issue by rudiservo** [lxc/lxd#6819]
Required information

    Distribution: Ubuntu
    Distribution version: 18.04
    The output of "lxc info" or if that fails:
        Kernel version: 5.3.0.26
        LXC version: 3.19
        LXD version: 3.19
        Storage backend in use: BTRFS

Issue description

In relation to a previous issue  #6607
The action is to copy a lxd container with deployed docker containers, to a new storage backend.
It now outputs a new type of error, is there an actual proceding to do this the right way?

```Creating webdevkit_mysql_1 ...
Creating webdevkit_mysql_1 ... error

ERROR: for webdevkit_mysql_1 Cannot create container for service mysql: stat /var/lib/docker/btrfs/subvolumes/5a06304b5921b85a03b4d6d69df3f23ac71e10ee217cd85cb3688015415dc19b: no such file or directory

ERROR: for mysql Cannot create container for service mysql: stat /var/lib/docker/btrfs/subvolumes/5a06304b5921b85a03b4d6d69df3f23ac71e10ee217cd85cb3688015415dc19b: no such file or directory
ERROR: Encountered errors while bringing up the project.

**Comment by stgraber** [comment]
@rudiservo any chance you can try this again on current LXD (3.21 or 3.22)?

I'd just like to get an updated error when on the newer storage implementation we have in place.

**Comment by stgraber** [comment]
No, should be pretty straightforward to reproduce and it makes sense too, the issue is with how to fix it...

We need to find a way to send multiple subvolumes in a single `btrfs send` without breaking our migration API that has some pretty strict constraints on how multiple chunks are sent.

**Comment by rudiservo** [comment]
@stgraber sorry, I haven't tried it, it has been a bit of madness at work... we haven't really stopped...
maybe I am trying it the wrong way, it would be nice if it works because it means we can replicate a production system and fiddle with it has much has we want.

but maybe I am looking at it the wrong way, maybe I need to make it more stateless containers, a bit orquestration and rsync the raw data has a copy inteaded.

**Comment by tomponline** [comment]
I've re-created this issue by doing:

Node 1:
```
lxc storage create btrfs btrfs
lxc init ubuntu:18.04 c1 -s btrfs
lxc start c1
lxc exec c1 -- btrfs subvolume create /root/test
lxc exec c1 -- touch /root/test/helloworld.txt
lxc stop c1
lxc copy c1 node2:c1
```

Node 2:
```
lxc start c1
lxc exec c1 -- ls -la /root/test
Not found
```

**Comment by tomponline** [comment]
Also noticed that when doing an optimized export that any containers on BTRFS with subvolumes fail with the error `btrfs send ... is not read only`. Despite using the readonly and recursive arguments on `snapshotSubvolume`.

**Comment by tomponline** [comment]
I found the issue with the non-read only snapshots, it was a particular 'feature' of the `snapshotSubvolume` function which needed to switch to non-readonly mode for the top level subvolume for taking recursive snapshots. However I've fixed that now by making the top level sub volume RO afterwards.

Have also successfully passed multiple volumes to the btrfs send command as so:

```
btrfs [send -e /var/lib/lxd/storage-pools/btrfs/containers/migration.753475986/.migration-send /var/lib/lxd/storage-pools/btrfs/containers/migration.753475986/.migration-send/rootfs/root/test] 
```

Using both with and without the `-e` flag.

Both appear to work and the volume is received OK on the other end. However the subvolume that was sent doesn't materialise. Not sure where its going to yet.

**Comment by tomponline** [comment]
@stgraber I dont think that we will be able to use a multi-volume `btrfs send` by itself, as on the `btrfs receive` side it cant recreate the subvolumes relative to their original location in the main tree. So we will need some way send the meta data about sub volumes across the to target (be that a migration target or a backup restore target from a tarball) to instruct it where to create the final r/w snapshot of the restored subvolumes in the target tree.

**Comment by rudiservo** [comment]
@tomponline do you think that BTRFS team might do something that if we pass a new flag it will handle the subvolumes also like we need it to be, it wont fix the issue for now but in the future who knows, it might be a feature that dev's need in btrfs.

**Comment by stgraber** [comment]
@tomponline oh, where does it recreate it?

**Comment by tomponline** [comment]
@stgraber it creates it in the root of the btrfs receive path, e.g. this is the result of sending two subvolumes one called ".backup" and the other called "test" (which was a subvolume in ".backup/rootfs/root/test").

```
btrfs receive -e /var/lib/lxd/storage-pools/btrfs/containers/backup.777006279 
total 0
d--x------ 1 root    root 22 May  4 14:06 .
drwx--x--x 1 root    root 64 May  4 14:06 ..
d--x------ 1 1000000 root 78 May  4 14:06 .backup
drwxr-xr-x 1 root    root 28 May  4 13:56 test
```

**Comment by tomponline** [comment]
@stgraber my working branch with patches to support sending multiple subvolumes is here: https://github.com/tomponline/lxd/tree/tp-storage-btrfs-subvols

**Comment by tomponline** [comment]
@stgraber so for sending the sub volume information across to the target during a migration (both cross-local-pool and true migration modes) we need a way for the BTRFS storage driver to communicate with its counterpart.

We discussed yesterday adding a 'feature' for subvolume support during the offer header negotiation. And whilst this part can be done generically during the normal negotiation, scanning for subvolumes that are actually present needs to happen inside the BTRFS driver.

The obvious place for this to happen is inside the d.MigrateVolume() function. However this is called after the offer headers have been exchanged, and has no access to the migration control channel (it doesn't exist for local cross-pool copies anyway).

Instead I was thinking, what if we used the negotiated 'subvolume' feature to indicate to both sides that we would send detected subvolume data across the data channel (perhaps as JSON) as the first 'frame' of data, which the target would then decode and then wait for the actual output of btrfs send to be received. We could always send this driver-level meta data frame first so that even if there was no subvolumes detected the two sides would know what to expect.

This got me thinking that this sort of driver-level volume-level meta data might be useful for other drivers and other features, and that rather than call the BTRFS feature 'subvolumes' we could call it something like 'metadata_subvolumes' and then in the future if any of the negotiated features had the prefix 'metadata_' the target would know to read the first frame and decode before expecting the actual volume data.

This could also be useful to instruct the target the order to expect the volumes, rather than it being implicit at the moment.

**Comment by stgraber** [comment]
@tomponline So I think it makes sense to advertise a btrfs-specific `migration_header` feature as well as a `header_subvolume` in protobuf and if both sides support them, then use that to send the JSON data. We still need to rely on the migration layer to do feature detection so we'll extend the list of `header_*` as needed.

That effectively allows for other migration source (e.g. lxd-p2c) to advertise that they understand the JSON frame mechanism but then may not support all the bits we put in it.

Makes sense?

**Comment by tomponline** [comment]
@stgraber yep sounds good so to summarise I have understood:

For BTRFS optimized migrations we will negotiate on the following new features: 

- `migration_header` - which means that we expect to send/recv a driver-level migration header in the data channel before sending the actual volume data.
- `header_subvolume` - which means we expect that the `migration_header` will contain a list of subvolumes being sent (each subvolume will contain `name`, `path` and `readonly` properties).

The `migration_header` feature may be used with other storage drivers in the future, combined with other header specific features to indicate what we would expect the migration header to contain.

**Comment by stgraber** [comment]
yep, that sounds right

**Comment by stgraber** [comment]
Ok, so we should have the migration story sorted out now.
There's more btrfs work we're doing, but this particular one should be done.
