### ISSUE TITLE
Unnecessary RSYNC to /var/lib/lxd/backups

### ISSUE THREAD

**Issue by s3rj1k** [lxc/lxd#6880]
When doing container export for stopped container, `Dir` storage, LXD unnecessary rsyncs container `rootfs` prior to archiving to `/var/lib/lxd/backups`.

Desired behavior would be to create archive directly from `rootfs` for container is `STOPPED` state.

**Comment by stgraber** [comment]
So this is expected behavior and actually unrelated to running/not-running.

When exporting a container, the following happens:
 - The storage driver is asked to generate the backup at a provided path (under /var/lib/lxd/backups)
 - The backup layer then takes care of adding the needed meta-data to that path and call the compressor
 - The resulting backup is recorded in the database and made available for download
 - The CLI fetches the backup and then requests for it to be deleted

Similar to publishing, we do need a writable version of the filesystem that can be moved around while generating the tarball and in some cases can be shifted/unshifted. In the past we had "optimization' logic which would allow for this to be done in-place, but that was extremely dangerous as someone starting the container or LXD crashing while an export or publish was in progress would cause irreparable data corruption.

It's also worth noting that because a container is stopped doesn't mean you can't alter it, the file API for example works just fine against stopped containers.

For that reason, we have now moved to not crossing boundaries between storage and backup/publish layer so the right locks can be used and we can ensure that no data corruption will occur. This does unfortunately come at a space cost in some cases, which hits the `dir` storage driver particularly badly as usual.

I can't think of a particular safe way out of this. The storage drivers that support optimized exports are a lot less affected by this as even though there is data duplication during the export process, it tends to be properly compressed and much more compact than a dir export.
