### ISSUE TITLE
Unable to import containers larger than 10GB into ceph-backed LXD cluster

### ISSUE THREAD

**Issue by gpl** [lxc/lxd#6882]
# Required information

 * Distribution: Ubuntu 19.10
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.3.0
   * LXC version: latest
   * LXD version: 3.21 (via snap candidate, but also occurs w/ 3.20)
   * Storage backend in use: ceph

# Issue description

When importing a 14gb container into a ceph-backed lxd cluster, a tar output appears stating that there is no space left on device. 

# Steps to reproduce

 1. Create a 15gb container, then create a snapshot.
 2. lxc publish container/snapshot
 3. lxc image export container .
 4. import the image with `lxc image import container.tar.gz`
 5. `lxc init container some-container-name`
 6.  Tar will return `no space left on device` after a while.

(n.b.  a similar condition happened when trying to `lxc copy` this container from my computer to the lxd cluster.)

# Information to attach
I (unsuccessfully) attempted to create the container by specifying a container that has 128gb of space as its root file system, as opposed to the default of 10gb.  This failure mode also occurs with lxc copy from a source host not in cluster, to a destination that's in a cluster.  

Upon trying to re-import the image, a new error appears: 

The root file system has at least 800GB of space left, with ample room left in memory and in ceph itself.
```
Error: Create instance from image: Failed to run: rbd --id lxd --cluster ceph --image-feature layering clone <pool name>/<exported-image-id>@readonly <pool name>/container_some-container-name: 2020-02-15 02:48:02.689772 7f39d7fff700 -1 librbd::image::OpenRequest: failed to set image snapshot: (2) No such file or directory
2020-02-15 02:48:02.689923 7f3a029f2100 -1 librbd: error opening parent image: (2) No such file or directory
rbd: clone error: (2) No such file or directory
```
I have to delete the image using the ceph tools in order to be able to attempt reimporting this image again.

For containers smaller than 10GB, there doesn't appear to be any issue w/ importing.

(n.b. All lxd instances at hand here are running the same lxd version.  They're also on the same kernel and OS version. )

Here is the profile....
``` 
:~# lxc profile show <>
config: {}
description: 128g
devices:
  br40:
    name: br40
    nictype: bridged
    parent: br40
    type: nic
  root:
    path: /
    pool: default
    size: 128gb
    type: disk
name: <>
used_by:
```

Here is some output on the ceph side.....
```
:~# rbd du -p <pool_name>
NAME                                                                                  PROVISIONED USED
<some containers, none related // redacted>
image_<long_hash_here>                    9.3 GiB  9.3 GiB
<redacted>
<TOTAL>                                                                                   1.0 TiB   74 GiB
```

**Comment by gpl** [comment]
I went trawling through the documentation another time, and it looks like setting volume.size on the storage pool to the appropriate size, `lxc storage set default volume.size=25GB`, does the job.

I was unsuccessful in setting the volume.size parameter on the `lxc launch` command.  Is there any other way to get the end result w/o having to set a default volume.size?

**Comment by stgraber** [comment]
No, there isn't and bumping volume.size prior to the first use of the image is indeed the way to go.

We can't do it at launch the because the image is only unpacked once when the first container is created from it.

We also can't tell how much space it will take as things like sparse files and the various compression and deduplication options can make the final size order of magnitudes larger or smaller depending.

**Comment by gpl** [comment]
Sorry for the late reply (and reopen!)

My current method is set, create the container, then unset the volume.size, but this sometimes allows containers w/ a larger root image than I'd prefer to be created. 

Is there any way to set the volume.size for a single operation? e.g.:

`lxc init some-container-image some-container-name -c volume.size=25GB`?

**Comment by stgraber** [comment]
No, there isn't. Because of what I mentioned above.

When using a storage backend that stores images as block devices, like ceph or LVM, the first time you use an image, LXD will create a volume of the size configured in `volume.size` and then EVERY container you create from that image are clones of that initial volume.

What you can do is set the `size` property on the root disk of your containers.
You would usually do that using profiles such as setting a default size on the default profile.

What LXD will do with that is resize your container's clone of the image to the configured size on first startup of the container. Obviously if configured to a size that's too low, the resize will fail and the container won't start, but it does work well for growing to a larger size.

So the recommendation would be to set `volume.size` to whatever you need to import all your images properly. Then set the `size` property on the `root` device in the `default` profile to the size you want your containers to be. If you want variety in options there, then create more profiles with different values.

**Comment by gpl** [comment]
I see, that makes sense.  Thanks for the help.
