### ISSUE TITLE
Further clarification on image expiry and auto-updating

### ISSUE THREAD

**Issue by Kramerican** [lxc/lxd#6890]
LXD 3.18 from Snap
Ubuntu Bionic

Due to an unrelated networking issue, which we are still trying to track down, download speeds of remote images have suddenly become atrocious (down to 200K/sec intermittently) when connecting to remotes. 

Seeking a solution to this by treating it symptomatically revealed secondary "unexpected" behavior from LXD, which may be due to the documentation being unclear and us simply not configuring LXD correctly from the get-go.

At the moment we configure LXD with the following flags:

```
  images.auto_update_interval: "0"
  images.remote_cache_expiry: "1"
```

This is in order to faciliate the behavior as described in #3698 

My understanding is that `auto_update_interval=0` disables auto updating entirely and `remote_cache_expiry` marks images as expired after 1 day (24 hours) if it hasn't been used so that we will not have old images hanging around.

This means LXD does no auto-updating - but when a new container is requested with lxd init using one of our remote images, then LXD will basically almost always re-download the image (as images are only kept around for up to 24 hours after last use)

Now, this is all fine and well when there is good network connectivity - but now we would rather want LXD to not expire images at all if the alias is found locally. Instead we would want to push images or force an update manually when required (or ideally have LXD understand when there is a new _**version.**_ of an image available on the remote, and only update then)

In order to achieve the manual update approach, would we then simply set `auto_update_cached` to false, the other settings then become irrelevant (but shouldn't setting `auto_update_interval` to zero have the same effect? )

Then, when we have an image we want to update on our clients, we would run `lxc image copy myremote:something local: --copy-aliases`

Correct?

However, with the two setting set as seen above and `images.auto_update_cached` left to its default boolean true, we see LXD attempting to update remote images _**despite them not having been changed or touched on the remote**_ this is presumably due to the behavior of `remote_cache_expiry` which is documented as _Number of days after which an unused cached remote image will be flushed_

This seems to me to be the missing ingredient and where we are not quite clear on the behavior. Meaning rather the solution is probably to set `remote_cache_expiry` to some really high value in conjunction with turning off auto update. But this all adds up to a rather opaque picture where we are not sure what setting to touch in order to achieve what we _ideally want._ 

**We imagine a lot of folks want to do what we want:**

1. Publish images on an image server
2. Have clients download these and cache them _**untill a newer version is available**_

And in the interim, keep the cached version and not expire it just because it hasn't been used recently.

**Then** only when a new version is published, with the same alias but different fingerprint (or newer date), on the remote, LXD updates the image (and nuke the old version, because why keep that around?).

This would solve our current problem, and is really the behavior we have been after all along - but it is terribly unclear to us whether this exact behavior is even possible, and if it is, what the correct configuration is :)

Maybe something like:

`auto_update_cached=true`  - yes please update images 
`auto_update_interval=1`  check for updates every 1 hour
`remote_cache_expiry=365` But keep images around for a year _**if no update to the image has been made in the interim**_

Would this allow us to publish images, knowing they will get picked up by clients at most 1 hour after the update has happened, otherwise clients happily used their cached copies? 

But would this not reveal our original "problem" where old versions of images are left hanging around on the client for no good reason eating up disk space..? Which was the issue which led us to the current settings we came up with way back in 2017 ...

Anyway, thank you in advance for any clarification you can provide here :)

**Comment by stgraber** [comment]
auto_update_internal=1
remote_cache_expiry=365

Should do what you want in that when auto-updating an image, its previous version is deleted at the end of the update process.

https://github.com/lxc/lxd/blob/0e3f3dacd100307257c079d33ea6527888b2b3ed/lxd/images.go#L1019 is what's run during the background image updates.

https://github.com/lxc/lxd/blob/0e3f3dacd100307257c079d33ea6527888b2b3ed/lxd/images.go#L1084 is what's run on an individual image basis and as you can see, ends with the deletion of the current image.


I suspect the issue you're having is that the client is telling LXD to use the remote image, LXD looks up what that points to and then proceeds to download the updated version of the image immediately rather than waiting for the background update.

The way you can avoid this is with:

  - lxc image copy ubuntu:18.04 local: --alias my-18.04 --auto-update
  - lxc launch my-18.04 blah

So long as you use the `my-18.04` local image alias, you'll never get hung on an image download.
Because of the `--auto-update`, LXD will record the source of the image and at the configured interval, will see if it now points somewhere else, if it does, it will download the image in the background, then swap the index to the new image and delete the old one.

**Comment by Kramerican** [comment]
@stgraber 

Thank you for your clarifications - I am guessing `auto_update_internal` is not just some magic undocumented option, but just a typo and you of course mean `auto_update_interval`

Second, the issue is that - as I mention above - _**images have not been updated on the remote**_. Whatsoever. This is what has been tripping us up in that LXD, after some period of time starts fetching the image from the remote again presumably just due to the behavior of `remote_cache_expiry` - and given how long it's been since we settled on setting that to =1 I am guessing the behavior may have been changed / augmented since late 2017 :)

Anyway, we will try and set `remote_cache_expiry=365` and observe / test and report back if we find anything odd. I hope we have this cleared up now. 

PS: Thanks for linking to the source - made things a bit clearer.

**Comment by stgraber** [comment]
ah yeah, just a typo :)

**Comment by Kramerican** [comment]
I'm sorry to have to bring this up again, but we have now run into the same issue as what led us to our original configuration where we set expiry to 1 day - but which then led to LXD constantly re-downloading images. What we are seeing:

When LXD fetches a new updated image, and `remote_cache_expiry=365` is set to some high value, the old images are kept around. They loose their alias (as that is now assigned to the updated image) but are just hanging out on the server.

How can we wrangle LXD into behaving like we want? Meaning

- Fetch an update IF and only if there is a new (updated) version on the remote matching the alias provided
- Once the updated image is fetched, it replaces the local copy
- And where it doesn't try to re-download remote images if they haven't been updated on the remote

This seems simple, but the behavior we are seeing is not quite that, it seems :)

**Comment by stgraber** [comment]
Hmm, your behavior doesn't match the code. When an image is refreshed, the previous image is deleted.

One thing that would explain your behavior is if you're manually running `lxc image copy` to update the image rather than running `lxc image refresh` on the existing image. The latter should cause LXD to pull the new image and then delete the previous one.

As you're never actually using cached images in this setup, the configuration options related to caching shouldn't apply here.

**Comment by stgraber** [comment]
So to recap, I would expect:
 - `lxc image copy image-server:alias local: --alias whatever --auto-update`

Initially to populate the local image and set the alias.
Then if you want to manually update it, you need to run `lxc image refresh whatever`.

I believe the auto-refresh should also work on those but I don't remember whether you have that enabled or not.

**Comment by Kramerican** [comment]
Alright! That makes a whole heap of sense

Thank you for the clarification @stgraber - this is exactly what I was looking for :)
