### ISSUE TITLE
Machine resources: CPU reports numa_node per-core rather than per-thread

### ISSUE THREAD

**Issue by albertodonato** [lxc/lxd#7116]
This was first reported here: https://bugs.launchpad.net/maas/+bug/1869990

Currently the numa node information for cpu is filled once per-core (https://github.com/lxc/lxd/blob/master/lxd/resources/cpu.go#L248-L253), but  in the above case it's actually different for threads in the same core.

**Comment by stgraber** [comment]
AMD keeps surprising us with that stuff... it really makes little sense for a thread to be on a different numa node than the other thread on the same core...

**Comment by mmallon** [comment]
Yeah, it definitely reports a little weird. I think the problem is that they're effectively two sockets in a socket and they reuse core_id (see https://developer.amd.com/wordpress/media/2012/10/51803A_OpteronLinuxTuningGuide_SCREEN.pdf - page 5). It doesn't help that I think there was a bit of marketing from AMD around threads vs cores at the time so they're not reporting threads because each core has its own integer pipeline but  share a floating point unit and an instruction fetch/decode unit.

**Comment by wgrant** [comment]
The bug here is that cpu.go addresses cores as (physical_package_id, core_id), but on AMD MCM systems it's (physical_package_id, die_id, core_id). See cputopology.rst for details.

There is another oddity here, though: because AMD's CMT implementation shares some resources between cores, for scheduling purposes they're not independent so they're closer to Linux's thread concept. So you end up with each Bulldozer-derived logical processor having a unique (physical_package_id, die_id, core_id), but its thread_sibling_list includes one other logical processor with either the next or previous core_id. This is unlike SMT (on Intel cores or AMD Zen-derived cores) where anything in thread_sibling_list is always on the same (physical_package_id, die_id, core_id).

I think as long as LXD is fixed to consider die_id this should all work fine.

**Comment by stgraber** [comment]
Thanks, I've sent https://github.com/lxc/lxd/pull/7120 which now handles CPU dies and should fix the reporting on such systems.

**Comment by mmallon** [comment]
I can see die_id on newer AMD cpus (Zen 2 desktop) but not on the Opteron 6376 that triggered this or my first gen Epyc hosts. Their topology entries look like this:

user@host:~$ ls -salh /sys/devices/system/cpu/cpu0/topology/
total 0
0 drwxr-xr-x 2 root root    0 Apr  2 00:21 .
0 drwxr-xr-x 8 root root    0 Mar 30 05:34 ..
0 -r--r--r-- 1 root root 4.0K Mar 30 05:36 core_id
0 -r--r--r-- 1 root root 4.0K Mar 30 05:35 core_siblings
0 -r--r--r-- 1 root root 4.0K Mar 31 23:50 core_siblings_list
0 -r--r--r-- 1 root root 4.0K Mar 30 05:35 physical_package_id
0 -r--r--r-- 1 root root 4.0K Mar 31 08:46 thread_siblings
0 -r--r--r-- 1 root root 4.0K Mar 31 23:50 thread_siblings_list
user@host:~$ uname -a
Linux host 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by stgraber** [comment]
Right, you need a newer kernel, 4.15 doesn't have the file.

**Comment by stgraber** [comment]
If you can get a newer kernel on the Opteron, please run https://dl.stgraber.org/lxd-resources

That should then show you the correct topology considering CPU dies.

**Comment by stgraber** [comment]
@wgrant went digging in the kernel code and apparently there's no logic to set the die_id to the right value on AMD chips, so that new binary is unlikely to make a difference at this point...

**Comment by wgrant** [comment]
It turns out that die_id was introduced by Intel in 2019 for Cascade Lake-AP, and is only set by the Intel topology code (based on CPUID 0x1f), so is probably only non-zero on Cascade Lake-AP (and Cooper Lake-AP in future, I guess).

amd_get_topology (based on topoext, CPUID 0x8000001e) doesn't set die_id, even though it's exposed in ECX on Bulldozer and Zen (tested Interlagos and Naples). But it isn't necessary for unique core IDs on Naples, since Naples core_ids don't repeat between dies within a socket, unlike Interlagos/Abu Dhabi.

I don't see any way to get meaningful unique core IDs on Bulldozer-derived MCMs on today's kernels. Extending amd_get_topology to set cpu_die_id based on 0x8000001f.ECX would work, and probably makes sense, but requiring that is ugly.

I think you're going to have to synthesise core IDs if you want them, and it's tempting to do that across the whole system rather than per-socket, in a way that is opaque and not guaranteed to be persistent. Information about die, socket, CCX etc. is going to be platform-dependent metadata, when it's mostly NUMA distance that's interesting.
