### ISSUE TITLE
DHCP blocked on Fedora Rawhide

### ISSUE THREAD

**Issue by Saviq** [lxc/lxd#7150]
# Required information

 * Distribution: Fedora
 * Distribution version: Rawhide
 * The output of "lxc info": [lxd.info.txt](https://github.com/lxc/lxd/files/4444850/lxd.info.txt)

# Issue description

Container get no addresses from DHCP on Fedora Rawhide Workstation.

# Steps to reproduce

 1. Install Fedora from [the latest iso](https://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Workstation/x86_64/iso/)
 2. `snap install lxd`
 3. `sudo lxd init --auto`
 4. `sudo lxc launch ubuntu:`

# Information to attach

 - [x] [dmesg.txt](https://github.com/lxc/lxd/files/4444887/dmesg.txt)

**Comment by Saviq** [comment]
As a workaround: `sudo systemctl stop firewalld` makes it work again.

**Comment by stgraber** [comment]
@tomponline want to take a stab at that one?

Probably can be done with a LXD VM of Fedora 31 and enabling firewalld in there.

It'd be interesting to see exactly what's blocking us and whether we can tweak our default firewall rules in LXD managed networks to allow traffic through in such cases.

If not possible, we should at least add a documentation paragraph on needed firewalld config to make things working again.

**Comment by tomponline** [comment]
@stgraber yep will take a look

**Comment by tomponline** [comment]
Looking at this now.

**Comment by tomponline** [comment]
@stgraber @Saviq so the issue with firewalld blocking inbound DHCP requests to the LXD bridge is caused by this section:

```
table inet firewalld {
...
	chain filter_INPUT {
                type filter hook input priority filter + 10; policy accept;
                ct state { established, related } accept
                ct status dnat accept
                iifname "lo" accept
                jump filter_INPUT_ZONES
                ct state { invalid } drop
                reject with icmpx type admin-prohibited # This is a default reject rule.
        }
...
}
```

Despite the fact that LXD adds its DHCP allow rules as priority 0 (filter), which is a 'higher' priority than 10 (filter + 10) that firewalld's chain uses, nftables requires that all chains accept a packet before it is actually accepted. Whereas a single reject/drop will cause the packet to be rejecte/dropped. So it doesn't matter that LXD's rules are evaluated first and are accepted, the packet still traverses the `firewalld.filter_INPUT` chain and is rejected.

I will see how to configure firewalld to remove that default drop rule (or some other way to get firewalld to allow LXD's rules to take effect) and update our docs.

**Comment by tomponline** [comment]
Running the following command appears to work persistently (including after reboots).

```
firewall-cmd --zone=trusted --change-interface=lxdbr0 --permanent
```
