### ISSUE TITLE
Upgrading to 20.04 Attempts to Install LXD via Snap Store

### ISSUE THREAD

**Issue by patrick330602** [lxc/lxd#7157]
Originally reported at:
  https://bugs.launchpad.net/bugs/1862550
# Issue description

Upgrading to 20.04 attempts to install LXD via snap which fails on WSL.
The WSL instance is unable to reach the snap store.
snap is not currently supported on WSL.

# Steps to reproduce

1. Enable and Install WSL on a Windows 10 Insider Preview machine;
2. Import Ubuntu 18.04 Image using the following method: <https://wiki.ubuntu.com/WSL#Installing_Ubuntu_on_WSL_via_rootfs>
3. `sudo apt update && sudo apt upgrade -y`
4. `sudo do-release-upgrade -d`

![Attempting to reach snap store](https://bugs.launchpad.net/ubuntuwsl/+bug/1862550/+attachment/5326778/+files/Annotation%202020-02-09%20174833.png)

![Package configuration page to retry, abort, or skip ](https://bugs.launchpad.net/ubuntuwsl/+bug/1862550/+attachment/5326779/+files/Annotation%202020-02-09%20174306.png)

**Comment by stgraber** [comment]
Closing as not a LXD issue, this is a distro/packaging issue unrelated to LXD itself.

All users on Ubuntu 18.04 will upgrade to the snap upon moving to 20.04, this logic has been in place since 18.10.

The skip option can be used by users that have never used LXD before which includes upgrading WSL1 users, selecting that option should get your upgrade going.

**Comment by sirredbeard** [comment]
It would be nice if there was a way to suppress this message, to make the upgrade from 18.04 to 20.04 on WSL smoother. Any suggestions?

**Comment by pbrkr** [comment]
This sadly makes lxd unusable for us as snaps are banned in our organisation. lxd is used as the base of all our containers and so we need control over how it is updated, this doesn't seem to be possible with snap (e.g. https://askubuntu.com/questions/1131182/how-can-i-disable-automatic-update-for-a-single-snap-in-ubuntu).

Please re-think this.

**Comment by ageric** [comment]
Seconded. Snap packages (or rather, uncontrollable updates) are forbidden in every government agency in sweden, as well as all municipalities, healthcare and other vital function banks and everyone who wants to connect with either of the above. It's largely the same across all of europe. I can't imagine this was a developer decision, but I can't for the life of me understand why Canonical would want to commit suicide on an antire continent either.

I guess people just fugly-build their own packages and run with that. It's what we're currently doing, while looking for alternatives and spending some time aiding the debian packaging effort. The snap mentality of forcing unchecked updates down peoples throats is so insanely stupid. Whoever thought up that particular insanity must never have actually worked in IT.

**Comment by tomponline** [comment]
We've got an article on the forums that covers some options for managing/delaying automated updates, including the snap proxy which is suitable for larger deployments where updates must only be applied after being approved. https://discuss.linuxcontainers.org/t/managing-the-lxd-snap/8178

**Comment by pbrkr** [comment]
@tomponline Sadly that's too little, too late. The net effect of this issue is that I removed Ubuntu completely from my infrastructure and switched to Alpine Linux instead (after 8+ years of running Ubuntu). Switched from LXD to Docker (and soon to Podman). I have concerns with docker and would prefer to use LXD but it's not an option if issues like this are considered EWONTFIX.
