### ISSUE TITLE
/snap/lxd/14709/commands/lxc: 6: exec: aa-exec: Permission denied

### ISSUE THREAD

**Issue by clauded** [lxc/lxd#7239]
In reference to https://github.com/lxc/lxd/issues/7222, I have the problem with 4.0.0 and now 4.0.1 (I'm running lxd snap on Solus): the aa-exec file is located in /usr/bin, not /usr/sbin as indicated in the AppArmor profile files. As a temprary work around, edit those files (I haven't checked if it's present in other files) and change this line:

`/usr/sbin/aa-exec ux,` becomes `/usr/bin/aa-exec ux,`

Another solution would be to simply add `/usr/bin/aa-exec ux,` to those files.

This is the whole procedure:

```
find /var/lib/snapd/apparmor/profiles/snap.lxd.* -type f -exec sed -i 's|/usr/sbin/aa-exec ux,|/usr/bin/aa-exec ux,|g' {} \;
apparmor_parser -r /var/lib/snapd/apparmor/profiles/* -v
systemctl stop snap.lxd.daemon.unix.socket
systemctl stop snap.lxd.daemon.service
systemctl start snap.lxd.daemon.unix.socket
systemctl start snap.lxd.daemon.service
systemctl status snap.lxd.daemon.unix.socket
systemctl status snap.lxd.daemon.service
```

**Comment by stgraber** [comment]
This is a snapd bug which has been fixed quite a while back.
You may try `snap install snapd` to hopefully have snapd re-exec and not use your distro's version, or otherwise may need to get an updated snapd onto your system so it has the fixed apparmor logic.

**Comment by edenist** [comment]
Thanks @clauded for this information. This fixed things up on my up-to-date solus install as well. 

@stgraber this issue was raised with the solus devs and it has been sent back this way [https://dev.getsol.us/T8917]

Regarding the bug  in snapd being fixed, was it this one? 
https://github.com/snapcore/snapd/pull/7716

I can confirm that my snapd is reporting itself as a version higher than the system version, and to a version after that merge. 


```
$ snap list
Name       Version               Rev    Tracking  Publisher   Notes
core       16-2.44.3             9066   stable    canonical✓  core
core18     20200427              1754   stable    canonical✓  base
freeorion  2020-02-02.db5347183  67     stable    agrrr3      -
lxd        4.1                   15067  stable    canonical✓  -
snapd      2.44.3                7264   stable    canonical✓  snapd
```

```
$ eopkg info snapd
Installed package:
Name                : snapd, version: 2.39.3, release: 54```

Then again, the following suggests it is still using the system version [and thus apparmor generation is still broken].

```
$ snap --version
snap    2.39.3
snapd   2.39.3
series  16
solus   4.1
kernel  5.6.13-153.current
```

I think I'm going to report back to solus devs with this information. It would be good to have snapd updated locally to be sure.

**Comment by stgraber** [comment]
Right, looks like you distro has re-exec disabled, which would get you that behavior.
