### ISSUE TITLE
No information about unprivileged containers with lxd and all possible images list

### ISSUE THREAD

**Issue by cryptofuture** [lxc/lxd#725]
Since /etc/lxc is mostly empty when using lxd. I found some information about creating lxc unprivileged containers. But that should be adapted to lxd. Want to run steam easy with lxd. And that must be normal amd64 ubuntu trusty container. (most games use 64bit)
https://www.stgraber.org/2012/11/16/running-steam-in-a-lxc-container/  

Maybe we can just adapt steam-lxc to execute on lxd-images import lxc steam trusty amd64 --alias steam or something like that. But that way steam-lxc needs upgrade. But better solution will be create end-user image with separated profile (direct GPU access, pulseaudio access ) for lxc/lxd configuration.  

Also there are no information on linuxcontainers.org about all possible images we have now, and where and how we can share user created images.(container + profile)
Best description will be what container include and how to create it.  
For example:  
Ubuntu 14.04 64 bit:  
   lxd-images import lxc ubuntu trusty amd64 --alias ubuntu  
Debian 7 Wheezy 64bit:  
   lxd-images import lxc debian wheezy amd64 --alias debian  
Ubuntu 12.04 32 bit:  
   lxd-images import lxc ubuntu precise i368 --alias ubuntu  
Ubuntu 14.04 64 bit steam image:  
   lxd-images import lxc steam amd64 --alias steam  
etc...  
Maybe wiki will be best solution for that, where users can add information about new container images and links for them, with install instructions  in case when image can't be used or hosted on original linuxcontainers.org. Most people use same software, so repository with prepared container images can save bunch of time.

**Comment by chrisglass** [comment]
Just a quick note: *all* containers are always unprivileged when using LXD.

You can check that easily by ps'ing on the host on a running container (the container's process is mapped to user 100000 here).

**Comment by stgraber** [comment]
As for images, the best is to have the image server behave as a LXD server, as is the case for images.linuxcontainers.org (lxd-images doesn't have to be used for it).

Then just do:

    lxc remote add images images.linuxcontainers.org

And after that you can simply do:

    lxc image list images:

To list all images and:

    lxc launch images:ubuntu/trusty/amd64 blah

To start a container from one of those images (caching it in the process).

**Comment by cryptofuture** [comment]
>lxc remote add images images.linuxcontainers.org  
>lxc image list images:  

Thats even better then what I want. Cool. How I can setup my own image server?  
>Just a quick note: all containers are always unprivileged when using LXD.  

I know about process rights on main machine, checked that. But how to get user shell from container and run applications with user only? (without droping rights in container itself and using ssh)
For example, with that commands I get root shell and htop running with root rights.
`lxc exec conname -- /bin/bash`
`lxc exec conname -- htop`

And sorry for another stupid question how I can get container autostart with lxd or lxc, when using lxd. As I already said, we haven't many things in /etc/lxc.  
Currently I'm using
`/usr/bin/lxc start conname >/dev/null 2>&1` in /etc/rc.local

**Comment by stgraber** [comment]
For image servers, you can run a public LXD with public images, that should work.
The implementation on images.linuxcontainers.org however is done by manually writing json files and with a few rewrite rules so that a static http server can act as a lxd image server.

User namespaces make it so that uid 0 (root) inside the container isn't actually real root outside of it.
So when you do "lxc exec", you see that you are root and most everything will think that you are, but you're not, from the host point of view, you're uid 165536 or some such.

As for auto-start, there's no such thing in LXD. But recent versions have a "last-state" mode which you can trigger by sending SIGPWR to the lxd daemon. It will then perform a clean shutdown of all containers and exit. Upon restart it will then restore all those containers to the state they were before LXD was shut down.
