### ISSUE TITLE
Feature request: "lxc history" command

### ISSUE THREAD

**Issue by gbonazzoli** [lxc/lxd#7252]
Stated the fact that in order to manage a cluster of servers lxd already leverage a database behind the curtain, why don't use it also for storing commands that were thrown to the cluster.

Informations to keep are also the who submitted the command (or API endopoint...), datetime, and the version of lxd at the time of the command.

More or less try to mimic the "zpool history".

Keep the good work!

**Comment by stgraber** [comment]
Nope, not going to do that.

It would cause an absolutely crazy amount of database writes that would degrade overall performance and not actually log something that most users could relate to (API requests rather than the commands they ran).

If you need this for some reason, you could implement it yourself with your own service connecting to the events API. We send lifecycle events for most common user operations and the logging events get the rest.
