### ISSUE TITLE
SNAT specific interface.

### ISSUE THREAD

**Issue by uwejan** [lxc/lxd#7311]
Hi, a feature request if possible. 
The ability to specify the `SNAT` interface. The purpose: allow 2 bridges communication internally. 
Please refer to this discussion for details.
https://discuss.linuxcontainers.org/t/lxd-2-bridges-comunication/7042/16

**Comment by stgraber** [comment]
So I don't think we'll want to do this at this time. It would have us put one foot into network to network firewall rules while not thinking through all other aspects of it, leaving us with configuration keys we can't remove because of backward compatibility, causing headaches when we get to a proper solution.

For now, custom bridge firewalling should be done outside of LXD and if needed, LXD's own rules be disabled.

We do have plans to tackle firewalling and security groups in the next year or so, which will then come with the ability to control network to network flows. If two networks are configured to access between each other, then we'd just route and bypass NAT, if not, then they'd be treated as WAN access, get NAT-ed and enter into the other network as WAN.

Anyway, none of that is particularly relevant until we have done design work on security groups which will come after we've done our current work on virtual networks.
