### ISSUE TITLE
Implement system-wide remotes

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#7322]
The CLI tool (`lxc`) reads its config from `~/.config/lxc/config.yml`, that's where the various remotes are defined except for the built-in ones.

Users on shared systems have shown interest in adding remotes to all users.
For this, we'd need the LXD CLI to read both its normal config as well as a global configuration.

The apply order would effectively be:
 - Built-in
 - System
 - User

With each level being able to override the other, resulting in a complete config.
When saving, only what's specific to the user should be saved. Users will be able to override system remotes at which point they'll just be added to their own config.

On top of having a global `config.yml`, we also will need a global `servercerts` directory to host potential certificates for the global remotes. If a remote is marked as coming from the global config, we'd look for certs in that path rather than the usual `~/.config/lxc/servercerts`.

**Comment by zhenr667** [comment]
Hi! I'm a student from UT and my team would like to tackle this issue!

**Comment by stgraber** [comment]
Thanks, assigned it to you.

**Comment by stgraber** [comment]
@zhenr667 Do you still intend to work on this or should we un-assign so someone else can have a go at it?

**Comment by zhenr667** [comment]
@stgraber I don't think I can work on this, sorry for the trouble.

**Comment by presztak** [comment]
@stgraber Can I work on this one?

**Comment by stgraber** [comment]
Of course, assigned!

**Comment by presztak** [comment]
@stgraber , as usual couple of questions to you:

1. Is it ok to keep global config in `/var/lib/lxd/config` (as default, of course respecting [`shared.varPath`](https://github.com/lxc/lxd/blob/e504a0c18a1eaec9d322a486ffdbeedb98357e04/shared/util.go#L207))?
2. Should we introduce new `Global` field for [`Remote`](https://github.com/lxc/lxd/blob/afff9e5620d6adb6a735f8da7d346102274619e7/lxc/config/remote.go#L23) struct because as you said we need to know where to search potential certificates?
3. How we should behave when user try to rename global remote. Should we create a new one in user config and display two of them (new from user config and old one from global)? Or maybe prevent renaming global remotes? Or display only new one but then we need to keep info about relation to the global one.

**Comment by stgraber** [comment]
I think I'd want to avoid `/var/lib/lxd` as that's really the server data.
Instead, it'd be more appropriate to use `/etc/lxd` for this I believe.

**Comment by stgraber** [comment]
Introducing a `Global` bool to `Remote` similar to `Static` would probably make sense, if only to be able to show where a remote came from and to avoid saving it in the local config.

**Comment by stgraber** [comment]
Any change to a global remote should cause it to get duplicated into the local config, so if `set-url` is used, you get a copy under the same name, if `rename` is used, you get a local copy under the new provided name.

**Comment by presztak** [comment]
@stgraber should we have any possibility to add, remove system remotes from cli (`lxc`)? Or this will be allowed only manually?

**Comment by stgraber** [comment]
Just manually for now is fine.
