### ISSUE TITLE
Cannot create VM from published image that is >10GB

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#7346]
See https://discuss.linuxcontainers.org/t/how-to-set-vm-root-volume-size-when-lxc-init/7753/5

```
lxc init ubuntu:18.04 v1 --vm -s lvm
lxc config device set v1 root size=20GB
lxc publish v1 --alias myvm
lxc init myvm v2 -s lvm
Creating v2
Error: Create instance from image: Failed converting image to raw at /dev/lvm/images_8b9e22918ea77c65b9522da6a5864555ba5719e010fc8cab9a0e721dd8414d3d.block: Failed to run: qemu-img convert -O raw /var/lib/lxd/images/lxd_image_unpack_675811621/rootfs.img /dev/lvm/images_8b9e22918ea77c65b9522da6a5864555ba5719e010fc8cab9a0e721dd8414d3d.block: qemu-img: /dev/lvm/images_8b9e22918ea77c65b9522da6a5864555ba5719e010fc8cab9a0e721dd8414d3d.block: error while converting raw: Device is too small
```

```
DBUG[05-11|09:38:53] CreateInstanceFromImage started          driver=lvm pool=lvm project=test instance=v2
DBUG[05-11|09:38:53] EnsureImage started                      driver=lvm pool=lvm fingerprint=8b9e22918ea77c65b9522da6a5864555ba5719e010fc8cab9a0e721dd8414d3d
DBUG[05-11|09:38:53] Database error: &errors.errorString{s:"No such object"} 
DBUG[05-11|09:38:54] Logical volume created                   driver=lvm pool=lvm vg_name=lvm lv_name=images_8b9e22918ea77c65b9522da6a5864555ba5719e010fc8cab9a0e721dd8414d3d.block size=10000000000b fs=ext4
DBUG[05-11|09:38:54] Logical volume created                   driver=lvm pool=lvm vg_name=lvm lv_name=images_8b9e22918ea77c65b9522da6a5864555ba5719e010fc8cab9a0e721dd8414d3d size=49999872b fs=ext4
DBUG[05-11|09:38:54] Mounted logical volume                   driver=lvm pool=lvm dev=/dev/lvm/images_8b9e22918ea77c65b9522da6a5864555ba5719e010fc8cab9a0e721dd8414d3d path=/var/lib/lxd/storage-pools/lvm/images/8b9e22918ea77c65b9522da6a5864555ba5719e010fc8cab9a0e721dd8414d3d options=discard
DBUG[05-11|09:38:54] Unmounted logical volume                 driver=lvm pool=lvm path=/var/lib/lxd/storage-pools/lvm/images/8b9e22918ea77c65b9522da6a5864555ba5719e010fc8cab9a0e721dd8414d3d
DBUG[05-11|09:38:54] Mounted logical volume                   driver=lvm pool=lvm dev=/dev/lvm/images_8b9e22918ea77c65b9522da6a5864555ba5719e010fc8cab9a0e721dd8414d3d path=/var/lib/lxd/storage-pools/lvm/images/8b9e22918ea77c65b9522da6a5864555ba5719e010fc8cab9a0e721dd8414d3d options=discard
DBUG[05-11|09:38:54] Running filler function                  driver=lvm pool=lvm dev=/dev/lvm/images_8b9e22918ea77c65b9522da6a5864555ba5719e010fc8cab9a0e721dd8414d3d.block path=/var/lib/lxd/storage-pools/lvm/images/8b9e22918ea77c65b9522da6a5864555ba5719e010fc8cab9a0e721dd8414d3d
DBUG[05-11|09:38:57] Failure for task operation: 868366c1-d569-4c4e-b7a9-149d6c0385d5: Create instance from image: Failed converting image to raw at /dev/lvm/images_8b9e22918ea77c65b9522da6a5864555ba5719e010fc8cab9a0e721dd8414d3d.block: Failed to run: qemu-img convert -O raw /var/lib/lxd/images/lxd_image_unpack_675811621/rootfs.img /dev/lvm/images_8b9e22918ea77c65b9522da6a5864555ba5719e010fc8cab9a0e721dd8414d3d.block: qemu-img: /dev/lvm/images_8b9e22918ea77c65b9522da6a5864555ba5719e010fc8cab9a0e721dd8414d3d.block: error while converting raw: Device is too small 
```

**Comment by likema** [comment]
I suggest to implement a config named `root.size` additionally, such as

```bash
lxc init myvm v2 --vm -c root.size=20GiB
```

**Comment by tomponline** [comment]
@likema the first step is to ensure that we can create optimised cached image volumes that are larger than the default 10GB, otherwise we wont even get to the phase of creating the actual instance.

**Comment by likema** [comment]
> @likema the first step is to ensure that we can create optimised cached image volumes that are larger than the default 10GB, otherwise we wont even get to the phase of creating the actual instance.

Yes.

**Comment by stgraber** [comment]
Ok, so thinking through this mess again, it feel like we're trying to accommodate block backed instances much the same way we do filesystem backed instances where space constraints aren't really a thing (outside of the host running out of space).

As a result, I think we want to ensure that:
 - If `volume.size` is set, we respect it above all else, same should go for filesystem based drivers. An image which unpacks to something larger than `volume.size` should fail. This is DoS protection against badly crafted images and is critical to shared hosted platforms.
 - When `volume.size` isn't set, filesystem based drivers allow for as much space to be consumed as is available in the pool.
 - The equivalent for block based is to figure out the size of the image (easy for VMs, harder for containers) and allocate that instead. If that's smaller than the default volume size, then this should be grown to that size.
 - If `volume.size` is then lowered, then that's where we get into troubles because we have images for VMs which cannot be shrunk but are asked to create an instance of a smaller size. In such cases, we should pull the real size again, if it fits in the current `volume.size`, we should throw out our current optimized image and re-import it using the new configured `volume.size`.

The last tricky case is if a new instance is created using a root disk size lower than `volume.size` but equal or larger to the image size. In this case, we don't want to invalidate our cached image. So we should instead do a direct unpack for that one instance.

**Comment by tomponline** [comment]
Recording suggestion of using `volatile.rootfs.size` on the image volume's DB record to cope with cheaply inspecting virtual qcow2 size for unified image tarballs.

**Comment by tomponline** [comment]
@stgraber thanks for your summary, my interpretation of your points applied to this particular issue is the following:

- If the pool's `volume.size` setting is specified and is < the qcow2's virtual size then we should just refuse to create the cached volume (or the actual volume for drivers that don't support optimized volumes). Effectively resulting in a similar error the OP is getting today (albeit it something more user friendly).
- However if the pool's `volume.size` setting is *not* specified, then we are free to create the volume (cached or otherwise) as large as we can to accommodate the image's virtual size.

Also, your last point about the tricky case if a new instance is created user a custom root disk size. How is this achieved using the lxc cli? I tried doing: `lxc init ubuntu:18.04 c1  -c root.size=15G` but got an error: "Create instance: Unknown configuration key: root.size"

**Comment by likema** [comment]
`lxc init ubuntu:18.04 c1 -c root.size=15G` is very straightforward in some scenario.

**Comment by tomponline** [comment]
I dont think we would add that as it is, as root.size would conflict with the namespace of the instance config keys. It would need to be something else, maybe a special -d for device flag `-d root.size=15GB` indicating that the first `root.` part is the device name. Anyway @stgraber may already having something in mind for this.

**Comment by stgraber** [comment]
We have some syntax for it in copy I think
