### ISSUE TITLE
lxc import breaks container's quota

### ISSUE THREAD

**Issue by kautMaks** [lxc/lxd#7365]
* Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-29-generic
   * LXC version: 4.1
   * LXD version: 4.1
   * Storage backend in use: dir

# Issue description
lxc import breaks container's quota

# Steps to reproduce
1. lxc launch ubuntu:18.04 test

Output of `repquota -avugPs`:
```
                        Space limits                File limits
Project         used    soft    hard  grace    used  soft  hard  grace
----------------------------------------------------------------------
#10010    --    704M      0K 1048576T          35914     0     0       
```

2. lxc export test test.tar.gz
3. lxc delete test --force
4. lxc import test.tar.gz

Output of `repquota -avugPs` after that:
```
                        Space limits                File limits
Project         used    soft    hard  grace    used  soft  hard  grace
----------------------------------------------------------------------
#10011    --      4K      0K      0K              1     0     0       
```

# Information to attach
FS - ext4 with prjquota enabled
```
# tune2fs -l /dev/md2 | grep features
Filesystem features:      has_journal ext_attr resize_inode dir_index filetype needs_recovery extent 64bit flex_bg sparse_super large_file huge_file dir_nlink extra_isize quota metadata_csum project
```
```
# mount | grep /dev/md2
/dev/md2 on /var/lib/lxd type ext4 (rw,relatime,lazytime,nouser_xattr,noacl,prjquota)
```

**Comment by stgraber** [comment]
@tomponline something you can take a look at?

**Comment by tomponline** [comment]
@stgraber yep ill take a look

**Comment by tomponline** [comment]
@stgraber so the issue is caused because during backup restore we do not have the instance database entries created until *after* the storage volumes have been unpacked and created.

This causes a chicken/egg problem because we derive the project quota ID from the database storage volume ID. In order to work around this we created a special `volIDQuotaSkip` ID that was passed to the `Volume` when restoring from backups to indicate we don't want to setup quotas at unpack time.

Then, once the DB records have been created, we do initialise the quota in the post hook returned by `CreateInstanceFromBackup`.

This is why we do see the project quota record created on restore.

The issue is that the unpacked files are not actually part of that project because the project didn't exist when they were created on disk.

I've experimented with using `chattr -R -p 10020  =P /home/user/dirprojquotapool/test/containers/c1` to recursively set the project ID on the files which seems to work, although I get quite a few errors on some files, suggesting that not all files have been included in the project (although a good proportion do).

However when trying to replicate this approach by doing `quota.SetProject(path, projectID)` on every file recursively using `filepath.Walk()` in Go, pretty much ever file fails with a non-descript error.

Do you think that recursively updating the project of all files in the post hook is a potentially viable approach or should I look at something more invasive, such as only partially unpacking the backup.yaml and empty snapshot dirs sufficient to 'trick' `internalImport` from creating the database rows, and then performing the actual unpack in the post hook?

**Comment by stgraber** [comment]
`quota.SetProject` is I believe meant to be used for a new directory structure, applying it on files is unlikely to succeed.
You'd need an equivalent of what chattr does.

This may be viable but we'd need to ensure that should we hit an out of disk issue we need to fail and delete the volume.

**Comment by tomponline** [comment]
@stgraber thanks for the tip, I think I've identified the difference, `quota_set_path` tries to set the `FS_XFLAG_PROJINHERIT` flag, but this can only be set on directories, whereas the chattr command with just a `-p projectID` flag just does:

```c
int fsetproject(const char *name, unsigned long project)
{
#ifndef FS_IOC_FSGETXATTR
	errno = EOPNOTSUPP;
	return -1;
#else
	int fd, r, save_errno = 0;
	struct fsxattr fsx;

	fd = open (name, OPEN_FLAGS);
	if (fd == -1)
		return -1;
	r = ioctl (fd, FS_IOC_FSGETXATTR, &fsx);
	if (r == -1) {
		save_errno = errno;
		goto errout;
	}
	fsx.fsx_projid = project;
	r = ioctl (fd, FS_IOC_FSSETXATTR, &fsx);
	if (r == -1)
		save_errno = errno;
errout:
	close (fd);
	if (save_errno)
		errno = save_errno;
	return r;
#endif
}
```

**Comment by stgraber** [comment]
Okay, so we could add a recursive project add function to the project quota package and call that in this case, mimicking that logic.

**Comment by tomponline** [comment]
@stgraber OK so I've got this almost working (and I also found a file descriptor leak in the existing C code).

The final remaining problem is that I cannot set the project ID attribute on non-regular files (symlinks and device files). The `chattr` command also has this same restriction.

However apparently there is a way around this, as if you setup the project on a directory with the inherit flag before creating the files (which is what happens when the new container is created normally), then apparently these files *are* recorded under the project.

I've added detection for non-regular files, which means I can restore a backup and have all but circa 450KB accounted for. But I can't figure out how to get these non-regular files accounted for when setting the project post-create.

Example:

```
sudo repquota -avugPs
*** Report for project quotas on device /dev/loop15
Block grace time: 7days; Inode grace time: 7days
                        Space limits                File limits
Project         used    soft    hard  grace    used  soft  hard  grace
----------------------------------------------------------------------
#0        --    456K      0K      0K           4694     0     0       
#10116    --    694M      0K      0K          31056     0     0       
#10117    --    695M      0K      0K          35750     0     0  
```

In the example above, project 10116 is the restored container from backup, and the 4694 files in project 0 are the devices and symlinks from the container.

31056 + 4694 = 35750, i.e the same amount as the files in project 10117 which is a freshly created container.

**Comment by stgraber** [comment]
Doesn't matter, neither of those really have a size, so it's just an inode we're not accounting which isn't a big deal.

**Comment by tomponline** [comment]
Cool id hoped you would say that, ill put a PR up first thing tomorrow. 😃

**Comment by s3rj1k** [comment]
> Doesn't matter, neither of those really have a size, so it's just an inode we're not accounting which isn't a big deal.

Still I think it should be referenced somewhere in docs.
This is not exactly an expected behavior.

**Comment by kautMaks** [comment]
@tomponline @stgraber Thank you!
And I also think it should be referenced somewhere in docs, as @s3rj1k said :)

**Comment by stgraber** [comment]
I don't really see this being relevant to mention in docs and frankly just confusing :)

The space usage is properly accounted, the number of files is off because some files cannot be assigned to projects other than at creation time. That's a kernel restriction but not one which actually impacts the feature (space limit).
