### ISSUE TITLE
Stream exports

### ISSUE THREAD

**Issue by johanehnberg** [lxc/lxd#7454]
Using LXD 4.1 snap on Ubuntu 20.04 as a reference.

Currently `lxc export` seems to do the following separate steps:
1. Create a backup of the container on the server
2. Compress the backup on the server
3. Send the backup as a file to the client

The drawbacks of this approach are unnecessary disk usage as well as inefficient use of cpu, memory and network resources.

A stream export would do the equivalent of (pseudo):
`lxd send | gzip | nc` <-- network --> `nc > file`

This way, each process is parallelized resulting in a faster action.

Inserting buffers between each part further improves performance. This practice is quite common in zfs/btrfs send scripts.

Streaming also more elegantly solves https://github.com/lxc/lxd/issues/5515

A further benefit is that interrupted processes will not cause orphaned files that eat up disk space. The only file is the target, and it is easy to spot if something goes wrong.

**Comment by johanehnberg** [comment]
This also solves the obvious issues snaps have with saving files at arbitrary locations and filesystems. Currently, those files simply disappear with an exit status of 0, which is slightly scary. Streaming allows us to put the file where we want, and avoid workaround such as writing the image where snap can find it first, and the move it separately.

**Comment by stgraber** [comment]
`lxc export` is based on the LXD backup API which by design depends on artifacts being built, stored and recorded in the database, then can be downloaded by one or multiple clients until it's deleted or expires.

Streaming is also incompatible with some of the compression options (like squashfs) which require the ability to seek the file they're compressing.

If a backup failing doesn't cause files to be deleted, then that's a bug which needs fixing.
For disk space issue, the option to store backups in a volume on a storage pool usually covers that problem.

We also already have have a streaming API, the migration API, that one is guaranteed to support streaming, though obviously because it does, the client side of it is far less pleasant :) But one could certainly write a tool which hits the migration API to pull an optimized or non-optimized dump of a particular instance.

**Comment by johanehnberg** [comment]
For posterity, I am exploring using `lxc query` for this purpose in this thread:
https://discuss.linuxcontainers.org/t/is-it-possible-to-use-lxc-query-to-stream-a-container-to-stdout/7979

**Comment by stgraber** [comment]
That's going to be tricky. You can definitely use `lxc query` to setup the migration operation but you'll need to either extend `lxc query` to handle websocket or use a separate websocket-enabled http client to actually fetch the data as well as exchange the management frames over the control socket.

**Comment by johanehnberg** [comment]
Websockets would not be an issue, but management frames are not likely in any format an off-the-shelf tools would understand.

**Comment by stgraber** [comment]
If you're doing this from a Go codebase, you can import our migration package which has the management frame logic, that's what we do from `lxd-p2c` which is another standalone tool that talks to the migration API (though in this case to send an rsync stream).

If you're using another language, so long as there is a protobuf binding, it should be hard to import `lxd/migration/migrate.proto` through that binding, then fill up the migration struct and have it written to websocket.

**Comment by stgraber** [comment]
As the migration frame will always be the same in your case, you could also just capture it one time and just blindly repeat it.

I believe the way this works is that when you connect to the control websocket, the server will send you a frame, then normally you'd parse it, change any bits you don't support and push it back. In your case because it will always be the same thing, you could just read one message and then write your fixed message back, which will then initiate the rsync stream on the other websocket.

**Comment by stgraber** [comment]
(That assumes you don't want all the snapshots too, if you do, then that would need some parsing on the receiving side to know how many snapshots and with what names will be transferred and then expect that many rsync streams.)

**Comment by johanehnberg** [comment]
That makes sense. Ultimately this puts it outside `lxc query` capabilities, in the realm of custom tooling, which in my case is mostly limited to bash. I guess the way around it is to use `zfs send` for fs + `lxc config show` loop for a metadata dump.

**Comment by stgraber** [comment]
Just zfs should be sufficient, the metadata you can get back from backup.yaml in the dataset.

**Comment by stgraber** [comment]
In case you need to restore such a dump, you'll need to move it back to a LXD server, make sure it's at the same spot it was in the zpool, then mount the dataset at its usual spot and run 'lxd import NAME' (note lxd, not lxc).

This is effectively using the disaster recovery import method described in our backup docs.
