### ISSUE TITLE
[Request] Clarify loop-backed storage creation in lxd init

### ISSUE THREAD

**Issue by toby63** [lxc/lxd#7491]
When I wrote a pull request for getting-started-cli (https://github.com/lxc/linuxcontainers.org/pull/426) I added a section to describe the options in `lxd init`.

I noticed that the questions and options in https://github.com/lxc/lxd/blob/master/lxd/main_init_interactive.go only once mention a `loop device` in:
> Size in GB of the new loop device (1GB minimum)

So it might not be clear for everyone that LXD will create loop-backed devices.
Maybe the questions (and descriptions) in `lxd init` could be improved, for example by adding:
* a question that let's the user decide between using a partition (or zpool, volume etc.) (that already exists or needs to be created manually) and a loop-backed storage: so both options are visible at the same time
* a short explanation:
    * that LXD will create loop-backed devices 
    * what the difference is 
    * about disadvantages (loop-backed storage is slower etc.)
* an overview of all options before the init starts, or a link to getting-started-cli.md in case someone wants to inform him-/herself beforehand

**Comment by stgraber** [comment]
Hmm, so I'm not sure how much we can realistically do about this without making `lxd init` longer (user feedback is that it's too long as it is) and without causing more confusion.

We tried some different wording in the past to push people more towards using disks/partitions rather than loop devices, but the result was people getting confused and entering their current partition path, causing potential data loss...

We also don't want our most common path to show what appears to be a scary warning or blurb of text that would interrupt the flow.

I'll send a branch which does the following though to try and limit some of the most common issues:
 - Re-phrase the `existing block device` question to instead say `existing empty disk or partition` which sounds clearer
 - Change the loop size logic to be 5GB min, 30GB max, 20% free space target from 15GB min, 100GB max, 20% free space target. This should help quite a bunch on space constrained systems and growing a loop device is much simpler than shrinking it.

**Comment by toby63** [comment]
https://github.com/lxc/lxd/commit/5139e3ca54d1a880ecc8fbebd090665c3835e1b3 :+1:

> existing empty disk or partition

Ok, I will add the word "empty" to the getting-started-cli.md as well.

Still I think https://github.com/lxc/lxd/blob/master/lxd/main_init_interactive.go could maybe be improved:
1. Clearly show all possible paths in the first question about storage (maybe difficult or longer to explain, but better than letting people run in the false direction)
This is especially useful for people who read the documentation, that now gives clearer advice on this.
Example:
```
  1. dedicated storage (preferred method; needs an existing empty partition or disk; supported by "zfs", "btrfs", "lvm" etc.)
  2. shared storage on host (preferred method; either needs existing zfs- or btrfs-pools on host; or use "dir"-backend)
  3. loop-disk (alternative method (slower); LXD can create these; all storage-backends supported)

For help see documentation: https://linuxcontainers.org/lxd/docs/master/storage
```
2. add a mention about "loop-devices" to clarify that LXD will "now" create a loop device.
