### ISSUE TITLE
LXD container not able to run few docker containers

### ISSUE THREAD

**Issue by Cloud-Mak** [lxc/lxd#7496]
# Required information

  * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-47-generic
   * LXC version: NA
   * LXD version: 3.0.3
   * Storage backend in use: 

# Issue description
I am trying to install RKE (rancher K8 engine) on one of LXD cotainers and getting below error for one of container rancher tried to deploy as part of installation process - 

FATA[0008] [Failed to start Certificates deployer container on host [10.70.241.23]: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused “process_linux.go:449: container init caused “process_linux.go:415: setting cgroup config for procHooks process caused \“failed to write \\\“a : rwm\\\” to \\\”/sys/fs/cgroup/devices/docker/326881b50b64365bbf4a3aa9457cd3fa45220464222bfd89cf214222910bc595/devices.allow\\\”: write /sys/fs/cgroup/devices/docker/326881b50b64365bbf4a3aa9457cd3fa45220464222bfd89cf214222910bc595/devices.allow: operation not permitted\”"": unknown]

The same LXD containers can run other containers (including rancher setup help containers) fine. Its only the container named cert-deployer failing. This containers only job is to create a self signed certs for K8.

**Comment by stgraber** [comment]
Docker is trying to allow that container full access to every character and block device.

This explains the error you're getting as your LXD container is not allowed to do that kind of access since that would be a huge security issue.

My guess is that this one Docker container is using --privileged or some similarly problematic option.

Closing as this isn't a LXD bug but expected behavior. Our forum may be a better location to discuss deployment configurations.
