### ISSUE TITLE
Wrong error message during storage pool creation

### ISSUE THREAD

**Issue by toby63** [lxc/lxd#7700]
# Required information

 * Distribution: Arch
 * Distribution version: Stable
   * LXC version: 4.0.3
   * LXD version: 4.3
   * Storage backend in use: btrfs

# Issue description

During `lxd init` I tried to use a btrfs partition (formatted but otherwise empty) as a new storage pool.
I got an error message (sry I don't have the original anymore) that said something like:
`Partition is not empty, use -f (force) to overwrite it.`

This was obviously because it was pre-formatted.

Now I see two problems:
1. This message is confusing because a new user might ask him/herself "where should I apply `-f`?".
2. `lxc storage create` does not seem to have an `-f` option (anymore?).

# Potencial Solutions:

1. Edit the message so it represents the current situation, especially specifying what the problem is (in this case the partition already being formatted) and what the user should do now (re-run `lxd init`? proceed without it and add it manually with `lxc storage create`?)
2. Let the user use a preformatted but otherwise empty partition.
3. Implement an option in `lxd init` to solve the problem.

**Comment by stgraber** [comment]
The original error message would have included what command failed and made it clear that this wasn't an error that LXD itself was throwing but instead forwarding it.

**Comment by stgraber** [comment]
The exact error returned varies based on kernel, version of the tools and filesystem in use, so it's unrealistic for LXD to catch all of those.

We also can't tell whether a partition is in use or not, it can be in use on another system if it's a SAN volume, it can be in use in a VM or mount namespace hiding it from us, in any of those cases, even attempting to mount it to see if it has stuff in it could cause irreparable data loss.

We also don't want to implement a universal force flag for that, because again, not all filesystems and tools implement forcing the same way and there's also a pretty bad track record of users using `--force` without thinking very much, which in this case, based on past values we've seen be used, would cause the immediate loss of their entire hard disk.

**Comment by stgraber** [comment]
For the few that hit this error when the partition/disk is in fact wrongly formatted and there is indeed no data there, using a disk manager or directly wiping the beginning of the disk/partition is easy enough.
