### ISSUE TITLE
CLI - add confirmation for delete

### ISSUE THREAD

**Issue by zacbri** [lxc/lxd#781]
Although I agree we should be responsible sysadmins, mistakes happen.
It might be good to have a safety net as a simple confirm y/n when running "lxc delete <container>"

**Comment by tych0** [comment]
Since github seems to have eaten another email reply of mine:

I'd prefer not (or instead, to have a --please-confirm flag a. la. rm                    
-i), simply because I very rarely typo things, but I very often delete                   
things, so I end up having to /always/ confirm, which is a nuisance.

**Comment by jgriffiths1993** [comment]
I'd prefer to not have confirmation; a `--confirm` flag would be sufficient

**Comment by zacbri** [comment]
Ok, makes sense.
I agree, a -i or similar switch would work fine.
Thanks

**Comment by zacbri** [comment]
Another suggestion : what about a behaviour similar to lxc-destroy which requires the container to be stopped before being able to destroy it ?

**Comment by jgriffiths1993** [comment]
I was thinking something along these lines; requiring `[ --force | -f ]` to remove containers which are not stopped.
