### ISSUE TITLE
Remplacement of lxd-client package (who stops with 3.0.x) in a container without privilèges ?!

### ISSUE THREAD

**Issue by nfournil** [lxc/lxd#7817]
Hello,

I'm using LXC/LXD since 1.x and I use it in production since. Everything was ok... before trying Ubuntu 20.04 with LXC/LXD over snap... who is really a big change !

We are using an homemade cloud supervisor IN A CONTAINER who runs lxd-client cli command calls ... and of course we had to install snap to get lxd-client inside the container and ... container snapd inside snapd without privileges doesn't work. 

How can we handle this ?

PS: I will not use MAAS as supervisor : it cannot handle all our requirements.

**Comment by stgraber** [comment]
So you can definitely run just the LXD client from the snap inside an unprivileged container.
What exactly is your setup and what's the error you'regetting?

**Comment by nfournil** [comment]
Hello, 

To be more precise, it's more than we can't make lxd work via apt installation, without privileged mode. Here is more details about the issue : 

We are forced to install snap and lxd in an offline environment ( from a local repo ) 

so far, we tried multiple ways to install it  : 

First on an new and empty container, ( without snap ) , we disabled snapd.pref ( rm /etc/apt/preferences.d/snapd.pref ), and then installed lxd-client from a local repository ( lxd 4.4,  apt install lxd-client ). 

It installed lxd and snap as expected, but after that, when we do a snap list, they appears as broken : 


snap list
Name    Version  Rev    Tracking       Publisher   Notes
core18           1880   latest/stable  canonical✓  broken
lxd              16558  4.0/stable/…   canonical✓  broken
snapd            8542   latest/stable  canonical✓  broken


We then restarted the container, got a clean snap list, but the following error : 

cat: /proc/self/attr/current: Permission denied
/snap/lxd/16558/commands/lxc: 6: exec: aa-exec: Permission denied



The second method was, on a fresh container :

- we turn on priviliedged / nested mode 

- then we restart the container   

- we rm /etc/apt/preferences.d/snapd.pref and install lxd via apt ( apt install lxd ) 

- we restart the container 

- we manually execute a snap connect lxd:lxd-support core:lxd-support and then restart snap.lxd.daemon

- we then disable privileged/nested mode

- and finally restart the container again 


and then it worked. 


Is it necessary to use priviliged mode to make it work ? 

Thank you for your time.

**Comment by nfournil** [comment]
Hello, 

after a bit more digging from our side, we managed to make it work : 

here are the differents steps we followed : 

- On a fresh container, we first rm /etc/apt/preferences.d/snapd.pref to install lxd via apt ( We are forced to install snap and lxd in an offline environment, from a local repo )

- We rebooted the container, and then got a clean snap list : 

snap list
Name    Version   Rev    Tracking       Publisher   Notes
core18  20200707  1880   latest/stable  canonical✓  base
lxd     4.0.2     16558  4.0/stable/…   canonical✓  -
snapd   2.45.2    8542   latest/stable  canonical✓  snapd

but the following error : 


cat: /proc/self/attr/current: Permission denied
/snap/lxd/16558/commands/lxc: 6: exec: aa-exec: Permission denied

To make it work we have to execute a snap connect lxd:lxd-support core:lxd-support 

Shoudln't the snap connect be automatic ? 

Thank you for your time.

**Comment by stgraber** [comment]
Ok, so that's likely normal.

Interface auto-connection happens as a result of signed store metadata (assertion).
It sounds like in your offline environment, those assertions aren't getting loaded into snapd causing this issue.

I don't know what's in your 4.4 deb but maybe there's something wrong with the store assertions it contains which prevents the auto-connect and require that additional step?

Another thing worth mentioning as potentially useful to you is the snap store proxy which can work either in proxy mode (only one machine allowed access to the actual store) or even in fully disconnected mode. Clients then interact with it as if it was the public store.

https://docs.ubuntu.com/snap-store-proxy/en/airgap

I've personally never used the airgap mode, but we do use it as a proxy for our isolated CI environment.

(Closing as this isn't really a LXD issue as much as a snapd one)
