### ISSUE TITLE
Restoring snapshot storage volume, doesn't restor the right uid/gid as before

### ISSUE THREAD

**Issue by redno2** [lxc/lxd#7831]
# Required information

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

Linux host 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ lxc --version
4.4
$ lxd --version
4.4

* Storage backend in use: ZFS

# Issue description

After created a new volume and attached it to my container. I've create some file, snapshot the volume and restore it.
I saw that the uid and gid is set at 1000000 not the same as the snapshot was created.

# Steps to reproduce
$ lxc exec test bash
root@test:~# ll /data/
total 2
drwx--x--x  2 root root  2 Sep  1 11:07 ./
drwxr-xr-x 23 root root 24 Sep  1 11:02 ../
root@test:~# ll /data/
total 2
drwx--x--x  2 root root  2 Sep  1 11:07 ./
drwxr-xr-x 23 root root 24 Sep  1 11:02 ../
root@test:~# touch /data/bob2
root@test:~# touch /data/bob43
root@test:~# ll /data/
total 3
drwx--x--x  2 root root  4 Sep  1 11:13 ./
drwxr-xr-x 23 root root 24 Sep  1 11:02 ../
-rw-r--r--  1 root root  0 Sep  1 11:13 bob2
-rw-r--r--  1 root root  0 Sep  1 11:13 bob43
root@test:~# echo bvoboibobob > /data/bob2
root@test:~# ll /data/
total 3
drwx--x--x  2 root root  4 Sep  1 11:13 ./
drwxr-xr-x 23 root root 24 Sep  1 11:02 ../
-rw-r--r--  1 root root 12 Sep  1 11:14 bob2
-rw-r--r--  1 root root  0 Sep  1 11:13 bob43

$ lxc storage volume snapshot lxd test-data

root@test:~# rm /data/bob*

$lxc storage volume restore lxd test-data/snap0

$ lxc exec test bash
root@test:~# ll /data/
total 3
drwx--x--x  2 1000000 1000000  4 Sep  1 11:13 ./
drwxr-xr-x 23 root    root    24 Sep  1 11:02 ../
-rw-r--r--  1 1000000 1000000 12 Sep  1 11:14 bob2
-rw-r--r--  1 1000000 1000000  0 Sep  1 11:13 bob43

Thanks

**Comment by tomponline** [comment]
Please can you provide output of `lxc config show test --expanded`.

**Comment by tomponline** [comment]
Confirmed issue.

**Comment by redno2** [comment]
> Please can you provide output of `lxc config show test --expanded`.

I just remove the cloud-init conf data.

$ lxc config show test --expanded                             
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 18.04 LTS amd64 (release) (20191021)
  image.label: release
  image.os: ubuntu
  image.release: bionic
  image.serial: "20191021"
  image.version: "18.04"
  user.user-data: "........."
  volatile.base_image: d6f281a2e523674bcd9822f3f61be337c51828fb0dc94c8a200ab216d12a0fff
  volatile.eth0.host_name: veth7998365f
  volatile.eth0.hwaddr: 00:16:3e:d4:2c:74
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: lxd
    type: disk
  test-data:
    path: /data
    pool: lxd
    source: test-data
    type: disk
ephemeral: false
profiles:
- default
- cloud-init
stateful: false
description: ""

**Comment by tomponline** [comment]
Thanks.

So there appears to be an issue with the `storagePoolVolumeAttachShift()` function that is run when an instance starts the disk device that mounts a custom volume.

When the snapshot volume is restored the volume's volatile config keys are removed (@stgraber is this expected?). E.g.

```
config:
  volatile.idmap.last: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000}]'
```

However when starting the instance if not running inside the snap, although the re-shifting is logged as occurring, the files remain owned on disk as `1000000` whereas running inside the snap the files are then shifted again so they are owned as `2000000`. I'm looking into why this is, but have confirmed it affects multiple storage engines, not just zfs. I'm using dir for testing.

**Comment by tomponline** [comment]
Actually I take that back, the issue is not specific to snap packaging. The reason I wasn't seeing it locally was that my subuid range wasn't large enough to allow another level of shifting and an unhandled error here https://github.com/lxc/lxd/blob/b361dde6df5e7da01b27098461121cafd3485b07/shared/idmap/idmapset_linux.go#L476 was being silently ignored.

Setting my subuid/subgid to `root:1000000:1000000000` reproduces the issue locally too.

**Comment by tomponline** [comment]
@redno2 can you also provide output of 

```
lxc storage volume show lxd test-data
```

and

```
lxc storage volume show lxd test-data/snap0
```

**Comment by tomponline** [comment]
@stgraber so I think the issue here is that when restoring a custom volume snapshot, the lxc client PUTs to `/storage-pools/%s/volumes/%s/%s` with a `Restore` field but without any config, see https://github.com/lxc/lxd/blob/9f8f2f581224e93f3f45881bc6fc573e8a672116/lxc/storage_volume.go#L1623-L1625

Then the handler detects the `Restore` field and correctly restores the snapshot.

However it then goes onto apply the (empty) config that was supplied, see here https://github.com/lxc/lxd/blob/0280fa42f097dd960f7a76c1a8b9263a6e50e98f/lxd/storage_volumes.go#L960-L974

This removes the volatile keys from main volumes config, so the next time the volume is 'started' via an instance's disk device, it is then shifted again.

I see a couple of potential fixes for this:

1. Modify `storagePoolVolumeTypePut` in LXD to detect a non-empty `Restore` field and restore snapshot, but *only* apply config updates if the supplied `Config` field is non-nil when `Restore` is non-empty.
2. Update the LXD client to retrieve the volume's config (parent or snapshot volume config?) and submit that with the `Restore` PUT request so that it is applied afterwards.

**Comment by tomponline** [comment]
The PR above implements option 1.
