### ISSUE TITLE
Allow online growth of containers on LVM/Ceph

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#7867]
Currently growing a container backed by LVM or Ceph (block storage) requires a restart.
This should not be required so long as the container is backed by ext4 or btrfs.

We should check the filesystem and attempt a live resize if on ext4 or btrfs and only use the current behavior of doing it on next startup for filesystems which cannot be resized online (xfs).

**Comment by mattdombrowski21** [comment]
Hello, I am a student at UT Austin and am looking to contribute to this project. I see some of my classmates have contacted you already, and you went through and added a bunch of good issues that our groups can work on. My group would like to tentatively claim this one. Thank you!

**Comment by stgraber** [comment]
Sounds good, assigned it to you for now.

@tomponline should be able to provide more details on what needs changing to fix this issue.

**Comment by tomponline** [comment]
@mattdombrowski21 let me know when you are planning to make a start on this and I'll dig into the code and give you some more detailed instructions. Thanks

**Comment by mattdombrowski21** [comment]
@tomponline sorry for the late response, just now getting to this. We had a separate project that we had to finish before going on to this, but my group and I are ready to start working on this issue. Thanks

**Comment by tomponline** [comment]
@mattdombrowski21 Great! Searching the code base for `"apply_quota"` will be a good starting point to see how the current logic works today.

You will then see that if the `size` property of a disk gets updated on a running instance, the `d.applyQuota` function can return an error of type `storagePools.ErrRunningQuotaResizeNotSupported`. In this situation, the storage driver is indicating to LXD that it doesn't support live resize and LXD then records the requested size in a `volatile.<device name>.apply_quota` config key which is then applied the next time a container is started.

The `d.applyQuota()` function calls the `SetInstanceQuota()` function on the backendLXD https://github.com/lxc/lxd/blob/15be1123bc153b000df1e4494da496a1af8ff324/lxd/storage/backend_lxd.go#L1601, and it is here that the error type is returned after inspecting the storage pool driver's feature flags.

https://github.com/lxc/lxd/blob/15be1123bc153b000df1e4494da496a1af8ff324/lxd/storage/backend_lxd.go#L1607

Searching the code base for `ErrRunningQuotaResizeNotSupported` will also show you one other place where this logic is applied in `UpdateCustomVolume` https://github.com/lxc/lxd/blob/15be1123bc153b000df1e4494da496a1af8ff324/lxd/storage/backend_lxd.go#L2854-L2868.

This is to prevent custom volumes being resized while attached to running instances if the storage driver doesn't support it.

Strictly speaking this card doesn't cover the scenario of live-growing an attached custom volume, just a container's root disk, so if you get time we can discuss that scenario later.

So I think what we need to do here is to remove the check in `SetInstanceQuota()` for `RunningQuotaResize` and instead add detection in each driver that doesn't support running resize to detect if the volume is mounted in `SetVolumeQuota`. That way the driver will be able to decide whether it is growing or shrinking the container's filesystem, and if it is growing it and the driver supports it it can complete the request, and if not then it can return `ErrRunningQuotaResizeNotSupported`.

This will require moving the error `ErrRunningQuotaResizeNotSupported` into the `storage/drivers/errors.go` file and the references updated.

If I think of any more I'll add but that should be enough to get you started and having a look at the problem.

**Comment by tomponline** [comment]
This forum post (https://discuss.linuxcontainers.org/t/live-storage-volume-resize-error/9494) references this card as the new volume in-use detection added in LXD 4.8 is (correctly - as it currently stands anyway) preventing in-use custom volumes from being resize. However we should allow online growth for lvm/ceph custom filesystem volumes when in-use the same as we want to do for container volumes.

**Comment by tomponline** [comment]
@stgraber whilst working on https://github.com/lxc/lxd/pull/8163 to allow profile changes to disk size to be asynchronously applied to VMs it has also highlighted how the driver level `RunningQuotaResize` property is too coarse to be able to accurately represent the different scenarios and restrictions we have today.

My feeling on this is that we should remove the `RunningQuotaResize` field entirely from the `Info` struct (https://github.com/lxc/lxd/blob/master/lxd/storage/drivers/driver_types.go#L15) and instead rely on each storage driver's `SetVolumeQuota` function to either perform the resize or return an appropriate error.

In the case where a block volume is being shrunk they can continue to return `ErrCannotBeShrunk` as they do today.
And for cases where we do not allow the grow to take place when an instance is using the volume (either root or custom) the driver could detect this is in use by checking the mount reference counter is non-zero and then return `ErrInUse`.

The returned `ErrInUse` error could then be detected by disk device's `Update()` function and set the `apply_quota` key instead.

We could then also remove the `ErrRunningQuotaResizeNotSupported` error.

This would then allow each storage driver to:

- Fail shrink requests for block volumes, rather than delay the error until  `apply_quota` is applied.
- Reject grow requests for block volumes that are in use, triggering the  `apply_quota` to be set where relevant.
- Allow grow requests for filesystem volumes that are in use.
- Reject shrink requests for filesystem volumes that are in use, trigger the  `apply_quota` to be set where relevant.

WDYT?

**Comment by stgraber** [comment]
@tomponline sounds good to me

**Comment by tomponline** [comment]
@mattdombrowski21 I'm likely going to end up implementing this card by way of my other changes happening https://github.com/lxc/lxd/pull/8163

So I'll assign this one to me, are you OK to look at a different task? Thanks
