### ISSUE TITLE
do something nicer on setting/unsetting security.privileged

### ISSUE THREAD

**Issue by tych0** [lxc/lxd#787]
Right now, all this does is flip the bit in the DB. We should either: 1. ideally uidshift the whole fs when the bit is flipped or 2. fail to flip the bit after the fs is initialized so that people don't try and boot a container with e.g. files all owned by root or whatever.

**Comment by tych0** [comment]
And I guess this gets really complicated when you consider that profiles can affect this as well. Additionally, we should forbid changing this while the container is running (this also suggests a potential solution; remember the uid map the rootfs was created with, and compare it to the boot time uidmap, and if they're different, shift).

**Comment by stgraber** [comment]
Right, so I think the best way to solve this is by:
 - Introduce a new volatile.last\_state.idmap variable which contains a serialized version of our IdMap struct. This will be set every time the container starts.
 - If at startup, the value of volatile.last\_state.idmap differs from the one we're now running with, we'll shift the rootfs.
 - Idmap on the container struct should also be changed to reflect the current container idmap (parsing volatile.last\_state.idmap if set) rather than the next start idmap. This is required to ensure file pull/push uses the right uids/gids.
