### ISSUE TITLE
Bulk instance state change API

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#7934]
There has been interest in making `lxc start --all` and similar stop/restart/pause commands be handled server-side rather than client side.

This would also allow those to respect the `boot.autostart.priority`, boot.autostart.delay` and `boot.stop.priority` properties either out of the box or when provided an extra flag.

The current plan is to implement this through `PUT /1.0/instances` taking a struct similar to that we use for `PUT /1.0/instances/NAME/state`.

**Comment by turtle0x1** [comment]
Will LXD safely skip or "throw an exception" if for example I try to stop a stopped instance? In the case of the exception is the whole operation "transactional"? (I.E do you check and throw before you actually start  any instances?)

The reason I ask is because if you "throw an exception" with out transactions it means some clients may have todo all the logic checks anyway at which point, how hard is starting an instance?

Will this take a list of instance names or just try to start / stop everything? because if the clients could just provide the names it would be a more useful "bulk" API (to my mind)

**Comment by stgraber** [comment]
Initially we'd just have it behave as we need for `--all` in start/stop/restart/pause so it would behave the same way, that is, select instances in a suitable state and perform the action on those. The only case where you'd get an error is if the action fails, instances already in the target state will not cause errors.

I think it would however be useful to expand this API later on to support server-side filtering similar to that we have on `GET /1.0/instances` in which case that filter would be applied to the list of operations needing a state change.

So I still wouldn't expect you to ever get an error because of instances already in the target state, I would only expect an error to be thrown if one or more instances fail to reach the requested state.

**Comment by kevtheappdev** [comment]
My team and I interested in pursuing this one if possible!

**Comment by stgraber** [comment]
Assigned!
