### ISSUE TITLE
lxd cluster

### ISSUE THREAD

**Issue by kamzar1** [lxc/lxd#7941]
Is there a way to remove/disable/dissolve cluster?
I mean not the single nodes, but the whole cluster which was enabled?
It actually competes with:
1. pure lxc command (lxc command [remote:]
2. lxd api (curl remotehost:8443/... command)
3. ssh remotehost lxc command...
which do not require complex configurations and homogeneous iface/bridge storage pools ... 
without any visible advantage, beside using a centralized dqlite.db
And for that above advantage which could eventually been done externally by any database, it adds layers and layers of additional configuration and possible failures making the whole construct useless.
It has not a smart resource control (Node CPU, storage, weight ...)

**Comment by stgraber** [comment]
No. The LXD database goes through irreversible changes when clustering is enabled which is why there is no disable option in `lxc cluster`.

You can shrink it back down to a single node but you can never change a node address as that's part of the disturbed log that backs the database.

And yes, for some having multiple standalone LXD servers and using them as distinct remotes is a better solution.

Clusters are really meant for cases where you have pretty uniform systems and want to easily spread many instances on those. It avoids having to sync your profiles and other configs on all systems and makes things like project limits apply across multiple systems.
