### ISSUE TITLE
Implement `HEAD` for file transfer API

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#8019]
When using the files API it would be nice to know if a entry is a "file" or "directory" otherwise you have to download the entry to find out - which is obviously "expensive"

The use case is fairly obvious but when listing directory contents in a "view" (webpage) for a user its best to indicate the "entry type"

_Ignore the poor ordering_

![lxd](https://user-images.githubusercontent.com/12494629/95662980-06c8e980-0b33-11eb-8c72-9d586f27840d.png)

**Comment by stgraber** [comment]
Originally I was going to punt that to a wider rework of the file API where we would ideally implement a full webdav-ish (ideally compatible) endpoint but after thinking about it some more, I think we can at least do something more sane for both listing and getting file information by implementing the `HEAD` method in the file API.

This is a method we've never used within LXD so will need a tiny bit of low level work for that but it should then let us have a dedicated method for fetching information about paths rather than the paths themselves.

I'd then expect `HEAD` to always return JSON with the ability to give us a whole bunch of information on the path itself and if it's a directory, allow for fetching details on its descendants.

**Comment by stgraber** [comment]
@brauner something for you to think about, can you think of a more flexible way for LXD to perform file operations inside a container?

Right now we have one `forkfile` type call for each operation, requiring dedicated C logic for everything we do in there.

It would be quite neat if we could instead have a single Go `forkfile` codepath which would take in a communication fd and provide a REST API on it (kinda like the agent), then LXD itself would just forward the user's request over it, limiting the amount of glue code involved for this.

It would also then let us implement things like recursive pull/push using a single API call and multi-part file transfers and have LXD spawn a single process for the entire operation.

Think that can be done safely?

**Comment by turtle0x1** [comment]
You've made my heard hurt

As long as you return `isDirectory`~ json key i could care less
