### ISSUE TITLE
lxc move need to check origin container DELETE permission before execution

### ISSUE THREAD

**Issue by diegomontoya** [lxc/lxd#8075]
db is on storage1 and security.protection.delete set to true.

I want to move db to storage2
```
lxc move db db-2 -s storage2
Error: Failed to delete original instance after copying it: Container is protected
```
There is nothing wrong with the error but lxc on MOVE command should first check the orginal container can be deleted before doing the COPY then DELETE operation. Otherwise, DELETE may fail which is not good usability-wise.

**Comment by stgraber** [comment]
The issue is that `lxc move` is just expanded in the API as `lxc copy` and `lxc delete`.

That said, we can have the client unset security.protection.delete before deleting the container following the copy operation. We don't really like having to make the client do that kind of trick, but it should be fine in this case.

**Comment by diegomontoya** [comment]
I am against this bypass for the reason that `security.protection.delete=true` should be treated as a immutable state that should be honored when any attempt to delete is performed on the container. Would rather have `lxc move` stop execution when it encounters the security bit=true. 

Having  `security.protection.delete=true` is a true piece of mind and safety guard for critical data since lxd is so easy to use which leads to accidental commands. 

If it can be bypassed with explicit toggle then there is a hole in the security.protection concept.

**Comment by diegomontoya** [comment]
`lxc move` is expansion to `lxc copy` AND/&& `lxc delete`. It can be argued that the 2 commands must execute successfully in a serial fashion. However, If the second command is guaranteed to fail, the first expanded command should not execute. As in this case where `lxc move` encounters the security bit.

**Comment by stgraber** [comment]
The fact that move is implemented as copy+delete is an implementation detail. As far as the user is concerned, the data was moved and therefore never deleted, so the deletion protection should not kick in.

We actually have alternative APIs that get used during move in some environments which already will not fail because of this config option (as they don't call the delete API), so this change will make things consistent.

The config key is meant to prevent accidental user deletion of the instance. It's quite hard to do an accidental move and even if you do, no data was lost, you can just move it back.
