### ISSUE TITLE
missing /boot/config-5.4.0-52-generic in container

### ISSUE THREAD

**Issue by srkunze** [lxc/lxd#8107]
Using the following versions in Ubuntu 20.04 (fresh install) and installing Kubernetes in a LXD container, I found
`/boot/config-5.4.0-52-generic` to be missing.

```
srkunze@mexico:~$ lxc --version
4.7
srkunze@mexico:~$ uname -r
5.4.0-52-generic
```

Current work-around:
```
lxc file push /boot/config-5.4.0-52-generic k8s-lxc/boot/config-5.4.0-52-generic
```

**Comment by stgraber** [comment]
This file ships with the kernel packages, containers don't run kernels and therefore do not have the package installed.
So this is really expected behavior.

Whatever software thinks it needs this is likely flawed in some way. A workaround like the one you used will only work until the next update of the host kernel.

**Comment by srkunze** [comment]
Alright, thanks for that clarification and good point regarding the update of the host kernel.

I will raise this issue then to kubernetes to make them aware of it.
