### ISSUE TITLE
lxd launch --vm should wait for lxd-agent to be ready before returning

### ISSUE THREAD

**Issue by paride** [lxc/lxd#8148]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 21.04 (devel)
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.8.0-25-generic
   * LXC version: 4.7
   * LXD version: 4.7
   * Storage backend in use: zfs

# Issue description

Currently when `lxd launch --vm` returns there's not guarantee that the VM is already reachable via `lxd-agent`. When using LXD interactively this means that one should try `lxc exec` several times before being able to proceed (poor UX). In automation this translates in polling loops that do basically the same. I understand there isn't really a better way then polling, but then I think this polling should be done by LXD itself and hidden from the user/consumer. 

The polling loop is not immediate to do right, as sometimes right after a VM launch `lxd-agent` becomes reachable for a short moment, then unreachable again, and then finally up for real (see "steps to reproduce" below). This causes issues in automation and working around it with an arbitrary `sleep` feels wrong. Another good reason to have a solid wait logic implemented on the LXD side.

# Steps to reproduce

```
$ lxc launch --vm ubuntu:focal paride-f-vm
Creating paride-f-vm
Starting paride-f-vm

# Nice! VM is up?

$ lxc exec paride-f-vm uptime
Error: Failed to connect to lxd-agent
$ lxc exec paride-f-vm uptime
Error: Failed to connect to lxd-agent
$ lxc exec paride-f-vm uptime
Error: Failed to connect to lxd-agent
$ lxc exec paride-f-vm uptime
 10:29:50 up 0 min,  0 users,  load average: 0.00, 0.00, 0.00

# There, it's up! But let's check again:

$ lxc exec paride-f-vm uptime
Error: Failed to connect to lxd-agent

# It's down again :(

$ lxc exec paride-f-vm uptime
Error: Failed to connect to lxd-agent
$ lxc exec paride-f-vm uptime
Error: Failed to connect to lxd-agent
$ lxc exec paride-f-vm uptime
 10:30:02 up 0 min,  0 users,  load average: 0.00, 0.00, 0.00
$ lxc exec paride-f-vm uptime
 10:30:04 up 0 min,  0 users,  load average: 0.08, 0.02, 0.01

# Now it's up for real.
```

**Comment by stgraber** [comment]
This is not really any different than waiting for networking or cloud init to complete with containers.

Not all VM images will have the agent running either and more importantly, LXD has no idea when the agent is ready.

The agent responding and then going away in your case is most likely because the VM rebooted to do a clean cloud-init run.

I'll take a quick look at that part of the logic as we may be able to prevent the agent from answering in that case.

**Comment by tomponline** [comment]
@stgraber could we add something to the `lxc info <vm>` command showing that we have an lxd-agent connection?

**Comment by paride** [comment]
@stgraber one difference with waiting for network/cloud-init is that in those cases it's easy to wait for them:
```
lxc exec <container> systemctl is-system-running --wait
# or:
lxc exec <container> cloud-init status --wait
```
What would you think of a `lxc launch --wait` flag that *makes documented assumptions* on the container/vm (like: has systemd, has lxd-agent, ...)

**Comment by stgraber** [comment]
@tomponline we already have that to some extent, PID is -1 until we have an agent.

@paride as I said, LXD has absolutely no idea when the agent is ready and with instances like Windows, MAAS, ... it actually never will be. Having LXD keep poking those instances indefinitely would be a waste of time and resources.

Having to wait for something to respond is a pretty normal thing to do when interacting with virtual machines or the cloud, LXD is far from being unique there.

The main issue here is that the agent was responding and then went away and came back. This is because of the reboot we're doing to workaround cloud-init's lack of native LXD support but we need to fix the agent so that it doesn't actually accept requests on that first startup.
