### ISSUE TITLE
Empty devices

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#8166]
When you `GET` an instance with no devices you get an empty `devices` key, if you try to `PUT` that empty `devices` key back you get something like;

```
cannot unmarshal array into Go struct field InstancePut.devices of type map[string]map[string]string
```

This is a mild annoyance because you have to remove the empty `devices` key despite LXD giving it to you (ive seen in other comments you tend to `omit` keys not set by the user)

It would be good if LXD could just silently ignore the empty `devices` as removing it altogether is probably a non-starter

**Comment by stgraber** [comment]
I think it's a problem in your logic.

I can reproduce your error with:
```
stgraber@castiana:~$ lxc query /1.0/instances/test -X PUT -d '{"architecture": "x86_64", "profiles": ["default"], "devices": []}' --wait
Error: json: cannot unmarshal array into Go struct field InstancePut.devices of type map[string]map[string]string
```

But that's because my input is invalid, `devices` is a map/dict, not a list.

All of those succeed:
 - `lxc query /1.0/instances/test -X PUT -d '{"architecture": "x86_64", "profiles": ["default"]}' --wait`
 - `lxc query /1.0/instances/test -X PUT -d '{"architecture": "x86_64", "profiles": ["default"], "devices": null}' --wait`
 - `lxc query /1.0/instances/test -X PUT -d '{"architecture": "x86_64", "profiles": ["default"], "devices": {}}' --wait`

**Comment by turtle0x1** [comment]
Ah yeah PHP

Sorry!
