### ISSUE TITLE
Failed instance creation: Unknown configuration key: volatile.uuid

### ISSUE THREAD

**Issue by jamielsharief** [lxc/lxd#8265]
Ubuntu 20.04
LXD 4.9 (VirtualBox)
ZFS storage pool on a custom partition 

Steps: I create an Alpine container, stop it, and then try to move it

```
$ lxc launch images:alpine/3.11/amd64 c2
$ lxc stop c2
$ lxc move c2 server2:c2
```

I get the error 
`Failed instance creation: Unknown configuration key: volatile.uuid` 

Looking at the [source code](https://github.com/lxc/lxd/blob/master/lxc/move.go#L193) for `move`  it says *keep the volatile entries*  and the `--debug` shows that it is sending it . When using the API I have to remove those for it to work.

Yesterday I also ran into random errors with with `Error transferring instance data: Unknown configuration key: volatile.uuid` and it turns out my ZFS store was getting locked, and i had to restart.  I thought I caused this by using CTRL-C in the command line when trying to copy or move.

I am not sure if this is related but the errors were similar. Previously my code was working through the API, but i was not using a custom ZFS storage pool. I just saw on discuss that 4.9 was released yesterday so i thought I would post here.

**Comment by stgraber** [comment]
LXD does not support moving instances from one server to an older server.

**Comment by stgraber** [comment]
To be a bit more verbose, you're getting this error because the server you're moving the instance to does not know about `volatile.uuid` which is a new internal configuration key that we recently introduced.

Copying from an older server to a newer one will work fine and we'll sort any issue in that direction, but going to an older version gets you into the same kind of issue as trying to downgrade LXD.

Note that it really depends on the releases. Most of the time unless you're using the latest bleeding edge feature, such a copy will succeed, but whenever we introduce a new key on all instances, as is the case here, then you get in trouble :)

**Comment by jamielsharief** [comment]
Thanks for the explanation, I must of upgraded one of the test servers yesterday.
