### ISSUE TITLE
Give a way to tell from `lxc config` and `lxd init --preseed` if any configuration changed

### ISSUE THREAD

**Issue by strk** [lxc/lxd#8282]
It would be useful to know, when configuring LXD (via `lxc config` or `lxc init --preseed`) if any configuration setting really changed. Right now the only way to do that would be saving `lxd init --dump` output to a file before and after a change, to check if anything changed (and would still fail to determine if the `core.trust_password` configuration changed.

**Comment by stgraber** [comment]
Your best bet if you need to automate something like this through LXD is to do:
 - GET /1.0/whatever
 - Retrieve the ETag value
 - Determine if you want to change something
 - If you do, push change with ETag value
 - LXD will apply the change or if something changed in between will reject it due to ETag mismatch

At that point you'll know that any change you request has been applied and the state matches yours.

For other update commands, LXD doesn't actually perform any comparison, it clears its state and puts the new state in.
Similarly for the password, LXD sends the password through a hashing algorithm and stores it that way without ever pulling the previous value and never retaining the clear text value.

Closing as it's not something that LXD was ever meant to provide, the API design doesn't really allow for it and nor does the server side config handling.
