### ISSUE TITLE
cannot compile lxd 4.0.4: dependency problem with qmp: please add explicit dependency tracking

### ISSUE THREAD

**Issue by muir** [lxc/lxd#8293]
# Required information

 * Distribution: Ubuntu 20.04
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version: n/a
   * LXC version: 4.0.4
   * LXD version: 4.0.4 
   * Storage backend in use: n/a

# Issue description

Cannot build from source: dependency go-qemu/qmp has changed APIs:

```
lxd/instance/drivers/qmp/monitor.go:121:31: not enough arguments in call to m.qmp.Events
        have ()
        want (context.Context)
```

# Steps to reproduce

```
LXC_VERSION=4.0.4
export GOPATH=$HOME/LXD
mkdir -p $GOPATH/src/github.com/lxc $GOPATH/bin

cd $GOPATH/src/github.com/lxc
git clone https://github.com/lxc/lxc.git
cd lxc
git checkout tags/lxc-$LXC_VERSION
./autogen.sh && ./configure && make && sudo make install

cd $GOPATH/src/github.com/lxc
git clone https://github.com/lxc/lxd.git
cd lxd
git checkout tags/lxd-$LXC_VERSION

```

Now cut'n'paste those `export` commands. 

Then

```
CGO_CFLAGS="$CGO_CFLAGS -I/usr/local/include"
GO_LDFLAGS="$CGO_LDFLAGS -L/usr/local/lib"
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"

make
```

This kind of dependency problem can be avoided if lxd included explicit dependency tracking and shipped with `go.mod` and `go.sum` files...

So consider this issue to be to add explicit dependency tracking so that every released version continues to be able to be compiled.

**Comment by stgraber** [comment]
Our official release tarballs include the dependency tree.

**Comment by muir** [comment]
@stgraber For my immediate uses, the tarball is fine.  However, if anyone wanted to build on top of LXD in Go, then including dependency information becomes very useful.

**Comment by drybjed** [comment]
I also encountered this problem while investigating why my build of LXD from source code stopped working.

I'm building the LXD binaries on Debian Buster based on the cloned git repository of the codebase. For some time now I've been using the `stable-4.0` branch since the [4.0.1 release had broken dependencies](https://github.com/debops/debops/commit/9341c1c2eec773b8c677e98dd8acb54c38af1482). The cloned code is verified using the @stgraber's GPG signature. However recent commits on that branch from about 3 days ago were signed by the GitHub Automatic Signing Key, which broke the build scripts. After trying the `lxd-4.0.4` tag I encountered the problem mentioned in this pull request.

I'm not sure how to solve this problem in the long term. Sudden change in @stgraber's habits might indicate tampering, or might be benign. I understand that signing each commit properly is cumbersome, but since GPG signing is used to verify integrity, any deviation in such important element is a cause for concern. An alternative is to depend on signed git tags for verification, but these releases have broken dependency information. If that's not somehow resolved, I'm not sure on what I can base the trust chain while building LXD. Using release tarballs is less convenient than single `git clone` command which supports automatic GPG verification.

@stgraber, do you have any plans to provide the dependency information in the future LTS releases of LXD?
