### ISSUE TITLE
LXD device nic add routed ipv4(6).address (comma delimited list) should check for duplicates 

### ISSUE THREAD

**Issue by diegomontoya** [lxc/lxd#8341]
Version: lxd snap 4.10

The ipv4(6).address list should be error checked for uniqueness. Otherwise, really bad things can happen. 

We made a mistake and added around 40 ips as list with about  6 out of 40 as duplicates by mistake and this server/network pretty much went down. Not sure if arp storm, due to conflicting ips was cause but it was so bad and so sudden we dare not to try again unless in a lab. It was our fault to begin with but I believe lxd can help prevent this serious network issue.

Currently LXD allows the following which may kill the local server network and even affect neighboring ports. 

```
lxc config device add c1 eth0 nic nictype=routed parent=en0 ipv4.address=ip1,ip2,ip3,ip1,ip2,ip3
```

Proposed fix:

Unique check ipv4(6).address and throw error if duplicate is found. Do not allow this dangerous config to be saved.

**Comment by stgraber** [comment]
@tomponline guess we should extend the checks in `validate` to look for duplicates?

**Comment by tomponline** [comment]
@stgraber @diegomontoya Yes it makes sense to extend the validation to improve the user experience. However I've not been able to reproduce the issue reported above. 

When I tried adding duplicate IPs the container failed to start because it couldn't add the duplicate static route on the host (which makes sense).

That being said it did appear to leave the ARP proxy entries on the host, so perhaps that causes a broadcast storm, although not something I've been able to reproduce.
