### ISSUE TITLE
Cluster in broken state after a single snap failed to upgrade

### ISSUE THREAD

**Issue by vosdev** [lxc/lxd#8388]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: Linux node1 5.4.0-64-generic #72-Ubuntu SMP Fri Jan 15 10:27:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
   * LXC version:
   * LXD version: 4.9 > 4.10
   * Storage backend in use: ceph

# Issue description

Hey guys,

A few weeks ago I found my cluster in a completely broken state. Unfortunately I did not keep a copy of the logs at the time or raised an issue here right away but I decided to post the details from memory.

Snap updated my cluster to 4.10 but failed doing so on node1 (The cluster leader). The LXD daemon exited on node1 (master) and failed to start afterwards because the database scheme did not match. `sudo snap refresh --list` stated 4.10 was available, `snap refresh lxd` did not update the snap.

Node2 and node3 successfully updated to 4.10, their logs stated they were both waiting on node1 to come up for almost 12 hours.

The issue was resolved by restarting snapd, the lxd snap was immediately updated to 4.10 and my cluster came back online. 

The problem with this situation is that both node2 and node3 were waiting for nearly 12 hours for node1 to come up and probably continued to do so if I did not fix the issue manually. Node2 and node3 form a majority yet did not try to take lead in the cluster.

Is there a logical order issue when upgrading a cluster or is this just bad luck :-)

**Comment by stgraber** [comment]
This is unfortunately expected behavior. The LXD DB schema isn't backward compatible, so we can't allow an older server to still interact with the database. Patches applied during a major upgrade may also affect multiple servers, especially in the case of data migration when shared storage or networking is used.

As a result, when a DB change is performed or when a new API is introduced (LXD doesn't actually care about the version), we require all servers to be at the same level before any of the APIs become accessible again.

We have daily cluster upgrade tests to validate that things go smoothly and LXD has logic to effectively self-refresh so you don't need to wait for snapd to trigger a daily refresh on each of the systems. Whenever the first one refreshes, all the others will run a local `snap refresh lxd` to match the version.

In your case, it sounds like the issue ended up being a snapd bug holding up one of your servers...

To make things smoother, you could decide to do the major version upgrades by hand by using one of the versioned channels rather than latest. Some details can be found here: https://discuss.linuxcontainers.org/t/managing-the-lxd-snap/8178
