### ISSUE TITLE
Docs: Poor example to get a shell

### ISSUE THREAD

**Issue by danboid** [lxc/lxd#8402]
I was looking at the LXD quickstart guide today:

https://linuxcontainers.org/lxd/getting-started-cli

The example command given in the section to get a shell inside a running container seems like a poor example to use:

https://linuxcontainers.org/lxd/getting-started-cli/#shellterminal-inside-container

```
Get a shell inside a container:

lxc exec instancename -- /bin/bash
```

Surely using:

```
lxc shell instancename
```

Instead is easier to read, understand, type and remember?

**Comment by stgraber** [comment]
Yes and no. `lxc shell` is a convenience built-in alias which will only work with images that ship a working `su` command have have a proper PAM stack. It may also result in the environment getting reset depending on PAM settings.

As a result we never use it in our tests or documentation because it will not work with all images and its behavior as far as environment is dependent on the image.
