### ISSUE TITLE
Improve image refresh in a cluster

### ISSUE THREAD

**Issue by monstermunchkin** [lxc/lxd#8436]
In a cluster, whenever there's an image which can be refreshed, the new image is downloaded by all nodes that need it. We should improve that logic by having only one node download the new image. That node should then push the image to the other nodes.

**Comment by stgraber** [comment]
The ultimate test for this should be:
 - Setup a 3 nodes cluster
 - Set image replication to just one node (to make it easier to see what's going on)
 - Make sure storage is provided by something with optimized volumes (not `dir`)
 - Create 3 projects: a, b and c
 - Configure a working default profile in all 3
 - Copy images:FINGERPRINT into all 3 projects (use the fingerprint of an old image in `images:`)
 - Create a container from the image in all 3 projects, one instance will go on each system and optimized volumes will get created
 - Alter the DB record of the image in project a and project c so it has a valid source and has the auto-update flag enabled
 - Reduce the image refresh delay to the minimum
 - Wait for it to kick in and see what happens

What should happen is that only a single server will process the image, despite it having separate records in 3 projects with different config, it's still the same image. That one server needs to fetch the image to disk, needs to identify what other servers need the image, in this case, only the first and third servers, the second server has the instance and image from project b only and that one wasn't altered to update, so there's no reason for it to receive the update. For those that need to get the updated image, the source server will send them the image through `POST /1.0/images` and then send an internal query to have the image loaded on the storage pools where it's needed. If the old image is no longer relevant, the source server will then send a DELETE request for that image to the target server.

So in short, the source server does all the figuring out of the update. For that one fingerprint it's processing, it's getting all the DB image records, identifies any that have a source and auto-update flag, see if that source image has changed and if it does, will deal with retrieving it. Once it has it, it tracks down the affected systems and makes sure that they get that image too. It then does the DB record replacement for the affected projects, moving the existing config/profiles over to the new image and if now unused, deleting the old one.

The only thing that the other servers do in this is receive a `POST /1.0/images` from the source server to receive the new image, receive a `POST /internal/image-optimize` (or whatever we call it) to be told what storage pool the image needs to be loaded onto and then receives a `DELETE /1.0/images` if the old image is unused and must go away from disk. No DB operations should be performed from a target server, all of them should be handled by the source directly.

@monstermunchkin does that make sense? Our current logic is quite messy so getting a reliable test environment where you can easily add debugging statements and run through the update will be quite useful. I'd also recommend adding a temporary /internal API to manually trigger the image auto-refresh function so you can just `lxc query` that instead of waiting an hour ;)

@tomponline how does that sound to you?

**Comment by tomponline** [comment]
@stgraber this makes sense, as you say its pretty complicated so would be good to have an automated test for the scenario (even if its just a jenkins CI script and not a test).

Also, what does "Set image replication to just one node (to make it easier to see what's going on)" mean?

Would you expect multiple calls to `POST /internal/image-optimize` one for each pool where the image volume exists or have the target server work out which pools have the image locally?

**Comment by monstermunchkin** [comment]
> Also, what does "Set image replication to just one node (to make it easier to see what's going on)" mean?

@tomponline I guess that means setting `cluster.images_minimal_replica` to `1` (it defaults to `3`). It describes the minimal numbers of cluster members with a copy of a particular image.

**Comment by stgraber** [comment]
Oops, I'm two weeks late to this question, but yes, I meant reducing minimal_replica to 1.
