### ISSUE TITLE
Blocksize incorrectly reported on IBM Z

### ISSUE THREAD

**Issue by ltrager** [lxc/lxd#8477]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-65-generic
   * LXC version: 4.0.5
   * LXD version: 4.0.5
   * Storage backend in use: N/A

# Issue description

I am working on enabling IBM Z for MAAS. LXD is reporting the block size on all devices as `2199023255552` which is obviously incorrect. I suspect the block size isn't getting detected so LXD is returning the value as undefined. LXD should either return the correct value or nothing.

# Steps to reproduce

 1. Get access to an IBM Z partition in DPM mode
 2. Gather system resources from LXD
[ibmz.log](https://github.com/lxc/lxd/files/5999566/ibmz.log)

**Comment by stgraber** [comment]
weirdly enough, the ioctl we're sending looks correct and is getting 512 back from the kernel, it's something after that, possibly in Go's handling of the syscall that's turning it into garbage.

**Comment by stgraber** [comment]
yep, pretty sure it's a bug in `unix.IoctlGetInt` not a bug in our code...

**Comment by stgraber** [comment]
Re-implemented this thing through a direct syscall using the correct type, this should fix it on all big endian systems.

**Comment by frank-heimes** [comment]
If unix.IoctlGetInt has a problem that occurs on big endian systems only, i.e. on s390x, we can also open a LP bug and ask IBM to have a look at it and to get it fixed upstream.

Btw. the blocksize on s390x depends on the storage in use and there are largely two kinds of storage:
zFCP storage (which is virtually SCSI) will be (as usual) 512 (and zFCP is what ltrager is using),
but there is also DASD storage that has 4096 by default.

**Comment by stgraber** [comment]
So I don't think it's actually a big in that Go package, it's just confusing behavior on big endian systems that will likely hit a bunch of other people :)

The issue is that the common function to run an Ioctl from Go stores all results into an int64, regardless of what type integer the kernel actually returns.

That's harmless on little endian systems but in big endian systems this causes a completely wrong value.

One way around this would be for the Go Unix package to offer a 32bit version of that Ioctl function so one can use that instead in such cases. The problem then will be for developers to know when to use it as it's far from obvious what type to use for what Ioctl...

**Comment by frank-heimes** [comment]
Ok, understood.
Well, such kind of things are typical big endian 'challenges'.
Thx for dealing with it (in #8478)!
