### ISSUE TITLE
Implement ACL's with disk devices and add a create_cmd

### ISSUE THREAD

**Issue by pcdummy** [lxc/lxd#850]
When i create a new container with lxd i do the following:

```
lxc init ....
sudo btrfs subvolume create /cdata/<hostname>
sudo setfacl -Rm user:lxd:rwx,default:user:lxd:rwx,user:10000000:rwx,user:10001000:rwx,default:user:10000000:rwx,default:user:10001000:rwx,mask:rwx /cdata/<hostname>
lxc config device add srv01:<hostname> mntdir disk source=/cdata/<hostname> path=data
```

It would be nice when LXD will do the ACL and the btrfs subvolume thing here.

I think of:

```
lxc config device add srv01:<hostname> mntdir disk source=/cdata/<hostname> path=data create_cmd="btrfs subvolume create /cdata/<hostname>;  setfacl -Rm user:lxd:rwx,default:user:lxd:rwx,user:10000000:rwx,user:10001000:rwx,default:user:10000000:rwx,default:user:10001000:rwx,mask:rwx /cdata/<hostname>"
```

Refs issue: #714 and #733

**Comment by stgraber** [comment]
Would have to think a bit more on that one. I'm usually against having any kind of interface allowing our users to run code as root directly from the API. The main reason for that is that we expect there will be other implementations of the LXD API, on other OSes or inside very limited environments, so raw command execution as root tends to be awfully brittle.

**Comment by pcdummy** [comment]
Your right, we don't want someone to execute an arbitrary command as root with only access to the API.
Can we add an option for UIDs we want recursive ACL's and maybe another for creation method (btrfs subvolume or mkdir at the moment)?

**Comment by rhass** [comment]
Just a thought, but maybe a thin FUSE overlay wrapper could be implemented to do this and run as a non-root user.

**Comment by stgraber** [comment]
Going to close this one as we've not seen much more need for this in general and don't like allowing for arbitrary root commands to be run on the host through the remote API.

The uid/gid part of this which at the time could only really be dealt with through filesystem ACLs is I believe better handled through shiftfs these days which is now available on Ubuntu systems and for other distributions that carry those patches or package it as a dkms module.

We're also actively working on getting this feature integrated in the upstream kernel as part of the VFS layer so that we can soon rely on it on all distributions.
