### ISSUE TITLE
HDD RPM not reported correctly for LXD server by resources API

### ISSUE THREAD

**Issue by szeestraten-ntnu** [lxc/lxd#8718]
# Required information

 * Distribution: `Ubuntu`
 * Distribution version: `20.04.2 LTS`
 * The output of "lxc info": https://paste.ubuntu.com/p/VHsx2njqBy/
   * Kernel version: `Linux hcc-store33 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
   * LXD version: `4.13` (`git-ee6eda2` from snap)

# Issue description

The [resources API](https://linuxcontainers.org/lxd/docs/master/rest-api#10resources) is incorrectly reporting HDDs with RPM `0`, instead of the correct value of `7200`. I am not sure how/why this does not work, but I have tested with `latest/edge` LXD snap.

The resources API is being used by MAAS commissioning to identify and populate storage information which leads to incorrect values and assumptions that the disks are SSDs rather than HDDs. See MAAS bug: https://bugs.launchpad.net/maas/+bug/1921475 for more information.

# Steps to reproduce

* Install LXD
* Query `lxc query /1.0/resources | jq .storage.disks[-1]`
* Get output with `"rpm": 0`

# Information to attach

* Output of [`lxc query /1.0/resources`](https://paste.ubuntu.com/p/cw4vVS2SG6/) which shows RPM of `0` which is incorrect
* Output of [`lshw`](https://paste.ubuntu.com/p/jxdbtf8gM5/) which shows RPM of `7200` which is correct

**Comment by stgraber** [comment]
```
root@athos:~# lxc query /1.0/resources | grep "rpm"
				"rpm": 0,
				"rpm": 0,
				"rpm": 5700,
				"rpm": 5700,
				"rpm": 5700,
				"rpm": 5700,
				"rpm": 0,
				"rpm": 0,
				"rpm": 5700,
				"rpm": 5700,
				"rpm": 5700,
				"rpm": 5700,
```

So doesn't appear broken here.

**Comment by stgraber** [comment]
Can you show:
 - `ls -lh /run/udev/data/`
 - `cat /run/udev/data/b8:192`

**Comment by szeestraten-ntnu** [comment]
Hi @stgraber, thanks for taking the time! See links below for requested output:
* [`ls -lh /run/udev/data/`](https://paste.ubuntu.com/p/4cnHFsqm5m/)
* [`cat /run/udev/data/b8:192`](https://paste.ubuntu.com/p/Fnpvb6Tjmz/)
* [`udevadm info /dev/sdm`](https://paste.ubuntu.com/p/FDFsspvmv8/)

P.S. Had to redeploy machine, but devices should hopefully be the same.

**Comment by stgraber** [comment]
LXD relies on udev having the proper `E:ID_ATA_ROTATION_RATE_RPM` property set.
In your case, udev did not detect the RPM for your drives and so LXD doesn't have it either.

Closing the issue here as we need udev to be reporting this data properly before LXD can expose it.

**Comment by stgraber** [comment]
You should file a bug against systemd in Ubuntu and ideally test with the very latest version to see if that got resolved and would just need a cherry-pick. If not, then the systemd maintainers should be able to help you get a suitable trace from udev to figure out why it can't get the RPM speed on that device.

**Comment by ddstreet** [comment]
@stgraber systemd doesn't report ATA parameters for SCSI drives, only for (S)ATA drives. You won't see the 'E:ID_ATA_ROTATION_RATE_RPM' udev property for a scsi (or sas) drive.

**Comment by ddstreet** [comment]
udevd exposes it for ata devices because the atapi identify device command provides the rotational state in the response, while the scsi inqury only gets pages 0x80 and 0x83, neither of which provide the device rotational speed. The scsi_id built-in command would need to also query page 0xb1 to get the block device characteristics, which includes the rotational speed. This would need to be added to upstream systemd as a new feature.

The kernel does (kind of) provide rotational info for block devices, at /sys/block/$DEVICE/queue/rotational, however that is RW. Not that anyone should be manually setting the rotational flag for their block device queue, but it's possible.

**Comment by stgraber** [comment]
Ah, could you show `/sys/block/*/queue/rotational` on a few systems (ideally with mix of drive types) so we can see how feasible it would be to read that as an alternative source for the RPM value?

**Comment by ddstreet** [comment]
Here's one system with nvme, SAS drives, nvme-sata, dvd, raid, and lvm:

https://pastebin.ubuntu.com/p/9C9FTBfzpv/

and another with nvme, sata-sdd, sata-drives, dvd, raid, and lvm:

https://pastebin.ubuntu.com/p/DmkDv9qKhN/

**Comment by stgraber** [comment]
Ok, so that's unfortunately not providing us with the actual RPM.

I guess what we can do is report an RPM of 1 if we don't have a value from udev and the drive is rotational.
It's obviously a bit of a lie, but less of a lie than 0 I guess ;)

**Comment by ddstreet** [comment]
Also if you have hdparm and sdparm installed on the system, you can use those to get the rotational rate, since they support all parts of the ata (hdparm) or scsi (sdparm) protocols, e.g.:

For ATA drives, using the standard rotation rate field in the normal inquiry data:
$ sudo hdparm -I /dev/sde | grep 'Rotation Rate'
	Nominal Media Rotation Rate: 5400

For SCSI drives, using the older (obsolete) rigid disk page MRR field:
$ sudo sdparm -p 0x04 /dev/sda | grep MRR
  MRR           7200  [cha: n, def:7200, sav:7200]

or the newer VPD block device characteristics page rotation rate field:
$ sudo sdparm --inquiry -p 0xb1 /dev/sda | grep 'rotation rate'
  Nominal rotation rate: 7200 rpm

but of course it those might not be installed, and it would be better if udevd's scsi_id could just add support for reading the VPD block characteristics page and add udev properties.

**Comment by stgraber** [comment]
hdparm/sdparm both issue ioctl to the disk so won't typically work unprivileged and rely on the drive controller answering making them costly calls that could hang should the drive be busy or in a bad state.

Given how often the resource API logic may be called, it's something we'd like to avoid doing.
