### ISSUE TITLE
adding new network device does not show up inside guest/container

### ISSUE THREAD

**Issue by kkptNinja** [lxc/lxd#873]
Hi,

I am using ver 0.13 of lxd and have been trying to add a nic device to a container to no avail. This is what I have done:

`$ lxc config device add p1 p1-eth1 nic nictype=bridged parent=lxcbr0` 
`$ lxc restart p1`

Then, when i check the outcome:

`$ lxc exec p1 ls /sys/class/net`
`eth0  lo`

I have tried to examine the situation on the host by inspecting the net namespaces with `$ ip netns list` but that commands returns an empty list. I am out of ideas and was wondering if someone would how i could troubleshoot this situation?

Thanks in advance

**Comment by stgraber** [comment]
Try stop and start instead of restart.

Restart only sends a signal to the container, asking its init system to restart the container, this doesn't go through the configuration codepath.

We've got a couple of issues related to live updating of container configuration which once implemented will make such changes apply to the container immediately.

**Comment by kkptNinja** [comment]
Thanks Stephane. This stopping-starting did the trick.
