### ISSUE TITLE
lxc launch deletes already existing zfs dataset

### ISSUE THREAD

**Issue by thugcee** [lxc/lxd#8861]
# Required information

 * Distribution: Ubuntu 20.04.1
 * Kernel version: 5.4.0-58-generic
 * LXC version: 4.0.6
 * LXD version: 4.0.6
 * Storage backend in use: zfs

# Issue description

Running `lxc launch ... <NAME>` when `<POLL_NAME>/containers/<NAME>` already exists, fails due to `dataset already exists` error and then deletes this dataset. 280GB of data has been lost.

# Steps to reproduce

 1. `zfs create some_pool/containers/some-storage`
 2. `lxc launch ubuntu-minimal:20.04 some-storage`
 3. `zfs list`

`some-storage` will be gone.

Log:
```
t=2021-06-06T13:41:44+0200 lvl=info msg="Creating container" ephemeral=false instance=storage-man instanceType=container project=default
t=2021-06-06T13:41:44+0200 lvl=info msg="Created container" ephemeral=false instance=storage-man instanceType=container project=default
t=2021-06-06T13:41:46+0200 lvl=info msg="Deleting container" created=2021-06-06T13:41:44+0200 ephemeral=false instance=storage-man instanceType=container project=default used=1970-01-01T01:00:00+0100
t=2021-06-06T13:41:48+0200 lvl=info msg="Deleted container" created=2021-06-06T13:41:44+0200 ephemeral=false instance=storage-man instanceType=container project=default used=1970-01-01T01:00:00+0100
```

As `launch` command is used to create new entities it should not destroy anything already existing. It even destroyed snapshots of that dataset.

**Comment by stgraber** [comment]
@tomponline thoughts?
Can we easily have the storage drivers return a standard error for already existing volumes which can then be picked up by the instance layer and skip the deletion step in revert?

If this is easy to do, I don't see a big downside to doing it (just slightly slower creation time). But if this requires a lot of reshuffling then I'd leave things as they are.

I believe our storage documentation already points out that LXD assumes complete control of its storage pool, so it shouldn't really be a surprise if manual actions performed by the user outside of LXD may cause data loss.

We've had cases in the past where we've needed LXD to clean up any dataset or snapshots that it didn't know about so that logic would have similarly wiped this manually created dataset.

**Comment by thugcee** [comment]
@stgraber, you are right, it is mentioned in the documentation:
> Note that LXD will assume it has full control over the ZFS pool or dataset. It is recommended to not maintain any non-LXD owned filesystem entities in a LXD zfs pool or dataset since LXD might delete them.

I didn't know about it. My fault. This deleted dataset came up when I was shuffling files during some migration. I wasn't careful enough because I didn't expect that _create_ command can delete something.

**Comment by tomponline** [comment]
Looking into this now, I think we can do a better/safer job here.
