### ISSUE TITLE
Inconsistent OS & Setting config key removes other data

### ISSUE THREAD

**Issue by jamielsharief** [lxc/lxd#8923]
**Problem 1**
If I create an image based upon an Alpine container sending a post request to `/images`, the image OS is said to be `alpinelinux` which is inconsistent with Alpine images. 

Normal image
```
 "properties": {
        "architecture": "arm64",
        "description": "Alpine 3.13 arm64 (20210616_13:00)",
        "os": "Alpine",
        "release": "3.13",
        "serial": "20210616_13:00",
        "type": "squashfs",
        "variant": "default"
    },
 ````

What I get (notice OS key)
```
 "properties": {
        "architecture": "aarch64",
        "description": "Alpinelinux 3.13 aarch64 (20210526_13:00)",
        "name": "alpinelinux-3.13-aarch64-default-20210526_13:00",
        "os": "alpinelinux",
        "release": "3.13",
        "serial": "20210526_13:00",
        "variant": "default"
    },
```

**Problem 2**
I then followed the manual and tried to manually set the OS in the post request, but  then other information such as variant, release, serial and type are removed.

```
POST /1.0/images
{
    "aliases": [
        {
            "name": "apache",
            "description": null
        }
    ],
    "source": {
        "type": "container",
        "name": "apache"
    },
    "public": false,
    "properties": {
        "os": "Alpine"
    }
} 
 ```

Result
```
    "properties": {
        "os": "Alpine"
    }
```

**Comment by stgraber** [comment]
I don't think there's an actual bug here, what's happening is:
 - When creating an image from an existing instance, the metadata visible in `lxc config metadata show` is used, I expect that one shows the properties you're seeing in your image.
 - Image servers can overwrite image properties (as you would with a `lxc image edit`), this only changes the image server's stored properties, not the image metadata file itself (as this would result in a completely different image with a different hash).
 - When importing a remote image such as during launching of an instance, LXD uses the metadata provided by the remote server, not the one inside of the image file.
 - Setting `properties` during `POST` lets you override the properties that would normally be read from the metadata, a full set is expected (PUT/POST always expect full structs, PATCH is the only one which doesn't)

So in your case, the alpine image on the remote server is called `alpine` in the public index but distrobuilder which generated the image called it `alpinelinux` so that's what's in the metadata.yaml inside the image. The local cached entry mirrors that from the remote server (including properties overrides) but when publishing the instance as a new image, what's in its metadata is what's used, so you end up with an image showing the `alpinelinux`.

In general, I'd recommend updating the instance metadata to properly describe what it is ahead of publishing it as a new image.
This doesn't really matter if you just want to use it locally but if you want to export the image and import it somewhere else, you'll be happy to have your metadata all cleaned up first.

The metadata is accessed/updated at `/1.0/instances/NAME/metadata`.

Closing as there's no indication of a bug, the source of the confusion is our image server having listed properties which differ from those in metadata.yaml (a side effect of the image server using simplestreams and those properties not actually being configurable in our case).
