### ISSUE TITLE
Bad user experience when qemu crashes 

### ISSUE THREAD

**Issue by townsend2010** [lxc/lxd#8958]
Recently, we've run into an issue where qemu will "crash" when creating VM's with multiple CPUs and a relatively small amount of memory, such as using the `-t c2-m2` option.  That seems to come from a bug in grub or the signed shim in the image and is not the fault of LXD nor Qemu.

However, when qemu does falter, there is no feedback from LXD that there is an issue other than the state says stopped.  I think it would be better if LXD could provide a "broken" state to at least alert that there is a problem in this case.

Also, not sure if this should be a separate bug, but once qemu and LXD get in this state, trying to delete the "broken" instance won't work due to the fact that qemu is actually still running and holding the zfs volume open and so the `zfs destroy` fails.  The error that is presented to the user is scary and unhelpful and a user would have to know to kill the "crashed" qemu process by hand to get out of this mess.

**Comment by stgraber** [comment]
I'll take a look again but last I checked there really wasn't much we could do. LXD talks to qemu over QMP and when qemu crashes in this way, it remains running but with QMP refusing connections...

**Comment by tomponline** [comment]
I think we have an 'error' state for containers we could reuse here?

**Comment by townsend2010** [comment]
Yes, being able to forcefully kill QEMU from the client will avoid the zfs issue (`dataset is busy`) that comes as a result of this.

**Comment by tomponline** [comment]
@townsend2010 I have added a PR above that attempts to handle the crashed QMP socket while the QEMU process is still running. We had already handled the case where the QMP socket fails to connect but the QEMU process is still running, but I suspect in your scenario LXD was still able to connect to QMP, but was not able to get a suitable response.

Are you able to describe reproducer steps to get QEMU into the state that LXD was showing it as "Stopped" rather than "Error"? As apart from removing the QMP socket file (which simulates an inability to connect to QMP - which we are already handling) I am not sure what to simulate to gets QEMU into the state you were seeing. Thanks.

**Comment by townsend2010** [comment]
Hey @tomponline,

Thanks for this!  For me, I was able to reproduce using `lxc launch ubuntu:20.04 test -t c2-m2 --vm` or `lxc launch ubuntu:20.04 test -t c2-m1 --vm`.  It seems there may be some bug in grub and/or the signed shim that causes this.

**Comment by tomponline** [comment]
@townsend2010 reproduced it thanks, it appears that QEMU is returning "internal-error" as its status via QMP.
