### ISSUE TITLE
slow response time for remote operations

### ISSUE THREAD

**Issue by rrva** [lxc/lxd#897]
`lxc list` for a remote is far slower than `docker ps` between the same client and host. lxc list executed locally is fast.

on OSX client, remote ubuntu:

    time lxc list
    real    0m0.806s

Executed on lxd host

    time lxc list
    real    0m0.137s

docker ps on OSX client, remote ubuntu:

    time docker ps
    real    0m0.036s

(docker does not use TLS encryption in this setup).

**Comment by stgraber** [comment]
It's a known Go issue, nothing to do with LXD. Go spends 700ms doing basically nothing when negotiating a TLS connection (well, actually, worse than that, it burns your CPU during that time).

Go 1.5 is supposed to finally have the fix for this which will save 700ms on the network case and end up to a similar execution time as local.

**Comment by rrva** [comment]
Is there an unencrypted, insecure way of using lxd?

**Comment by stgraber** [comment]
Nothing that LXD itself exposes, nor are we planning on doing so. You can however use socat or other tools to forward /var/lib/lxd/unix.socket to a tcp socket. Though you'll have to forward it back to a unix socket on the client side as the lxc command line tool doesn't support unencrypted transport over tcp, nor do we intend to add this.
