### ISSUE TITLE
Swagger spec is invalid

### ISSUE THREAD

**Issue by NateKomodo** [lxc/lxd#9121]
# Issue description

The [swagger spec](https://github.com/lxc/lxd/blob/master/doc/rest-api.yaml) contains a number of errors and cannot be used for codegen. I tested the version on master as well as the 4.0.7 tag.

# Steps to reproduce

 1. Copy the swagger spec (by either downloading it or ctrl+c and ctrl+v, or importing from the url)
 2. Paste it into editor.swagger.io or any other swagger validator or codegen
 3. Observe the big wall of errors

# Information to attach
[Here are all the errors output by the swagger command line tool](https://pastebin.com/raw/CxnFERMB)

**Comment by stgraber** [comment]
The swagger spec is available for API documentation purposes only (effectively for https://linuxcontainers.org/lxd/api/master/) and not for use with code generation. LXD actively relies on a bunch of things which swagger cannot represent (protocol over websocket, TLS based authentication, ...).

**Comment by stgraber** [comment]
Closing as we're not aiming for a valid spec but instead for a spec which generates the output we want for our online doc.

In an ideal world, both would be the same, but it's currently not the case and fixing most of the reported issues would actually regress the API documentation that we generated.

It looks like some of what we're doing (like examples for parameters) is supported by some of the swagger tools because of OpenAPI 3.0 supporting those features. Unfortunately the tooling on the Go side currently doesn't make it easy for us to just generate OpenAPI 3.0 instead, so we'll be stuck with what we have now for a little while longer at least.
