### ISSUE TITLE
Bind lxd container port to specific namespace

### ISSUE THREAD

**Issue by TommyLike** [lxc/lxd#9202]
This is a general question that now we can use proxy plugin to expose container's port to host via command below:
```
lxc config device add <instance> <name> proxy listen=tcp:0.0.0.0:80 connect=tcp:127.0.0.1:80
```
Can we bind lxd container port to specific namespace? The usecase is we want to manage lxd container by its parent kubernetes pod while we can expose the container port via kubernetes traffic, something like that:
```
Ingress->Service->Pod->LXD container
```
Question:
1. Is it possible to support this in lxd? Will it be supported?
2. Do we have other solution for this case?

# Required information

 * Distribution:
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version:
   * Storage backend in use:

# Issue description

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Hmm, no, LXD will always deal with the host and the container, it doesn't support attaching to an arbitrary network namespace rather than the host's.

I'm also not sure that it's something we'd have much interest in doing as there are some difficulties with that.
We'd need to either get provided the path to a bind-mounted nsfd entry or be given a PID to attach to.

Now in general LXD runs under some kind of confinement and we restrict what `forkproxy` can attach to.
Having it go and attach to a container that LXD doesn't know about would be a bit odd to setup.

There's also the slight issue of how network namespaces work. If we were to do this. It would make that network namespace remain alive until `forkproxy` exists. Stopping that other container wouldn't get rid of the network namespace which can lead to "interesting" situations where the namespace being kept alive also keeps virtual network devices alive which in turn causes duplicate MAC addresses or IP addresses on the network.

As for better ways to allow two separate containers to communicate with each other. Maybe you could instead share a directory with both containers and have them use a UNIX socket on there rather than a TCP one? UNIX sockets just use basic file permissions for access so that would be a good way to share this.

**Comment by TommyLike** [comment]
@stgraber thanks, you are correct, after investigating the lxd code, we preferred to mount the share directory into both of the containers and connect them by domain socket.

**Comment by TommyLike** [comment]
@stgraber thanks, you are correct, after investigating the lxd code, we preferred to mount the share directory into both of the containers and connect them by domain socket.

**Comment by stgraber** [comment]
Cool, glad that approach works for you!
