### ISSUE TITLE
Possibly Expose "ZFS Send" or Stream Backup Over Websocket?

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#9246]
`zfs send` seems like the most popular way to make backups quickly [list of of forum posts] could it be exposed through an API?

If not `zfs send` could a `backup` be streamed over a web-socket? 

LXD Cluster is recommended to be co-located (the same data centre) so any down stream, centralised, app should be hosted there as well, even in single host environments. Streaming a backup over a socket should be "cheap" in terms of bandwidth, even if its not for the `lxc` client, you could omit the functionality from `lxc` if it was a concern.

Its a pain because down stream providers cant match the speed / "cheapness" of someone that can write a bash script to-do `zfs send` avoiding the disk writes & overhead.

**Comment by stgraber** [comment]
This is already what our migration API does. One could hit `POST /1.0/instances/NAME` to trigger a migration, send a migration struct saying that their side does ZFS and what features are supported and they'll get the ZFS send stream from LXD over the migration websocket.

**Comment by stgraber** [comment]
The main limitation currently is that this gets you a full stream with or without snapshots, that's what's used during `lxc copy`, `lxc move` and the matching `lxc storage volume` commands.

What's currently not supported is a refresh. That's why `lxc copy --refresh` and `lxc storage copy --refresh` use more bandwidth as the delta is handled by rsync instead.

We have plans to allow most storage drivers to handle an optimized refresh though where a temporary snapshot is effectively created at the source and then the delta since the most recent snapshot on the destination would be used. So as long as you have frequent snapshots in place, the delta would be quite limited. But this will need quite a bit of thought as not all storage drivers behave the same...

**Comment by turtle0x1** [comment]
https://github.com/lxc/lxd/issues/9246#issuecomment-921961801

Well, im a silly person - ill look at that.

Any idea what version that supports back to / an `api extension` I can check for?

**Comment by stgraber** [comment]
At least 2.0, likely earlier than that.
