### ISSUE TITLE
Superflous "snapshot-" prefix on snapshots on ZFS

### ISSUE THREAD

**Issue by spirritus** [lxc/lxd#9269]
Snapshots on ZFS have the prefix "snapshot-" before the snapshot pattern. This is useless, with the default pattern the generated snapshot is named snapshot-snapshot-$somedate. Changing the pattern sill leaves the prefix e.g. the pattern TEST becomes the snapshot name snapshot-TEST.

# Required information

 * Distribution: debian
 * Distribution version: 10
 * The output of "lxc info" is attached.

[lxc-info.txt](https://github.com/lxc/lxd/files/7210790/lxc-info.txt)

**Comment by stgraber** [comment]
They are not superfluous, they are used to differentiate temporary snapshots such as those generated for refresh/migration from persistent snapshots that are in LXD's database.

**Comment by spirritus** [comment]
I beg to differ, the "snapshot-" part is also added when a snapshot is created with "lxc snapshot instance".
This does not happen on BTRFS

**Comment by spirritus** [comment]
So this seems to be ZFS specific, in that case I might suggest using a ZFS property instead of the name. Since some backup tools e.g. sanoid depend on the snapshot name.

**Comment by stgraber** [comment]
Again, this is absolutely intentional. Any legitimate snapshot generated by LXD, either through scheduling or through a user running `lxc snapshot` WILL result in a `snapshot-NAME` snapshot name in ZFS.

This lets us easily separate those from temporary snapshots generated as part of publish, export, import and migration operations as LXD can rely on anything starting with `snapshot-` having a DB entry whereas anything else should get ignored or just plain get automatically deleted by LXD.

It's not ZFS specific, other storage backends that similarly track snapshot names separately from their mount paths like Ceph use the exact same prefix mechanism.

`btrfs` and `dir` don't as they are directory/mount based instead so this is tracked differently.

**Comment by spirritus** [comment]
Ok thx for clearing that up
