### ISSUE TITLE
Managing alternative virtualization solutions

### ISSUE THREAD

**Issue by tomposmiko** [lxc/lxd#9420]
hi,

It would be great, if we could run and/or manager other virtualization solutions too.
I don't mean vmware, but some cutting edge, like rust-vmm, firecracker and cloud-hypervisor. Actually I'm not fully it makes sense and these are really kvm and lxc alternatives. Correct me, if I'm wrong.

**Comment by lowercase00** [comment]
Hi @stgraber I have the same doubt as @tomposmiko and found this issue.

From what I understand, the new "micro vms" solutions don't (and won't) support everything in the list.
Firecracer seems to support Intel, AMD and ARM, but has limited support Virtio devices and I don't think it support other items on the list as well. I imagine same thing happens with cloud-hypervisor.

As LXD provides one of the best API experience, and a great container-VM interaction, I was wondering if it would make sense to support other virtualization solutiosn and explicitly discriminate the limitations. I guess for many of us looking for lightweight virtualization, the limitations are acceptable and expected, and making explicit that this is the limitation of the virtualization platform (and not LXD itself) could be positive for the project, since could bring new Firecracker/Cloud-Hypervisor users to the LXD platform.

About benefits, I think the lightweight aspect of Firecracker is the main one. I've yet to benchmark LXD VMs vs Firecracker vs raw KVM-QEMU, but as Firecracker replaces QEMU completely and have been showing positive performance, my first guess is that it would be hard to bit using QEMU.

What are your thoughts on adding a limited lightweight virtualization solution to LXD as an alternative to QEMU?
