### ISSUE TITLE
Certificate last used

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#9449]
This might be out of the question due to the possible 1 query per request requirement but would it be possible to a `last_used` field on trusted certificates?

Its probably a niche issue because I end up recycling certs alot but I have about 120~ certs trusted on my system and its hard to know (without scripting) which ones I can delete.

**Comment by stgraber** [comment]
Hmm, yeah, I can see how that'd be useful but indeed I don't think it's something we can realistically do.

This is one a code path where we really really can't be hitting the database every time. Most LXD requests are made of around 3 HTTP requests, if each one of those needs a database write, overall performance will drop like a rock.

It's a codepath which is already optimized currently specifically to never access the database. We load up all certificates from the database into memory on startup and update that set whenever the database is updated. This is done specifically to avoid performance slowdowns due to accessing the certificate table.

I definitely see how having the data would be useful, but I can't think of a way to provide that without significant performance degradation. Worth noting that if someone needs this kind of data from an auditing point of view, it would be pretty easy to build a third party tool which hits /1.0/events?type=lifecycle and then keeps track of the requestor field (which includes the certificate).

This would let you track the last action triggered by a particular certificate just by listening for LXD events and keeping your own state.

**Comment by turtle0x1** [comment]
@stgraber  thanks for the work around, as I suspected it's was unrealistic expectation from the LXD team.

At least its now documented and if in 3 years you add it I can be quietly sanctimonious as I was with (#5955) ;)
