### ISSUE TITLE
Add `lxc help --sub-commands` to list all sub-commands

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#9523]
The `lxc` command line tool has a lot of sub-commands at this point.
`lxc help` or `lxc --help` will show a subset of the top level ones (all if `--all` is passed).

It'd be nice for `lxc help --sub-commands` to show a tree of the sub-commands, so `lxc help --all --sub-commands` would show absolutely everything that's supported.

**Comment by dillonsamra9** [comment]
Hi. I'm a CS student at UT Austin and am currently taking a Virtualization class. I would be happy to take a look at this issue?

**Comment by stgraber** [comment]
Sounds good, assigned it to you!

**Comment by dillonsamra9** [comment]
Should I include the descriptions along with the listed sub-commands or just their names?
<img width="350" alt="subcmd" src="https://user-images.githubusercontent.com/60369763/144768476-04021d74-1839-4b07-9d64-d5dd32e54e16.PNG">

**Comment by stgraber** [comment]
I think having the one line description is quite useful.
I'm assuming this is all automated so we don't have to actually duplicate any of those strings, right?

**Comment by dillonsamra9** [comment]
Sounds good. Correct, none of the strings were duplicated. Since the help text is generated by CobraCommand, and CobraCommand doesn't have direct support for displaying sub-commands, but it does allow the user to override the default help template, so my approach was to create an alternate help template that includes sub-commands and is only used if the --sub-commands flag is passed.

I have a few padding issues I'm working out and then I should be good to put in the pull request.

**Comment by stgraber** [comment]
Sounds good!
