### ISSUE TITLE
Add reservation/refreservation in addional to quota support in ZFS driver

### ISSUE THREAD

**Issue by weastur** [lxc/lxd#9773]
It would be great to add support of setting `reservation` and `refreservation` because now, as I can see, it's possible only to set a limit for container/volume size. Still, it's not possible to guaranty that space would be available in the pool.

**Comment by stgraber** [comment]
Yeah, that should be fine. I don't think we'd let you set it to a different value, that'd get a bit complicated with migrations and whatnot, but we can put a config option so you can opt a pool or potentially single volume into using those instead of regular quotas, similar to how we have a flag to use refquota already.

**Comment by weastur** [comment]
To clarify, I believe it should work together with quotas, but not instead. If we set some limit for storage, we should guarantee that this amount of space is available. If I'm acting from an inside container, for instance, running the `df` command, I expect that I'm free to use all I see there.

**Comment by stgraber** [comment]
Right, in this case both should be set together.

**Comment by weastur** [comment]
If you don't mind, I will work on that.

**Comment by stgraber** [comment]
Certainly, assigned it to you!
