### ISSUE TITLE
defunct / zombie processes in Ubuntu 16.04 container

### ISSUE THREAD

**Issue by panticz** [lxc/lxd#9851]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 21.10
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.13.0-27-generic
   * LXD version: 4.0.8 (snap)
   * Storage backend in use: zfs

# Issue description
defunct / zombie processes inside of Ubuntu 16.04 container, regards i386 and amd64 architecture, Ubuntu 18.04 container works fine

# Steps to reproduce
 1. lxc launch ubuntu:16.04/i386 u1604
 2. lxc shell u1604
 3. service ssh restart
 4. service ssh restart
 5. ps axf

```
root@u1604:~# ps axf
    PID TTY      STAT   TIME COMMAND
     29 pts/1    Ss     0:00 su -l
     30 pts/1    S      0:00  \_ -su
    102 pts/1    R+     0:00      \_ ps axf
      1 ?        Ss     0:00 /sbin/init
     79 ?        Zs     0:00 [sshd] <defunct>
```

**Comment by stgraber** [comment]
LXD isn't responsible for the processes running inside the container.

In this case I suspect your issue is that you're trying to run a distro requiring cgroup1 on a host which uses cgroup2.

We're in the process of tagging those older distros so you get an error on startup for new instances but that won't retroactively apply to existing instances.

If you need to run a 16.04 container on a 21.10 host, your only option is to boot 21.10 in cgroup1 mode which can be done through a kernel boot option.

I'm on my phone right now so can't easily look it up again but it can be found in 'man systemd' and is something along the lines of systemd.cgroup_unified=false
